[quote.epigraph, , Heb 11:4]
____
She being dead yet speaks.
____

== Introduction

As it is declared that "`the memory of the just is blessed,`" and
"`the righteous shall be in everlasting remembrance,`"
it seems to be the duty of those who possess the requisite materials,
to select and bring forward such particulars,
respecting the lives and characters of pious and devoted individuals,
as may tend to instruct and encourage survivors, and exalt the power of divine grace.

My beloved mother did not keep a regular journal;
yet when absent from home she mostly transmitted copious details of her engagements
and sometimes made memoranda to which she often mentioned her intention of adding;
but frequent attacks of illness, and the occurrence of trying circumstances,
combined to frustrate her purpose;
so that when not actively engaged in the service of her Lord and Master,
the leisure she possessed was seldom accompanied by sufficient ability for much writing.
In the following pages, however, her own language has been generally adhered to,
although in making extracts some trifling verbal alterations were found necessary;
but great care has been taken to preserve the true sense and
import where any small variation seemed expedient.

The prosecution of this interesting employment has been
attended with a consciousness of inability to do
justice to the valuable documents committed to my trust,
and the character of my departed parent;
both of which are capable of being made extensively useful,
had the office of editor been filled by one more competent to perform its duties.

The work is now submitted to the public, with an earnest desire,
that one who spent so large a proportion of a lengthened life in
seeking to promote the highest interests of her fellow-creatures,
may, though dead,
continue to speak instructively to the hearts and understandings of
those who are alike called to glory and virtue.

[.signed-section-signature]
Elizabeth Dudley

[.signed-section-context-close]
Peckham, Eleventh month, 1824.
