== Chapter I

[.chapter-synopsis]
* From her birth to the time of her joining the Religious Society of Friends, in 1773.

Mary Dudley was the daughter of Joseph and Mary Stokes, and born in the city of Bristol,
the 8th of the sixth month, 1750.
Being of a delicate constitution, she was, during infancy and childhood,
subject to frequent and severe indispositions; yet she was early sent to school,
and has often mentioned as a proof of serious thoughtfulness,
her love of reading the Holy Scriptures,
and that her partiality for the Prophecies of Isaiah was such,
as to make her governess repeatedly inquire
whether she had not yet got through that book?
Being of quick parts, and possessing facility in acquiring knowledge,
she made rapid progress in learning; and as she advanced to youth,
the vanity which is inherent in the human mind was much
fed by the admiration of her relations and acquaintance;
yet, even at this early period,
she was at times sensible of the humbling visitation of divine love;
and in expressing her solicitude for young people, she has often been heard to say,
how highly she should have valued the privilege of Christian counsel and sympathy,
under those convictions which were at times counteracted on
one hand by incitements to worldly pleasure,
and on the other by ridicule for wishing to appear better than her contemporaries;
nor were these efforts untried on the part of
those whose duty it was to act very differently.

The following are her own observations:
"`I am drawn to commemorate the gracious dealings of a
merciful Father and Creator in early visiting my mind,
which though ignorant of the nature of deep religious feelings,
was certainly often impressed with them in the morning of my day; though,
from a remarkably lively disposition, I did not yield to that awful fear,
at seasons felt,
which preserving from the snares of death would
have led into a conformity to the divine will.
Being educated in great strictness by my parents,
respecting the observance and ceremonies of the worship they professed,
(that of the Establishment,) I was a constant attendant upon them from childhood,
though with this, allowed to enter into most of the amusements of the world,
to which my natural disposition greatly inclined;
while in the midst of dissipation I often felt a dissatisfaction,
and my mind was visited with something so awful that I appeared to others very grave,
and have frequently been laughed at for it.
I was fond of reading, and found much pleasure in yielding to it; which,
with a turn for poetry, and the intimate acquaintance of several sensible,
seriously inclined persons,
occupied much of my time from seventeen to eighteen years of age.
These circumstances, together with the death of my beloved grandmother,
gave a shock to that vanity,
in the gratification of which she had much contributed to support me;
and a disappointment in an affectionate attachment
terminated the attraction to visible objects,
so that my mind was like a blank, waiting to be filled up,
and prepared for the more extensive reception of the precious visitation, which,
early in the twentieth year of my life, was sweetly vouchsafed;
so that all that was within me bowed in deep prostration,
and yielded to the superior power of heavenly love.

My mind being in the prepared state above described,
it would be unsafe to date this change from the particular
period of my attending the Methodist meetings;
though in doing so I certainly felt more of
divine impressions than at any previous season,
and particularly when under the ministry of one of their preachers,
who seemed commissioned with a message to my mind.
I continued to hear him, with many others; attended all the means, as they are called,
and was often sweetly affected and comforted;
yet even at such times there was something within me craving the purity of an inward,
spiritual life---and seeing that without holiness no man could see the Lord,
as I did believe was attainable,
how did my whole soul breathe for this knowledge to be revealed,
and in the depth of silence, struggle that I might rightly seek and experience it.
I went into various places of worship among the Dissenters,
and was at one time greatly taken with the Baptists; but still found a lack,
a vacuum unfilled with that good I was thirsting after.
Not from conviction, but partly from persuasion,
and something in me yielding to the way I thought might easily settle me,
I joined the Methodist Society,
and also continued constantly to attend the established worship, that of my education;
but in the several ceremonies of this, and the different meetings of the other,
such as classes, bands, etc.
I felt unsatisfied, and often,
while others were engaged in attention to the preaching and singing,
has my spirit in solemn silence communed with the "`Lord my strength,`"
so that I scarcely knew what was passing around me,
and even felt disturbed from this inward attraction,
when obliged to draw to that spot where the outward
elements were prepared for the congregation.`"

"`Oh! how did I then feel the heavenly mystery, and sweetly partake of the bread of life,
so that all forms and shadows fled away,
and became no longer of use or efficacy to a mind feeding spiritually on the substance.
During these feelings and consequent shakings from all visible things,
I often went into Friends`' meetings, and there, especially in silence,
did my spirit feed, as it also did in deep awful retiredness, when no eye saw me;
but when, by this powerful attraction, hours have passed away,
so that my body seemed to do with a very small portion of rest or sleep.
I felt like a child clinging to its parent`'s breast; and in this state covenant was made,
which to this hour, I humbly trust has not been forgotten.`"

Her totally withdrawing herself from those scenes of amusement
in which she had dissipated much precious time,
brought upon her the ridicule of her young companions,
and even the censure of many who were much older though less thoughtful than she was,
and the expectation of her again returning to worldly pleasures, was frequently evinced;
while both flattery and entreaty were made use of,
to counteract that seriousness of demeanor which
was deemed so unnecessary at the age of nineteen.
The change which she felt it her duty to make, by leaving off ornaments,
and wearing such attire as was consistent with her views of Christian simplicity,
being very mortifying to some of her nearest connections,
she suffered considerably on this account.
The peace, however, with which her mind was favored,
more than counterbalanced these trials;
and strength being mercifully proportioned to the occasion,
she was enabled to persevere in the path of obedience,
and has frequently been heard to say,
that her company soon became as undesirable to her former gay associates,
as theirs was to her;
while her society and example proved the means
of solid advantage to some of her contemporaries,
who continued or sought her acquaintance.
At this period she frequently recorded her feelings in metrical composition;
and the two following pieces are selected, as instructively describing her state of mind.

=== Written on Her Twentieth Birthday

[verse]
____
Did angels`' love or seraphs`' glowing fire
My bosom warm, or my glad breast inspire,
With what loud praises would I pierce the skies,
What tuneful incense from my lips should rise.
Yet though my powers with no such ardor glow,
The feeble strains of thankful love may flow;
My languid numbers shall a tribute bring,
And humble praise awake the silent string.
While nineteen years their varied seasons rolled,
How chained this captive heart in winter`'s cold;
Unawed by threatenings and uncharmed by love,
It still refused the quickening draft to prove.
Vain the return of every annual day,
Its call still slighted or neglected lay;
In vain it told me that it gave me birth,
For still it found and left me slave to earth.
Immersed in shades of interwoven night,
In Nature`'s dismal chaos, void of light,
Thus lay enwrapped my powers, till mercy spoke,
And through the gloom a ray obedient broke.
Amazing grace! through this I still survive,
And boundless love has bid the rebel live;
Bids me, for once, with joy behold the day
That brought to light this animated clay.
Since Mercy deigns to smile,--hail welcome morn!
Forever solemnized be your return;
On you let pure devotion ever rise,
And breathe to heaven unsullied sacrifice.
____

=== A Hymn, Written in the Twenty-First Year of Her Age

[verse]
____
How shall I tune a trembling lay.
How touch the softened string?
Fain would I heavenly love display,--
The God of mercy sing.

I would,--but Oh! how faint each power,
How far too high the theme;--
Come, blessed Spirit, aid restore.
And raise the languid flame!

What wondrous grace! What boundless love!
What soft compassion this,
That calls my rebel heart to prove
A never-fading bliss!

Long have I sought the pleasing sound,--
But sought, alas! in vain--
Explored in Pleasure`'s mazy ground,
In Nature`'s desert plain.

What grace that I am not consumed.
Not hurled to endless night;
Mercy has all her pow`'r assumed,
And yields a cheering light.

`'Tis Mercy bids me seek the Lord;
`'Tis Mercy bids me fly;
`'Tis Mercy speaks the balmy word,
'`Repent, your God is nigh.

`'Tis Mercy fills my trembling heart
With agonizing pain,
With keen distress and poignant smart,
Nor heave these sighs in vain.

The tears that now in torrents flow.
This Mercy will repress;
Remove the load, a pardon show,
And speak a healing peace.

Then let me humbly wait the hour--
The hour of sweet release;
Incessant, saving grace implore,
Incessant, pant for peace.

At your blessed feet, my Lord and King,
Resigned let me lie,
Till the glad peals of triumph ring,
And Faith behold You nigh.

Then shall the stammerer`'s tongue proclaim
The goodness of the Lord;
In grateful strains rehearse His fame,
In hymns His love record.

I`'ll warble to each listening ear
The feeble song of praise;
My sweet employ while traveling here.
To lisp Redeeming Grace!
____

She was much esteemed by John Wesley,
and other distinguished characters in the Methodist connection,
and was frequently urged to become what is called a class leader;
but she freely confessed to him, and other members of the society,
that her views were not perfectly accordant with their tenets,
and she uniformly refrained from taking any active part among them.
Her exercises of mind, under the gradual discoveries of the divine will concerning her,
being in degree unfolded in some letters to a dear and intimate friend,
it is thought the following extracts will be acceptable to the reader.

May 10th, 1771--"`I have nothing, my dear friend, to tell you,
but of mercies--nothing but unbounded love should be my theme.
The Lord is indeed gracious, and has lately given me to feel it.
Oh! what sweet calls, what gentle admonitions has He indulged me with.
The feeble structure of clay is impaired--but, glory to my God,
my soul feels the invigorating influence of his grace;
in some moments of retirement lately, it has been ready to burst its barrier,
and I have earnestly longed to be with my Beloved, nor can I think it will be long first.
Glorious prospect!
Oh! my friend, if our next meeting should be around the throne!
While I write, my heart feels unutterable desires.
Pray for me, that the work of grace may be completed in my soul.
I believe it will--I feel I lack everything,
and am fully confident Jesus will supply all that is lacking.
In the eyes of some, this might appear as the wild excursion of enthusiasm;
to my friend it will wear a different aspect, and I trust,
engage her in my behalf at the throne of grace.
This, however, we are certain of, there is no danger from anything that leads to God,
and an impression, whether real or imaginary, of our nearness to death,
cannot but give a solemnity to the mind.`"

November 5th, 1771--"`Do not you, do not I,
feel the need of just such an all-sufficient Redeemer, as the compassionate Jesus?
Blessed be his name, we cannot, we would not do without Him,
as our Prophet, Priest, and King.
Here our poverty is indeed our greatest riches: we are content, yes, we rejoice,
that our whole dependance is on,
and our entire support derived from Him in whom all fullness dwells;
as having nothing and yet possessing all things.
Christ is indeed eyes to the blind, ears to the deaf, feet to the lame, yes,
all the sinner needs.`"

"`For my own part, I feel I am all weakness and helplessness,
having everything to learn,
but find the Lord Jesus to be that rock whereunto I may always resort.
I long to be more closely united to Him who has so graciously condescended,
and mercifully delivered me.
Oh! that my one desire, aim, and intention, may be to live to His glory.`"

"`To be in the will of Him who does all things well, is blessed:
may we bow continually to his easy sway.
Oh! what happiness should we find resulting from the desire that He might choose for us.
Surely infinite love joins with infinite wisdom, and wills our peace.
May our language then be ever this--

[verse]
____
'`Melt down our will and let it flow
And take the mould divine.`'
____

[.no-indent]
--"`Consider the Apostle and High Priest of our profession,
Jesus Christ, who for the joy that was set before Him endured the cross.
Oh! my friend, let us press toward the mark,
this glorious mark of conformity to our divine Lord and Master.
Does nature, that principle which cries spare me, oppose,
and strongly resist the operation of that power
which lays the axe to the root of the tree,
and forbids self-indulgence?
yet, let us in the strength communicated, obey that command,
"`follow me,`" and will not every act of self-denial we are enabled to perform,
weaken the power of our enemies, and encourage us to persevere in the glorious combat?
Verily it will, and also meet a present recompense of reward from condescending grace.
Come, then, my beloved friend, gird up the loins of your mind, be sober,
and watch unto prayer; the Bridegroom comes, go you forth to meet him; meet Him,
by adverting to him in your own heart, where he waits to speak in righteousness,
mighty to save.`"

"`Oh! for that attentive listening to His secret voice, which one felt who said,
'`Be still, Oh my soul! speak, Oh my Love!`' I had almost said, Hail celestial silence,
sacred source of heavenly safety, sweetest spring of solid peace.`"

"`I know not of any path besides that is truly safe,--it is an impregnable fortress.
'`I will watch to see what he will say unto me,`' was the
determination of an ancient servant of the Most High:
may my friend go and do likewise,
and may the God of all grace enable His weakest worm to follow every solemn injunction,
and obey the dictates of His spirit.
Pray that I may ever keep an attentive watch,
lest I should be surprised in an hour I expect not.`"

"`I have frequently wished for an opportunity of addressing you through this channel,
but in vain, till the present moment, and with more than usual pleasure I embrace it;
but what can I say?
Not rich and increased with goods, but poor and needy, where is my spring of help?
Even in Him who is the Alpha and Omega;
if in matchless condescension He deigns to communicate, as His is the power,
to Him also may the glory be ever ascribed!
I suppose my friend expects an interpretation of what has been lately hinted,
with regard to the approbation I feel of the Quakers`' mode of worship:
on this point I have little to say,
yet with the most unreserved freedom will I speak to that friend,
whom I wish to know the inmost recesses of my heart.
I need not tell you how exceedingly different my
natural disposition is from the love of solitude,
whether internal or external.
Prone to activity, and fond of dissipation, I pursued the attraction,
till a more powerful and all conquering one allured me.`"

"`Since I have known anything of the peace which is from above,
retirement has been pleasant, though a principle of acting was yet alive;
this was encouraged by my connection with the Methodists,
who I need not tell you are in the active class.
Having premised how opposed to my own, I think I may conclude,
that the Spirit of God has now produced a cessation of self-working within me,
and by emptying as from vessel to vessel, is showing me I have everything to learn,
and that by lying in His forming hand, the temple will be raised to his own glory;
this leads me into the inward path of abstraction from
those things I once thought essential,
and to the confirmation of these feelings the
ministry of the Friends has much contributed;
the small still voice has whispered unutterable
things to His unworthy dust in their assemblies,
and given tokens of his approbation to my meeting with them.
Adored be his condescending love!`"

"`Hitherto then has the Lord brought me, and who has been His counsellor?
Verily his own unerring wisdom: the future, with the past, is His;
ignorance itself am I. I have no light, but as he diffuses it,
and He has graciously promised that His followers shall not walk in darkness,
but shall have the light of life; they shall be taught of God.
Is this Divine Teacher my friend?
May I be all attention to Him who has given me the desire to be instructed by Him.
To this guiding, my much loved friend, I leave my cause;
I feel it my privilege to wait upon God.
I know not that it is my duty to be joined with this part of the flock,
though my mind strongly unites with them:
my path must be more illumined before I presume to take a step so important.
I want not a name, need I tell you so?
it is the nature of that Christianity which is life and spirit,
that can alone administer real peace to mine and to every soul.
Permit me then, my friend, to meet with,
and love those who are the subject of your fears--your friendly,
tender fears--and think not that I shall ever realize these,
unless plainly directed thereto.
My ever dear friend will, I doubt not, bear me on her heart before the throne of grace,
where I trust our united language will forever be--'`Father, your will be done.`'`"

Many others of her religious acquaintance also testified their
uneasiness at her evident attraction to the Society of Friends;
and John Wesley wrote to her in very strong terms of disapprobation.
The following letter to him closed her correspondence with this highly esteemed friend,
who afterwards continued to treat her with affectionate regard,
and to speak of her in terms of respect.

[.embedded-content-document.letter]
--

[.letter-heading]
Letter to John Wesley, July 29, 1772.

[.salutation]
My very dear and worthy friend:

For once I can say, the receipt of a letter from you has given me inexpressible pain;
lam therefore constrained to address you in this manner, before we personally meet,
as I fear my spirits would not enable me so freely to speak,
as to write the undisguised feelings of my heart.
I believe the apprehension of my valuable friend and father,
arises from a tender affection for an unworthy worm;
of the sincerity of which he has only added a fresh and convincing proof.
Whether I may give weight to,
or dissipate your fears, the most unreserved declaration of my sentiments will determine.
Your reviving in my remembrance,
the many favors I have received from the liberal hand of mercy,
since my connection with our dear friends, is kindly proper;
I think I have some sensibility of the love of God towards me in this respect,
and esteem that memorable hour when I heard the gospel trumpet among them,
the happiest of my life.
Yes, my dearest sir,
my heart burns while I recollect the attraction of heavenly grace! the many,
the innumerable mercies since then received, I desire with thankfulness to acknowledge;
and which, unless the spirit is separated from the gracious Author, cannot be forgotten.
'`Beware of striking into new paths,`' says my revered friend.
Much, very much, should I fear exploring any of myself,
or taking one step in so important a point, without the direction of Him,
who is emphatically called, '`Wonderful! Counsellor!`'
To His praise be it spoken.
He has given me the desire to be guided by Him; and I humbly hope,
in obedience to this Holy Teacher,
I have at some seasons lately attended the Quakers`' meeting,
but not at the time of our own worship, except Sunday evenings, when, with truth I say,
the excessive warmth of the room was too much for me to bear.
I am obliged to testify, the Lord has clothed his word delivered there with divine power,
for which the heart of my dear father will rejoice, since

[verse]
____
'`Names, and sects, and parties fall,
And you, O Christ, are all in all!`'
____

['.no-indent']
With regard to silent meetings,
I apprehend their authority may be known by the power they are attended with.
I have not been at such,
yet in my own experience find the unutterable prayer to be the most profitable,
and am led much into what is so beautifully expressed in one of our hymns.

[verse]
____
'`The speechless awe that dares not move,
And all the silent heaven of love!`'
____

[.no-indent]
I long to be more internally devoted to that God,
who alone is worshipped in spirit and in truth; and find,
in order to keep up a spiritual communion, there must be a deep, inward,
silent attention, to the secret intimations of divine love,
for which my inmost soul aspires to Him,
who has promised to fulfill the desire of them that seek him;
and is this, my dear sir, '`stepping out of the way?`'
Surely it cannot,
while I find a peace that passes all understanding.
Can this lead me to think slightly of my old teachers?
Oh! could my heart be opened to my friend,
he would see far other characters impressed.

Will this teach me to neglect my meetings?
I esteem them great privileges where, not custom,
but a sincere desire for God`'s glory is our principle of action.
What further can I say to my honored friend,
after disclosing so much of that heart which holds him
in most affectionate and respectful love.
I can only add the request,
that he would join me in that emphatic prayer to the God of all grace,
'`Your will be done;`' to which an attention and obedience will, I trust,
divinely influence his very unworthy, but gratefully affectionate,

[.signed-section-signature]
Mary Stokes.

--

After this she gradually withdrew from the Methodist Society,
and became increasingly sensible that it was her religious duty to profess with Friends,
which she was strengthened openly to acknowledge in language and demeanor,
about the middle of the year 1773.
This important event, and the deep exercises by which it was preceded,
are thus stated in my dear mother`'s own narrative:

"`The active zeal of the people I loved, and had joined,
now appeared to me irreconcilable with that self-abasement,
and utter inability to move without holy help, which I experienced.
I had nothing but poverty and weakness to tell of;
and when from the force of example, I did speak,^
footnote:[This alludes to the practice of disclosing individual
experience in class meetings of the Methodist Society.]
my little strength was rather diminished than increased.
Indeed, I found little but in quietude and inward attention, and when centered here,
I had all things, because I possessed the good itself.
Thus was my mind drawn from all creatures, without the help of any,
to the Creator and source of light and life, who, to finish His own work,
saw fit to deprive me of my health; this happened in the year 1773,
about the time of my dear father`'s death,
on whom I closely attended through a lingering illness, wherein he said to me,
'`O Polly! I had rather see you as you are than on a throne.`'
I believe he died in peace.
My complaints threatened my life, being consumptive,
but I felt no way anxious respecting the termination.
I was weaned from all creatures, but felt, beyond all doubt, that if life was prolonged,
were there no Quaker on earth, I must be one in principle and practice;
but being determined if the work was of God, He himself should effect it,
I read not any book of their writing.
Being utterly unable to go from home, I attended no place of worship,
and conversed with very few, except my beloved and most intimate friend,
Rebecca Scudamore,^
footnote:[This friend was a member of the Church of England, and highly esteemed,
as a woman of distinguished piety and deep spiritual experience.
A short account of her life was printed at Bristol about thirty years ago.]
and even to her were my lips sealed respecting the path pointed out to me;
but after hesitating and shrinking many weeks from using the plain language,
wherein the cross was too great to be resignedly borne, she told me her fixed belief,
that I ought to use it, and that my disobedience caused her great suffering,
or to that effect: I then told her, I was convinced of its being required, but,
that if giving my natural life would be accepted, I was ready to yield the sacrifice.`"

"`My health grew worse, and every act of transgression increased my bodily weakness;
until feeling all was at stake, in the very anguish of my spirit I yielded;
and addressing my beloved and hitherto affectionate mother,
in the language of conviction, my sufferings grew extreme through her opposition;
but never may my soul forget the precious influence then extended.`"

"`The very climate I breathed in was sweet, all was tranquil and serene,
and the evidence of heavenly approbation beyond expression clear;
so that this temporary suffering from mistaken zeal, seemed light, comparatively;
and indeed all was more than compensated by future kindness,
when light shone about that dear parent`'s dwelling.
My health mended, I soon got to meetings,
and though ignorant of the way Friends had been led,
or some peculiar testimonies they held,
the day of vision clearly unfolded them one after another,
so that obedience in one matter loosened the seal to another opening, until I found,
as face answered face in a glass,
so did the experience of enlightened minds answer one to the other.
I here remember the strong impression I received
of the lack of rectitude and spirituality,
respecting the payment of tithes or priest`'s demands; feeling great pain in only handing,
at my mother`'s request, a piece of money, which was her property,
to some collectors for this purpose:
so delicate and swift is the pure witness against even touching that which defiles.`"

Her relations left no means untried to dissuade her
from a profession which involved so much self denial,
and seemed, in their view, to frustrate every prospect of worldly advantage;
and her mother considering her change as the effect of temptation,
was in hopes the interference of the minister of the parish would prove helpful,
and accordingly promoted their having an interview;
but this did not produce any alteration,
neither was it very satisfactory to either party.
The clergyman very strongly censured her for having
taken so important a step without first consulting him,
to which she replied, that not feeling at liberty to confer with flesh and blood,
even by consulting her own inclinations, she dared not seek any human counsel,
and was endeavoring to act in simple obedience to the
discoveries of divine light in her own soul.

Upon leaving her, he presented a book, which he enjoined her to read,
but upon looking at the title [.book-title]#A Preservative from Quakerism,# she pleasantly observed,
"`It is too late, you should have brought me a restorative.`"
In the midst of this opposition,
she was much encouraged by the sympathy and Christian advice of Elizabeth Johnson,
a conspicuous and valuable member of the Methodist society.
This friend had frequently visited her during her illness,
and once when she was thought near her end,
after spending a considerable time in silence by the bed side,
solemnly addressed her in the following language:
"`I do not believe that your Heavenly Father is about to take you out of the world,
but I believe you are called to make a different profession;
you are not led as the Methodists are, but are designed to become a Quaker.`"
This, though very striking and of an encouraging tendency,
did not produce any acknowledgment of what was then
passing in the conflicted mind of the invalid,
who, however, continued to derive comfort from the visits of this valuable acquaintance;
and has often mentioned the sweet and strengthening
influence of which she was at times sensible,
when no words passed between them,
as well as the tender and maternal interest which she afterwards manifested,
when the view she had expressed was realized,
by her young friend publicly avowing religious sentiments different from her own.
