== Chapter IV

[.chapter-synopsis]
* Journey to some parts of Holland, Germany and France
* in company with Sarah Robert Grubb
* 1788.

The next religious engagement upon which my dear mother entered,
was one of an extensive and deeply important nature: the prospect of this,
and her preparation for entering upon the service,
will be best described in her own words.
Alluding to the year 1787, she says:

"`About the fall of that year I was seized with an alarming illness,
out of which few expected I should recover,
nor did I myself when judging from bodily feelings.
As to my mind,
it was kept in such a state of deep poverty that I
could form no settled judgment respecting anything,
save that at some seasons, the evidence of having passed from death unto life,
by the feeling of near unity with the brethren, consoled me.`"

"`During this probation, though apparently I was near the closing scene,
there were moments when the love of the gospel so prevailed, that a willingness,
and even desire to live was felt,
so that I might by any means be thought worthy to
suffer or do anything for the promotion of truth,
and the good of others.
These impressions were accompanied with a belief, that if I were raised up again,
it would be for this purpose; and my heart was called,
at a period when those about me expected my dissolution,
to such a deep attention to the discoveries of light, that, as in a vision,
though perfectly awake and sensible, I was carried to some distant parts,
even to a people of a strange language;
where gospel liberty was fell in '`a remarkable manner: then the vision was again sealed,
being for an appointed time, nor did I ever fully understand it,
though from that period a solemn covering spread over my mind,
till my ever dear and valuable sister Sarah R. Grubb laid before our
monthly meeting her concern to visit some parts of France and Germany.
The nearness of spirit I had with her,
in her watchful attendance on me during the first of my illness, was surprising;
and often, when no words passed, we mingled our sighs and tears,
though she never gave me any hint of the exercise she was under,
nor had I then any perception of being under
preparation for any service in conjunction with her.`"

"`After she had obtained her certificates,
we united in a little visit to a branch of our monthly meeting;
and on returning I wished to hasten her departure,
but found she felt no liberty to proceed, and said all concern was taken from her;
but so closely queried of me respecting my feelings, that without saying much I wept,
and thereby discovered what I was struggling against, or at least wished to conceal,
believing it was impossible I ever could be resigned to such a movement.`"

"`From this time, the weight grew almost insupportable, so that sleep,
appetite and strength, nearly departed from me,
and my dear husband queried--after watching unperceived by me--what can this be?
He once mentioned France, but I requested him no more to do it,
being affected to trembling,
and I believe I could as readily have given up my natural life as made this surrender.
Oh! great indeed was the struggle,
until at length the precious grain of all-conquering faith proved victorious,
and believing Him faithful who had promised, I ventured to move in this awful matter,
and when the needful steps had been taken,
left all and endeavored resignedly to follow my Great Master.`"

She had seven children at this time, the youngest only ten weeks old,
and her health was very delicate, so that the sacrifice was indeed great,
but the merciful extension of proportionate assistance is thus acknowledged by herself:--

"`In the course of the embassy, many and sore were my provings,
and of a closely trying nature my conflicts, but the arm of all sustaining help was near,
and I feel thankful that this cup has been drunk;
for though mingled with deep and exercising sufferings, it has, I trust,
tended to the further reduction of the creaturely will and choosing,
and brought measurably into willingness to submit to
the humiliating leadings of the holy hand.`"

The following is extracted from her own account of this journey.

"`Second month 27th, 1788: I parted with my beloved husband, and many dear friends,
in Waterford, and in company with Robert and Sarah Grubb,
went on board a vessel bound for Minehead, setting sail with a tolerably fair wind,
but after being out all day, and getting several leagues out to sea, the wind changed,
and the captain found it best to put back into harbor.
Being very sick we concluded to go on shore about noon, landed at Passage,
and spent a comfortable night at Brooklodge; embarked about ten next morning,
were favored with a safe, though rather rough passage, to our destined port,
and met a kind reception at our friend Hannah Davis`'s, where,
after the inconvenience of sea-sickness, we were consoled by friendly attention.`"

"`We left Minehead on third-day, and arrived in London on fifth;
I was affectionately received by my dear friends John and M. Eliot, and retired to rest,
under, I hope, a thankful sense of many unmerited mercies,
with the additional one of hearing from my family that all were well.`"

"`Sixth-day, attended meeting at Grace Church street--a low time to my poor mind,
which seems oppressed, and as it were in prison.
Some prospect of moving forward opened this evening, in a conference with George Dillwyn,
who seems bound to the awful service on the continent.
It is pleasant to have the prospect of so strong a link to this chain.
I am very low and poor,
emphatically '`going forth weeping`'--may the right seed be kept in dominion!
Amidst such qualified servants in this mission how little do I feel myself!
Yet hope I have not entered presumptuously on the list--the cause, I know,
is in the best hands, and if my venturing brings no dishonor to it,
I hope to be thankful--further seems not now in my view.`"

"`The kindness of dear John and M. Eliot is mixed with a
feeling of friendly sympathy better felt than described,
and I have not been without some apprehension that John Eliot feels deeper
on the occasion than mere unity with the concern of others;
but he is reserved and cautious;
and if it so prove, it will, to be sure, be pleasant.`"

"`First-day the 9th, was a day of peace and liberty to me,
though one wherein there was rather a descending
to the deeps than ascending to the heights.
The morning meeting at Grace Church street was large, gay, and oppressive,
but it is a favor to be allowed to visit the seed in prison,
and a great one to feel a willingness so to do.
My beloved Sarah Grubb was afresh anointed in both meetings,
and I thought my small vessel contained a little more than what was properly my own; and,
we read, the debt was first to be paid,
before the residue of the oil was set apart to live on.
The day closed comfortably in a little season of retirement at Richard Chester`'s.`"

"`Second-day the 10th, attended the morning meeting, and produced our certificates.
Friends seemed disposed to enter thoroughly into the matter;
near sympathy and unity were expressed,
and a committee was appointed to draw up certificates for us,
and one for George Dillwyn, who laid his concern before them.
We had a conference this day with Adey Bellamy respecting our proposed journey.`"

"`Third-day, 11th, sat a quiet solid meeting at the Peel, held in silence,
wherein a little renewal of faith was afforded, and cause for confidence in holy help.
Last night confirmed me in a feeling sense of my short-sightedness.`"

"`The southern parts of France being all along the first object in my view,
the way to get there the soonest, appeared desirable,
and the passage from Dover to Calais that which effected this desire most speedily;
but our beloved companion George Dillwyn feeling
the passage to Holland most clear to his mind,
I felt mine greatly tried, wishing if I had but ever so small a bit of ground to move on,
it might be my own.
I went to bed thus exercised, and endeavored to think only of Dover,
but after a season of very close conflict,
and I think honest travail for right direction,
a serene sky seemed over this prospect of George Dillwyn`'s,
and every other passage to France utterly closed,
so I simply communicated my feelings this evening to my companions, and,
thus far peace attends.`"

"`Our dear friend John Eliot is, I believe, bound to the south,
but has as yet made no movement in his monthly meeting.
Adey Bellamy has laid his prospect before Friends,
and it is likely will be liberated by the time J. Eliot is,
if he discloses his feelings at his next monthly meeting.
Our having come here seems providential,
as John Eliot and Adey Bellamy understand the language well;
and the hope of this seasonable assistance has tended to renew my faith, and patience,
which I sometimes trust will hold out to the end.`"

"`Fourth-day, 12th. We attended Grace Church street monthly meeting,
that for worship was low to my feelings, the one for discipline long and flat,
much business agitated, and many pertinent remarks made; but life seemed oppressed,
and human, more than divine wisdom uppermost.`"

"`Fifth-day, 13th. After being at meeting at Ratcliff,
I accompanied George Dillwyn and wife to Jacob Bell`'s, to dinner;
a solemnity covered my mind afterwards, under which it felt pleasant to have a pause,
for seeking the renewed influence of the pure principle of life and love,
and the season was graciously owned.
Spent the evening at another friend`'s, I thought profitably, in free conversation.`"

"`First-day, 16th. Went to Horselydown meeting in the morning--a low time:
Grace Church street in the afternoon,
and at six in the evening a public meeting appointed by George Dillwyn,
in which he was largely engaged.
I again felt, in a painful manner, the consequence of withholding more than is fitting,
yet trust willful disobedience was not the cause,
but a fear of not feeling sufficient authority:--'`do you seek great things?`'
seems the query often put to my poor mind on such occasions,
and though the injunction is added '`seek them not,`' how slowly do I learn!`"

"`Second-day, 17th. Morning meeting, a time of favor through several instruments;
our certificates were signed, I believe, by all present,
and the meeting seemed to conclude under the uniting evidence of Christian fellowship;
many dear friends expressing near sympathy with us, poor pilgrims, in our going forth,
and George Dillwyn closing with solemn supplication for
the continuance of gracious protection.`"

"`Third-day, 18th. We turned our backs on the great city,
and got to Colchester to dinner; met a kind reception at our friend John Kendal`'s,
and had there in the evening, the company of Thomas Corbyn and Thomas Hull,
who returned with John Kendal from the service of visiting the meetings in that county.
It was pleasant to us to see Thomas Corbyn before our embarkation,
and he was kindly affectionate and sympathizing tons;
dear Rebecca Jones also spent the night herein her return from Ipswich.`"

"`Fourth-day, was their meeting in course, which we attended,
not knowing but we might afterwards proceed to Harwich;
but our George Dillwyn found a cloud remaining on his tabernacle,
at which I wondered not,
as I had before told him I did believe he would
not get away without a meeting for the people:
one was held that evening, and I think owned by gracious regard.`"

"`As no packets leave Harwich regularly, but on fourth and seventh days,
our proceeding there seemed not desirable till near the time;
we therefore rested at our comfortable lodgings fifth-day,
and on sixth went to Manningtree, where a meeting had been appointed fur ten o`'clock;
the house is small, and few Friends reside here,
but it was pretty well filled with a solid, quiet company,
and was to me the best meeting since my leaving home,
a time of enlargement in true love and productive of peace.
After dining at a Friend`'s in the town, we went on to Harwich,
and had a meeting there at six in the evening; the house, a new small one,
was soon filled with fashionably dressed people,
and a considerable number were in the yard;
they seemed rather unsettled in time of silence, but quiet when anything was offered:
my beloved Sarah Grubb and George Dillwyn were afresh anointed with gospel oil,
and I was comforted in beholding good work well done.`"

"`My poor mind is under discouragement from various causes;
remarkable anxiety has attended me for several days about home, and faith is indeed low,
though I thankfully remember having been enabled to surrender
all I have to the disposal of unerring wisdom.`"

"`Seventh-day, 22nd. The wind contrary, and no prospect of sailing, I feel very low,
and almost in danger of casting away hope.
First-day, So ill that I could not get up till about noon;
our company went to meeting, where,
I think, only about seven attended.
In the evening, a solemnity covered us,
under which dear George Dillwyn revived the query put to the disciples,
'`when I sent you without purse or scrip, did you lack anything?
and they said, nothing:`' again,
they that have left all '`shall receive a hundred fold now in this time,
and in the world to come eternal life.`' This seemed so
peculiarly applicable to my tried state,
that while my soul was as though it refused comfort,
I could not but taste a little renewal of hope.
We just broke up when a summons to go on board was sent us.`"

"`There being but little wind, and that not quite fair, we had a tedious passage,
but were favored to experience holy protection,
and landed about eight o`'clock on fourth-day evening, at Helvoetsluys,
where we got to a clean inn, kept by two English women.
While in the boat going on shore, a sweet calm covered my mind,
accompanied by the fresh application of that gracious promise,
'`I will be to you mouth and wisdom;`' this,
after the tossings I had been tried with for many days,
tended to renew my confidence in divine sufficiency and goodness.`"

"`Fifth-day, 27th, Left Helvoet this morning in a carriage wagon,
and travelled on a very deep road--often in danger of overturning--to the Briel;
here we crossed a ferry about a mile over, went again by land to another ferry,
and from there to Maasslandsluys.
In this place we seemed as gazing stocks to the people, many following us,
though all behaved civilly,
and had they understood our speech would probably have helped us.
I felt what I think was the love of the gospel,
my heart being so filled that I could have spoken to
the people as I walked along the street,
and while in the house where we stopped to get a little refreshment;
but I felt what I was, and who I was with,
and had not to courage to query whether we might not as well remain a while;
therefore with the heaviest heart I ever remember feeling at leaving any place,
we went on board a treckschuyt for Delft, from which we proceeded to Rotterdam,
and there got to the house of an English woman that night.`"

"`I feel sensibly confirmed in the belief,
that passing through Holland was the right way,
for in coming through the towns to this place, there has been so much love prevalent,
that it has felt to me as though we were not among strangers,
though with a people of a strange speech;
and that there were many who could be spoken to from something
answering in their minds to what is felt by us,
even without outward interpretation.
A minister of the Calvinist church drank tea with us, this evening,
and undertook to give notice of a meeting which is appointed for tomorrow.`"

"`Seventh-day, 29th. The meeting was held at ten o`'clock;
George Dillwyn and Sarah Grubb were strengthened to recommend
inward waiting for the revelation of divine power,
but there seemed little openness among the few assembled;
several ministers of the Calvinistic church attended,
and we took tea with one of them--many others were present,
and a good deal of religious conversation took place,
wherein an explanation was entered into of our principles and testimonies;
George Dillwyn opening these clearly, and apparently to their satisfaction.
I thought this was a season spent profitably,
though as to my own feelings I am like one in prison;
may I be helped to resign myself into His hands who has, I trust,
sent me out on this journey; for while my conflicts seem rather to increase than lessen,
and the exercise of my spirit almost weighs down the poor body,
I do at times feel renewed confidence that I shall be preserved,
and that those I have left will be taken care of.`"

"`First-day, 30th. A public meeting at four in the afternoon: it was very large,
more coming than the house could hold;
some liberty was felt by all of us in expressing what arose,
but it was an exercising low time: a physician and his wife came to tea with us,
and expressed satisfaction in our company, which we also felt in theirs,
and parted from them in that love which throws
down all distinctions of names in religion.`"

"`Second-day, 31st. After a solemn season with the only person we knew of here,
who makes any profession with us, we set off in a treckschuyt, for Amsterdam,
where we arrived the next evening, and met a kind reception, from John Vanderwerf.

Fourth-day, attended the monthly meeting of the few Friends here,
and light seeming to shine upon visiting these, in their own houses,
we entered upon the service,
which was so owned by the prevalence of gospel liberty and love,
that hard things were made comparatively easy.
Sarah Grubb and I had never before spoken through an interpreter,
which office John Vanderwerf junior filled agreeably,
and our minds were bowed in thankfulness to the Lord,
who manifests himself a present helper.`"

"`The situation of these few sheep, as it were in a wilderness country,
calls for near sympathy, and it is a favor when not only this feeling is extended,
but a willingness accompanies to let it run as it flows.
It is about four years since they were first visited by George Dillwyn, Samuel Emlen,
and John Kendal; that life which is the crown of all profession is certainly low;
the seed seems in a wintry state, scarcely shooting above ground,
yet we have thought it is under the care of Him who can nourish and bring it forth,
if it be only allowed to lie under His cultivating hand,
and not exposed too much to the chilling breath that surrounds.
There are also some hidden,
seeking minds in these parts--perhaps mixed with the various names to religion,
and others who we find do not join with any denomination,
but keep quietly among themselves, exemplary in their conduct, doing good,
and communicating of their outward blessings; plain in their appearance and manner;
one of these, after sitting in an opportunity where evident solemnity covered us,
observed, that though we could not understand each other,
there was '`a feeling and unity within.`"

"`First-day, 6th of Fourth month.
We had two public meetings, one at half-past nine, the other at four.
George Dillwyn and Sarah Grubb were favored to minister with gospel love and authority,
I had fresh cause for confusion, and the acknowledgment that to me belongs shame;
pain still attends the remembrance of my lack of dedication in these meetings.`"

"`Second-day morning.
We had a little sitting among ourselves, desiring to feel our way from,
or detention in this city, rightly ordered; we were afresh helped to believe, that,
as the eye was kept single.
He who had led forth would continue to preserve us.
We went to tea with a family named Decknatel--a widow, her son, and two daughters;
these were educated in the Anabaptist profession,
her husband having been a preacher among this sect,
but since his death they have not joined in communion with any particular people,
but keep themselves select, except going sometimes to the Moravian worship.
A sweet influence prevailed in the house,
and a good deal of religious conversation occurred--
John Vanderwerf being with us to interpret.
They believe in the sufficiency of the spirit of Truth to lead into all truth,
though they seem not fully to have entered into that
rest where there is a ceasing from our own works,
as they sing hymns sometimes, and have an instrument of music in their house.
They were very desirous of understanding us,
and our errand--it seemed strange to them for me to leave a husband and seven children,
but feeling liberty to enter a little into the cause,
and some particulars of my convincement,
etc. as the remembrance arose with renewed thankfulness,
they appeared not only fully satisfied, but to comprehend the language.
This conversation introduced to a solemn silence, in which they readily joined,
and we had each to unite in the testimony that the
salutation of '`peace unto it`' belonged to this house:
this memorable season closed in awful supplication,
and we parted under a feeling of that pure love which
throws down the narrow barriers of nominal distinction,
and baptizes into the unity of the one Spirit.`"

"`9th. At four o`'clock this afternoon we had another public meeting,
which was well attended as to numbers, but the people were unsettled in time of silence;
the doctrine of Truth ran clearly,
and a hope was raised that some felt a testimony to it in their own minds.`"

"`10th. Left Amsterdam with John Vanderwerf jun., and Frederick Mentz,
in a carriage boat, the usual way of traveling in this country;
it is drawn along a canal by a horse, and consists of a small cabin,
calculated to hold seven or eight,
and a larger room which will contain about thirty people,
with seats to accommodate all the passengers, and light sufficient to work by.
We arrived at Utrecht between three and four o`'clock,
felt exercised respecting a meeting here, but not living enough by faith,
and looking too much outward, discouragement prevailed.`"

"`11th. Set off from Utrecht in a post wagon, and travelled over deep roads,
through a woody country thickly inhabited, though the land is poor,
and we found but indifferent lodging and entertainment until we reached Dusseldorf,
on the evening of the 13th, where we got to a good inn.`"

"`14th. Concluded to stay this day, to feel whether bound or dismissed from hence;
in the forenoon called on Michael David Wetterboar,
whom our friends Decknalel recommended us to see, we also drank tea with him,
and found him an inward retired man, living pretty much alone,
and not knowing that he has any companions in this large place,
where superstition seems to reign.
We had a season of solid retirement after tea,
and some profitable conversation through Robert Grubb in French.`"

"`15th. Went off the direct course about eighteen miles to Elberfeld,
expecting to find some seeking people.
We were directed to a person named Smith, with whom we spent a little time;
he speaks English and was civil, but seemed fearful of engaging to be our interpreter:
he informed us there were some mystics in the town, who met together on first-days,
but we found no way to get into their company.
In the morning we walked out, George Dillwyn and I one way,
and Robert and Sarah Grubb another, but though we called in at some houses,
no way opened for a meeting, we therefore returned to Dusseldorf to tea.
M+++.+++ D. W. spent the evening with us,
and we had a season of spiritual refreshment in
the feeling of Christian liberty and love,
under which we parted.`"

"`17th. Left Dusseldorf about half-past six,
and got to Cologne to dinner--a dark place of popish superstition,
crosses and images appearing almost everywhere in and about it:
we all felt oppressed and glad to leave this place; reached Bonn, a smaller town,
where similar idolatry prevailed: George Dillwyn, and Robert Grubb, walking out, saw the host,
as it is called, carrying about, and the people kneeling to it.`"

"`18th. Rode through a beautiful valley of vineyards, and other plantations,
bounded on one side with richly cultivated mountains, and on the other by the Rhine,
on each side of which, towns and villages thickly appeared,
also some monasteries and ruins,
altogether forming as diversified and lovely a scene as I ever rode through;
but in this day`'s journey I found nature unusually oppressed,
so that it was hard to bear the motion, and my illness increased so much,
that when I saw a town on the other side of the Rhine,
not knowing it was our destination, I thought it looked a desirable resting place,
and wished to get to it; when the driver turned the carriage that way,
and it proved to be Nieuvied, a place to which we had recommendations.^
footnote:[Copy of one of the Introductory Letters given
by the family of Decknatel.--"`My Dear Brother;
I give this address by these Friends, whom they call Quakers, from England;
perhaps they will call in their journey at Nieuvied--
though you cannot speak with them but by an interpreter,
yet you may have an agreeable feeling and influence in silence,
through the favor of the Lord,
which you desire--I salute you with renewed affection.--J. D.`"]
Here we got to a comfortable inn, like a private lodging, kept by Moravians,
who received us cordially, and we took up our quarters with them.`"

"`19th. I was very ill, so as to lie in bed all day, low in mind as well as in body;
dear Sarah Grubb indisposed also,
and we felt glad in this state to be in a quiet asylum.`"

"`20th. First-day, my complaints continuing I was not able to go out,
my dear companions sat at my bedside, where, in a season of quiet refreshment,
we remembered with comfort that it was when the disciples walked together and were sad,
that their great Master joined Himself to them.`"

"`21st. A day of distress every way, mostly in bed during the forenoon:
after dinner went to see the Moravian establishment, the schools for girls and boys,
etc., but so low that nothing seemed capable of cheering me;
my faith and patience are so tried that I am
often ready to fear the honor of the great name,
and that excellent cause which, through every discouragement, is dear to my heart,
may suffer by my engaging in this embassy.
I feel myself so insufficient for the work, and even at seasons when holy help is near,
qualified to do so little, that I am ready to query, for what am I sent?
Yet I remember there are various vessels in a house,
and it may sometimes seem proper to the Master to call for one of the smallest,
to use as He pleases--to convey what He appoints;
and if care be only taken to have this vessel kept clean,
though it may not be often called for, or able to contain much,
it may answer some little purpose, by having a place in the house;
and help to fill up some corner, which a larger one could not so easily get into.
I know that I sought not this,
that I ventured not without feeling the weight of
'`Woe is unto me if I preach not the gospel`'
where the holy finger is pleased to point:
and the remembrance of these baptisms, with the renewal of frequent close conflicts,
raise a hope through all, that though the sea may be permitted to swell,
and the waves rise exceedingly high,
the poor vessel will be preserved from becoming a wreck amidst the storms,
and the little cargo be safely landed at last.`"

"`23rd. We called this morning on an old man,
belonging to a sect who called themselves inspired--a little
conversation through an interpreter proved rather satisfactory.
At seven in the evening we went to sit with these people in their meeting,
expecting from the account received of them, that they sat mostly in silence,
but we found it far otherwise.
They remained awhile still, with apparent solemnity, then all kneeled down,
and used words as prayer, afterwards singing,
then one of them read part of a chapter and expounded.
We sat still until they had concluded, when a few words were,
as well as the language admitted, conveyed to them.
On the whole we were not sorry we obtained this
acquaintance with their manner of worship,
as others denominated them Quakers,
and we were now able to unfold to them the difference between us.
We have abundance to discourage us within and without, many fears,
and no outward help but the comfort we find in being closely banded together;
and beside the sufferings we are dipped into,
no apparent prospect of these tending to gather many, if any, from the barren mountains;
for let us feel as we may, we have, since leaving Utrecht,
been unable to convey our meaning to the people in general,
and appointed no meeting--what our passing through, and being as gazing stocks may do,
must be left; it will, I trust, increase our humiliation, if no other good be done.`"

"`24th. In a little retirement this morning
light seemed to shine on a public meeting here,
the Menonists, agreeing to give the use of their house at 4 o`'clock in the afternoon;
a few of these, with some Moravians, and Inspirants, attended.
Joseph Mortimer, a single brother from Yorkshire, kindly acted as interpreter for us.
Feeling a little desire in my heart to call on a man
whose countenance had struck me in the meeting,
we went: on entering the house a salutation of love arose, and a memorable season ensued,
which to me seemed like a brook by the way,
consolatory after a season of great trial and drought--and we left Nieuvied
with renewed feelings of that love which had nearly united us to many there.`

"`We got to Wisbaden the evening of the 26th,
and met with an Englishman who accompanied us to several bathing houses,
this place being famous for an extraordinary boiling spring of a sulphureous nature,
which is communicated by pipes to the different houses.
From there we proceeded to Frankfort, a fine populous town,
remarkable for the liberties it possesses, being governed by its own magistrates,
who are Lutherans; it is supposed to contain twenty thousand inhabitants,
and among these three thousand Jews.
No man pays more than five pounds a-year taxes,
which commences on his declaring himself worth fifteen hundred pounds.
This city being so privileged is a thriving one, and not obliged to take part in war,
unless the empire be invaded.`"

"`Here we met one called a Pietist,
with whom we had some religious conversation to our mutual comfort.`"

"`From Frankfort we pursued our journey through Fridburg, and some parts of Suabia,
and being favored with delightful weather, and having little delay,
we arrived at Basle the 3rd of the Fifth month.`"

"`4th. Had a little season of quiet retirement alone,
and in the evening we went to see a person named Brenan,
with whom Claude Gay lodged for three weeks--he and another
old man lived retired--they are of the sect of Inspirants;
several met us to tea, and religious conference ensuing,
liberty was felt in recommending silent wailing for ability to worship.
This sitting renewed that fellowship which is indeed the bond of the saints`' peace,
and the harmony in service increased that cement,
which is as precious ointment sending forth a sweet savor.
We went to supper with Jean Christe,
a Moravian to whom we were recommended from Nieuvied; several of that sect were with us,
and we had a satisfactory time of innocent cheerfulness and freedom.`"

"`5th, Sat as usual together in our chamber;
my mind was under some exercise about a public meeting,
but I felt fearful of mentioning it; our friend Christe came to tea with us:
the symptoms of being measurably redeemed are obvious in this man;
we all felt much love in our hearts towards him, and his seemed opened to us.
J+++.+++ Sulger, a Moravian, who understands English, kindly interprets for us;
in him also the seed of life appears to shoot forth in grain which we hope is ripening.
Oh! if these visited ones were but inward enough, how would their growth be forwarded!`"

"`6th. Went to tea with a large company of Moravians;
some of their inquiries respecting women`'s preaching and the nature of our visit,
were answered to apparent satisfaction,
but our minds being drawn into silence we found it a
close conflict to yield--the company were ready to hear,
or talk, but the opposition in them to silence, and our nature pleading to be excused,
brought on deep exercise.
Our friend Sulger asked if he should desire them to be still;
this was a relief to Sarah Grubb, and myself, and she was, after some time of stillness,
engaged to explain the nature of true worship,
and the necessity of waiting for preparation to perform it.
They again began talking, to show their approbation of what had been said;
but silence being again requested, George Dillwyn followed with good authority,
and I thought some of them then felt what true silence was, particularly our interpreter,
to whom, as well as through him, I believe, the testimony flowed.
I sat some time in close travail, desiring that the people might feel as well as hear,
but found it a great trial to speak what seemed given me for them;
at length love prevailed, and this memorable season, which closed in solemn prayer,
was to me, one of the most relieving since I came on the continent.`"

"`We went to sup with the two dear old men, J. Christe accompanying us;
it was a pleasant visit--peace evidently surrounding the dwelling:
on parting I just remembered how Jacob was favored near the close of his life,
and what worship he performed leaning on his staff; after reviving which,
we left them in love.`"

"`7th. Our men Friends called on a few persons at a little distance from town,
and in the evening we all went to J. C.`'s, where after some time,
silence was procured, several young people being present,
to whom our minds were drawn in feeling of gospel solicitude,
which we were enabled to evince; and although this season was a strange thing to,
I believe, all, except ourselves, what was said seemed well taken,
and we felt peace in having yielded to this manifestation of duty.`"

"`8th. On a little comparing our feelings this morning,
we thought it best to appoint a meeting: many difficulties occurred,
but at length our friends J. and H. Brenan agreed to give us a room in their house.
It proved a deeply exercising season,
though strength was mercifully afforded to express the feelings that were raised:
but the opposition to this way of worship was, I believe,
clearly felt to obstruct the stream from running as it otherwise might.
Those called Inspirants have a great dislike to women`'s preaching,
and our transgression in this respect, probably did not suit them; we however felt easy,
and this little act of dedication tended to an increase of peace,
and cleared the way for moving on.`"

"`9th. Parted with our dear friends at Basle under a sense of uniting love,
and travelled through a beautiful country,
richly diversified by nature and improved by art, to Geneva,
where I was confined one day by illness at a poor inn:
here we got an account of our friends John Eliot and Adey Bellamy having arrived at Lyons.
Though I was still greatly indisposed, we set forward on the 16th,
and travelled through almost incessant rain to Chalons, a little French village,
where we were indifferently entertained and lodged at a very dirty inn.
Next day we had a romantic ride between very high rocks and mountains--
strong torrents of water pouring with wonderful rapidity,
some not less than three hundred feet,
with perpendicular and sloping falls--these emptying themselves into a lake below,
and from there into the Rhone.
This scene of grandeur was rendered awful by remarkably loud claps of thunder,
and vivid flashes of lightning, which continued some hours,
accompanied by heavy hail storms and rain.
Through divine preservation we got to a tolerable inn to sleep,
and were favored to reach Lyons the evening of the 18th;
where the interview with our dear friends proved mutually comforting;
and I had fresh cause for thankfulness in
finding several letters from my beloved husband,
conveying the intelligence of all being well.
This, after suffering much from anxiety about home, was humbling to my heart.
May I learn increasingly to commit all into the divine hand!`"

"`We proceeded from Lyons in a carriage boat down the Rhone,
passing many towns and villages, on the banks of this rapid river; landed at Pont Esprit,
and reached Nismes in the afternoon of the 22nd;
from which we proceeded next day to Congenies,^
footnote:[Congenies is a small village in the department of the Garde, where,
and in the several adjacent places, a number of persons reside,
who profess nearly the same principles as those held by Friends in this country,
although they are not yet recognized as members of our religious Society.]
about three leagues distant.`"

On the coach stopping at a little inn where we designed to alight,
a large number of people surrounded us, some looking almost overcome with joy,
others surprised, some smiling, but all behaving civilly.
Our men Friends alighting in order to make arrangements for our reception,
left us women in the coach;
but such was the covering with which my mind was then favored,
that being a spectacle to thousands would have seemed trifling to me; tears flowed,
from a renewed sense of unmerited regard,
and the extension of the love of the universal parent to His children,
spread a serenity not easily set forth.`"

We were desired to accompany some who joined us to a neighboring house,
and the room we entered was soon tilled with persons, who,
by every testimony we could comprehend, rejoiced in seeing us;
though many expressed their feelings only by tears.
They reluctantly consented for the first night,
to our occupying three tolerably commodious bed-chambers at the house of a Protestant,
(but not one professing as they do,)
and we designed to engage these rooms,
with another for a kitchen, and hire a servant to attend on us:
but before we were dressed next morning,
several of these affectionate poor women carried off our trunks, etc.;
and on consulting together,
we concluded it was best to yield to the wishes of those we came to visit,
resigning the personal convenience we might enjoy,
in being permitted to provide for ourselves.
We therefore accepted apartments in two of their houses,
and while these and their manner of cooking,
are very different to what we have ever been accustomed to,
the belief that we are herein right direction,
smooths what would otherwise be hard to bear.
Their love for our company is such that they seldom leave us alone,
and-seem to think they cannot do enough to make us comfortable.

"`A few both of the men and women are sensible, intelligent persons, with whom,
could we converse, some of us would be well pleased.`"

"`We are well aware,
that speaking only through an interpreter obstructs the stream of freedom,
and yet I have thought that even this might have its use,
by tending to prevent too much conversation,
and thereby drawing their and our minds from that stale of watchfulness,
wherein receiving suitable supplies,
we may be qualified properly to administer in due season to their needs.`"

"`First-day,
25th. Their meeting this morning was attended by between eighty and ninety persons:
soon after sitting down several of them appeared strangely agitated,
and no less than five spoke one after another,
partly in testimony and partly in supplication, all sitting except one man,
who stood up and expressed a little in humility and tenderness.`"

"`We found that our safety was in getting to our own exercise, desiring,
as ability was afforded, that the right seed might rise into dominion,
and the imaginations of the creature be brought into subjection:
and though it was evident, that but few of them were acquainted with that silence,
wherein the willings and workings of nature are reduced,
and the still small voice which succeeds the wind and the fire, intelligibly heard,
yet we were comforted in observing much of this emotion subside,
and the meeting was favored towards the conclusion, with a solemnity it lacked before;
the people settling more into stillness,
while testimony and prayer went forth through George Dillwyn`"

"`Thinking that sympathy with them in their different growths, and situations,
was likely to be more fully known by a discriminating visit,
we proposed after having our certificates read this evening,
to sit with them in their families, which proposal they gladly accepted.`"

"`Sixth month 4th. Since the 20th ult.
we have sat with twelve families in this village--one at Fontanes, six miles distant,
two at Quisac, nine miles further, and one at Calvisson, one and a half-mile from hence;
at this last mentioned place resides Louis Majolier,
who has been our attentive companion in the family sittings, and at our lodging,
since we first came; he is a sensible, intelligent young man,
evidently under the tendering visitation of Truth,
and humbly desirous of right instruction.
As is often the case among the more privileged members of our religious Society,
we have in many of these visits to struggle hard for the arising of life;
some of those we sit with seeming unacquainted with the
necessity of witnessing the dominion of that divine power,
which is the crown of glory and diadem of beauty to the true Israel:
but there are others, who, having measurably learned where to wait,
we believe are a little strengthened by our sympathy with them,
and receive with joy the communicated word.
In some seasons this has had free course, many, like thirsty ground,
drinking in the rain; so that the watered,
and those who have been renewedly helped to water, have rejoiced together.`"

"`Their appearance, manner of behavior, etc.,
are certainly such as bear little resemblance to our Society;
but the honest simplicity there is among them,
the apparent consciousness of their deficiencies, and tenderness of spirit,
confirm our hope of a clearer prospect opening in due season.
We have not felt it our business,
to call their attention to the different branches of our Christian testimony;
the little labor bestowed tending to centre them
to that '`light which makes manifest,`' and,
by an obedience whereto, the gradual advances of the '`perfect day`' is known;
and we are greatly deceived if this day has not dawned upon many in this dark corner,
though its brightness is yet intercepted by shades and clouds.
Their meeting last first-day was different from the former,
only one disturbing the quiet of it,
and none of those agitations which were apparent in the preceding assembly.
In the afternoon they held their Monthly Meeting,
the business whereof is only the care of their poor,
and oversight of each other`'s moral conduct; but our men Friends,
who understand the language, observed that their method far exceeded their expectations.
This season was also graciously regarded,
and renewed help afforded for the service required.
The company of John Eliot and Adey Bellamy, is truly pleasant,
and their facility in speaking French helpful; they lodge at a Friend`'s named Marignan,
and we at a widow Benezet`'s.`"

"`5th. I rose very poorly this morning, but set off with my companions for Codognan,
a place where about fifteen of the same profession with those here reside;
and feeling easy to take them collectively, we had but one sitting with them,
which was a season of openness in labor, though one of deep exercise,
they being mostly outward in their views, and very restless: towards the close, however,
some careless minds were, I hope, a little reached.
We returned to Confjenies in the evening.`"

"`6th. In a conference together this forenoon,
we concluded to have the most weighty part of the people here together,
and have a sitting with them; and after selecting some names for this purpose,
at four in the afternoon sat with a family who came from the country.`"

"`This was to me a season of instruction,
under a feeling of the universal regard of Him
who knows the various situations of His children,
not respecting the persons of any.
What was said to these poor people seemed to have entrance, and tended to our peace.
At six o`'clock we met as appointed with those selected; much freedom of speech was used,
in pointing out to them some inconsistencies,
and recommending to increasing watchfulness that being swift to hear, and slow to speak,
they might be enabled to distinguish the Shepherd`'s voice and follow it,
refusing to obey that of the stranger.
I hope this was a profitable season to them and us.`"

"`7th. We went about a league to sit with a few professors--rather a low time,
though liberty was felt to express what arose; and we parted under humbling feelings,
returning to Congenies to tea.`"

"`8th. First-day, about ten o`'clock, we met as usual:
the assembly was soon covered with great stillness, and evident solemnity,
which I sincerely desired might not be lessened by me,
though I believed it right to revive the language of David,
'`One thing have I desired of the Lord, that will I seek after;
that I may dwell in the house of the Lord all the days of my life,
to behold the beauty of the Lord,
and to inquire in His temple.`'
I felt renewed help in communicating what arose,
and the sense of good seemed to increase,
while the stream of gospel ministry flowed through other instruments;
and our spirits were bowed in awful reverence before Him,
who had not sent us a warfare at our own cost, but graciously supplied every lack.
They were afterwards recommended by Sarah Grubb, and myself, to be not only hearers,
but doers of the law, and, like Mary,
to ponder the sayings they had heard in their hearts, keeping up the watch.`"

"`I had previously mentioned to our company a view of
having the younger and unmarried people assembled;
and at the close of this meeting it was proposed to
have them convened at four o`'clock in the afternoon.
At two, we sat with nine persons who came from a distance, to satisfaction;
and at the time appointed met our young Friends,
who made a considerable appearance as to numbers.
The forepart of this sitting was heavy, but life gradually arose,
and sweet liberty ensued: our belief being confirmed that there is, among this class,
though in an unfavorable soil, a seed sown, which through individual faithfulness,
would spread and become fruitful to the praise of the great husbandman.
These were honestly cautioned against what might retard their growth,
and earnest prayer was offered on their behalf Some of us feeling
desirous of having a meeting with the inhabitants of this place,
the subject was solidly considered among ourselves,
and notwithstanding apparent difficulties, we agreed to attempt it.`"

"`By the laws of the land no public meeting is allowed to any but the Catholics,
Protestants meeting even here in the fields or private houses,
and the dear people we are visiting sit in their assemblies with the outside door locked;
and believing they had not yet attained sufficient
strength to be exposed to much suffering,
we have feared putting them out of their usual way; the proposal, however,
of giving liberty to any of the neighbors who might incline to acce.pt the invitation,
was readily acceded to by them.
At ten o`'clock on the morning of the tenth, a considerable number of Protestants,
and some Roman Catholics, assembled; they behaved with great quietness,
and the meeting was mercifully owned by a feeling of liberty to labor,
and a sense of that love which is universal,
and would gather all under its blessed influence.`"

"`11th. We rose early,
and after breakfast most of those we had visited
in the village collecting in our apartment,
a solemnity covered us,
under which the same love which had attracted us to them flowed in a strong current,
and the language of the apostle was revived, '`Finally, brethren, farewell!
Be of one mind, live in peace,
and the God of love and peace shall be with you.`' We parted,
with many tears on both sides, from these endeared people, for whom we had,
in our different measures, travailed that Christ might be formed in them,
and they be not only the visited, but redeemed of the Lord.
L+++.+++ Majolier and F. Benezet accompanied us to a town called St. Giles,
where we lodged at a comfortable house belonging to one of our Friends,
and on the 12th had a meeting with such as resided in the place;
next day I became alarmingly ill,
and was not able to join my companions in sitting with some who came from the country.`"

"`14th. My illness so increased that towards noon I
doubted my continuing long if not relieved.
My dear Sarah Grubb was poorly also:
what trials of faith and patience are permitted for the proving of some;
no doubt in unerring wisdom!`"

"`15th. Though still much indisposed I was not easy to stay from meeting;
therefore arose, and was made renewedly sensible, that when the creature is so reduced,
as to know indeed that it can do nothing.
He who is strength in weakness shows himself strong.
I was helped to discharge myself honestly, to my own peace,
and the meeting concluded in awful prayer and praise.`"

"`16th. We left St. Giles, and spent that night at Nismes;
here we experienced fresh conflict with respect to the way of proceeding; next day,
however, our difficulties seemed to lessen,
and the prospect of going to Alenon opened with clearness.
We had a solemn parting with dear L. Majolier who felt very near to us,
and to whom the language '`Be steadfast, immovable,`' etc.,
was addressed in the fresh flowing of gospel love.`"

"`We travelled from Nismes in a tedious manner,
drawn by mules at the rate of about thirty miles a day, rising early,
and late taking rest.
The country abounds with vineyards, olive yards, fig and mulberry trees;
pomegranates growing in the hedges like our white thorn,
and the air in some places rendered fragrant by aromatic herbs,
springing up spontaneously in rocky ground.
There is but little pasture land in these parts; a rudeness in appearance,
with the lack of neat fences, etc., render the country less beautiful than ours:
the houses are dirty, and the people slovenly;
they seem chiefly employed in making wine and raising silk-worms,
which give them profitable produce.
There was neither a cow nor a milch, goat in the village of Congenies.`"

"`We got to Lyons fatigued and poorly on the 21st: here I was again very ill,
and mostly in bed, till second-day afternoon, when we set out in three voitures,
and proceeded agreeably through a beautiful fertile country, richly improved,
fine pasture and corn fields,
and walnut trees frequently bounding each side of the road for miles together.`"

"`We arrived at Paris on the evening of the 29th,
and left it again the 2nd of the seventh month, traveling post to Alencon;
here our friend J. M. met us, and we went in his coach to Desvignes,
his place of residence, about a league distant; we were kindly received by his wife,
and being weak and weary, found this resting place comfortable.`"

"`6th. A solemn sitting with J. M., his wife, and little son,
was graciously owned by divine regard,
and sympathy renewedly felt with the hidden seed in a state of proving, as in the winter.
In a little conference among ourselves,
afterwards George Dillwyn avowed his prospect of going to Guernsey;
the idea of parting felt trying,
but the belief that it is individual faithfulness which constitutes Christian harmony,
tended to produce resignation.`"

"`8th. With a savor of good, covering all our minds, we took leave of this family;
and at Alencon under somewhat of solemn sadness,
parted with our endeared companions George and Sarah
Dillwyn and J. M. going with them to Guernsey,
and the remainder of our little band proceeding towards Dieppe,
where we arrived the afternoon of the 10th. We
were called up at four o`'clock next morning,
got on board the Princess Royal packet about six,
and through the extension of continued goodness, were favored with a fine,
though rather tedious passage of twenty-three hours,
landing at Brighthelmstone on seventh-day morning.
We went on that afternoon to East Grinstead, and from there twenty miles,
on first-day morning, to Croydon; attended meeting there, and reached London to tea.
In this great city our five-fold cord untwisted,
Robert and Sarah Grubb going to Richard Chester`'s, Adey Bellamy to his own house,
and John Eliot and I to Bartholomew-close;
where the company of dear M. E. and her children was a real consolation to my poor mind,
feeling this hospitable mansion as a second home.`"

"`14th. Attended the Quarterly Meeting for London and Middlesex,
which was large and favored.
We feel, I trust,
humbly thankful at being once more indulged with seeing many near and dear friends,
whose affectionate reception of us,
seems a cordial to our spirits after our various exercises.
We attended many different meetings in the city,
and on the 21st returned to the Morning Meeting the certificates received therefrom,
and gave a little account of our movements in this arduous service,
of which a record was made on their books.
After this I was confined for nearly a week, by illness,
having struggled for several days with symptoms of inflammation on the lungs,
but yielding to the advice of my friends to consult a doctor,
his prescriptions have so far succeeded, that, through abundant goodness, I am now,
(on the 28th,) considerably better, though sensible of having a weak chest,
and being still hoarse.`"

"`29th. Left London and got to Brentford to tea,
where at the peaceful dwelling of our valuable friend T. Finch, we spent a pleasant, and,
I trust, profitable evening.
We attended meetings at Uxbridge and Amersham, on fourth and fifth-days,
and on the evening of the latter had one at High Wycomb, which was large,
and I think satisfactory.
Some private opportunities in this place were graciously owned by heavenly regard:
how do the preservation and growth of the dear young people among us,
excite earnest solicitude and breathing of spirit.`"

"`Eighth month 2nd. We reached Burford this forenoon,
and went to the house of our friend Thomas Huntley, with whose scholars, sixty in number,
we had a season of retirement, which was mercifully favored by the overshadowing of good.
We proceeded to Cirencester, and remained over their forenoon meeting on first-day,
which was deeply exercising to our minds,
the pure life feeling in a state of imprisonment: but in a little sitting after dinner,
at a Friend`'s house, where several were present,
we felt some hope that this short tarriance might not prove altogether in vain.
Having had a prospect of that little stripped spot, Painswick,
we felt easy to leave Cirencester afternoon meeting,
and go there to one appointed for seven o`'clock in the evening.
A large number of Methodists and others, attended,
and I trust no harm was done to the precious cause.
We were affectionately entertained at the house of our friend Davis.
Next day we called on the few families of Friends residing there,
and after several seasons of liberty and favor,
went on second-day afternoon from there to Gloucester.`"

"`4th. This morning we breakfasted with the only Friends residing here,
and in a time of quiet afterwards,
were enabled to discharge our minds towards the family.
We proceeded to Monmouth, and from there to Pontypool,
where we had an appointed meeting on fifth-day.`"

My dear mother`'s account ends here,
but there is reason to believe that she and her companions attended
meetings at Swansea and Haverfordwest in their way to Milford,
from which they sailed to Waterford,
and she was favored to reach her own habitation
in safety about the middle of the eighth month,
worn indeed in body, but with a relieved and thankful mind;
and in alluding to her late engagement, she writes as follows:

"`Under various deep exercises during this journey,
the language '`Why did you doubt!`' has been so legibly inscribed on my heart,
that I often think none has greater cause to depend on
the Arm of everlasting help than I have;
and the confirming evidence of a peace passing every enjoyment,
has been as a stay in the midst of conflict, an anchor`' in times of storm;
nor do I ever remember feeling a more abiding sense of this heavenly treasure,
than during my residence with that dear little flock at Congenies,
towards whom the current of gospel love still sweetly flows.`"
