== Chapter V

[.chapter-synopsis]
* From Twelfth month 1788, to Third month 1792
* Family visit in Cork
* Journey to Ulster Province
* Public Meetings in some parts of Munsler

In the twelfth month, 1788, being at her own quarterly meeting, held in Cork,
my dear mother felt a pressure of mind to unite
with Sarah Robert Grubb and Elizabeth Tuke,
in a visit to the families belonging to that monthly meeting,
but her affectionate attraction to home, induced her to attempt returning,
without an avowal of the concern she was under.
Her conflicts on this account, and some particulars of the arduous engagement,
are stated in letters to her husband,
and the following extracts seem calculated to
prove both instructive and encouraging to some,
who may be able to trace their own feelings in the experience here described.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`Cork, twelfth month, 15th, 1788.

It has turned out as I believe you expected it would, and I am once more in this place;
after you left me I determined to proceed for meeting you under our own roof this night,
and even set out for that purpose.
On entering the carriage, I instantly felt darkness cover my mind, still I went on,
but I never remember being quite so much distressed--rebellion--rebellion,
sounded through my heart, and I grew so ill, that I dared not proceed;
so turned about and had a comparatively lightsome journey here,
my body and mind feeling gradually relieved.
We reached Edward Hatton`'s to dinner,
but the conflict I had sustained made me require a little rest,
so that I did not get outwardly banded in this service till the evening,
when a harmonious exercise and labor were afforded,
as a comforting evidence of rectitude so far--
perhaps a few sittings may relieve my poor mind;
you know how gladly I shall embrace the dawning of release.

You will readily believe that our dwellings are not in the heights,
though I trust we are sometimes so helped to ascend the Lord`'s holy mountain,
as experimentally to know there is nothing there that can hurt or destroy;
it seems a time when rather the invitations than
threatenings of the gospel are to be proclaimed,
and I think there does seem an open door for communication, though it be sometimes sad,
because of the things which have happened.
I am far from being satisfied with myself, but I am truly so with my fellow-laborers,
and with my return to this city, even though bonds and afflictions await us in it.
Why should we not suffer when the seed suffers?
Where else would be our unity with this seed, which lies in a state of captivity?
There are now about twenty-nine families got through,
and I trust it may be humbly and gratefully acknowledged,
that hitherto the Lord has helped.

I may honestly confess that I am still bound to this arduous work,
and through divine mercy we are not only sustained, but have a little trust at seasons,
that '`the labor is not in vain.`' Some sittings have been graciously owned,
but I know not any so much so,
with the sensible gathering of that manna which falls from the heavenly treasury,
as one this morning in the dwelling of that prince in Israel, Samuel Neale,
whose outward man is visibly decaying, while the inward man is renewed day by day.
The spring seemed to open on our sitting down,
and the waters gradually rose as from the ankles,
till the refreshing consolation truly gladdened the Lord`'s heritage,
that in us which could own His planting, and by His renewed watering, glorify him.
It was truly encouraging and strengthening to hear this father in the church declare,
that he had not flinched from whatever had been required of him,
but had done it with all his might, and that, through divine mercy,
he now found support in the midst of infirmities, '`therefore,`' he added, '`be faithful,
follow the Lord fully,
and give up to every manifestation of His will.`'
We received a note declining an intended visit.
I confess such a repulse made me exceedingly low,
having had a particular feeling towards this family,
but I believe it safest to look from it; perhaps even this offer of ourselves may recur,
and not be useless, though we see it not; we could do no more than seek an interview,
and love still prevails towards them.

Yesterday was the three weeks`' meeting here, which we attended,
visiting our brethren also; hope no harm was done.
I am afraid of no one but myself, and I desire always to suspect that enemy self,
lest on any occasion, it should take the lead; but under heavy pressures here,
I have a degree of hope, that not going this warfare at my own cost,
I may yet be helped to the end of it, which now draws nigh,
having gone through about eighty-five families, and only a few remaining.`"

--

The next religious service of which there is any account,
was a visit to some part of Leinster Province, early in the year 17 90,
wherein her former companion Richard Shackleton, was her kind attendant and helper,
and her dear friend Elizabeth Pim united in a part of the work.
During this engagement she visited the families comprising the monthly meetings of Moate,
Edenderry, and Carlow, which she describes as a '`service closely trying,`' yet,
productive of solid peace, and near the winding up of this labor writes as follows:

"`Many are my fears and doubtings before willingness
is wrought in me to leave such endeared connections,
and many my tossings and conflicts, in seasons of separation; but may I,
with increasing devotedness, trust in the Arm of never-failing help.
Through unmerited mercy the Lord has not only given a degree of resignation to leave all,
when the call has been clearly distinguished,
but sustained under various laborious exercises, so that the promise is indeed fulfilled,
'`as your days so shall your strength be;`' and
there is cause to trust with the whole heart,
for future direction and support.`"

Towards the close of the year she had a long and suffering illness,
as well as considerable anxiety through indisposition in her family,
her eight children being in the hooping-cough at the same time;
and the death of her beloved friend and companion, Sarah R. Grubb, in the twelfth month,
was a heavy and unexpected affliction, which for a season sunk her very low.

But in the spring of 1791,
she believed it required of her again to leave her own habitation,
and pay a religious visit to Friends of Ulster.

After attending the National Meeting in Dublin,
she accordingly proceeded with her companion Sarah Shackleton,
and having sat a meeting with the few Friends belonging to Timahoe,
went on to Castle Freeman, from which her first letter is dated.

"`Fifth month, 13th. We reached this place very agreeably,
being favored in weather and roads.
I felt in passing through part of Old-Castle,
(where Friends`' meetinghouse is, though I did not know it,)
a spring of love towards the '`sheep not of this fold;`'
but said nothing about it till we got here,
when I found that some inclined to be visited by
having a meeting held in one of their houses,
but it seemed best to attend to the previous intimation,
and I ventured to have one appointed for nine o`'clock tomorrow morning,
with notice that it will be open to such as are disposed to sit with us.
You know me well enough to be aware that this prospect tries my little stock of faith,
which is indeed low, but it can be graciously renewed, and I trust will,
from season to season, as singleness of heart and eye is kept to.`"

"`Ballybay--Monaghan, Fifth month, 15th, 1791.
Respecting the meeting at Old-Castle, it may in commemoration of holy help be recorded,
that those who trust are not confounded,
but experience strength proportioned to the day of trial.
I do not remember many assemblies of this sort, more owned with the covering of good,
and the solidity of the people during the whole
meeting exceeded what is to be often met with;
at the close of the public sitting I felt a wish that Friends might keep their seats,
and that season was also one of relief to my mind.
We took a little refreshment in the meetinghouse, and then pursued our journey,
arriving at Cootehill, twenty-five miles in the evening, tired and poorly,
but humbly thankful for the assistance every way afforded.

As there are no Friends in circumstances to accommodate travelers, we lodged at an inn,
and attended meeting at the usual hour this morning,
to which many came who are not in profession with us,
and I trust nothing was said to discourage the honest inquirers after truth.
There was a little stop afterwards with the members of our own Society,
perhaps not exceeding eleven or twelve, among them a widow and her daughter,
who have joined Friends by convincement, and appear in a solid frame of mind;
we spent a little time with these,
and had a season of retirement with a young physician who was at our meeting,
and to whom my mind was particularly drawn; he was invited to drink tea at this widow`'s,
and in the prevalence of gospel love I freely
communicated what I felt to arise towards him,
which I believe was well received, and we parted under feelings which were precious,
and caused humble thankfulness of soul.
We came on to this place to lodge,
had a meeting appointed for eleven o`'clock yesterday morning at Castle-Shane,
with a small company of Friends, among whom very little life was to be felt,
which they were, I trust honestly, told; and went on afterwards, through wind and rain,
sixteen miles to our friend Thomas Greer`'s, where we were kindly received,
and concluded to stay a day, my poor body requiring rest.`"

Her getting to such a resting-place seemed critical,
for she was almost immediately taken alarmingly ill,
having been for several days affected with a heavy cold,
and symptoms of inflammation which required medical care.
The judicious prescription of a physician, and kind attention of the family at Rhonehill,
proved the means of seasonable relief,
and on the 21st of fifth month she writes as follows:

"`I am, through continued lovingkindness, considerably better,
which I ought thankfully to acknowledge,
as my situation for same days past rendered so speedy an amendment very doubtful.`"

"`Lurgan, Fifth month,
24th. Although my dear Friends and the doctor
would have had me stay some time longer to nurse,
yet apprehending my mind might obtain a little relief
by endeavoring to fill up the line of duty,
which while unaccomplished is an oppression to the body,
I ventured yesterday afternoon to go as far as Berna,
where our truly kind friend Thomas Greer,
sent me and my dear Sarah Shackleton, in his carriage; many Friends met us there,
and we were favored after tea with the spreading of the holy wing,
in a manner that I believe tended to the gathering and
centering nearly all present in a state of humble waiting,
wherein an enlargement of mind was experienced, to dip into feeling with,
and administer to, several states in the company; it was a season worth suffering for,
and we returned to our lodgings relieved in mind.`"

"`This morning while preparing to move on,
we felt a little stop which it seemed best to attend to,
and after a salutation of gospel love to the dear family at Rhonehill,
we separated in the feeling of sweet affectionate nearness;
Thomas Greer coming several miles with us.`"

"`Rathfriland, 26th. Attended the usual meeting at Lurgan yesterday,
and this morning that at Moyallen, both proving seasons of deeply exercising feeling,
the doctrine which opened being of a very close nature, and trying to deliver,
but assistance was graciously afforded to my humble admiration.`"

"`In getting so far through this Province,
it seems to me that no superficial work will avail,
nor anything short of a willingness to get down into deep feeling with the seed,
in its imprisoned and oppressed state, and administering as enabled to its needs;
in this exercise none can, I believe,
have an adequate idea of what conflicts await the poor mind,
but those who are thus introduced into them.
I know my capacity for right understanding
is far inferior to many of my brethren and sisters in the work;
but it seems as much as body and mind can at times bear,
to feel in my small measure for the hurt of the daughter of my people,
too many of whom feel not for themselves,
and I fear come under the description of the whole who need not a physician;
so that though there is abundant balm in Gilead, they remain unhealed;
though there is a sovereign physician there, they are unrestored.
Among such as these, if anything be uttered, it must indeed be a plaintive song,
a language of mourning and bitter lamentation, for many are falling before the enemy,
and carried away captive as into a strange land.`"

"`The meeting at Rathfriland on sixth-day,
was attended by most of the members and professors, a small company, and one,
among whom I think there was less of the moving of spiritual life,
than in any other spot we have been at.
The seed of the kingdom felt to me in a state,
where it could not be ministered to but by Almighty power;
the struggle for its arising was, however, mercifully continued, and through best help,
victory so far experienced,
that supplication could be vocally poured forth to the Fountain of light and life:
blessed be the name of Him whose throne of grace is ever accessible to faith.`"

"`We returned to our lodgings,
and after a season of honest plain dealing with the heads of the family,
and feeling with and about the large flock committed to
their charge in the wilderness of this world,
we felt clear of this trying spot, and proceeded to Stramore.`"

"`Lurgan, 31st. We attended Ballinderry meeting on first-day, which,
like all others we have here, was an exercising season; we returned here,
and in an evening sitting in this family, were, through unfailing mercy,
owned by the overshadowing of the holy wing.`"

"`Yesterday afternoon we went to see Mary Ann Clibborn,
who appears near being removed from a family of eleven children.
After a time of religious retirement with the afflicted Friend,
we sat awhile with the children and their father in another room,
which proved a season of merciful condescension, in not only opening the gospel spring,
but causing it to shed a softening influence,
so as to excite a consoling hope that the bread cast upon the waters may not be lost.
These visits produced real relief of mind, and indeed our feelings while in the house,
tended to renew a humble confidence in the leadings of unerring Wisdom,
at the same time bowing in that abasedness of self, wherein the heartfelt language is,
'`not unto us, O Lord, but to Your name be the praise,
when any little ability is renewed to labor for the promotion of Your blessed cause.`"

"`I had from the period of our first being in Lurgan felt inclined to return,
and though the visit already mentioned was one attraction, there was a further exercise,
even the prospect of another meeting, which I wished the inhabitants might attend;
but faith was very low, and it was accompanied with, I trust,
some little knowledge of myself, so that though I did intimate it,
I requested the notice might be confined: the meeting was largely attended by Friends,
and many not in profession with us were there also,
but an inconsiderable number to what might have been, had faith been strong enough;
however I may thankfully acknowledge it was a season of renewed instruction,
and life did in degree triumph over the death that seemed to threaten.`"

"`Gracious regard has again been manifested in a
season of retirement with some young people,
and heartfelt satisfaction experienced.
Thus we get on in a hobbling way,
yet I trust are in our right places so far; a hope which reconciles to difficulties,
and helps in a measure to surmount them.`"

"`Maze, near Lisburn, sixth month,
4th. On fifth-day morning we went from Lurgan to Ballinderry, sat a meeting there,
which was rather large, though a widely scattered settlement in a country place;
life was exceedingly low, but I thought rather increased towards the last,
liberty being felt to deliver close doctrine among them; we,
took a cold repast in a little cottage near the meetinghouse,
and Louisa Conran joining us, returned home with her and lodged.
Went next morning to the Monthly Meeting at Lisburn,
that for worship was passed in silent suffering;
the women`'s meeting was rather a relieving one to my mind.
At six o`'clock in the evening we attended the select meeting,
wherein a little light graciously shone,
and something of Christian fellowship was witnessed.`"

"`Yesterday afternoon an appointed meeting was held at Hillsborough,
the number present but small,
and to my apprehension little life was prevalent among them;
only a few of other professions attended,
and I thought the season clouded from too great a desire for words,
which tended to obstruct the arising of the
spring in the manner it might have been known,
had each been engaged to dig for the pure flowing thereof into their own hearts.`"

"`Lurgan, 8th. On first-day I was confined at John Conran`'s by indisposition,
and on second we went to Lisburn and called on a few of the families,
which proved a means of relief from some painful feelings.
Being so inclined we passed one night under the
roof of our tried friend Jonathan Richardson,
who lately lost his lovely wife in a consumption.
The Monthly Meeting here occurring, we attended it; that for worship rather low,
the succeeding one more open,
and the select meeting in the evening favored in the unity of life,
and a time wherein the liberty of the gospel was felt.`"

"`Lurgan, 13th. We arrived at Rhonehill on fifth-day,
and met as before a truly cordial reception.
Next day was the Quarterly Meeting of Ministers and Elders, which held long,
and was a very exercising season; some circumstances being unpleasantly handled,
caused a cloud to darken our hemisphere, but through favor this measurably dispersed,
and before our separation a degree of light and life spread over us.
The meetings for discipline on seventh,
and those for worship on first-day were very large, and mercifully owned:
my faith was low, but access being granted to the throne of grace,
ability to labor was experienced, much to the relief of my poor mind,
and I trust not to the injury of the precious cause.`"

"`On hearing of the death of Mary Ann Clibborn, I found it best to return here,
though sixteen miles additional riding, to attend the burial;
a very large number of Friends and others were assembled on the occasion;
we went to the house before meeting, and felt inclined to go again in the evening,
which some of us may be thankful we did,
from the renewed conviction that it is better to go to
the house of mourning than to that of mirth.
The bereaved husband, and ten children, were present at a solemn season,
which was marked by feelings of near sympathy,
and closed with supplication for support in the day of trouble.
The interment this day is the fourth from that house in two years,
three children and their mother!
These are indeed deeply instructive dispensations.`"

"`We purposed proceeding on third-day morning, but being very much indisposed in health,
and having gone through pretty close work for a week before,
we concluded to rest at the truly hospitable dwelling of James Christy,
before the fresh engagement of going round the Lough.`"

"`The usual meeting at Lurgan on Fourth-day was well attended by the members,
and though we had wanted to push forward, we had at this time,
cause for adopting the old proverb--a stop is no obstacle or real hindrance,
believing that our detention was in best ordering,
this meeting proving the most relieving to my mind, of any we had sat in this place.
Next morning we resumed our journey, and travelled through much wind and rain to Antrim,
seventeen miles from Lurgan, where only a few Friends reside.
We concluded to sit with this poor little flock in
their meetinghouse at six o`'clock in the evening;
there were several present,
who through one means or other had forfeited their right to membership,
though we knew not hereof, nor aught about them until after meeting;
the line of reproving doctrine ran closely, while the honest-hearted were, I trust,
encouraged to hold on their way, and though a suffering season,
it closed with renewed cause for humble thankfulness to our Almighty helper.`"

"`Sixth-day, the 17th. We went to Ballymena, near which one family under our name resides.
It had been usual for this family to meet Friends who were traveling,
at one of the meetings, but I felt an unusual inclination to go to them,
though it cost us a few more miles riding,
and as soon as we entered the town I thought I
understood why the impulse was so strong to visit it;
but I kept the pressure my mind was under to myself, and no meetinghouse being there,
nor Friends residing in the place, felt discouraging.
However, on going up stairs at the inn, I observed two rooms with folding doors,
which being opened made the whole pretty large; so I gave way to the impression,
and had notice circulated of a meeting, to which, besides the few Friends,
about forty persons came,
who sat in much quietness and solidity during the time of silence.
A solemn covering was evident, to the humbling of our spirits,
and in the prevalence of gospel love the testimony of Truth was a little opened,
gracious help being afforded beyond what I could have asked or expected,
so that I could renewedly say it is good to trust in You--yes,
none ever trusted and was confounded.`"

"`This morning we set out after breakfast, and a few miles from the town,
our guide informing us there was a settlement of
Moravians at a little village he pointed to,
I inclined to call on them: so we turned off the road,
and went up to the house of the single sisters, where we were kindly received;
and finding that I had been acquainted with many of their people in Germany,
produced additional attention to us.
They took us over their chambers, chapel, etc.,
and showed us the various works they wrought,
and afterwards requested us to take a bit of bread; we did so in the matron`'s apartment,
who appeared a religious, feeling woman, as was the case with several others of them,
and this little visit seemed mutually satisfactory and pleasant.
We got here to tea, and propose remaining over meeting tomorrow.`"

"`Toberhead, sixth month, 21st. We left Ballinnacree second-day morning,
and reached this place in the evening,
where we met a truly kind reception in the garb of simple hospitality,
and feel very comfortable in the humble dwelling of our dear friend Gervas Johnson,
attended by his two daughters, who, with their parents,
endeavor to make our little tarriance here pleasant,
and indeed it is much more so than many superior habitations would prove.
At the meeting here this day the house was nearly full of Presbyterians, the preacher,
his wife, and the clerk of their meeting among them; it was a season of liberty.`"

"`There seems an invitation in these parts, as well as others,
to those not professing as we do.
Oh! that all may be gathered to the teaching of Christ Jesus the true Shepherd.
Since tea we have been favored with a solemn season together in this family,
where the precious life cemented our spirits,
and under its prevalence a little of the oil ran
through some vessels towards the beloved youth.`"

"`Lurgan, 23rd. We arrived here this evening to tea,
after traveling seventeen miles of remarkably rough road, so much so,
that we were not only greatly shaken, but our chaise injured:
we have travelled since this day week about one hundred miles, had five meetings,
and several family sittings; the last meeting yesterday at Grange,
from which we proceeded to Antrim, nine miles, to lodge.
We intend to rest here awhile, feeling to require it after this journey,
which has been truly exercising every way,
but accompanied with a little of that peace which is worth suffering to obtain.`"

"`Maze, Seventh month, 4th. I was painfully confined more than a week at Lurgan,
and feel considerably reduced in strength by this attack,
but was enabled to get to meeting there on fourth-day;
my body suffered so much from the exercise which then fell to my lot,
that though we had concluded to leave Lurgan the same afternoon,
we gave up to rest a day or two longer.
On seventh-day we proceeded here, and yesterday morning went to meeting at Lisburn,
where, as in one I before sat in this place,
my mind was deeply pained and oppressed from the
prevalence of a spirit which was thirsting for words,
and sustained itself on the labor of others, without any exercise of its own,
after that food which can alone nourish unto everlasting life.
I was strengthened to get some relief by an honest endeavor to
deliver what I apprehended was the counsel committed to me,
and being out of debt felt a comfortable poverty,
very different from what is brought on by withholding what is called for.`"

"`Milecross, Fourth-day 6th. A meeting at Hillsborough on second-day evening,
was attended by a tolerable number of Friends and others,
and though there was less of the dominion of pure life
than in some other opportunities of this sort,
we had cause for renewed thankfulness; and yesterday morning,
before leaving our dear friends John and Louisa Conran,
we were favored with a precious cementing season,
our spirits being baptized under a feeling of that
unity wherein '`the Lord commanded the blessing,
even life forevermore.`' We arrived here in the evening and
met a friendly reception from Thomas and Sarah Bradshaw:
a meeting is to be held in their parlor, no meetinghouse,
and but few in profession with us being here.
Which way we shall move from hence is not yet fixed.
I am earnestly desirous to feel and see the right path,
and if that be towards my tenderly beloved connections,
it will indeed be deemed a favor.`"

"`Lurgan, Seventh month, 9th. I am once more in this place,
after being not only permitted, but apprehending it right for me,
to seek that rest from close and deeply trying exercise,
which I may find in my own habitation.
My frame is exceedingly shaken,
and according to human judgment unable to bear much more at present; and though I think,
I was favored to experience,
(during the conflict I have passed through to obtain divine
certainty,) a degree of willingness to spend and be spent,
in that path whereon light shone,
I believe that a gracious Master has mercifully withdrawn, at least for the present,
the view of crossing the water,
and caused peace to rest on the conclusion to return home,
without which I hope I should feel afraid so to do.`"

"`Our closing visit at Milecross, was on several accounts remarkable,
different religious opportunities in the family being so owned by the
extension of almighty help as to produce the thankful acknowledgment,
'`Your mercies are new every morning, great is Your faithfulness and Your truth.`"

"`Dublin, Seventh month, 16th, 1791.
I told you of my exercise respecting Scotland, and present release from the prospect.
At Belfast our minds were renewedly dipped into the baptism of the cloud,
and we had to be still while it remained;
when a little light sprung up we discovered there was something required,
which being strengthened to give way to, we left that place comfortably,
and proceeded peacefully to Moyallen,
where we were sensible of gospel love to the sheep not of our fold,
and had the afternoon meeting postponed from four to five; the attendance was large,
and I trust the season was productive of no injury to the precious cause of truth,
solidity being evident.
A large company supped at our lodging,
and I think the covering we were favored with constituted a feast indeed,
and felt like a sanction to a separation from some truly beloved Friends.
Next morning we breakfasted at M. P.`'s, with whom, her twelve children,
and several near relatives, we had a season of retirement to the relief of our minds.
Feeling attracted back to Lurgan to see one family, we went there,
and next morning proceeded to Warrenstown,
where we were again favored with gracious unmerited help.`"

"`On Fifth-day morning, after a solid cementing opportunity,
of renewed feeling with and for each other,
we parted in near affection with several endeared friends,
and travelled very agreeably to Dundalk that day; twenty-seven miles further yesterday,
and this day arrived here,
under I trust some little sense of numberless
undeserved favors received from boundless mercy.
May I be so preserved as not only diligently to inquire what shall I render?
but resignedly to follow the answer, which,
from season to season a gracious Master may see fit to return,
in entire dedication to His will.`"

She returned from this journey much exhausted in body,
and was considerably indisposed for a long time,
but her mind became strengthened for increasing exercise,
and further religious service soon opened to her view.
That upon which she next entered was to the city and western parts of the county of Cork,
where she was engaged to hold meetings for those not in profession with herself.
When on the point of leaving home for this service, she wrote as follows:

"`I am going very poor and low in mind,
but hope not without knowing whom I have believed,
and whom I trust I desire humbly to follow, as His pure will is graciously revealed;
if I return with renewed experience of his preserving power and in peaceful poverty,
it will be enough.`"

The chief account of this journey is contained in letters from
which the following extracts have been taken.

"`In humble gratitude to the author of all our mercies it may be acknowledged,
that the meeting at Bandon was a time wherein holy help was afforded,
and not only a door of utterance but one of entrance opened,
by His power who opened the heart of Lydia of old.
The people were attentive, solid, and I believe many of them thoughtful;
not only inwardly inquiring what is truth?
but willing to receive the answer as there was strength to explain it;
and the consoling hope attended, that some for whom our spirits then travailed,
would be everlastingly enclosed in the true sheep-fold.
This opportunity of feeling and laboring in the ability afforded,
left solid satisfaction on our minds, with desire to commit the outcome to Him,
who orders all things according to the purpose of His own will.
In the evening we sat with the few Friends there collectively;
the labor here was abundantly more difficult, the work harder, and the hope less,
because it seems indeed, when our little church is felt with, and ministered to,
it must be as in a state of sickness,
and alas! may it not be feared that this sickness is not deeply enough felt?
therefore health is not in the sure way of being restored, which it otherwise might be.`"

"`We held a meeting at Skibbereen, which was very largely attended,
and mercifully owned by holy help,
to the humiliation of self and exaltation of that name which is above every name,
and whereto I trust some present bowed in reverent thankfulness of soul.
Next day we went, through wind and rain, to Baltimore,
a poor straggling place at the sea side, mostly inhabited by fishermen,
seafaring persons and revenue officers, who I apprehend are generally Protestants.
No suitable place could be obtained for a meeting but the public worship house,
which we were glad to accept, the feeling of gospel love being strong to the people here.
We filled one of the pews, and I believe all the others were nearly full:
the company were quiet and solid in the time of silence,
and very attentive during the communication of
those truths we had to declare among them:
indeed, soon after sitting down,
the covering of solemnity was beyond what is frequently witnessed on such occasions,
and I have a consoling hope that the labors of that day will not be altogether in vain.
You hardly expected your poor trembling wife would ever
be strengthened to move in such a line,
much less reason with the people in such a place;
but it seemed no matter where the gospel was published, if given to publish,
and indeed it added to the thankful feelings of my poor mind,
that divine mercy had enlightened my eyes to distinguish truth from error,
and substance from shadows.`"

"`Castletown has been our headquarters,
and we are now going to hold a meeting in the Custom-house,
which is preparing for the purpose; my heart is heavy at the prospect,
and every fresh exercise of this kind ought to feel weighty.
My health is as good as I could expect, though our difficulties are not a few,
and my dear E. Pim is a kind and sympathizing companion.
We are favored with having five Friends of Cork meeting,
whose company is helpful and pleasant to us.`"

The winding up of this service was rendered memorable,
by its furnishing an opportunity for visiting Samuel Neale, in his last illness,
and also of attending his burial.
He had long been an intimate and much beloved
friend of my dear mother`'s and her companion;
and manifested near sympathy and concern for them in the commencement of their journey;
inquiring, when very weak in body, how they were getting on,
and what assistance they had, in the affectionate terms,
'`who is taking care of these good women?`' On returning to
Cork they found his complaints had made rapid progress;
and it may not be uninteresting to such as knew and valued this devoted man,
to peruse a few particulars of his state, and her own feelings in witnessing it,
as related in a letter dated the 27th of second month.

[.embedded-content-document.letter]
--

"`It was awful to enter the chamber of our venerable friend,
and to behold one who had been so often the messenger
of consolation to me and to many others,
so reduced as to be almost unable to drop one collected sentence,
without immediately rambling to something different,
though all perfectly innocent and sweet as a child.
He looked at me and said,
'`You have great burdens,`' adding that it was long since he saw me.
I sat about an hour by his bedside, assisted in moving him, etc.,
but he manifested little sign of distinguishing one from another;
I scarcely expected the change would be so great in eight days; his breathing was hard,
and by many corroborating symptoms it was evident that the termination drew near.

The situation of this beloved friend has seemed to
cloud any little prospect my mind may have had,
so that it seems best to stand still until this trying dispensation is full.
Yesterday evening, after taking tea with dear Sarah Neale, I came to my lodgings,
where many Friends assembled, and a solemn season ensued,
wherein the prospect of the removal of this Elijah brought an awful covering,
and renewedly raised the inquiry,
'`Where is the Lord God of Elijah?`' who
condescended to draw near unto the minds of some,
and own their sad communications.

This evening I have been again at the house of mourning,
and waited until the last conflict terminated in everlasting peace,
of which I thought it a great favor to be permitted to feel such an evidence;
that instead of lamentation the language of praise might be uttered,
while on account of the church this renewed loss is certainly grievous.`"

--

On the 28th,
my dear mother and her companion resumed their important engagements by going to Kinsale,
where a meeting was appointed for the next day;
respecting which and subsequent religious service she writes as follows:

"`The appointment of this meeting had been an object of considerable weight,
and was given up to much in the cross,
but through continued mercy it was memorably owned by our unfailing Helper.
The number collected was very large,
and it seemed to us as if more than a few were inwardly gathered,
and like thirsty ground prepared to receive such gospel
communications as there was ability to impart.
Our stay in, and departure from this place,
were rather singularly marked by feelings of peace and thankfulness,
an abundant recompense for any little service;
and what a favor it is that the sacrifice of our wills is graciously accepted,
that our deficiencies are mercifully made up, and our transgressions pardoned:
surely we may well say, worthy is the Lord to be served and fully obeyed!`"

"`Fifth-day we had a meeting for the youth belonging to Cork meeting,
which was large and solemn; it felt comforting to be among our fellow professors,
and renewedly to believe that the extension of heavenly love is towards the children.`"

"`Fifth-day, 2nd of Third-month, was the interment of our honorable friend, Samuel Neale;
the meeting was very large, and great numbers assembled at the ground;
my dear companion was confined from both by illness, which caused me to feel lonely;
for the help of her exercised spirit,
and her labor in word and doctrine are consoling and rejoicing to my heart.
She has been frequently during this embassy clothed with gospel power,
and enlarged in her sound acceptable gift.`"

"`We had a solemn season of retirement at Edward Hatton`'s in the evening,
and apprehending that light shone upon our return, we set forward on seventh-day morning,
and I was favored to find all in good order at home that evening.
Next day commenced our province meeting,
and on the following first-day we had a public meeting at Carrick,
which was graciously owned by the covering of good, and left us in possession of peace.
This step had been long in prospect with me, but a sense of my childhood,
and the greatness of the work kept me from avowing it,
until encouraged by the experience of divine help in late engagements.`"

Soon afterwards she had a public meeting in Clonmel,
and this being the first time she had so evinced
her concern for the place where she resided,
it felt weighty in prospect,
as will appear by the following account of this important step.

"`Hadst you been here I might have been a little more valiant than I found myself,
when a matter came to the point that I long had in view,
though I never told anyone of it till, in the anguish of my heart it escaped me,
after meeting on first-day, to M. G. and E. P. on their inquiring what ailed me?
The time for the fulfillment of this prospect seemed now arrived,
and being favored in the afternoon meeting to
feel that rise into dominion wherein there was,
even vocally, a surrender of my little all, as light might be mercifully afforded,
I ventured to stop a few Friends afterwards,
and informed them of the concern I was under: they evinced much sympathy,
and encouraged me to follow apprehended duty.`"

"`The meeting was attended by a considerable number, who were generally quiet and solid;
and although there was more of darkness to encounter, and less, I thought,
of the right thirst, than in some late meetings, yet it may be thankfully acknowledged,
help was graciously extended, and that the honor of Truth being only in view,
preservation was experienced from injuring the precious cause.
I never more forcibly felt that truth, '`without me,
you can do nothing.`' May it be deeply sealed on my spirit,
and the spirits of all who move in this awful line, that so,
sufficiency being derived from Him who can alone qualify, His own name may be exalted,
and the creature laid in the dust.`"

The following letter was written in the year 1790,
and so manifests the continuance of affectionate and Christian
solicitude on behalf of her friends on the continent,
that it appears calculated to prove an acceptable termination to the present chapter.

[.embedded-content-document.letter]
--

[.salutation]
"`My beloved Friend, L. Majolier:

Were I to tell you and your dear wife, with my other valued friends at Congenies,
that I have not ceased to love you,
as often as the sensible renewings of Christian fellowship refresh my mind,
our converse in this way would be frequent; but though I may,
through continued gracious regard,
be indulged with this symptom of having passed from death unto life,
love to the brethren,
I seem but seldom under qualification to help any of my
fellow professors in their spiritual travail;
being often brought very low, not only in mind but in body;
instructed by frequent chastisements of love, that I have no continuing city here.

You, my dear friends, know some of my many infirmities,
and I often gratefully remember how affectionately you sympathized with me,
and endeavored, by your friendly attentions,
to alleviate such as I was tried with while among you; yes,
the remembrance of having been with you is pleasant,
and there are seasons when I seem so to visit you in spirit, to feel with and for you,
that I am as though personally among you, joying,
(if I may use the words of an apostle,) and rejoicing,
to behold the steadfastness of some: among these have you, beloved Louis,
refreshed my mind,
in believing that the visitation of divine love has not been extended in vain; but,
that in yielding obedience to the heavenly vision,
you have known an advancement in the line of righteousness,
and an increase in stability and peace.
Go on, my endeared friend;
the sense that often impressed my heart while with you now revives,
even that much depends on your perseverance;
not only your own and precious companion`'s welfare, but that of the little flock,
mercifully gathered by the everlasting Shepherd,
under whose holy guidance I view you delegated to lead them,
designed in the forcible language of example to encourage them,
'`to follow Christ.`'
Ah! my dear brother,
how much is implied in being a follower of Christ:
how deep ought the dwelling of such to be,
in order that a full conformity may be wrought to His will,
by a total renunciation of our own under every appearance.

The work of thorough subjection is truly a great work, and it is to be expected,
in the refining process,
that deep sufferings and closely proving conflicts should attend the exercised spirit.
'`You shall indeed drink of my cup,`' was the blessed Master`'s language,
and be baptized with.
the baptism that I am baptized with;
this is sealed in the experience of his tribulated servants;
they measurably partake of the dispensations so largely filled up by Him,
when in the prepared body, and herein their union with him is effected; but,
blessed be His name, there is a consoling declaration gone forth, if we suffer,
we shall also reign with Him.

There are seasons when such baptized sons and daughters know, even here,
through the resurrection of life, something of this sort,
when Truth rising into dominion over all in their hearts,
they are made as kings and priests unto God; and there is a season approaching, when,
being unclothed of these mortal bodies,
such shall be clothed upon with immortality and eternal life.
My heart has been unexpectedly filled to you my dear friend,
and I have given my pen liberty; if anything can be gathered up from these broken hints,
which may serve as an encouragement to you in your trying allotment, I shall be glad,
for surely I would encourage you; may you put on strength in the Lord`'s name,
and trusting therein find it a strong tower, yes, an impregnable fortress,
where the enemy cannot hurt, though he may roar and greatly disquiet.
Remember the language applied to the true church,
and which belongs to every living member therein, '`He reproved kings for your sake,
saying, touch not my anointed, and do my prophets no harm.`' And now,
having relieved my mind a little towards one, I feel a renewed salutation to you,
my endeared friends, who were collectively the objects of our visit;
a visit to which love was the moving cause,
and the consoling attendant of our minds while with you,
and which I believe we all now feel to be the cement of a union,
not broken or impaired by external separation.

In the extension of this pure principle my mind is often drawn towards you,
in fervent affectionate solicitude that the good
work mercifully begun may abundantly prosper,
and He who has been the Alpha become the glorious Omega, perfecting the new creation,
and fulfilling His gracious purpose, by making you a people to his praise.
It is, dear friends, and many of you have seen it, a gradual work; it begins,
as in the first or outward creation, with that heavenly command,
'`Let there be light.`'
There are those among you who have
intelligibly heard this in the secret of your souls,
and, through illuminating grace,
have clearly distinguished the way wherein you should walk:
now this light is to be attended to, according to what the apostle tells the believers,
'`to which you do well to take heed,`' because
it shines more and more unto the perfect day.
While we simply follow it, we come under the description of walking in the day,
and stumble not; but are, by regular gradations,
introduced into the acceptable state of children of the Lord; taught of Him,
and established in righteousness.

It is, my beloved friends, this desirable state of establishment in the right way,
that my spirit renewedly craves for you and for myself;
that every visited mind among you may become redeemed; every called, a chosen disciple,
by unreserved dedication of heart to the pure unerring leadings of the only sure guide.
Wait, in the silence of all flesh, for the further unfoldings of the divine law;
seek to know a taking root downward;
and as you come to witness the sap of heavenly grace to nourish and strengthen the root,
you will in due season be qualified to bring forth fruit to the Lord`'s praise,
'`First the blade, then the ear,
after that the full corn in the ear,`' ripening under holy influence,
and by the maturing rays of the Sun of Righteousness
prepared to be finally gathered into the garner.
Oh! how my spirit longs for the safe advancement of the beloved youth among you.
May the enriching showers of celestial rain descend to preserve and nourish them;
and may the further advanced, those in the meridian and decline of life,
wait in humble resignation to know their spirits
renewedly seasoned with the salt of the kingdom;
that this may produce its salutary effects, enabling to minister grace,
suitable example and precept, to the younger.
Finally, beloved friends, farewell in the Lord!
May He _be sanctified in those who come near_ Him,
and the gracious purpose of His will be effected, by preparing for himself
'`A glorious church, not having spot, or wrinkle, or any such thing.`'
In the fresh feeling of undiminished love,

[.signed-section-closing]
I am your cordial friend,

[.signed-section-signature]
Mary Dudley.`"

--
