== Chapter VI

[.chapter-synopsis]
* 1792+++.+++ Religious Visit to Dunkirk and Guernsey

A service for which my dear mother had long been preparing,
and which she contemplated with awfulness and many fears,
now presented as the immediate requiring of her great Master,
and early in the sixth month she laid before her
monthly meeting a concern to visit Friends in Dunkirk,
Guernsey, and some parts of the north of England and Scotland,
having in prospect to hold meetings also with those not in profession with our Society.
The trial which it was to her affectionate feelings, and the conflicts she endured,
when thus about to leave her husband and children,
are somewhat described in the following extract from a letter:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Sixth month, 23rd, 1792.

Your sympathy in my present important prospect is truly consoling,
and your encouragement to follow apprehended duty is strengthening.
Ah! My progress has indeed been slow, and my experience comparatively small;
but how much has it cost my nature, yes, almost its destruction,
to be in the degree I am, loosened from my precious domestic ties.
When a gracious Master demands the sacrifice of obedience,
what struggles do I renewedly feel to give up all;
at this moment I am even ready to question whether that faith
to which all things are possible will be victorious,
or rather that the small grain will so increase as to give the victory.

--

On the 1st of the eighth month she sailed from Waterford,
being accompanied by her dear friends, Elizabeth Pim and Edward Hatton,
who both felt bound to the service; respecting the accomplishment of which,
my dear mother writes as follows:--

"`Through merciful preservation we arrived at Milford about seven o`'clock this morning,
after a very tedious passage,
the wind turning quite against us about two hours after we got on board,
and next day it was mostly calm,
so that little but fishing went forward among the sailors:
we were all distressingly sick, but it is a great favor we had no storm,
and have been so far preserved.`"

"`5th. We proceeded from Haverfordwest to Carmarthen, where,
as there was a meetinghouse belonging to Friends,
we ventured to invite the people to come and sit with us:
a little solid company attended,
and I think there was no reason to be dissatisfied with this step.
We rode on to Llandovery to lodge, and reached Monmouth the next day,
called on a family of Friends about a mile from the town,
who are settled in a lonely situation far from meeting,
and separated from the Society of Friends;
some communication in a sitting with them tended to relieve our minds,
and I hope sealed some profitable instruction on theirs.
We went from there to Ross,
and finding their Monthly Meeting was to be held the next day, concluded to attend it.
Our minds being drawn in gospel love to those not of our Society,
notice was circulated and many came to the meeting, which proved a solemn one.
Edward Hatton was engaged with good authority,
and the season ended in humble acknowledgment of divine mercy.
We had a religious sitting in the family where we lodged,
and proceeded that evening to Gloucester, where we also felt bound to appoint a meeting;
and though but few attended, it was an open, relieving time,
affording renewed cause to trust in the never-failing arm of saving strength.`"

"`We reached Burford the evening of the 9th,
and were affectionately received at the hospitable dwelling of Thomas Huntley.
In religious retirement after supper, we were refreshed together,
and felt a little of that fellowship which is with the Father,
and with his Son Jesus Christ.
We had a season of religious worship next morning with the boys in their school room,
and afterwards proceeded to High Wycomb,
where we arrived just as Friends were going to a meeting held
at seven in the evening on that day of the week;
it was a solid time, the number attending not large.
Here I met with my old companion Adey Bellamy, who took me to his house,
and with his wife, a valuable religious woman, lodged and entertained us most kindly.`"

"`11th. After breakfast we went to see our friend Mary Green, and her three daughters,
where we were favored with an opportunity the most
refreshing and strengthening to my poor mind,
of any we have had since leaving Waterford.
Adey Bellamy supplicated, and after some communications in the line of ministry,
his wife revived the language of David,
'`Surely mercy and goodness has followed me all the days of my life,`' etc.,
when our valuable friend Mary Green, with whom much sympathy was felt,
made humble acknowledgment of the mercy renewedly extended to her;
after which another return of prepared praise closed this memorable season,
wherein it seemed to me such food was graciously handed,
as might be gone in the strength of many days,
and our spirits were bowed in thankfulness to the Lord.
We left this place; in peaceful serenity, and reached London to tea,
being cordially received at my dear friend John Eliot`'s.`"

"`12th. Attended Westminster meeting, which was to my feelings a low season,
though Edward Hatton was well concerned in testimony.
The afternoon meeting was wholly silent, but I thought inward travail was got to,
which it is a favor to be willing to abide under,
even a state where the seed can be profitably visited and interceded for;
believing that in this situation groans which cannot be uttered, reach the sacred ear.
My mind was instructed in these seasons,
as well as in a time of retirement at our lodgings, in the evening,
and though my lips were closed in this city,
I was in degree thankful for one sense of life, renewed willingness to suffer.`"

"`13th. After attending the Morning Meeting, where our certificates were read,
we apprehended ourselves clear of London,
and left it about four o`'clock accompanied by John Eliot and John Bevans.
Arrived at Rochester late that evening,
and not feeling easy to proceed without having a meeting there,
one was appointed for next morning.
This through divine favor proved a season of considerable relief;
it was wholly confined to Friends, and I believe properly so,
as it appeared a visit to our fellow members,
who are sometimes deprived of their portion when others are present.
Many Friends dined with us, at William Rickman`'s,
and a solemn season afterwards crowned this labor of love.
We proceeded to Dover that night, where, though not arriving until past ten o`'clock,
we were hospitably received at Richard Baker`'s.`"

"`We found that our dear friends Martha Routh and Christiana Hustler,
were daily expected from Dunkirk,
and that a vessel was likely to sail for that place in the morning.
We had before thought only of Calais, but Richard Baker recommending this, in preference,
we changed our original intention, and set sail on fourth-day morning the 12th,
with a favorable breeze, but this soon slackened,
so that we were about twelve hours on sea, and suffered much from sickness.
The gates of the town being shut when we got into harbor,
we were obliged to remain on board all night.
On reaching the house of our kind friend William Rotch, next morning,
we found it was their usual meeting day;
but not feeling ourselves equal to sitting down profitably, so soon after a voyage,
it was deferred to six in the evening, when we assembled, and though but a small number,
it felt a time of solemnity.`"

"`On conferring together next morning,
it seemed consonant to all our feelings to sit with the few families,
and we began at that of our kind host, with whom, his wife and two daughters,
we were favored to feel spiritual refreshment.`"

"`In proceeding with this engagement, much exercise attended,
and the truth of the Scripture assertion was sensibly enforced,
'`you have need of patience:`' but I had afresh to consider that it
is part of the laborer`'s business to break up the fallow ground,
as well as to sow the seed; this is the hardest portion of the work,
but the servant is not to choose.
It is enough for the servant to be as his Master, and the disciple as his Lord.
May I increasingly learn this salutary lesson,
for I am far behind my fellow-laborers in the glorious work.`"

"`First-day, the 19th.
Our meeting this morning was attended by a few others besides Friends,
and through the extension of divine regard, proved solemn;
holy help being afforded to visit the different states of the people to some relief,
and I trust profit.
In the evening, at our lodging, a memorable season crowned this day,
so that it was indeed measurably known that through continued
mercy the outgoings of the morning and the evening rejoice.`"

"`20th. After the last family sitting an exercise which
had attended my mind since coming here,
became so heavy that I mentioned to my companions the view of
having a meeting with the inhabitants of this place;
they encouraged me, but did not appear to be themselves, under the weight of it.
This tried my faith, and on speaking to our dear friend William Rotch,
he expressed some fear that owing to the present state
of public affairs it would not be of much advantage.
Having moved so far, I felt relieved, and willing either to give the matter wholly up,
or yield to it in the morning, should the pressure continue.
After supper, a very solemn season ensuing,
wherein access was mercifully afforded to the throne of divine grace,
and renewed strength experienced, we again conferred on the subject,
and concluded to appoint a meeting, and though the number attending was but small,
it proved a season owned by the liberty of the gospel.
Edward Hatton was early engaged with good authority on the testimony concerning our Savior,
'`In Him was life, and the life was the light of men:`' Elizabeth Pim followed acceptably,
and strength was afterwards afforded for one of the poorest to
be engaged in the service of a gracious Master,
who was pleased mercifully to help while advocating His cause.`"

"`At the close of this meeting, the members of our Society were requested to remain;
and we had to recommend an attention to some points
which seemed overlooked by Friends in this place,
and to encourage to deep watchfulness lest the testimony of Truth might fall;
also to strengthen the hands of those concerned for its support:
this felt a solemn conclusion to our visit here,
and my mind was favored with a sense of calmness and relief.`"

"`Apprehending that liberty was now given to proceed we prepared for doing so,
and just before separating, the feeling of divine love sweetly cemented our spirits,
under which a fresh salutation arose to several present,
and solemn acknowledgment of the Lord`'s unfailing mercy was made; under which covering,
and the evidence of solid peace, we parted with this dear family.
There were, besides the household,
several at this last opportunity for whom travail of soul had been experienced,
that they might abide under the softening influence of heavenly love,
and submit to the holy discipline of the cross.`"

"`Benjamin Rotch accompanied us to Calais,
where we were detained two days by unfavorable wind; a trial of patience,
feeling anxious to get forward.`"

"`24th. We embarked about four o`'clock in the afternoon,
and had a sick passage of eight hours; landing at Dover, I trust with thankful hearts,
and were again affectionately received at our kind friend Richard Baker`'s.`"

"`26th. Attended the usual meeting which was an exercising time:
the life of religion being so low that suffering with the oppressed seed was our portion.
My companions were well engaged,
and I was drawn to supplicate for the church in her wilderness state,
faith being mercifully afforded to trust that she will yet be brought forth:
this I felt to be a renewed favor from the divine hand.`"

"`We left Dover comfortably, and reached Canterbury,
where we had requested an evening meeting might be appointed,
and notice circulated among the inhabitants;
but very few were there besides those who professed with Friends,
and from our first assembling it felt very hard
to get to profitable settlement or exercise.
Dear Elizabeth Pim and Edward Hatton were concerned to minister,
but my spirit was in a state of captivity with the captive seed,
so that I could not visit the few who had given us their company,
nor dared I address those for whom I was led into painful travail,
until there was a separation; which being proposed, those not of our Society withdrew,
and I ventured to express my feelings in a line of honest close labor;
for truly it seemed as if no other would do in this place,
where there felt too much rubbish in the way availingly to build anything;
and the outward appearance was such as might raise the
inquiry whether most present were of our fold or not,
so great a conformity to the fashions of the world was evident.
Though little or no hope attended this labor,
yet peace succeeded obedience to the manifestations of duty,
and this is all the poor servant has to do with;
we must leave the issue to Him who alone gives the increase.`"

"`27th, We arrived at Rochester to dinner at William Rickman`'s,
and had a satisfactory sitting with the children in his school;
reaching London the same evening.`"

"`On Third-day, the 28th, attended Devon shire-house meeting,
where we met our dear friends Martha Routh, and Christiana Hustler.
This proved a truly baptizing season,
and out of the mouth of several witnesses words
were established to the comfort of some of us.
This favored opportunity closed in supplication;
and a consoling hope was a raised that a precious living seed was preserved,
and under holy cultivation;
for which earnest desire was felt that gracious care might continue to be extended,
and the Lord cause it to bring forth fruit to His own everlasting praise.
We dined with these dear friends at Simon Bailey`'s,
and in the evening proceeded to Staines, lodging at John Finch`'s, where, after supper,
a solemn silence prevailed,
gathering our minds to the place where not only acceptable prayer is made,
but strength mercifully obtained to journey forward in the spiritual race;
liberty was felt to visit several states present, and we parted for the night,
under a precious covering of good.`"

"`29th. We reached Southampton about seven o`'clock in the evening,
and found a packet just ready for sailing to Guernsey, in which we embarked;
and after a tempestuous night, with much danger and distressing sickness,
made about two-thirds of our passage in twelve hours: but the wind proving contrary,
we got but little on our way through the night of the 30th: we were, however,
favored to make the port, late the following evening,
and met a kind reception from Nicholas and Mary Naftel.
We felt it a mercy to be once more preserved over the great deep, while crossing which,
all our minds were tried on various accounts, though measurably kept in quietness,
and confidence in the arm of effectual help;
so that I did not wish myself any where else,
and in the midst of distress had a view of this island,
accompanied with the belief that there were some here prepared to receive a gospel visit;
may our spirits be renewedly qualified for the service required.`"

"`Ninth month, 1st. Prospects seem opening and the work feels heavy:
may there be a centering deep so as to know the Master`'s will,
and resignation to follow it let it lead as it may.
We this evening took a walk, to see an elderly man,
who was a member of the Church of England, but embraced the principles of Friends,
from conviction, on reading some of their writings:
he resides alone in a retired situation, about a mile in the country, has a garden,
and with what it produces, etc., is worth about £14 per year:
he considers himself rich with this,
and teaches gratuitously a number of poor children to write.
Soon after our entering his cottage, a precious covering spread over us,
under which prayer was offered for future preservation,
and humble acquiescence with the will of our divine Master.
This was a season of renewed strength to my mind,
which has been much tossed and tried lately.`"

"`First-day, 2nd.
The meeting this morning was largely attended,`'
and I trust it was a profitable time to some:
my mind was under such a weight respecting what was to take place in the afternoon,
that I felt thankful silently to labor for a little strength;
a meeting being appointed for the inhabitants,
and permission granted to hold it in the assembly room.
When we went, there was a large number collected, and the room was soon nearly filled;
many of the people were solid, and apparently serious, but others restless,
and so noisy that it required much faith to move at all; but the exercise being heavy,
and the love of the gospel prevalent, as there was a venturing in simplicity,
faith and strength increased,
and gracious help was so afforded that what might be
compared to the boisterous element was gradually calmed;
and truth rose into such dominion, that not only from the necessity,
but in the feeling of precious liberty,
the gospel could be preached and its doctrines a little unfolded.`"

"`The meeting concluded under increasing solemnity,
and a consoling hope that all would not be lost,
but some of the fragments be seen after many days.
Though much exhausted from this laborious exercise, a time of divine favor after supper,
tended to renew bodily and mental strength,
and salutary repose again wound up the springs of nature.`"

"`We went on second-day three miles into the country,
to see a sister of Peter la Lecheur`'s, the person already mentioned, who like him,
joined the Society of Friends from conviction;
and held a meeting in a barn near her dwelling.
Many people assembled and we spoke through an interpreter,
which was made easier to my companions than they expected,
solemnity and gospel love were prevalent,
and I trust several were helped a little on their way;
for while liberty to unfold the doctrines of Truth was experienced,
there felt a door of entrance to the minds of some present.
No Friends reside in this place, except the woman already alluded to;
her husband is a Methodist, he was much tendered in the meeting,
and very kind to us at his own house, where we dined; their children are also Methodists,
the husband of one daughter lately felt a scruple at having his child sprinkled.`"

"`We returned through heavy rain but in peace, and went to take tea with a solid man,
who professes with Friends; his wife, a well-minded woman is a Methodist;
we had a religious sitting with them in the evening to our refreshment.`"

"`Fourth-day was their usual meeting, at which several besides Friends were present,
among them a Calvinist minister, who had been with us twice at our lodgings,
and with whom we had much conversation.
At the close of this meeting, which was a time of solemnity,
those not in profession with us were requested to withdraw,
and we had a very relieving season with the few individuals of our Society,
only ten in number.
After these opportunities we began to think about returning,
and hope we did not do wrong when we engaged a
vessel which only came in the preceding day.
No regular packet being then going,
nor had anyone sailed for England while we were on the island.`"

"`Fifth-day, we crossed the water about half a mile, to a place called Castle-Island,
where there is a garrison, and Edward Hatton, would gladly have had a meeting,
but it could not be obtained without the Governor`'s permission, so was relinquished.
We called in returning, to see a man and his wife, who had removed from Ireland,
and who had been educated in our Society, and were pleased at having made this visit.
In the evening most of our Friends were with us at Nicholas Naftel`'s,
and the covering of solemnity was again mercifully spread over us,
the precious cement of gospel love binding us as in the one bundle.`"

"`Sixth-day morning, 8th. While waiting to be summoned on ship-board,
a sweet parting season crowned this visit, wherein a consoling hope was felt,
that through many infirmities the arm of the Lord had not only been near to sustain,
but graciously strengthened for the work whereunto He had called,
so that in renewed faith His great cause might be committed to His holy keeping;
while the belief was satisfactorily revived,
that these Islands would learn more and more to wait for His law, and trust in His name:
He can gather without instrumental means,
and complete His own work by the effectual operation of Almighty power.
I felt a rest in this assurance beyond all that I can set forth,
and some deep conflicts respecting these parts seemed, as it were,
swallowed up in that ocean of love,
which I verily believe will operate until the knowledge of the Lord cover the earth,
as the waters cover the sea.
Under these precious feelings, praise renewedly waited as in the gates of Zion,
for heavenly acceptance, and after getting on board the vessel,
so strong did the current of gospel solicitude continue to flow,
that I was constrained to express a few words to a
number of persons who were collected on the pier.
Holy support was near through this exercise, and peace succeeded,
for which pledge of divine acceptance what is too dear to part with?
May all our imperfections and short-comings be
mercifully forgiven and every deficiency supplied,
for the language is, I trust, deeply inscribed '`to us belongs confusion of face.`'`"

"`We were favored with a fine passage of less than twelve hours to Weymouth,
a distance of twenty-four leagues,
and having a fair wind all the way were able to stay upon deck,
and partake of the captain`'s provisions, feeling much better than I could have expected,
though sick part of the time.
While on the water I was sensible of gospel love towards the inhabitants of Portland,
and wished we could land there instead of at Weymouth;
but I feared avowing too much lest the vessel might not safely anchor there,
so said nothing until seventh-day, when being about to proceed,
and looking over our maps for awhile,
I told my companions I did not believe the line would be discovered there,
at least for me, and acknowledged the prospect I had of this island.`"

"`After making some necessary arrangements we went a mile and half to the ferry,
but not being able to procure any conveyance at the other side,
had to walk a long way upon rough gravel.
At length after Edward Hatton had gone on to try for a cart for us,
Benjamin Rotch discovered one returning to Weymouth, and representing the poor women as tired,
and offering generous payment, we obtained possession, and found our friend Edward Hatton,
at the inn sending off a conveyance to meet us.
Here we were kindly received,
and found that Deborah Darby and Rebecca Young had held
a meeting in a very large room in the house,
on being put ashore there on going to Guernsey.`"

"`We appointed a meeting for eleven o`'clock in the morning,
finding the Methodists held theirs at nine,
and it felt unpleasant to interfere with the hour of other professors.
The Isle of Portland is divided into several little villages,
our men Friends gave notice in the one we passed through, and that we were then in,
but I apprehend the intelligence reached further,
as several came on horseback and many were in the house before the appointed hour.
The room, though very large, was not only filled,
but the stair-case and adjoining chamber seemed crowded,
and a solemn favored season it proved;
one wherein the poor could be invited to partake of durable riches.
The people are mostly of a laboring, industrious class, reckoned very honest,
and diligent in attending their place of worship, which is the establishment;
there has been lately opened a Methodist meeting, and a rich man of that profession,
named Brackenbury,
has settled there with a view of benefiting the inhabitants in a religious sense:
he was from home,
but some of his family were at the meeting and conversed freely with us afterwards;
they appeared solid persons, and were very friendly.
A steady looking man, a preacher,
came after dinner and invited us to this gentleman`'s house,
but we were about setting off, and declined the invitation in consequence.`"

"`This meeting recompensed us well for our little pains in getting to it,
and I trust some were helped on their way: however we felt relieved,
and renewedly encouraged to trust in the unfailing arm of divine support.
As we left the Island, many at the doors spoke kindly to us,
and our hearts and lips could affectionately say farewell.
We went back peacefully in our cart to Weymouth,
and after a cup of tea proceeded to Dorchester to lodge,
where on second-day we parted from our dear friend Edward Hatton,
who set forward for Sherborne:
we separated under the hope that each was endeavoring to follow the light afforded,
though the division was sensibly felt on both sides.
We proceeded under the kind care of Benjamin Rotch to Poole,
were we lodged at Moses Neave`'s: several Friends spent the evening with us,
and a very solemn season ensued before supper,
which compensated for the little circuit we took in coming here,
and accounted for the inclination we felt to do so.
The 11th and 13th we were at Alton and Staines week-day meetings,
and on the evening of the latter, reached London,
which seemed to be the proper port re-ship for another voyage.`"
