== Chapter XII

[.chapter-synopsis]
* From 1798 to 1801
* Illness and temporary residence in Bristol
* Religious service there, and in some places adjacent
* Return home, and visit to the Families of her own Monthly Meeting
* Letter to a Friend

An affection of the lungs, under which my beloved mother had suffered for several months,
became in the spring increasingly serious; and her cough, with other alarming symptoms,
brought her so low as to cause much apprehension in the minds of her family and friends,
and induce her medical attendants to recommend a sea
voyage and short residence at Bristol Hot-wells.
It was with peculiar reluctance she yielded to this advice,
as the awfully disturbed state of Ireland in the year 1798
precluded her affectionate husband from accompanying her;
but in this trial of faith and patience she was mercifully supported,
under the belief that it was her duty to use
every means for the restoration of her health.
She was in so weak a state on leaving home,
that some friends who assisted her on board the packet expressed it
as their opinion that she was then leaving Ireland never to return:
such, however,
was not the will of Him who had repeatedly brought her up as from the gates of death,
and graciously designed again to qualify her for His service.

She embarked at Waterford with her eldest son and four daughters; landed at Milford,
and after passing some weeks in that neighborhood,
she was so far recovered as to proceed to Bristol by sea.
Her dear friend George Fisher met her at Pill harbor and conducted her to his own house.
He had recently lost his valuable wife,
between whom and my dear mother a strong friendship had subsisted,
and her visit at that juncture seemed not only grateful to his affectionate feelings,
but her religious sympathy soothing and helpful to his mind.
She stayed much longer under his hospitable roof than
was contemplated upon first going to Bristol;
her native air and the waters of the Hot-wells proving, as heretofore,
beneficial to her health;
though her amendment was very slow and interrupted by
such frequent attacks of indisposition,
as caused her physician to entertain little or no hope of ultimate recovery:
she was not able to attend meetings till near the end of the year,
about which time she writes as follows:

"`I have gone three times to the Fryers meeting-house; it tried my frame sensibly,
but afresh convinced me who was, and continues to be, strength in weakness;
having been assisted beyond what I could have looked for, so that,
although I scarcely expect an establishment in
even usual health will ever be my experience,
I have latterly conceived that my continuance in time might be lengthened out,
and feel desirous that every portion of strength entrusted, may be occupied with,
according to the will of the gracious Giver.
Some unfoldings of duly have been recently afforded,
and whether or not I may be drawn to visit a few families,
or attend any meetings in adjacent places,
I do believe I ought to stand resigned to move as bodily strength is furnished,
in order that the remainder of my stay here may be
filled up to the relief and peace of my mind.`"

In accordance with these views she applied to her Monthly Meeting for a certificate,
in the following address.

[.embedded-content-document.address]
--

[.salutation]
"`My dear Friends,

Notwithstanding my leaving,
home was under different prospects than the probability of any religious engagement,
nor does the degree of bodily strength yet experienced,
warrant an expectation of much of this nature being required;
yet being sensible of increasing exercise,
and desirous to have the time spent on this side the water,
as well as the portion of health afforded,
used as consistently with best direction as I may be favored to discover;
I feel resigned to mention,
that an apprehension exists in my mind that something is due from me, in this city,
and to parts adjacent,
in which I request liberty of the Monthly Meeting to move as Truth may point out.
I believe there are those among my dear friends in Clonmel,
who will feel with me in this exercise,
and as soon as clearness is felt transmit me their decision.

After spreading this prospect I may just add, that though separate in person,
under the pressure of various infirmities and hidden conflicts,
my spirit has often saluted, and renewedly does salute you, my dear friends,
wishing with my own,
your preservation and establishment on the rock of immutable support;
that whatever our individual allotments may be,
we may experience that '`we have a strong city,`' and know
salvation to be '`appointed for walls and bulwarks.`'

[.signed-section-closing]
I am, in gospel and affectionate love, your friend,

[.signed-section-signature]
Mary Dudley

[.signed-section-context-close]
Bristol, Eleventh month, 22nd, 1798.`"

--

After receiving the concurrence of her friends, which was readily granted,
the first step she believed it right to take in the line of religious duty,
was to visit some of the larger families belonging to the Monthly Meeting of Bristol,
and she paid, while in a weak state of health, upwards of thirty visits.
During this engagement, and respecting some further service, she remarks as follows:

"`In the procedure so far,
frequent and closely exercising have been my conflicts in and out of meetings,
though in some of these merciful help has been vouchsafed,
so that relief has been measurably obtained.
Being sensible of a weighty concern respecting the inhabitants of Temple Parish,
I ventured to appoint a meeting at that meeting-house
on the evening of the 24th of second month,
which was large and solemnly favored.
Through the extension of divine assistance, not only a door of utterance was granted,
but comfortable persuasion that one of entrance was also opened;
so that renewed cause was administered to follow in the path of manifested duty;
and the subsequent feeling of unmerited peace was truly precious.
When this service was accomplished,
I felt increasingly drawn towards some little
places in the north division of this county,
and on the 3rd of the third month proceeded to Sidcot,
where I sat an exercising meeting with Friends, under a deep sense of the lack of life,
and prevalence of an indolent unconcerned spirit,
whereby the burden of the sensible feeling part was abundantly increased.
After a time of silent travail, strength being communicated,
a little relief was obtained,
and clearness of feeling in appointing a meeting for the next morning,
of a more general kind.
Similar views having presented respecting Congersbury,
we went to our friend Joseph Naish`'s, whose house being thought suitable,
a meeting was appointed for the evening, and a very large number came.`"
A covering of solemnity early spread,
and liberty in stating the preparation for performing spiritual worship ensued,
under which the minds of the people seemed
solidly impressed and gospel love arose sweetly,
so that help was witnessed to minister to some states,
I hope with profitable instruction;
and the season closed under a thankful sense of
gracious regard and the feeling of quiet poverty.
This I deem a rich inheritance, and far more than any surrender of my will,
or feeble attempt to advocate the cause of pure truth, has any claim to,
but all of abundant mercy from Him to whom praise assuredly belongs.`"

"`Second-day, 4th, attended the appointed meeting at Sidcot, which was large and quiet;
supplication early went forth, and He who raises and answers prayer graciously drew near,
sensibly qualifying for the portion of labor allotted,
and spreading the canopy of pure love, under which names and distinctions seem lost,
and that spirit which breathes peace on earth and good will to men happily prevails.
We dined at the school, and had a solemn season before we left it,
several precious young people being present: returned to Congersbury to lodge,
and passing a thoughtful night I opened to my affectionate
sympathizing friends Joseph Naish and George Fisher,
my feelings about Longford, a place adjacent,
to which we took a ride and found that way presented
for a meeting by a room being offered at the inn.
We spent a few pleasant and solid hours at Winthill, with John Thomas, and Sarah Squire,
and returned to our quarters to tea,
where a quiet night refreshed a feeble body and mind.`"

"`Fourth-day, 6fh. We attended Claverham meeting in course,
which was a season of very deep exercise,
my poor mind being unusually plunged into a state where faith was at
so low an ebb that very little prospect of relief opened,
though a necessity for moving seemed felt.
To my humbling admiration, help was so extended,
that from one of the lowest it became a time of considerable relief,
through honest plain dealing with the indifferent and lukewarm,
while encouragement was sweetly felt to an exercised and deeply tried remnant,
hidden but precious in the Lord`'s sight.
In the afternoon went to Longford, where at the hour appointed,
a considerable number came.
A solemn covering spread,
and though among a people to whom such a meeting was wholly new,
it not being remembered that any of this kind had ever been held there.
He, whom winds and waves obey, graciously calmed by His own power,
and to much outward stillness vouchsafed a quietude scarcely to be expected.
This so increased, that during the previous travail and succeeding vocal engagement,
the waters gradually rose, and the conclusion of the season was memorably owned;
a time wherein all that was feeling within me,
and I believe other fellow travelers united in gospel fellowship,
bowed in thankful acknowledgment of continued merciful regard.`"

"`We separated under a solid feeling, the people departing in much commendable quietness;
which I esteemed a peculiar favor,
as our being at an inn had caused me to fear unsettlement after the meeting.
Several beloved Friends continued with us that night,
and accompanied me next morning to Bristol.
I felt symptoms of cold and fatigue requiring rest, but undeserved peacefulness of mind.`"

When a little recruited she went to the neighborhood of Olveston,
and had many meetings with Friends and others in that and some adjacent districts,
being wonderfully strengthened for the service to which she was thus renewedly called.
Her views extending, as ability of body increased,
she travelled a good deal during the summer of 1799, in the counties of Somerset,
Gloucester, Wilts, and Hereford; visiting the families of Friends in some places,
and holding above thirty public meetings, among which were three at Bath,
and one in the Town-hall, at Wells.
At the latter place she had been accustomed to enjoy much worldly pleasure in early life,
and was still remembered by some of the more respectable inhabitants.
Many of these manifested an affectionate recollection and esteem for her character,
when thus among them as a minister of the gospel;
several about her own age acknowledging,
that there was more solid satisfaction in the path she had
wisely chosen than could ever result from self-gratification,
though the pursuit of this, still occupied and was allowed to engross their minds.

In these journeys, Robert Lovell was my dear mother`'s kind attendant and helper,
and in some of her public services in the neighborhood of her native city,
she was accompanied by her friend and fellow minister Samuel Dyer.

While in Bristol she visited three men who were under sentence of death in Newgate,
and continuing much exercised on their account, wrote the following letter,
which was conveyed to them a few days before their execution,
and appeared to be both seasonable and comforting.
One of the men requested a religious person who attended them to the last,
to express his sense of the kindness,
and tell the Friend who had manifested such concern for them,
that her words were fulfilled in his experience,
for his prison had indeed become as a palace, and in the immediate prospect of death,
he would not change situations with the king on his throne.

[.embedded-content-document.letter]
--

[.salutation]
My dear Brethren,

For so I can call you in that love and deep solicitude
which allows no distinction of names to religion.
I feel with and for you in the flowings of gospel love,
and under this influence could spend hours with you in your solitary and awful situation.
But I fear your even beholding the persons of any,
unless those who are of necessity about you,
lest your minds should be drawn to anything inferior to the great object,
which you ought every moment to have in view.
I therefore adopt this method of beseeching you,
to endeavor to draw near to the spring of living help,
which is mercifully with and in you, as an infallible means of opening to you,
not only all your needs, but the glorious remedy provided for their supply.
This, my friends, is '`Christ in you,`' the promised reprover for transgression,
and comforter of the contrite, penitent soul, which leans upon him.

Oh! let your attention be inward and deep,
your eye singly turned to His all-convincing saving light.
He is the good Samaritan, the searcher and binder up of those wounds that sin has made,
and can by His own power so apply the oil and the wine, as to restore the distressed,
mournful traveller to soundness and peace.
Oh! that this may be your individual experience; then will your prison be as a palace,
and your dismission out of this world,
a door of entrance into a state of liberty and endless rest.

Let nothing divert your minds from the essential necessary state of inward retirement,
and waiting upon the Lord:
and may He who can only preach spiritual deliverance to the captive,
graciously do His own work, even cleanse from sin, finish transgression, and make you,
by His redeeming, sanctifying power, fit for His pure and holy kingdom;
thus in a manner not to be fully described,
prays your concerned and deeply sympathizing friend.

[.signed-section-signature]
Mary Dudley

[.signed-section-context-close]
Bristol, Fourth month 29th, 1799.

--

In reviewing her late engagements, and alluding to the disturbed stale of public affairs,
she writes as follows:

"`Truly the signs of the times are awful, and everything enforces,
with emphatic language, the necessity of dwelling near,
or within that impregnable fortress, where these things cannot move us from the calming,
consoling persuasion of divine sufficiency.
May our minds be mercifully stayed in holy quiet,
while the potsherds strive with the potsherds of the earth.
Often does my spirit long that we, as a people,
may gather more and more into this precious habitation,
out of that spirit which produces tumult, or mingles with it;
and thus exalt the pure peaceable principle, which through all,
I cannot but steadily believe, is making its own way even gloriously in many minds,
and will spread in the earth, until men beat their swords into plowshares,
and their spears into pruning hooks.`"

"`Never did a more convincing evidence attend my mind than of later times,
that a great work is on the wheel of Almighty power in this favored nation;
where there are truly many righteous, whose fervent intercessions are no doubt availing,
and many others evidently inquiring the way to the kingdom of inward settlement.
To these the gospel message is joyful,
and precious is the liberty felt in proclaiming it; under the sense whereof,
in seasons of close but truly relieving labor,
my soul has been bowed in awful admiration of what the
Lord is doing for the honor of His own name,
and the advancement of truth.`"

She returned with her family to Ireland early in the year 1800,
and was not long at home before she manifested the renewal of
gospel concern for the members of her own Monthly Meeting,
by visiting them in their families: she also held some public meetings in Clonmel,
and places adjacent.

The unsoundness of principle,
which about this time was distressingly evinced by many
who had filled conspicuous stations in our Society,
was a source of deep heartfelt sorrow to this
true and loyal subject to the King immortal,
for the increase of whose dominion she had long '`labored and
not fainted.`' The following letter will show,
how earnestly she desired the preservation and help of her fellow professors,
as well as the clearness and consistency of her own views,
with respect to the fundamental truths of Christianity.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Suirville, near Clonmel, Eighth month 22nd, 1800.

[.salutation]
My dear Friend,

In returning the manuscript with which you entrusted me, allow me to observe,
that though the system therein laid down is, to the eye of reason, very plausible,
it is one my understanding, or rather my best judgment, as sensibly revolts from,
as that of the writer did at the contrary.
It is not written in the lines of my experience;
and having from the earliest opening of my understanding in spiritual things,
endeavored simply to receive, what in the light which makes manifest might be revealed,
I may add, that according hereto I conceive it to be an erroneous system,
formed more by the strength of the rational or natural faculty,
than the clear unfolding of pure wisdom,
in that spot where the creaturely judgment is taken away,
and adopted by a part not yet fully subjected to the cross of Christ.

My spirit will, if happily preserved, ever commemorate that mercy,
which restrained from those speculative researches to which my nature strongly inclined,
and which, as a temptation likely to prevail, in my first desires for certainty,
closely beset me.
Many a labyrinth might I have been involved in, in many a maze enveloped,
had the various voices which are in the world, (the religious world,) been,
in conjunction with these besetments, attended to.

Were it needful I could tell you much of the
danger to which my best life has been exposed,
but the standard at first erected being held steady in my view by divine power, even,
(I speak it with humble gratitude,) I will know nothing but Jesus Christ,
and Him crucified, proved a barrier to those wanderings in speculative opinions,
which I believe would have to me, and have to many mercifully enlightened minds,
been the means of obstruction to a progress in the way of redemption;
and introduced into that circuitous path, where the peaceful termination is not beheld.

Why should we seek to explore, or reconcile to our understandings,
the work or plan of redemption,
formed and carried into effect by divine unerring wisdom and love?
Can our creation, in the first instance or since,
be fathomed by all the finite powers of man?
And shall a more, (I was going to say,) stupendous work, that of redemption,
be arraigned, approved or rejected by these powers,
and the constituent parts of the wondrous edifice so shaken,
that the whole is in danger of being leveled?
Oh! that every attempt of this kind may be mercifully defeated.

Wherein does our spiritual life consist?
Is debate, speculation and reasoning the nourishment of the immortal part?
Is it matured by food so inferior to its nature?
Rather will it gradually weaken and come to decay,
if not replenished from a source equal to its origin; the pure milk of the eternal Word.

May you, my beloved friend, partake hereof and be sweetly satisfied:
anything contrary to this is dangerous food,
strengthening only that part destined by sacred
determination for subjection to that power which,
if allowed to reign, will reduce into holy order, harmony, and love.

From this state, in the rational and animal creation,
there was a departure in the original fall or degeneracy of man; and in succession,
as descendants from transgressing man, we partake of a nature or disposition to evil.
Notwithstanding, as early as the fall, there was, and in perpetuity has been and is,
a pure holy seed or principle to counteract the propensities so produced,
and though no guilt attaches where there has not been a joining with the evil, yet,
being possessed of a transgressing nature, we individually need redemption from it.
Nor are we really so redeemed, and delivered from the bondage of corruption, until,
through the sanctifying influence of that pure gift vouchsafed as a light,
leader and restorer, we experience the crucifixion of the old man,
(the first nature,) with his deeds, and in the gradual process of refinement,
a putting '`on the new man,
which after God is created in righteousness and true holiness.`' "`I fully believe,
that as soon as man was redeemed, after and out of transgression,
it was through faith in the promised deliverer and submission
to the divinely operative and efficient means,
mercifully provided by matchless love.

Yet it pleased the same love and inscrutable wisdom, in the fulness of time,
to open the way more perfectly by the appearance or
manifestation of this appointed Savior in the flesh,
therein to fill up that measure of suffering seen fit.
It is not our business to inquire why this should be a part of the marvelous plan,
but thankfully content with the remedy so graciously provided,
and beholding what manner of love the Father has bestowed upon us,
humbly to partake of the offered salvation,
by receiving and walking in that light leading to immortality,
through the glorious dispensation of the gospel or power of Christ;
the pure eternal Word, '`whereby all things were made.`'
What a convincing testimony to the eternal Godhead of the Son,
and thereby proving Him to be an omnipotent Savior,
as well as holy pattern of all excellence.

Never was there a more full and plain system than that of the gospel;
never can the strongest powers of the creature add to its clearness and beauty,
though the plainest truths may be rendered doubtful, and the way complex,
by subtle reasonings and eloquent disquisitions.

I repeat, let us be content; we have not as a people followed a cunningly devised fable,
and there are, I trust, those yet preserved who can go further, and say,
'`it is truth and no lie;`' having seen with their eyes, heard with their ears,
and been permitted to taste of the word of life, and if required, could,
through Almighty help, seal their testimony by the surrender of the natural life.

Little did I expect to enlarge thus,
and far is it from me to enter into controversy and debate,
a poor employment for one apprehending a more solemn call;
but my heart earnestly longs that the Lord`'s children
may stand firm in this day of shaking and great trial.
Let none beguile any of their promised reward,
through leading into reasonings and perplexing uncertainty.
'`I am the way, the truth and the life,`' is a compendious lesson, a holy limit;
and '`no man comes unto the Father, but by me.`'
I quarrel with none about forms,
or differing in non-essentials, but this is the one certain direction,
the consecrated path to salvation, through the divine lawgiver;
and if happily attended to, all will be well here and forever!

You and yours are dear to my best and affectionate feelings;
write to me freely if so inclined, I should be glad to hear from,
and be remembered by you, and am your sincere friend,

[.signed-section-signature]
Mary Dudley

--
