== Chapter XIII

[.chapter-synopsis]
* Visit to some parts of England
* subsequent domestic affliction
* family visit in Waterford, and journey into Leinster province, from Fifth month 1802, to Twelfth month 1804.

Believing it her duty to pay a religious visit to some
of the eastern and southern parts of England,
my dear mother obtained the concurrence of her own Monthly and Quarterly Meetings;
and leaving home the 8th of the fifth month, reached London on the 16th.

She was favored to attend all the sittings of the Yearly Meeting,
and often qualified by her great Master for
sharing in the active services of that solemnity.
She afterwards attended the Quarterly Meetings for Suffolk and Norfolk,
as well as many of the particular meetings in those counties, and also in Essex;
and held numerous public meetings,
to the relief of her own mind and satisfaction of others.
In these engagements she was accompanied by her friends Mary Savory and John Bevans,
and occasionally by Samuel Alexander.
She returned to London in time for the Quarterly Meeting there,
and was afterwards closely engaged for several weeks in the city and neighborhood,
visiting particular and Monthly Meetings; the families belonging to that of Ratcliffe;
and having a large number of public meetings, wherein as among her fellow professors,
she was strengthened to exalt the testimony of pure truth,
and powerfully to advocate the cause of her Redeemer.
While thus employed she writes as follows:

"`The line of my small engagements is no pleasant one, I assure you,
nor can it be so to the exercised traveller,
in this day of treading down and of perplexity.
Life seems low everywhere,
and perhaps there has hardly been a time when the opposition to its arising,
and consequent struggle before liberty can be obtained, were so sensibly felt:
so that it is no wonder if through the prevalence of a wasting, separating spirit,
the communication in the line of ministry should be of a more
searching kind than has Been needful in past times.
Oh! how is the very life wounded by the Herod-like nature in the minds of many.
It is indeed a favor to get to some quiet retreat,
where an excuse from feelings of this sort is afforded,
though only to partake of the fellowship of suffering with the mourners in Zion,
who are greatly bowed down, because of the things which have happened and are happening.
It is, however, a great mercy to find that under such exercises,
a degree of holy certainty is vouchsafed, and the belief confirmed,
that although unpleasant bread may be given to distribute, it is of the Lord`'s preparing,
who having graciously helped, ought to be depended on through all.
I hope I am endeavoring not to eat the bread of idleness,
however small my ability for availing labor,
or undeserving I feel of a crumb from the Master`'s table.`"

While in London my beloved mother was much tried with illness, and frequently confined,
after any particular exertion, for many days together,
so that as the season advanced she began to be anxious for a return home,
and was thankful when she felt easy to set forward about the middle of the tenth month.

Relative to her engagements after leaving London,
she seems only to have preserved the following brief observations.

"`Fourth-day, the 14th of tenth month, 1802, we went to High Wycomb,
where we were cordially received at the house of our dear friend, Adey Bellamy.`"

"`Sixth-day evening had a meeting at Beaconsfield, about six miles distant;
it was held in a room at an inn, and proved a solid satisfactory season.
Adey Bellamy was well concerned in the line of ministry.
The forenoon meeting at Wycomb on first-day, was very exercising.
Information being circulated,
a considerable number of the inhabitants collected with Friends at three o`'clock,
and we were favored with a very relieving, solemn opportunity,
though the labor was trying to my poor body.
A time of retirement with our little company, in the evening,
was productive of increasing peace,
and proved a memorable parting with some beloved connections,
including Joseph and Mary Savory, who had come from London to take leave of us.`"

"`Second-day, the 19th. After another religious sitting in the family,
we left Wycomb and got that night to Reading,
where there was a fresh experience of conflicting exercise from some unseen cause;
but in the morning of third-day, a town we had passed through sprang up to view,
and we returned to Henley; attended the usual meeting there on fourth-day,
and though the number was small,
there were among them such as felt of the wrestling seed, to whom encouragement flowed,
and the recompense of peace was afforded for the return there.
Went again to Reading that afternoon, and attended meeting there on fifth-day,
when such awful views were presented to my tried mind,
that I did not marvel at the previous baptism as into the cloud.
Ah! how various are the lets and hindrances to spiritual advancement! the world,
the flesh, and the evil one,
opposing the work which the Lord mercifully begins in meetings and individuals,
and from one step to another introducing into darkness and death.
On this account my soul mourned in this meeting,
yet through honest labor I was favored with relief, but not refreshment,
a rare enjoyment in the present trying day.`"

"`We reached Bath on seventh-day afternoon,
where I was confined several days by severe indisposition,
but through divine favor was enabled to attend meeting on fifth-day,
notice of which had been given to some of the inhabitants,
and though fewer came than was desirable, it proved a solid, relieving season.`"

"`First-day, 21st, sat both meetings at Bristol in a state of suffering silence;
attended the burial of an old and dear friend, Joan Holbrow,
and paid a visit to some of the mourners in the afternoon.`"

"`Second-day, sat the Monthly Meeting at Frenchay; fourth,
had a public meeting at Thornbury, and went from there to our friend John Lury`'s,
where we spent a day or two.
First-day attended the two meetings at Bristol, where, in the evening,
a little ability was granted vocally to pray for the deliverance of such,
as are oppressed by the darkness which is so prevalent in that meeting,
and afterwards to express a few words of encouragement to an exercised and tried remnant.
Second-day evening a portion of comfort was administered,
in a solemn opportunity with a large company at the house of my beloved friend,
George Fisher;
and on third-day I was enabled by close exercise
to gain some relief in the meeting at Bristol.
It was a season laborious both to body and mind,
but one that affords satisfaction in the retrospect;
and indeed this little visit altogether has been particularly satisfactory;
with some it has felt like a final parting,
and the recollection of having once more met will, I believe, afford mutual comfort.`"

The apprehension just mentioned, proved correct,
this being the last visit my dear mother paid to her native city,
and several of her dear and long known friends
were pretty soon afterwards removed by death.

From Bristol she crossed the New-passage into Wales,
and attended meetings in the way to Milford, from which she sailed for Ireland;
and was favored to reach her own abode in safety near the end of the eleventh month,
though in a very broken state of health, and under considerable depression of mind,
from a settled belief that some heavy trials were impending.

This view soon became painfully realized,
and her affectionate feelings were keenly wounded by the death
of several near relatives occurring in quick succession,
so that, the first few months of 1803 were signally marked by sorrow and bereavements.

The summer was chiefly passed under the pressure of bodily suffering,
which was at times so severe as to induce the apprehension
that the season of full deliverance was at hand;
while at others,
her mind was still so exercised for the advancement of truth and righteousness,
that it felt as though further labor would be allotted her:
and in the depths of affliction she was given not only to behold '`fields
white unto harvest,`' but afresh to surrender herself,
when the Lord might utter His command, to enter into these and work;
being favored with resignation to the will of her divine Master,
whether as to life or death.

In the second month, 1804, she went to Waterford,
in order to perform some religious service, which she had long had a prospect of,
both among Friends and others within those borders.
The following extracts from her letters contain an account of this visits

"`I have cause to be humbly thankful for the meeting yesterday;
the covering of solemnity was sensibly prevalent over the assembly,
and there were many serious seeking minds present, who I trust were not discouraged;
while relief was afforded to my exercised spirit,
though I believe its struggles respecting this service are not at an end;
for I apprehended from the first feeling about coming here,
that the line of my duty would be as much towards others,
as the members of our own Society;
and my view respecting families is rather confined to those lately married, new settlers,
and young people in large families.`"

"`The meeting this day was exercising but solemn;
several who attended yesterday were there:
a late fashionable but now thoughtfully concerned person, and her daughter like-minded,
who are rich in this world, were at both meetings, and called at my lodgings after.
For those who may be termed '`other sheep,`' I feel deeply,
and am sensible of life being raised by the
addition of such panting souls to our assemblies:
these, whether of us, or under whatever name, will be cared for;
they will be led to rivers of refreshing water, and nourished up unto everlasting life.`"

"`This has been, like the others, a laborious week;
but I desire to fake every step manifested as the line of duty,
and though run down in strength am wonderfully supported:
memorable is the Lord`'s goodness to my exercised mind.
I never remember a more proving season to me in this line of service,
nor is the labor attended with much hope,
save that an increase of peace is humbly hoped for,
and perhaps a little addition of strength to sustain
future trials may be mercifully bestowed.`"

After an interruption of the engagement by a heavy cold, which confined her some days,
she writes:

"`My late indisposition has impeded the work,
but being in the will of Him who knows what is best, I ought to be content,
and I am very tenderly cared for, many ways.
I attended the Monthly Meeting today; the first sitting was a season of some labor,
and a visit to the men`'s meeting not less trying to body and mind;
but these exercises feel a part of the allotted burden in this place,
where in a spiritual sense, small indeed are my portions of pleasant bread.`"

"`The labors of the last week have sensibly exhausted me, yet I got to meeting yesterday,
and was mercifully strengthened to clear out in such a way that I
trust much more is not likely to be called for in this line,
while here.
I hope I shall long gratefully remember the meeting last evening;
one so large and quiet had scarcely been known here;
and I think the covering of solemnity increased to the last.
In both instances gracious help and relief of mind were afforded,
to the bowing of my soul in reverent thankfulness:
and only for the Monthly Meeting tomorrow,
and wishing to see an individual or two lately come home,
I believe I might have comfortably left Waterford.`"

She had opportunities with the individuals alluded to and was enabled to perform
some other religious service to her additional relief and satisfaction,
besides attending the Monthly Meeting,
and returned home the latter end of the third month with feelings of peaceful poverty;
which she often spoke of as a sufficient
recompense for any labor she might be engaged in.

Before leaving home to attend the Yearly Meeting in Dublin this year,
my dear mother obtained the concurrence of her friends for some religious
service to which she apprehended herself called in the province of Leinster;
and while in the metropolis she wrote as follows:

"`Sadness and silent mourning have been mostly my lot,
and the labor assigned is of a close and arduous kind.
According to my feelings things are sorrowfully low,
and in the various sittings life has been sensibly oppressed;
yet a sense of continued mercy has sustained, and in knowing that we, as a people,
still have a gracious and long suffering Father to do with, faith in His love is renewed,
and the hope of a revival among us at times consoles.`"

"`The afternoon meeting on first-day was deferred till six o`'clock,
and notice circulated among those not in profession with Friends.
At the hour appointed a large number assembled,
and an evident covering of solidity prevailed in time of silence,
to which I was strengthened to bear testimony;
being made consolingly sensible that there were present, seeking, upright minds,
to whom was held forth the nature of a worship,
unmixed and acceptable in the sight of divine purity.
I have reason to acknowledge that so far the Lord has helped,
to His name alone be the praise! "`The meeting
on third-day was a truly exercising season,
yet one which left me considerably relieved, and free to depart; which I esteem a favor,
whether any fruits of the labor be seen or not.
It was altogether a day of solemnity,
other seasons occurring which were owned by feelings not at our command,
and which ought to produce thankfulness.`"

On leaving Dublin the 10th of fifth month, she was accompanied by Susanna Hill,
a dear friend and fellow minister who felt inclined to join her,
and proved not only a kind and affectionate helper,
but a valuable associate in the labor that succeeded;
respecting which the following account is taken from my dear mother`'s letters.

"`The Monthly Meeting at Carlow on sixth-day was tolerably
attended by such as have not given up the practice,
and was a suffering time.
Susanna Hill exercised her acceptable gift in a short testimony,
and the first sitting closed with supplication.
I was soon attracted to the men`'s meeting,
and there as well as among my sisters was relieved by communicating what oppressed me,
notwithstanding life was low.
Friends in these parts who are concerned for the cause of Truth,
and take any share in maintaining the discipline, are greatly to be felt for.`"

"`We went to meeting at Kilconnor on first-day morning;
I believe the members generally got out,
and there were also some others of different professions.
It was a season of trying exercise,
as might be expected among such as have evidently joined with the spirit,
customs and fashions of this world, in appearance, I think to an uncommon degree;
but I was mercifully relieved of a burden very heavy to bear,
and for this I desire to be thankful.
We returned to Carlow, where I had requested the afternoon meeting might be postponed,
and an invitation given to the inhabitants.
At half past five, many not in profession with us, as well as most who attend meetings,
assembled; and this also proved a time of labor, so that I felt weary enough in body,
though supported to my admiration.`"

"`There are very few of our name at Athy,
but several solid persons attended the usual week-day meeting, which was a solemn season;
yet my mind was not relieved without having one of a
more public kind appointed for the next morning.
This may be acknowledged as a very favored time.
A large number of serious persons were present from among the Methodists,
and Evangelical Society; one of their preachers, and a clergyman with his wife, etc.
I trust the precious cause was not injured,
while ability was renewedly given to proclaim the doctrines of the unchangeable gospel,
and my mind felt so relieved that I could have left the place;
but we had reason to be satisfied with that evening`'s detention.
The preacher of the Evangelical Society already mentioned, came to our lodgings,
with whom I was very unexpectedly led to enter
upon some points of doctrine held by that sect.
I do not remember when a conversation of such sort left me more satisfied,
or in the retrospect afforded greater confirmation to the belief,
that however the Christian world is separated into various forms, there is,
when impartially inquired into, less real difference than we are aware of.
This man seems on ground becoming a professor of the one faith,
and breathing a spirit which would not exclude any,
but longs for all to be gathered to the teachings of the true Shepherd.
I was uncommonly thoughtful about him next morning,
and felt desirous for another interview, but supposed he had gone off early:
on coming down I found he had so designed,
but inclining to call in at T. Chandlee`'s missed the boat.
We breakfasted together, and a season to be thankfully commemorated succeeded,
under which covering we took leave of one who had been made dear to our best feelings;
he saying that he was '`thankful to that adorable
providence which had cast his lot there that week,
and brought us to be acquainted.`'`"

"`We reached Roscrea seventh-day afternoon;
the meeting on first-day morning was a trying one;
the world is a cloud to our assemblies,
and the concerns of it a bar to the growth of vital religion.
A public meeting in the evening was largely attended,
but the people being evidently under the feeling of expectation,
and not gathered in mind, caused the labor to.be proportionally arduous.
At length, however, a precious covering was spread,
and the meeting closed under a thankful sense of divine goodness.`"

"`We were detained on second-day by very heavy rain,
but had some seasons of religious retirement in the families of our friends;
and on third-day after a solemn and relieving
opportunity in the house of our cousin E. D.,
set out with a kind friend W. N., who had accompanied and stayed with us;
reached Colerain, his place of residence, to tea,
and on fourth-day attended the Monthly Meeting at Mountrath.
The first sitting was low and exercising,
a silent and painful travail of spirit being our portion.
In the women`'s meeting we endeavored honestly to discharge what we conceived our duty;
and though great dismay seems almost to overspread many rightly concerned minds,
yet I think there was a sweet solemn influence to be felt,
and the business was conducted in a solid manner.
We visited our brethren, and with them had a time of close exercise,
but relieving to both of us.`"

After this meeting,
an illness under which my dear mother had been
suffering for several days became so oppressive,
that she was compelled to lie by for a day or two,
and not getting better deemed it most prudent to return home.
She accordingly left Mountrath on second-day,
and traveling slowly reached her own house the following evening, 29th of fifth month,
greatly indisposed;
but with thankfulness of mind for the favor of
being restored to her husband and children,
and a peaceful retrospect of having pursued the path of
manifested duty as far as health was afforded.
She continued very unwell for many weeks,
her complaint proving something of a slow bilious fever,
which she thought was in a great measure induced by
sleeping in a room that had been newly painted.

In the twelfth month she passed a few weeks in Cork, visiting Friends,
and some of other denominations, in what appeared to her the line of religious duty,
and having two public meetings, besides several for different classes in our own Society.
The service, though of an exercising kind, proved peculiarly relieving,
so that she felt thankful for having been enabled to use the small portion
of faith wherein she had entered upon this '`work and labor of love.`'
