== Chapter XV

[.chapter-synopsis]
* From Twelfth month 1807, to the end of 1814
* Family Visit at Clonmel
* Death of her daughter
* Removal to London
* Visit to Friends of Southwark Monthly Meeting
* Journey into Dorset and Hants
* Religious service within the Quarterly Meeting of London and Middlesex

My dear mother had for several years believed that her
measure of gospel labor in Ireland was nearly filled up,
and her husband uniting in the desire of a removal to England,
they had for a considerable time contemplated this change,
and were arranging for its accomplishment when he was
attacked with the disease which terminated in his death.
This awful event rather tended to confirm her feelings;
and the sense of release from that part of the vineyard was accompanied by a belief,
that she should be called to labor in different parts of her native country,
while she clearly saw that the place of her future abode ought to be
within the limits of the Quarterly Meeting of London and Middlesex.

During the last two years of her residence in Clonmel,
she frequently mentioned feeling herself but as a sojourner,
and waiting for the season of departure.
In the meantime she paid a religious visit to the families of her own Monthly Meeting,
wherein she was joined by her dear niece and child in the gospel, Hannah Grubb,
who lived but a few years afterwards.

The necessary preparations for so important a
removal occupied more time than was anticipated;
and before these were completed,
it pleased Infinite Wisdom again to diminish the family circle,
and keenly try the tender feelings of this affectionate mother,
by depriving her of a much beloved daughter; one who at the age of twenty-five,
and with qualities rendered increasingly valuable by
being submitted to the regulating influence of religion,
was an endeared companion and friend, as well as an attentive and dutiful child.

She had long suffered from ill health,
but was so much benefited by spending the summer of
1809 in the neighborhood of a chalybeate spring,
that the impending voyage and journey were looked to as
a probable means of completely restoring her.
Such, however, was not the will of Him who only knows what is best for His creatures;
and to the praise of His great name it may be recorded,
that under this deeply proving affliction the Lord granted adequate support.
To this the bereaved parent was strengthened to
testify at the grave of her precious child;
and near the spot where the remains of her husband and son had been recently laid,
poured forth the humble acknowledgment of her soul to
Him who had been her refuge in many troubles,
and was then sustaining in holy confidence, and granting resignation to His will.

The attendance of the Quarterly Meeting, held at Waterford in the tenth month 1810,
was the concluding service of my beloved mother in the nation of Ireland,
where she had resided thirty-three years,
and left a great number of dear and valuable friends.
The separation from these was sensibly felt on both sides,
but the bond of Christian union which had been experienced with some,
was such as neither time nor distance could destroy; and to the end of her days,
she was frequently animated with the feeling of this gospel fellowship,
while many in that land have testified that to them her memory is precious.

She arrived in London with her family, early in the eleventh month;
and took up her abode within the compass of Southwark Monthly Meeting,
to which she was soon after recommended by certificate.

The first religious service for which my dear mother
obtained the concurrence of this Monthly Meeting,
was a visit to the families composing it.
In this extensive and important work she was joined by her friend and fellow member,
J+++.+++ H. and neither of them being able to move on rapidly,
it was a considerable time going forward;
but through merciful assistance was ultimately accomplished to their relief and peace.

She also held public meetings in various parts of the city and neighborhood,
feeling her heart enlarged in gospel love,
and some of the prospects under which she had been long exercised so matured,
that it felt as though her time and strength were to be
wholly devoted to the service of her Lord.

In the summer of 1812 she was much tried with illness,
and but partially recovered when she laid before her
Monthly meeting a concern to visit Friends and others,
in Dorsetshire and Hampshire. She left home the 18th of the eighth month,
and returned the 5th of the tenth, having travelled above four hundred and sixty miles,
and held twenty public meetings,
besides attending all belonging to Friends in those counties,
and paying family visits in most of the places visited.

For these various services my beloved mother was strengthened beyond her expectation,
and the following is transcribed from a short account of the whole.

"`In retracing the merciful dealings of the Almighty throughout this journey,
it may be thankfully acknowledged, that although many close exercises,
and deeply proving baptisms, have been experienced,
yet holy help has been so graciously vouchsafed,
as to produce the tribute of gratitude to Him,
who has indeed been strength in weakness.`"

In the eleventh month she performed a visit to the families of Longford Monthly Meeting,
and held public meetings in several places, within and near its limits,
in which service D. C. was her companion.
The following account is taken from her letters, and some short memoranda.

"`Eleventh month 15th. The meeting at Staines was large for the number of members,
and a time of exercise; but there was a door of entrance,
and through honest labor life was measurably in dominion,
for which thankfulness could be acknowledged;
and I trust also access was mercifully vouchsafed to the throne of grace.`"

"`17th. An appointed meeting at Chertsey, held in a dissenting meetinghouse,
proved a season of rather remarkable favor and relief;
the pastor was truly kind in his attentions, sitting with us in one of the pews,
and at the conclusion evincing much unity and feeling.`"

"`In the evening, a large, solid, and favored public meeting at Staines,
proved a season wherein Truth was mercifully in dominion,
for which thanksgiving was I trust, acceptably poured forth.`"

"`First-day, 22nd. Last night we concluded the visit at Staines;
it has been an arduous labor of thirty-one sittings.
I sometimes feel nearly run down; and at other precious moments,
when mercy reigns triumphant, willing to be spent in a cause beyond all things valuable.
This day at Brentford there was a large meeting of Friends, and many truly solid persons;
whether accidentally coming or not, their company was strengthening,
and it was a good and relieving season, attended with peaceful feelings.`"

"`25th. Commenced a family visit at Uxbridge; and on the 27th went to Iver,
to an appointed meeting in a room at an inn; many assembled,
who were quiet and attentive,
but of a less serious class than are sometimes to be met with.
I trust no harm was done to the precious cause, which, however feebly advocated,
it is the desire of our hearts may be advanced, and the Lord`'s name exalted.`"

"`29th. A very large meeting of Friends and
others who accepted the invitation to join us,
and it may be truly said that it proved a day of holy solemnity,
a time to be thankfully remembered to the praise of Him who is forever worthy.
A renewed favor was granted at the time of the evening sacrifice,
with a large company of Friends at our lodgings,
which we accepted as a token for good in the retreat from this field of labor,
and a parting blessing before leaving some,
to whom near and precious sympathy had bound in
a feeling beyond the power of expression.`"

"`A meeting at Ripley is fixed for tomorrow; it is heavy in prospect,
but surely we may trust a good and gracious Master who has never withheld His assistance,
and whose promise remains immutable,
'`I am with you always, even to the end of the world.`'
Ah! if to the end, in mercy and in love,
of what small importance will the conflicts be, should these even reach to this period.
'`The Lord sits upon the flood, yes, the Lord sits as King forever.`'`"

"`If we only had a little more faith,
what a blessed soaring would there be above the troubles of time;
how would the spirit rise into the treasures of eternity, the rich '`inheritance,
incorruptible, undefiled,
and that fades not away.`'
To receive a little renewed capacity to cast a look here,
is a great favor; but though it is good, when in the divine will, to be thus helped,
the descendings must also be borne;
and perhaps we are never so fitted to arise as when we have afresh partaken of a state,
where, as at '`the bottom of the mountains, earth with her bars`' has been about us,
and the head wrapped as with weeds.`"

"`Twelfth month 1st. Attended the proposed meeting at Ripley, which was held,
in a dissenting chapel; it was a solemn relieving time,
among a people willingly receiving the important doctrines of the gospel,
as ability for proclaiming them was afforded; the pastor,
a solid looking young man cordially shook hands with us,
and desired that the blessing of heavenly goodness might be ours.
What a day of openness and Christian unity is the present!`"

The concluding service in this embassy was a public meeting at Windsor,
which had cost my beloved parent much thoughtfulness,
and was appointed under a deep sense of its importance,
and her own insufficiency for any good word or work.
Almighty assistance was, however, proportioned to the occasion,
and she thus relates the fulfillment of what had been a heavy prospect.

"`To the praise of divine mercy it may be thankfully acknowledged,
that by the all-sufficient help of a gracious Master, this long borne burden is removed:
this has been a solemn day, a season of renewed goodness,
and one which afresh encourages the hope of continued aid,
in every remaining step that Infinite Wisdom may appoint.`"

Early in the year 1813, my dear mother obtained the necessary concurrence of her friends,
for such religious service within the Quarterly meeting of
London and Middlesex as she might apprehend herself called to,
and be favored with strength to perform.

Her first engagement was a visit to the families
which composed the Monthly meeting of Barking,
wherein she was accompanied by E. J. F. During this service,
she felt her mind attracted to several places both in the neighborhood of Friends,
and where the principles we profess were but little known,
and held numerous public meetings to the relief and comfort of her exercised spirit,
and there is good ground to believe to the help and instruction of others.

In briefly noticing some of these seasons, she makes the following remarks:

"`Held a public meeting this evening, in a barn, for the inhabitants of East-Ham,
the first which I have ever ventured to appoint
in a place where opposition was threatened.
This was the case by a magistrate in that parish, but either from fear,
or conviction of being wrong, he was restrained, and the meeting was,
through divine favor, satisfactory and solemn, being also largely attended.`"

"`A sweet and precious feeling accompanies the belief,
that in some of these little villages there is a people
under the gracious care of Israel`'s Shepherd,
and whom He is gathering by His almighty arm nigh unto Himself.`"

After this she was similarly engaged within the precincts of Kingston Monthly meeting,
at the termination of which service she writes as follows:

"`We concluded this work and labor of gospel love, by a visit to a family,
which completes the fiftieth sitting.
I hope that where the seed has been honestly sown, all will not be lost; but that,
through the heavenly blessing, some increase may appear; yet,
whether this is the case or not,
the servant is to receive and follow the word of holy command,
and leave the outcome to Him who has all power.`"

"`It has been a field of labor indeed,
and also a time of entering into near sympathy with some,
who appeared to need strengthening and encouragement,
in order that they might manifest increasing attachment to the cause of righteousness,
and experience qualification to advocate it,
according to the purposes of Infinite Wisdom and to their own peace.
That no stratagem of the adversary may defeat the Lord`'s work in any of these,
is the earnest desire of my spirit.`"

A visit to the various schools conducted by Friends, in the vicinity of London,
constituted part of the present service;
and in conjunction with her dear friend Stephen Grellet,
she also visited many of the public institutions in the metropolis.
She was religiously concerned that the inmates of such charitable asylums,
should duly estimate and improve their great advantages of leisure,
and incitement to gratitude;
a feeling which my beloved mother was accustomed to
represent as worthy of being cherished by young and old,
and peculiarly acceptable in the sight of Him from whom every mercy is received.

The annexed letter will not, it is believed, be unsuitably introduced here.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Caraberwell, Sixth month 18th, 1813.

[.salutation]
To Louis Majolier, and other Friends of the Meetings in the South of France,
visited in 1788.

I may truly say, that although so many years have passed over,
and various have been your and my conflicts, beloved friends,
many waters have not quenched love; but that this sweetly banding influence,
being from time to time renewed, has made, and still keeps you,
as epistles written in my heart;
and while there has been no communication with the tongue or pen, desires, yes,
fervent prayers have often ascended, that the God of all grace might preserve,
strengthen and settle you, in the faith of His unchangeable and glorious gospel.
This remains the power of God unto salvation to all who happily obey it, though patience,
as well as faith, may be closely and painfully proved.

Trials were part of the legacy which our dear Lord and Master, Jesus Christ,
bequeathed to His humble followers.
'`In the world you shall have tribulation;`'
but ah! my beloved brethren and sisters,
in Him the light, life and power, is the treasure of peace, the pearl of great price.
In possessing Him as the way, the truth, and the life, in the soul,
all is rightly estimated; every sublunary good, or what may be termed evil or afflictive,
are kept in their proper subordinate places, and through all and in all,
He is the one source of solid hope, the spring of all our help.

May you grow, then, my dear brethren and sisters, in the root of life,
and may this lie so deep, and spread so widely,
that the branches may be lively and the fruit abundant, to the Lord`'s praise.

I sit up in bed, where illness has kept me some days,
just to tell those in that dear nation whom I have seen, and so long loved,
that they are truly dear to my heart;
as were those who have gone from your little church to that of the first-born in heaven.
This feeble but sincere salutation is designed to be handed
you by a brother dearly beloved and your countryman, Stephen Grellet,
whose heart the Lord has so enlarged as to make
him willing at this time of trial to visit you,
and such others as he may be turned towards in the pure disinterested love of the gospel.
You will doubtless receive him with gladness,
and may you be mutually refreshed and comforted,
if it be the will of Him who is thus remembering his flock and family,
scattered up and down on the habitable earth.
These the Lord is graciously regarding,
not only by calling His devoted messengers to run to and fro,
and declare His counsel in the ability received,
but causing many to know Him by blessed experience, as the everlasting Shepherd,
ready to lead beside the still waters, and in the green pastures of spiritual life.

Such will not lack,
as they humbly and resignedly follow Him in the paths of righteousness;
but through His abundant mercy, when walking through the valley and shadow of death,
be preserved from the fear of evil, and feel His rod and staff to support to, and at,
the end of all danger, conflict and pain.
This is the rich inheritance, my dear brethren and sisters,
which I pray we may each of us diligently seek, and happily obtain;
then in due season we shall meet where parting can be no more,
and unite in the one song of harmonious praise through eternal duration.

I feel the extension of Christian love to the various classes among you,
and with all my heart say farewell in the Lord!

[.signed-section-closing]
Your poor feeble, but affectionate sister,

[.signed-section-signature]
Mary Dudley.

--

At the time of the autumn Quarterly meeting,
she felt her mind so exercised on account of the young people belonging to it,
as to have a meeting appointed specially for them,
respecting which she made the following short memorandum.

"`Ninth month 29th, 1813.
A large and truly solemn season with those constituting the class from children to youth,
and advancing to maturity.
The pins of my enfeebled tabernacle seemed sensibly loosening at that time,
yet gracious help was vouchsafed, so that some good relief of mind was obtained,
and thankfulness felt for the renewed favor experienced.
Strong is the attraction which I feel to this beloved class of the people.`"

In the Twelfth month she entered upon a visit to some
of the families belonging to Devonshire-house meeting,
not feeling bound to the whole,
nor expecting that bodily strength would admit of extended procedure.

She had been only a few weeks engaged in the service,
when a heavy and alarming attack of illness occasioned an interruption,
which continued for several months; during which time she was brought very low indeed,
and in her own apprehension, and that of most who saw her,
not likely to be again equal to much active service.
But it pleased Him with whom is all power, to raise her from this state of weakness,
and afresh qualify her to advocate His cause.

When sufficiently recovered, the visit already mentioned was resumed,
and after having sat in above thirty families,
she felt her mind released from the exercise,
and adds the following remark to her notice of the last family she visited.

"`A truly solemn season,
confirming in the trust that this warfare was not engaged in at our own cost;
but through unmerited mercy, that all things requisite have been vouchsafed,
and the blessed experience given in some seasons of refreshing influence,
that such as water are watered themselves.`"

In this service she was accompanied by R. C.

While confined by illness from one of our Quarterly meetings about this time,
she wrote as follows:

"`After parting with two of my beloved children this morning,
whom I would gladly have accompanied as to a solemn assembly,
I was sensible of a degree of overshadowing goodness,
under the calming influence whereof I seemed drawn to consider,
how at such seasons there might be a profitable mingling in spirit,
even under external separation; whereby united prayers might ascend,
that the return of these convocations should be holy,
like the solemn feasts or fasts divinely appointed, and consecrated to the Lord.`"

"`It appears clear to my best feelings, that if those gathered,
and such as are in right ordering personally absent,
were first to feel after the renewings of inward strength,
bringing their spirits into a state of humble waiting,
resignation would be their peaceful covering as individuals,
and in proportion to the degree of spiritual life attained to,
concern felt that the assemblies might be crowned by the presence of the King Immortal;
or if he proved a God hiding himself,
that His devoted children might continue the acceptable exercise of faith and patience,
until he was pleased to command
'`light to shine out of obscurity, and their darkness to be as the noon day.`'
Yes, such would be encouraged to put up a prayer for the remnant that is left,
whether in vocal or mental aspiration,
till the Lord turn the captivity of the people generally,
and cause a glorious breaking forth as on the right hand and on the left.`"

"`Universal as this desire may be, extending from sea to sea, and from shore to shore,
I have been and am now afresh sensible,
that there are desires peculiarly earnest for the people among whom we dwell,
and bonds of spiritual unity with those of our brethren, who in a measure of pure life,
we feel as bone of our bone.
While for these the desire is renewedly raised,
that each may stand faithfully in their lot,
willing to do or suffer according to the divine will; fervent also is the solicitude,
that such as have not stepped further than the outer court,
may be brought under the awakening power of Him who sits between the cherubims,
and whose name is holy!`"

"`I am thankful to feel, in my secluded state,
and while tried with pain hard to nature, but I hope not murmured at,
the prevalence of that love which drew me here; where, as in my home,
I feel settled in concern for a Quarterly meeting, large and important,
as composed of various members, each designed to fill some place in the militant,
and be fitted to join the triumphant, church, when to them time shall be no longer.`"

"`I pray that the harmonizing power of divine love may be so known,
as for the great design to be fully answered, and that none may rest in a name,
without an experience of the nature of true religion.`"

"`I have viewed mentally an assembly such as our Quarterly meeting,
collected under the solemn profession of being spiritual worshippers,
sitting in outward silence before the Lord, and apparently waiting only upon Him.
Oh, the awfulness wherewith I have often beheld these meetings,
while my eye has affected my heart, and the language forcibly arisen,
let us be as we appear, let us gather to the Source of unfailing help;
fully believing that if all were properly engaged in feeling their needs,
and the only way of having them supplied,
the united breathing would ascend as pure incense,
and the lifting up of the heart be an acceptable sacrifice.`"

"`The Lord is powerfully at work in the earth,
operating through various means to effect his unsearchable purposes.
Oh! that the respective ranks in a society holding in profession the standard of Truth,
the sufficiency of divine light, the necessity of redeeming, sanctifying grace,
may not only see, but duly consider, their high and holy calling.`"

"`It is religious consideration which all have need increasingly to dwell under,
and were the mind sufficiently withdrawn from sublunary objects,
to the contemplation of those which are alone pure and permanent,
many would assuredly be prepared in a spiritual sense,
to unite in the testimony which was borne on a very inferior occasion,
by one coming from far, the one half was not told me.
No, verily! for had the Lord`'s messengers '`the tongue of the learned,`'
or could they utter with angelic power the sensations they may,
at times, be favored with, all would fall short in describing the beauty of Zion,
the safety of her inhabitants,
and those transcendent pleasures which are at God`'s right hand.
Let the Lord then work in your hearts, beloved young friends,
convincing how true substantial rest is to be found,
and through converting goodness entered into.`"

"`The choice is left to us all, none will be forced into the path of happiness;
but as the awakening attractive influence of divine love is yielded to,
and the light which makes manifest obediently followed,
the work of transformation will gradually advance;
'`the new man which after God is created in righteousness and
true holiness,`' will strengthen and mature,
until there is a reaching to the fulness of the stature mercifully designed.`"

After my beloved mother got out to meetings, and was again engaged in active service,
she wrote the succeeding observations:

"`Wonderful have been the dealings of unerring wisdom;
marvelously has the Lord preserved, sustained, and even consoled me,
in and through innumerable conflicts of body and mind,
and under inexpressibly proving privations.
Yes, He has, to my humbling admiration, made the clouds His chariots,
and the sorest afflictions ministers of His will;
having in some small proportion to multiplied advantages in the line of suffering,
effected submission, and I reverently trust,
produced increasing desire to love and serve Him.
Yet is my sole reliance placed upon His abundant goodness:
here I depend for the gracious acceptance of my
feeble efforts to promote His ever worthy cause,
and forgiveness of all omissions and commissions
against the pure revealed will of my divine Master.`"

"`Unprofitable servant, is a language I can unequivocally adopt,
and if I could sound through the whole earth what is my heartfelt belief,
it would be in unison with apostolic declaration,
'`Not by works of righteousness which we have done,
but according to His mercy He saved us,
by the washing of regeneration and renewing of the Holy Ghost.`'`"

"`Mercy, mercy is the sum and substance of my hope.
The unmerited mercy of God in Christ Jesus, for the remission of sins,
and perfecting the work of preparation for admittance into eternal settlement.`"

"`It is now between forty and fifty years since this ever to
be extolled mercy called me from darkness into light,
in a spiritual sense,
and the Lord was pleased to open the doctrines of the gospel with clearness to my view.
I trust I am safe in saying,
that since that time I have not dared to call in question the ways of His working,
nor to doubt the appointed means of salvation,
as revealed when my awakened soul in deep prostration understood the language,
and uttered it, A Savior or I die, a Redeemer or I perish.`"

"`Here conviction and repentance were known to be produced by
the efficacious working of the promised gift,
and nothing was left to depend upon,
but the purchased redemption through the great Sacrifice without,
and the sanctifying influence within.`"

"`What God has thus joined together, none can,
without derogating from his power and wisdom, put asunder.
I wish to leave the expression of my unshaken
faith in the stupendous plan of divine love,
as manifested in the incarnation, sufferings, crucifixion,
and resurrection of the ever blessed Redeemer,
His all-sufficient atonement for the guilt of sin,
and continued intercession for poor fallen man;
until in the gradual process of regeneration,
the dominion over all evil is happily effected,
and the great design in man`'s formation mercifully accomplished,
by his experience of full redemption,
through the operation of the pure and purifying spirit of Christ.`"

"`As this influence is submitted to,
there is a progressive advancement in the divine life,
from the state of childhood to that of maturity,
and a growing capacity to comprehend '`the deep things of God.`'
These are internally revealed through communion with Him,
the spring and source of all good,
when the mind is abstracted from every inferior feeling or consolation,
and knows the various streams of comfort to be as it were
swallowed up and lost in the ocean of ineffable love.`"

"`Surely the Christian believer is invited to experience redemption,
not only from the pollution of sin, the love of the world and its spirit,
the false ways and worship of man`'s ordaining; but from all mixture of creaturely choice,
wisdom, or willing.
And the heart which unreservedly yields to the refining process,
does witness redemption from self-seeking,
so as not to be moved by the praise or censure of men,
but in humble resignation uniformly breathes the acceptable language,
'`Your will be done.`'`"
