== Chapter XVII

[.chapter-synopsis]
* Visit to the families belonging to Devonshire Monthly meeting.
* Illness and death. From Twelfth month 1822, to Ninth month 1823.

In the twelfth month, 1822,
my beloved mother informed her friends of a fresh prospect of religious duty,
and obtained a certificate for visiting the
families belonging to Devonshire-house meeting,
as well as some more public service as strength might be afforded.

One of her first engagements was,
the appointment of a meeting for the young people belonging to
the Quarterly meeting of London and Middlesex.
This proved a time of solemnity and relief,
and she afterwards expressed her satisfaction in reflecting on the opportunity,
as well as her belief that it would be the last she should have of that kind.

The family visit in Devonshire-house meeting was commenced early in the first month,
1823; and although the weather was extremely cold,
my dear parent was strengthened to pursue the service in a manner wonderful to herself,
as well as to those who witnessed it.

Sometimes, at the conclusion of a day wherein she had satin five or six families,
she would remark that the haste she felt was such as
made her scarcely sensible to bodily fatigue.

After paying above one hundred and thirty visits,
with much less interruption than had frequently
attended such engagements in younger life,
she wound up this service amongst her fellow professors, in which M. S. had been united,
by having a meeting appointed for the heads of families,
and another for the young people constituting that particular meeting.

On one of these occasions,
when closely expostulating with some for whom deep religious concern had been felt,
my dear mother said with peculiar emphasis,
"`Bear with me, my friends, I have not long to speak.`"

On first-day, the 16th of third month,
she was largely exercised in the forenoon meeting at Devonshire-house,
and in the evening had an appointed meeting for the inhabitants of that neighborhood,
wherein she was wonderfully strengthened to
proclaim the important doctrines of the gospel,
in which she so surely believed.

While inviting those present to the consideration of their latter end,
she mentioned how surprisingly her own life had been extended,
and that having completed more than the threescore and ten years,
she could then look back upon her existence as but a point in comparison with eternity.

The solemnity which prevailed at that season was remarked by many who attended it,
and upon returning home in a very exhausted state of body,
my beloved mother expressed the peace and satisfaction with which her mind was clothed.
In the morning she also observed,
that whenever she had awoke in the night the remembrance of
that meeting was sweet and comforting to her,
and that she loved to think of the feelings by which it had been marked.

Thus with alacrity, and even cheerfulness,
did this aged servant of the Lord prosecute the closing labors of her day,
repeatedly observing, that although sometimes weary in her work,
she could honestly say she was not weary of it,
but felt the service of her Lord and Master to
constitute her meat and drink in a spiritual sense.

At the Quarterly meeting in the spring she was powerfully
engaged in advocating the cause and name of her Redeemer,
and seemed to overflow with love and solicitude towards her friends:
while the strength and clearness of her voice was
deemed by many an indication of renovated health.

For several weeks afterwards she continued to get out regularly,
and on first-day the 13th of fourth month, attended her own meeting at Peckham,
morning and afternoon; in the first she was exercised in the ministry,
and spoke of both seasons as having been times of refreshment to her spirit.

She was at the Monthly meeting of Southwark on the third-day following,
and continued tolerably well until sixth-day the 18th,
when she was affected with symptoms of a heavy cold,
and in the evening palpitation of the heart and faintness.
As my beloved mother was accustomed to sudden attacks of indisposition,
we did not feel any particular alarm.
Next day, however, she appeared very unwell,
and during several succeeding days repeatedly mentioned,
that she felt so loaded with illness as to make her apprehend
that nature would sink under the oppressive weight;
while this was always expressed in much calmness,
and with perfect resignation to the divine will.

Sixth-day the 25th, after taking with a relish something which had been prepared for her,
she said with great sweetness,
"`How good is our gracious Provider in thus supplying us with all we need;
yet how apt are we to pass by Him, regale ourselves with His gifts,
and forget the giver.`"

During that and the following day she was frequently
employed in a strain of heavenly rejoicing,
and once observed,
"`How little idea we can form of what will open upon the
spirit when the incumbrance of mortality is laid down.
I have not a wish to go,
if I could proclaim to one more soul the rich mercy of God in Christ;
but if it be the will of the Lord to take me,
I hope my dear children you will be resigned, and preserved from all evil;
and may the Lord preserve your goings out and
comings in from that day forth and for evermore.
I have no sight as to how it may be, but I do not feel able to struggle as heretofore;
my strength seems giving way, the sands sinking fast; but they may be renewed.`"

At another time, "`I have nothing to depend on, not a shred of my own,
no good works to tell of, only mercy; that which visited me in the morning of the day,
has supported me through life, and will support me in death; unmerited, unbounded,
and I trust unchangeable mercy!
I have loved the cause of my Redeemer; it was to draw to Him,
to attract and fix the attention of the mind on Him alone, that I have been willing,
made willing, to proclaim His goodness;
and though one Philip after another be taken away,
yet the happily awakened soul may go on rejoicing.
This was the case with the Ethiopian, while Philip was found at Azotus,
sent and commissioned to preach to others the unsearchable riches of Christ.

Seventh-day the 26th, was one of much bodily suffering; in the evening she said,
"`the Lord bless you, my precious child, for your care of me;
we have been together in heights and depths, in poverty,
and sometimes in the riches of the gospel; had it not been for a portion of these,
we must have utterly sunk under conflict and multiplied exercises, even of later times.`"

"`I am thankful that the labor in Devonshire-house quarter was accomplished,
and for those last meetings, both with Friends and others;
the Lord be praised for the strength He afforded to proclaim His goodness,
and He will be praised.
You may know more of it when I am dead and gone,
for there was a witness in many hearts to that which was his own work.`"

"`I have no sight of how it will be with me, at which I almost wonder;
but it will not do to judge by the weakness of the poor body;
the Lord can raise it up if it be His blessed will.
His will has been all to me, when the conclusions, doublings,
and hesitations of nature have been kept down.`"

"`'`Thy will be done,`'`" is the highest anthem ever sung on earth or in heaven;
that will of God which is our sanctification; and when fully yielded to,
operates in its own regulating and redeeming power, raising out of the fall,
and restoring to all that was lost, this I am sure of, to all that was lost,
the second Adam, the Lord's new creation in the quickened and believing soul.
My heart is full, but the poor body must have rest.
I trust you will be supported; try for a little rest;
this is granted to poor human nature as well as to the mind.`"

On awaking from an uneasy slumber she exclaimed,
"`Excellent, excellent;`" and asking her what was so excellent,
she replied with energy,
"`The support of religion is most excellent.`"

Third-day morning, the 29th.
My precious mother desired that the
12th chapter of the Hebrews might be read to her,
and while hearing it,
seemed as if deriving peculiar comfort from that
blessed record of divine doctrine and instruction;
observing, it was part of that chapter which engaged my attention
at the last meeting I bore testimony in London.
Upon the last verse but one being read,
"`Let us have grace whereby we may serve God acceptably with reverence and godly fear,`"
she audibly pronounced "`Amen, amen, amen.`"

Fifth-day, 1st of fifth month.
After a time of silence she evinced how her mind had been
occupied by mentioning the Yearly meeting of Ireland,
and said: "`A large number of Friends are collected in Dublin this day,
and many dear creatures; I wish they may be enabled to do their duty,
and preach Christ to the people.`"

Afterwards, with much composure,
and in a tone that bespoke the feeling of renewed thankfulness:
"`I seem to have nothing to do but with the present moment,
no looking back with pain or uneasiness,
but in grateful remembrance of that mercy whereon I trust there was a building long ago.
Oh, not to doubt the foundation is a great mercy; warn them, tell all,
there is no other way but resigning up all, the management of ship and cargo,
to the true, unerring pilot.
Then, (alluding to Paul's shipwreck,) though the vessel may be tossed,
however any are tried, some as on boards, and some on broken pieces of the ship, but oh,
the consolation, all will get safe to land.`"

"`Every feeling and desire of my heart seems comprehended in the language,
'`Thy will be done.`'
Only I fear that through long continued
suffering I may not exemplify that which I have declared to others,
the sufficiency of divine power: may patience have her perfect work,
whether any glimpse of the unspeakable glory be afforded or not.
Oh, if this is known, it must be glory to God in the highest,
through Him who came to procure peace on earth.
The language of the redeemed through all eternity will be, '`Not unto us, not unto us,
but unto Your name be the praise.`'

"`I sometimes feel as if I could fly even to distant
lands to proclaim the gospel of life and salvation:
'`the earth shall be filled with the knowledge
of the Lord as the waters cover the sea.`'`"

In the night of the 4th of fifth month,
my dear mother's mind appeared to be deeply exercised on some doctrinal subjects,
and she said with great energy: "`For a man to have his Bible in his hand and read,
'`as I live says the Lord God, I have no pleasure in the death of the wicked,
but that the wicked turn from his way and live,`' and then
venture to say that any soul is created for destruction!
Oh! surely the present dogmas nearly amount to an assertion of this kind;
I have not so learned Christ.
It is dangerous, dangerous.`"

"`I am a believer in the election of grace, the covenant and seed of life,
but not in the possibility of any state where the petition,
'`Lord save,'` will not be necessary,
nor that any human being is excluded from the offer of divine mercy.`"

Once on taking leave for the night she sweetly said,
"`The Lord direct our hearts into the love of God,
and into the patient waiting for Christ; then all will be well.`"
Thankfulness for favors received seemed the continual clothing of her spirit;
and instead of dwelling upon her complaints,
or recurring to the numerous afflictions which had marked her pilgrimage through time,
she spoke of the blessings afforded her, as abundantly beyond her deserts, saying,
"`What mercies I am a partaker of, and how poor and unworthy I feel, nothing to trust to,
but mercy, mercy, mercy; that which was early extended, that which has ever sustained.
Wonderfully was preserving grace afforded in the morning of my day,
guarding from evil and keeping from many snares.
It may well be said I girded you when you did not know me;
and since my heart has been surrendered to divine government and guidance,
the promise has been graciously verified,
'`I will never leave you, nor forsake you;`' Oh this rock.`"

The 7th of the fifth month was a day of considerable suffering from cough, etc.,
and the appearance of exhaustion was very painful.

When a little revived, my dear mother observed:
"`Sometimes after a fit of coughing it seems as if I should sink away,
and then again the feeling is rather different;
how it will be is remarkably hidden from me, but I feel perfect quiet and resignation.
What a mercy to have no burden or anxiety, though I am poor and unworthy,
nothing to depend on but the one foundation; if that fails, all is over;
but it never will fail; the mercy of God in Christ Jesus:
and whether I am able to express much or not, when the time comes, this is my anchor.
Oh! now to have a conscience stung with guilt! and this
might be the case but for gracious unmerited mercy:
for what am I? what have I? but '`He that spared not His own Son,
but delivered him up for us all,
how shall He not with Him also freely give us all things`' in time and in eternity.`"

"`I trust I have not been equivocal in proclaiming gospel doctrine,
that I have not shunned to declare what I believe to be the whole counsel of God.`"

On obtaining relief from a distressing symptom,
she desired the psalm might be read to her which begins, '`Unto you, oh God,
do we give thanks, for that Your name is near, Your wondrous works declare.`'

First-day the 12th, while Friends were at meeting,
my beloved mother requested her daughters to sit still awhile in her chamber;
and after a time of solemn silence uttered the following supplication:
"`Wherever gathered, Holy Lord God Almighty! whether in this little meeting,
in larger congregations, or under whatever name assembled,
bless those who wait upon and worship You.
Let your word have free course and be glorified
to the increase of the dear Redeemer's kingdom,
and the advancement of the great,
the glorious and universal work spoken of by your prophet,
when from the north and from the south, from the east and from the west,
Your suppliants shall be brought.`"

"`Bring them, gracious Lord, near unto Thyself; bring us, as a family.
Bless my children, I pray You; Your poor unworthy creature,
yet one who through Your mercy has trusted in You, and been desirous of Your glory.`"`"

She then prayed for each of her family,
in a manner which showed the clearness of her spiritual perceptions,
and the deep religious concern renewedly awakened on
account of those most near to her affections,
and concluded with these words, "`Wash all in the laver of regeneration,
and grant the renewings of the Holy Ghost,
that You gracious Father may be praised in time, and with the dear Son of Your love,
everlastingly receive glory and honor, thanksgiving and renown.
Amen and amen.`"

Her voice was remarkably strengthened for this exertion, and she afterwards observed,
"`What a mercy to be favored with a little fresh feeling;
without the fresh feeling what is all expression, what is anything?`"

In the afternoon she addressed her kind physician,
in a manner which evinced strong interest and Christian solicitude on his behalf,
offering gospel counsel and encouragement,
and enforcing the necessity of constant watchfulness and prayer.
She expressed feeling obliged by his affectionate attention;
to which he replied that he deemed it a privilege to
have the opportunity of attending her.

Upon one of her sons mentioning that his wife had been
detained from public worship that day on account of her infant,
she promptly answered,
"`'`The tabernacle of God is with man.`'
We have duties to fulfill;
but there is an altar to which we may continually resort:
the gracious language is accomplished,
'`He that is with you shall be in you;`' adding,
"`your children are very near to me; the Lord bless you and the dear babes;
Oh may He keep them from the evils of the world:
the evils of the heart must be gradually overcome
through submission to the spirit of Christ.`"

Third-day the 14th, hearing of our dear friend Mary Proud's being alarmingly ill,
my beloved mother was much affected,
and spoke of her as an endeared sister and fellow laborer in the gospel;
after a short pause she solemnly exclaimed;
"`Oh our poor Society!
Lord raise up judges, counsellors, feelers,
such as are quick of understanding in Your fear; and if children are to become teachers,
give them wisdom and humility.`"

The approach of the Yearly meeting was watched with lively interest by my dear parent,
and when it began her mind seemed clothed with the same Christian
solicitude as if she were personally mingling with her friends.

This was in degree manifested by an address which she
dictated to the Meeting of Ministers and Elders,
as well as by messages to many of her brethren
and sisters who were engaged in active service;
and she entered into the concerns of that important season as
fully at times as if she had no bodily ailment.
Yet her weakness was such as to render her unfit to see company,
and often to excite apprehension that her vital powers were rapidly sinking;
while she was still kept in ignorance, and as she would sometimes say,
remarkably blind as to the event.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Yearly meeting of Ministers and Elders, held in London, fifth month, 1823.

[.salutation]
"`Dearly beloved Friends,

Separated from you by the pressure of extreme bodily weakness,
that love which I trust is of the everlasting gospel,
has caused me to visit you in spirit,
and even bound in sympathy under your solemn deliberations.
Your attention has been claimed by the return of messengers, who,
having been enabled to lift up their eyes and look on the fields,
now thankfully feel that He who led into labor,
graciously sustained through the portion allotted them,
while they dare not rejoice in anything but the humble hope, at times afforded,
that through unmerited mercy their names are written in heaven, and their feeble efforts,
for the promotion of His ever blessed cause, accepted by the great Lord of the harvest.
You have also been called upon as a collected body,
to receive the acknowledgment that views of a similar, or more extensive nature,
are opened to some others who have been alike separated for the work of the ministry.

In considering the present state of things at home and abroad,
not only the lack of the prevalence of divine life,
but in many instances the oppression of the heavenly Seed; how has my soul travailed,
that such as are sent forth may not only go in the fulness of gospel commission,
but so dwell deep with the gift, as to be faithful to its revealings,
watchful and patient in times of concealing, and resigned to those reducing,
as well as qualifying operations,
whereby the command given to the tribe of Levi maybe understood,
and from time to time obeyed:
'`Let your Thummim and your Urim be with your Holy One,
whom you did prove at Massah,
and with whom you did strive at the waters of Meribah.`'
Here is the safety of ministers in this day,
as it was in preceding ages, who knowing that all their help is from the Lord,
cast their care wholly upon Him.

And for you, dear Friends, who are called, though in a less public manner, to labor,
whether at seasons in word and doctrine,
or as deeply baptized Elders to act like Aarons and Hurs,
my heart is engaged in sisterly concern.

Some of you in your different meetings, with larger or smaller companies,
have long known what it is, while desiring to bear your own part of the burden,
to sit as with your mouths in the dust, ready to utter the bemoaning language,
'`What advantage is it to me if the dead rise not.`'
May these be strengthened to hold on their way,
accepting for their encouragement the scriptural assertion,
'`Unto you it is given in the behalf of Christ not only to believe on Him,
but also to suffer for His sake;`' while through this deep experience there
is an increasing capacity to '`know Him and the power of His resurrection,
and the fellowship of His sufferings,`' so as to be '`made conformable unto
his death.`' The Lord has not forsaken His long regarded people,
though '`the time to favor Zion`' in the way that exercised spirits crave,
'`the set time,`' may not be yet come.
The Redeemer's kingdom will spread in His own way; the work is great,
but the arm which is carrying it forward is Omnipotent.

To the Lord then let us look; in Him let us trust, and to His name,
which is everlastingly worthy, be the glory ascribed now and forever.
Amen.

In the feeling of affectionate and gospel love, I salute you,
and am your very poor and variously tried friend,

[.signed-section-signature]
Mary Dudley`"

[.signed-section-context-close]
Dictated in her sick chamber but signed with her own hand at Peckham,
the 28th of Fifth month, 1823.

--

In the early part of the sixth month she so far revived as to
bear being taken from her chamber to a sitting room,
where, reclined on a sofa, and mercifully excused from much pain,
she frequently saw her friends,
and enjoyed that social and religious communion for which her
mind and disposition were so peculiarly adapted.

The first strangers she saw were two of her sisters in the ministry,
to whom she imparted much of her feeling on the most important subjects;
encouraging them to individual faithfulness,
and making many observations which are likely to
be well remembered by those who heard them.

She feelingly expressed her own sense of unworthiness,
and that her sole dependance was on the mercy and merits of her Redeemer.

The same day she had a very interesting interview with Isaac Stephenson,
whom she wished to see previously to his embarkation to America.

She was wonderfully helped to testify her continued
zeal in the cause of truth and righteousness,
as well as affectionate concern for those engaged in gospel missions,
earnestly desiring that divine assistance and
preservation might be experienced by this dear friend,
whom she blessed in the name of the Lord.

During the seventh month,
my precious mother was so far recovered as to ride out several times;
and we began to entertain hopes of a partial restoration,
fondly anticipating the probability of enjoying her valued society,
even though the days of active service might be over.

This she frequently said she believed was the case;
and spoke of the peaceful retrospect which she was often enabled to take,
while feeling that her gospel labors were only
valuable as tests of her love and obedience,
but not furnishing any ground of dependance.
Yet she was much engaged in encouraging to faithfulness,
often saying to those who visited her, as well as to her attendants,
"`Mind that the day's work keeps pace with the day;`"
and in exhorting her fellow ministers strongly expressed the
necessity of being completely devoted to the sacred calling,
and not shunning to declare the whole counsel of God.

These communications were accompanied by remarks which
evinced great humility with respect to her own services.
Once, upon some allusion being made to her diligent occupation of
the time and talents with which she was entrusted;
she sweetly and in great tenderness of spirit, replied,
"`Feebly and unworthily as they have been used,
I trust it was with a single view to the help of others,
and the glory of the dear Redeemer; and if He forgives all the mixture,
all that has been of the creature, and mercifully receives me into rest and peace,
whether he affords those bright prospects, which in the beginning of this illness,
and often since, have been vouchsafed, or not, oh,
may I never doubt or cast away my confidence.`"

"`I trust that He who has loved with an everlasting love, will continue to uphold me,
notwithstanding all the weakness of the flesh, and the temptations of the cruel enemy.
Oh this enemy! he never quits his hold of poor human nature while he can assail it.
Where is it said that the Savior condescended to be tempted?`"
The passage 14th of Hebrews and 15th verse was then repeated, to which she assented,
as what conveyed comfort to her soul.

Afterwards, when under considerable suffering of body, she prayed for patience,
and added "`Oh! if I should become impatient with the divine will,
what reproach it would occasion.
I feel poor and empty,
and when lying awake am not able to fix my thoughts upon what I desire and prefer,
but little things present, and this tries me.
David speaks of having songs in the night, but I sometimes say,
these (meaning intrusive thoughts), are not the Lord's songs.`"

"`I have nothing in the world that really occupies me,
no object of peculiar interest except my children,
and these I can leave to Him who I trust will care for them and protect them.`"

It was very striking to us,
and to some of those friends who occasionally saw my precious mother,
how entirely she was abstracted from temporal things,
seldom evincing much interest about passing events,
and repeatedly observing that every thing of a
terrestrial nature was so nearly alike to her,
that she could say desire had failed.

There was also such a settled solemnity of countenance
as indicated her thoughts and mind being in heaven.
I scarcely remember seeing her smile during the whole illness,
though nothing of gloom or anxiety was apparent.

Some Friends, for whose best welfare she had been long concerned,
coming to take leave of her when about to go a journey,
she testified the continuance of her solicitude by imparting much Christian counsel.
She enjoined the young people of the family to value the privileges of their education,
and not to be ashamed of the cross, even in what are termed little things;
saying that she wished the standard of simplicity might never be lowered amongst us,
and as their temptations to deviate would be likely to increase,
she felt earnest in pressing what it was probable would be her last advice.
This proved the case, for though she lived until their return, they never again met.

Early in the eighth month symptoms of increasing debility came on,
and it was obvious that her constitution was gradually sinking.
Of this she was fully aware, though from tenderness to those about her,
she seldom spoke on the subject.

On being settled in bed one night she solemnly said, "`When this poor body drops,
I should like if Friends see no objection, for it to be taken into Southwark meeting,
and from there to Bunhill Fields.
No invitations to be given, nor any unnecessary expense gone to;
only information to my friends that the pins of
the earthly tabernacle have at length fallen out.
Nothing done, nothing said, nor if possible thought,
but what lays the creature where it ought to be, and I trust is,
prostrate at the footstool of divine mercy: a poor, humble yet confiding sinner.`"

"`I trust enough may have been said, however feebly,
to manifest my faith and the ground of my hopes,
which solely rest upon the mercy and goodness of God in Jesus Christ.`"^
footnote:[In some written directions respecting her burial,
penned several years before her death, there are a few observations which,
in addition to the desire expressed above,
contain such evidence of gospel concern on behalf of her fellow members,
as to be judged worthy of insertion:
"`I request that my body may be taken to the meetinghouse of Southwark,
where I have for many years past mingled in person,
and often in deep unutterable and sometimes acknowledged exercise,
with the burden bearers there.
A meeting if not regularly held to be appointed, that while dead,
a silent testimony may be proclaimed to that love, wherein prayer has frequently arisen,
that grace, mercy, and peace might abound there,
and among all the Lord's professing people.`"]

About the same time when much tried with restlessness,
she expressed her fear that patience would not hold out;
but on its being observed that this virtue was
from time to time graciously renewed to her,
she said with earnestness;
"`'`As your day so shall your strength be,`' is a promise
which has been signally fulfilled in my experience;
and now all I desire is that patience may have her perfect work,
and that when passing through the valley light enough may be afforded.`"

One day in the latter end of the eighth month
when taking leave for the night of a relation,
towards whom she had acted the part of a tender mother, she said,
"`You see me, my dear, in a state of much poverty and weakness.
Oh that I may be favored with a little more light before entering the dark valley.`"
She replied, that she felt sweet peace on sitting beside her,
and repeated the language of our Savior,
'`Blessed are the poor in spirit for theirs is the kingdom of heaven;`'
to which the beloved sufferer answered, "`That is precious;
I can be thankful for even the smallest crumb from a
child of my heavenly Father's.
Preach Christ crucified,
to the Jews a stumbling block, and to the Greeks foolishness:
there is much of the Greek and Jewish spirit amongst us;
but be not you afraid to preach the cross of Christ,
and to proclaim not only what He would do within us by His spirit,
but also what He has done without us, the all-atoning sacrifice,
which should never be lost sight of.`"

After a pause she added, "`I often look back to the Quarterly meeting in the spring;
I am glad I was at it, and love to remember the sweet feeling that prevailed.
Oh what I have felt for the Quarterly meeting of London and Middlesex.
If I live to the next I should be willing to be taken to it,
and once more proclaim the mercy of God in Christ Jesus; all is mercy, unmerited mercy;
nothing, attaches to the creature,
all my dependance is on the mercy of God in Jesus Christ.`"

The 1st of the ninth month was a day of much bodily suffering,
but one wherein the affectionate and religious feelings
of my revered parent were peculiarly excited.
After writing a few lines indicating the unabated
strength and tenderness of her maternal feelings,
she expressed a wish to speak a little to her daughters,
and upon their all sitting beside her, said with much calmness,
"`It has been a low cloudy time of late,
but a little more light seemed to spring up this morning,
and if this should be the last time I may bear testimony to the goodness of the Almighty,
I can acknowledge with thankfulness that this has followed me all my life long.
That the Lord's mercy and love have never failed me,
since He took me out of the wilderness of the world, and before that time He girded me,
and restrained from evil.`"

"`I have never doubted the universality, the freeness and fulness of divine grace,
and my faith is now unshaken.
Oh! never limit this grace; proclaim it as that whereby all may be saved.
I go trembling and dependent,
hoping that my sins will be forgiven for the sake of
'`Him who loved us, and gave Himself for us.`'
I have nothing of my own, not a rag,
(if I may use the expression of another Friend,) to clothe me with.`"

She then gave some directions relative to the future and afterwards
remarked that she felt much relieved by what had passed.
Early in the morning of the 2nd she inquired where is that sweet language,
"`to be ever with the Lord?`"
Her countenance at the same indicating heavenly tranquillity,
and she seemed comforted by having the 4th chapter of
the first Epistle to the Thessalonians read to her.
Several times when taking leave of her family for the night,
she solemnly uttered this short petition,
"`Gracious Lord prepare us for what is to come.`"
And when suffering from pain, and the feeling of general irritation,
she frequently petitioned,
"`Lord enable us to trust that you will never lay more on me
than you will give strength and patience to endure,`" adding,
"`Pray that I may have patience.`"

On the 5th, conversing seriously respecting her situation,
it was remarked that her seeming ignorant as to the issue still produced a
degree of hope that the trial of separation was not yet at hand,
to which she quickly replied, "`That this is my death illness I have not the least doubt,
but the time may be wisely and mercifully concealed from me.
The end may come in a moment;
and if it be the Lord's will to save me from agonizing pain, and grant a quiet dismissal,
what a favor it will be.
Oh! to pass quietly away.
I feel very poor, and have many infirmities,
which I hoped might be less sensibly felt at this awful time;
but I have this one testimony,
'`I am nothing, Christ is all.`'
My friends are dear to me, there is nothing in my heart but love to all.
God is love; He has supported me through many trials,
and now enables me to rely on His free, full, and unmerited mercy.
Glory, glory, glory be to His name now and forever.
The earth shall be filled with the knowledge of the Lord,
and from the rising of the sun to the going down of the same His name is to be praised.`"

First-day, the 7th, she seemed like one on the verge of the eternal world,
and evidently thought herself going.
The difficulty of breathing and occasional spasms on
her chest being very distressing to herself,
and to those around her.
She several times said, "`Come Lord Jesus, come quickly.
Into your hand I commit my spirit.`"

Observing that she felt too weak even to hear the scriptures read, she sweetly added,
"`But I can think of their author.`"
When parting for the night she commended each of her children to divine protection,
imploring the heavenly blessing for them, under the influence of strong affection,
and with the solemnity of Christian concern.

Contrary to expectation she obtained some refreshing sleep, and became a little revived,
saying next morning, "`I expected to be in another world by this time.
Lord enable me to wait in the patience your appointed time.`"

The evening of the 9th, after hearing a chapter in the Bible,
she spoke with an audible voice,
"`Lord you have been our dwelling place in all generations,`" going
on correctly with the first four verses of the 90th Psalm,
and then added,
"`So teach us to number our days that we may apply our hearts unto wisdom.
Thus do, for my children, gracious Lord,
and oh! afford me a renewed evidence of your goodness,
for a day in your courts is better than a thousand.`"
After a little pause, "`How wonderfully He is supporting me,
and though there may be such an impoverished state as to have no oblation,
the Lord Almighty knows where the refuge is.`"

She once remarked,
"`There is too much religious reading and speaking among some serious persons;
a little precious quiet and fresh feeling, how far beyond all: do not depend on forms,
seek to have the spirit of prayer raised in the heart,
and then what is offered will be in the life, and meet with gracious acceptance.`"

On the evening of the 10th, she desired the 12th chapter of the Hebrews might be read,
and afterwards spoke at considerable length on "`the
privilege and blessing of the gospel,
the importance of attending to the voice of Christ as
it is littered in the secret of the heart,
where He speaks against sin,
and gradually prepares for being joined to the just of all generations;`" adding,
"`He tasted death for every man,
and the grace of God which brings salvation has
appeared unto all men;`" repeating the whole text,
and commenting upon it in a clear and instructive manner.
She afterwards prayed with great earnestness for her family, concluding with these words:
"`Let all the dispensations of Your wisdom be sanctified to their souls,
and in your great mercy prepare each of us to be joined to the just of all generations,
in ascribing to You everlasting praise.
Amen.`"

For above a week after this time,
my precious mother continued so bright and capable of entering
into those subjects which interested her best feelings,
that we were often ready to think the bitterness of death was again passed for a season,
and that we might enjoy her valuable society even for months to come.
A friend who had been from home some days and called to see her,
was quite surprised at the animated manner in
which she inquired about Friends in the country,
and conversed respecting the state of meetings, etc.

Upon asking her about this period what part of
the Bible she would like to have read to her,
she replied, "`Not a chapter that treats on doctrinal subjects,
my mind has been long made up on all those points.`"
And she frequently desired that either some of her great
Master's sayings or the Psalms might be turned to;
generally commenting upon what she heard with her accustomed force and clearness.
She saw a few individuals whom she expressed a wish to take leave of,
and was strengthened to evince her Christian love and solicitude for them,
in a manner which she afterwards said felt relieving to her mind.

First-day the 14th, when very weak and languid, she observed,
"`I cannot think or keep my attention fixed,
but merciful Goodness forgives the infirmities
of human nature;--what would become of me now,
if I lacked parsons, bread and wine, and to make confession of sins?
What a mercy to be delivered from all dependance on man, poor and weak perhaps as myself.
What is man whose breath is in his nostrils.
Lord receive me for Christ's sake, is my plea!`"

Being tried with restlessness, and the desire for frequent change of position,
she sweetly remarked, "`It is only the body, it does not get within;
all there is peaceful, quiet trust.`"
In the evening she desired that the family might collect for reading, saying,
"`We may not have another First-day,`" and listened
with close attention to the 16th chapter of John,
responding to different expressions with her usual quickness of feeling.

During the night she seemed as if richly enjoying the
foretaste of perfect happiness and peace.
Once, after taking some refreshment, she said, "`How good, all is sweet, sweet nurses;
what mercies to be thankful for; there are no nurses like children.
I have often thought lately,
whether the feeling of gratitude has ever been sufficiently prevalent in my heart,
the sense of heavenly goodness, and my many blessings seems so to increase;
I could have sung a song of praise this night.`"

In the morning she desired a few verses in the Bible might be read,
and being asked what part, said,
"`No matter, all is treasure;`" but in a minute or two added,
"`The Lord hear you;`" upon which the 20th Psalm was read, by which she seemed comforted,
saying at the conclusion, "`Lord we thank You that You have heard.`"

After obtaining some refreshing sleep she observed with emotion,
"`Often through divine mercy something so sweet touches my soul, my good Master is,
I trust, near me; all is well, all is right, the Lord has never forsaken me;
God forbid I should distrust His mercy, though the enemy has thrust sorely at me,
but I have remembered the language,
'`Oh you enemy, destructions are come to a perpetual end.`'
What mercy, a perpetual end.`"

A medical friend calling to see her,
she manifested the continuance of Christian love and interest for him,
by desiring the Lord might bless him in his undertakings; and added, "`Keep near to Him,
and may He keep you near to Himself; that is the way, my dear friend--keep near to God,
through that grace which brings salvation; farewell!

On the morning of the 19th,
a distressing spasm at her chest caused my beloved mother to feel as if dying,
and the appearance to those around her was awfully affecting; when a little relieved,
she spoke as follows: "`Glory, glory,
glory to Him that sits upon the throne and to the Lamb forever; nothing in the way,
all peaceful within; but ah these struggles!
Lord take me not away in anguish--grant a calm if it be Your blessed will.
Do not hold me; I can give you all up.
I must go; do you yield me up every one of you?
Ah! do not hold me.`"

Being told that we were endeavoring to feel resignation, and desired not to hold her,
she expressed satisfaction, and said, "`Now then leave me in the Lord's hands,
make no efforts; Lord Jesus receive my spirit.`"
After a while she had some sweet sleep, and on awaking said,
"`How wonderful that I am here, I expected to wake in another world:
Lord why is it, why am I kept?
but it is not for me to say what do You?`"

In an interview with our dear friend Maria Pollard,
she mentioned it as "`a great favor at such a time as this to have nothing in the way,
though I am a poor creature, very poor,
and have nothing to depend on but divine mercy;`" adding, "`how do you feel beside me?
Do not conceal a word even if reproof be needful.`"
Maria Pollard telling her she felt nothing but sweet peace,
and deemed it a privilege to be near her,
trusting that she should remember the opportunity with
thankfulness during the remainder of her life; she replied,
"`That is more to me than rubies; then I am not deceiving myself.`"

Humility, as it regarded her own attainments and feelings,
was strikingly conspicuous in my revered parent during her whole illness,
and the manner in which this was evinced,
by one of such deep experience in the way and work of righteousness,
offered very important instruction to those who
had taken fewer steps in the Christian course.

During the remainder of this day she frequently
expressed her surprise at being still in the body,
saying, "`I seemed just at the gate, to have almost entered it,
and now to be here,--what am I kept for?`"
After a short pause she added, "`Give my love to all Friends;
tell them to cast off the works of darkness, whatever they are,
and seek to be clothed with the whole armor of light, which is Christ within,
the hope of glory.
The world, the world gets in, and occupies the attention,
and then there is a settling down in form, without the power.`"

At night she said, "`Lord strengthen me to go through the remaining conflict:
I thought the conflict would have ended this night; enable me to wait in patience;
I am afraid I feel impatient; may I be forgiven if I do anything wrong.`"

First-day morning, 21st. After a distressing night,
and while tried with the feeling of restlessness,
lifting up her hands and eyes she fervently exclaimed,
"`Grant a moment's calm of body, if it be Your blessed will.`"
Which petition being almost immediately answered, she solemnly,
and with a clear voice proceeded, "`Praise, praise for this calm.
Now Lord, into Your hands I commend my spirit.
Bless my children, bless your own work.
Receive my feeble, but I trust, not unacceptable acknowledgments for Your great goodness,
while I have nothing to depend on, nothing to look to, but mercy, mercy,
unchangeable mercy.`"
Awhile after,
hearing her in a low voice mention the word "`Rock,`" it was
observed that she felt sustained by the Rock of ages,
to which she sweetly replied "`That's it, Oh! this Rock,`"
with some further allusion to the support she experienced,
in words which were not distinctly heard.

The whole of this day might be termed a sabbath indeed,
for while every affectionate feeling was in painful exercise,
under the certainty that the hour of separation was fast approaching,
the power and presence of the Most High were signally vouchsafed;
so that nature seemed hushed into stillness,
and reverent submission to the will of Him who was thus
condescending to make His strength perfect in weakness.

In the evening my precious mother suddenly uttered this language:
"`The dead shall be raised incorruptible, and we shall be changed, in a moment,
in the twinkling of an eye.`"
Part of the 15th chapter of the First of Corinthians being read to her,
she made remarks upon different expressions,
which evinced her clear and fresh conviction of those important truths,
and on hearing the 57th verse, she audibly pronounced "`Amen!`"
Soon after which she said,
"`Conflict is over; the combat is ended and victory proclaimed.
'`Thanks be unto God who gives us the victory through our Lord Jesus Christ.`'
Now is the accepted time,
now I trust is the day of salvation: glory, glory, glory!`"

Early in the morning, the 14th of John was read to her,
to which she attended with her usual quickness of perception.
At the 17th verse she remarked, "`There is the new covenant dispensation,
'`He dwells with you and shall be in you.
I will pour out my spirit upon all flesh.`' He tasted death for every man.`"

Oh! never limit divine mercy.`"
After a time of solemn stillness she said with peculiar emphasis,
"`Grace has triumphed over nature's feelings.
The Lord has fulfilled His promise.
He has given the victory through Jesus Christ, to whom be glory and power, dominion,
salvation and strength now and forever; holy! holy! Holy!`"

Second-day 22nd. While her family stood around her bed,
and it appeared as if she was on the point of
entering upon her eternal and much desired rest,
my beloved mother repeatedly asked, "`Do you give me up; who holds me?`"
She then said, "`Oh! do not hold me.
I proclaim I am ready.
Lord God Almighty, You have done Your part,
praise and thanksgiving to Your name for this day.
I am ready, and willing to go;
now Lord let your servant depart in peace according to Your word.
Oh! save the world; turn the hearts of the irreligious, give them hearts of flesh.`"
Her continuance in the body much surprised, and even tried her,
and she frequently queried, "`Why am I detained, Lord why is it?`"

A few hours after this she was strengthened to speak in
an extraordinary manner to some of her children,
and her little grand-daughter, adapting her language to the capacity of the child,
so as strikingly to evince the clearness of her recollection,
and unabated soundness of mind, when the powers of nature were all but exhausted.
She mentioned feeling a good deal spent with this exertion, but much relieved in mind,
and frequently remarked on the peace she enjoyed, sweetly saying, "`I feel so peaceful!`"

From this time it seemed as if my beloved mother
was scarcely an inhabitant of this world,
her language being generally that of adoration and praise,
and accompanied by the names and attributes of her God and Savior.
She was often evidently engaged in prayer, when only broken sentences could be gathered,
and the names of her children were pronounced with affectionate epithets.

In the forenoon of fourth-day, she began to slumber a good deal,
and lay in an easy and composed state,
which her attendants did not interrupt by asking her any questions:
thinking it most consistent with the awful occasion,
and knowing it to be accordant with her own feelings, not to excite natural emotion,
or recall the happily prepared spirit in any degree to the world,
from which it was gradually, and most peacefully receding.
For some hours the coldness and hue of death were apparent,
but her breathing was so easy that it seemed
scarcely possible the change could be so near.

The only evidence of approaching dissolution was a gentle sinking of the breath,
which continued like that of a sleeping infant;
until without any perceptible intermission or the slightest struggle, it ceased,
and the immortal and redeemed spirit ascended with joy
to the mansions of never-ending rest and peace,
about half past eight o'clock on fourth-day evening, the 24th of ninth month 1823;
leaving its worn tenement with the appearance of perfect tranquillity,
and a countenance which strikingly indicated holy settlement and permanent repose.

The repeated prayer of this ancient and honorable
servant of the Lord was thus remarkably answered,
by her last hours being exempt from any degree of bodily anguish,
and exhibiting the calm solemnity she so highly valued.
Under this feeling, and amidst the poignant sense of such a bereavement,
nature was mercifully hushed into stillness;
and while all her children stood around her bed,
a thankful assurance of the unspeakably glorious transition of one so justly beloved,
overcame selfish sorrow, and tended to produce that resignation to the divine will,
wherein the strength and true consolation of the believer are known to consist.
My dear mother was aged seventy-three years, three months and sixteen days.

On fifth-day, the 2nd of tenth month,
the precious remains were taken info a meeting appointed for the purpose at Southwark.
It was largely attended by Friends and others,
and signally favored with the covering of solemnity, both in the time of silence,
and while many Friends were engaged in the line of gospel ministry.

The same extension of divine regard was again evident,
while a numerous assembly stood beside the grave at Bunhill Fields,
and the last affecting duty of depositing the
coffin in the house appointed for all living,
was succeeded by a silence peculiarly impressive, so that then,
as at the moment of dissolution,
the tide of natural grief was restrained by Almighty power,
while the contemplation of her life and death emphatically
called upon survivors to follow her as she had followed Christ.
