[#testimony-southwark.style-blurb, short="Testimony of Southwark Monthly Meeting"]
== Testimony of Southwark Monthly meeting, concerning Mary Dudley, deceased.

This our beloved friend was born in the city of Bristol, the 8th of sixth month 1750,
of parents professing the principles of the established church;
who strictly attending to the ceremonies instituted therein,
introduced her from a child into a regular observance of them;
notwithstanding which she was allowed to enter
into most of the vain amusements of the world,
to which her natural disposition greatly inclined;
and being of engaging manners her company was much sought after,
and her temptations to gaiety thereby greatly increased.

It appears, however, by some of her memorandums,
that she was very early favored with the visitation of divine love;
and while pursuing the gratifications of time and sense,
she was often impressed with an awfulness and fear,
which led her to desire the possession of more substantial enjoyments;
and which ultimately produced a gravity of demeanor that
exposed her to the ridicule of her less thoughtful companions.

About the twentieth year of her age she withdrew from those scenes of
dissipation and folly to which she had been accustomed;
became dissatisfied with the forms and ceremonies in which she had been educated,
and apprehending that she had received benefit from the
ministry of some of the Wesleyan Methodists,
she was induced to connect herself with that society,
and continued a member thereof between two and three years;
but remained at the same time an attender of the established worship.
Here she observes: "`In the several ceremonies of this,
and in different meetings of the other, I felt unsatisfied;
and often while others were engaged in attention to the preaching, singing, etc.,
has my spirit in solemn silence communed with the Lord my strength,
so that I scarcely knew what was passing without me,
and even felt disturbed from this inward attraction when obliged to draw to
that spot where the outward elements were prepared for the congregation.
Oh! how did I then feel the heavenly mystery, and sweetly partake of the bread of life,
so that all forms and shadows fled away,
and became no longer of use or efficacy to a mind
feeding spiritually on the substance.`"

In this state she frequently attended the meetings of Friends,
and was so drawn into fellowship with them, that although she had no outward instruction,
nor was assisted in the understanding of their
religious principles from the reading of books,
it appears she had so clear a view of their profession and peculiar testimonies,
and was so strongly convinced of their consistency with the truth,
that she believed it would be required of her to demean
herself conformably thereto both in profession and practice.
But in submitting to this sense of duty, the opposition from her family was so great,
and the cross to her own will so heavy,
that she thought the yielding up of her natural life would have been an easier sacrifice.

She was, however, through mercy, strengthened to obey the divine requiring,
and in the twenty-third year of her age, on the ground of settled conviction,
joined our religious Society;
about which period she felt herself constrained to speak in the line of ministry,
from which her natural disposition exceedingly shrunk.
After exercising the gift with which she was entrusted, for some time,
the conflicts of her spirit were so great that she gave way to
reasonings and doubts on the subject of her call to the sacred office,
and thus became involved in unspeakable distress,
from which at times she could see no way to escape.

In the year 1777, she was married to Robert Dudley of Clonmel, in Ireland;
but the society of an affectionate husband, and an increase of domestic comforts,
proved insufficient to afford that peace of
which her exercised spirit felt so much the need:
and here she described her situation as "`often miserable`"--
concluding that by disobedience she had forfeited the divine favor,
and should never again be commissioned to proclaim her Lord's goodness.
But He who had called her to His service, and designed to qualify her for his work,
brought her out of these perplexities and close
probations in which her mind had long been involved,
to the comfort of many who had suffered with and for her, and to His own praise;
enabling her again to bear public testimony to His goodness.

Her constitution being naturally delicate, she was often affected with illness,
and it was at times under the pressure of much bodily suffering that
the prospect of religious services was opened to her,
and a preparation of mind for proceeding therein experienced.
This was strikingly the case in the year 1787, when by a complication of disease,
she was brought so low, as to be thought by those about her to be near her close;
yet in this state of bodily infirmity, her spirit was attracted to distant parts,
and in the love of the gospel a people of strange language presented to her view.
This prospect in a short time became more fully opened,
and her love and allegiance put to the closest test,
by an apprehension that it was required of her to unite with her
beloved friend Sarah Robert Grubb in a religious visit to France,
Germany and Holland, She had seven children,
the youngest only ten weeks old when entering on this engagement;
her health was very delicate,
and in the progress of the journey she experienced many deep conflicts.
But the holy arm of power being extended,
she was enabled to accomplish the service to the
unspeakable relief and peace of her own mind,
and we trust to the edification of those in that remote part of the vineyard,
who were thirsting for spiritual refreshment.

Her resignation to the foregoing requiring was the
commencement of that devotedness to the cause of religion,
which so conspicuously marked the future life of this dedicated servant of the Lord.
For the succeeding twenty years, when ability of body permitted,
she was much occupied in traveling; having within that period visited all the meetings,
and a large proportion of the families of Friends in Ireland, Scotland and Wales,
many of the counties in England,
and some parts of the continent not included in her former journey:
besides which she was engaged in most places in holding
meetings with those of other denominations.

After the decease of her beloved husband, and two children who had arrived at maturity,
trials which deeply wounded her susceptible feelings, she removed in the year 1810,
under an apprehension of duty, into the neighborhood of London,
and resided for the most part of the remainder of her
life within the compass of our Monthly meeting.
She was a minister highly esteemed amongst us; sound in faith and doctrine,
laboring diligently in gospel love for the promotion of
the cause of truth and righteousness,
under the pressure of much bodily weakness;
a bright example of devotedness in declining years;
and we believe it may be truly said of her, she was
"`fervent in spirit, serving the Lord;`"
that in her removal we feel the
church has sustained the loss of a mother in Israel.
After coming amongst us,
she visited most of the families comprising the
Quarterly meeting of London and Middlesex,
and travelled in several counties in the line of the ministry.

The youth in our Society were the objects of her peculiar and affectionate solicitude,
for whom she was at times concerned to appoint meetings.
She was also favored with a gift that remarkably qualified her for
service in meetings with those not in religious profession with us,
in the exercise of which she was frequently engaged in advocating,
in a clear and convincing manner, the doctrine of universal and free grace,
and the divinity of our Lord and Savior Jesus Christ.
She experienced many deep trials which she bore with exemplary resignation;
evincing thereby her reliance on divine support.
Thus could she feelingly sympathize with others under affliction,
and was often enabled to hand the cup of consolation for their encouragement.

Her last religious engagement was a visit to the
families of Friends belonging to Devonshire meeting,
which she was enabled to accomplish early in the past
year to the admiration of herself and others;
during which she frequently expressed her belief
that her day's work was drawing to a close.
After this, when ability of body permitted,
she continued to attend her own meeting until the 18th of fourth month,
when she was confined to her bed with what appeared to be the effects of a severe cold:
symptoms of fever soon followed,
and in a few days the disorder had made so rapid a progress that danger was apprehended.
She frequently expressed a belief that nature would sink under
the weight of illness with which she was oppressed:
saying, "`I do not feel able to struggle as heretofore,
but I have no sight as to how it may be,
nor any wish to go unless it be the will of Heaven.`"
Again she said, "`when the doublings and hesitations of nature have been kept down,
the divine will has been all to me.
Your will be done is the highest anthem ever sung on earth or in heaven.`"
She was eminently favored with the sensible enjoyment of the Lord's presence,
and often testified of the support and consolation thus afforded her.
"`I have loved the cause of my Redeemer; it was to draw to him,
and fix the attention of the mind upon him alone,
that I have been made willing to proclaim His goodness.`"
Being much tried with pain and other distressing symptoms she observed,
"`I only fear that through long continued suffering I
may not exemplify that which I have held up to others,
the sufficiency of divine power: may patience have its perfect work,
whether any glimpse of the unspeakable glory be afforded or not.
Oh! if this be known it must be glory to God in the highest,
through Him who came to procure peace on earth;
the language of the redeemed through all eternity will be.
Not unto us, not unto us, but unto your name be the praise.
I could say much; my heart is full; but the poor body must have rest.`"

First of fifth month.
This night when solemnly conversing on her precarious situation,
with a peculiar calmness and feeling she said,
"`I seem to have nothing to do but with the present moment,
no looking back with uneasiness,
but in thankful remembrance of great and unmerited mercy,
whereon I trust there was a building long ago.
Oh! not to doubt the foundation is a great mercy;
tell all there is no other way but that of resigning up all.`"
About this time she was informed of the alarming illness of a valuable minister,
when with much tenderness of spirit she uttered the following emphatic language,
"`Oh! our poor Society!
Lord raise up judges, counsellors, feelers,
such as are quick of understanding in your fear--and if
children are to become teachers give them wisdom and humility.`
On allusion being made to the diligence with which she had
occupied the time and talents committed to her trust,
she sweetly replied, "`Feebly and unworthily as they have been used,
I trust it was with a single eye to the help of
others and the glory of the dear Redeemer.
And if he forgive all the mixture, all that has been of the creature,
and mercifully receive me into rest and peace,
whether he affords those bright prospects which,
in the beginning of this illness and often since, have been vouchsafed, or not;
Oh! may I never doubt or cast away my confidence,
that He who has loved with an everlasting love will continue to uphold me,
notwithstanding the weakness of the flesh, and the temptations of the cruel enemy.
Oh! this enemy, he never quits his hold of poor human nature while he can assail it.`"

Early in the eighth month she became increasingly debilitated,
and thought it probable her remaining strength would be soon exhausted;
and one night after having given some directions respecting her funeral,
she expressed a wish that nothing might be done, nothing said, nor if possible thought,
but what would lay the creature where it ought to be, and where she trusted it then was,
prostrate at the footstool of divine mercy.

Her situation at this period was very fluctuating,
but the evidence of Almighty support and consolation became increasingly manifest.
On its being observed that, as she had no clear sight of the issue of her disorder,
a hope was induced, she might be again raised up, she replied quickly,
"`That this is my death illness I have not the least doubt,
but the time may be mercifully concealed from me;
and if it be the Lord's will to save me from agonizing pain, and grant a quiet dismissal,
what a favor it will be.`"
At a time when she was sending some messages of love to some of her friends, she said,
"`I am nothing, Christ is all! my friends are dear to me,
nothing in my heart but love to all--God is love.
Glory, glory, glory, be to his name now and forever.`"

During the last three weeks of her life,
she suffered much from the difficulty of breathing, and general bodily uneasiness:
her mind, however, was wonderfully supported;
so that to those around her she frequently appeared to be favored
with a foretaste of the rich enjoyment of perfect happiness and peace.
At another time, when tried with pain and restlessness, she said; "`It is only the body;
it does not get within: all there is peaceful, quiet trust;`" again,
"`nothing in the way. Ah! do not hold me; yield me up; I must go;
I could have sung a song of praise this night.`"

After a distressing night she prayed with earnestness,
"`Grant a moment's ease of body if it be your blessed will!`"
The petition appeared to be soon answered;
for almost immediately after she proceeded thus, "`Praise, praise for this calm.
Now Lord into your hands I commend my spirit; bless my children; bless your own work.`"
The attributes of her God and Savior now became almost her only theme;
and she often seemed as if scarcely an inhabitant of earth.
Her approaching dissolution was now apparent,
and the following are some of her latest expressions.
"`Grace has triumphed over nature's feelings; the Lord has fulfilled his promise,
he has given the victory through Jesus Christ, to whom be glory, and power,
dominion and strength, now and forever; holy, holy, holy.`"

Her departure was observable only by gradually ceasing to breathe,
and her immortal and redeemed spirit we doubt not
ascended to the mansions of never-ending rest and peace.
She died at her house at Peckham on the 24th of the ninth month, 1823,
in the seventy-fourth year of her age; a minister about fifty years;
and her remains were interred in Friends`' Burial Ground, near Bunhill Fields,
on the 2nd of the tenth month, after a solemn meeting at Southwark.

[.small-break]
'''

Signed in Southwark Monthly meeting, 10th of second month, 1824, by many Friends.

[.small-break]
'''

The Testimony of the Quarterly meeting for London and Middlesex,
held the 30th of the Third month, 1824.

[.small-break]
'''

The foregoing testimony concerning our beloved friend Mary Dudley,
whose memory is precious to us,
in the remembrance of her "`work of faith and labor of love,`"
has been read in this meeting,
and being cordially united with, after some small alterations,
is signed in and on behalf of the meeting, by John Eliot, Clerk.

[.small-break]
'''

Signed in and on behalf of the Women's meeting.
Hannah Messer, Clerk.
