== Chapter II.

[.chapter-synopsis]
* Conflicts respecting her call to the Ministry
* Marriage and Removal into Ireland, from 1773 to 1786

The state of her mind at this important period,
will behest set forth by a further extract from the memoir already alluded to:

"`I now kept constantly to the meetings of Friends,
and began to feel a settlement of mind in real peace,
which my tossed state for several years had caused me only transiently to possess; or,
at least, not in the degree of which I now partook;
not that all the work seemed requisite to commence anew,
for assuredly Christ had been raised in my heart, though until now,
the government was not wholly on His shoulders;
but by this unreserved surrender to His pure guidance,
the mystery of godliness was beginning to open in increasing light and power,
and that spirituality which had been discovered was now in a measure possessed.
The view I had been affected with on my first convincement, now cleared,
and appeared so near being realized, that my mind, almost without interruption,
dwelt under so awful a covering, that even all conversation impressed me with fear,
and I was held in deep inward attention for, and to, the revealings of life.
In religious meetings I was for some time frequently affected even to trembling,
when matter would present to my mind, as though I must deliver it,
though seldom more than a very little; notwithstanding the love I felt was so universal,
that I wanted all to be reached unto, but for this family, the Society of Friends,
among whom I had tasted the soul-sustaining bread;
Oh! how did I long for them and their good.

"`About this season, from a settled conviction of rectitude,
I applied to be received into membership; and thought I might,
when this privilege was granted,
feel more strength should this solemn requiring be continued;
but though my way was made so easy, that one visit only was ever paid me on this account.
Friends being quite satisfied in their minds respecting the work begun in me;
yet while the previous deliberation in the meeting took place,
the fire of the Lord so burned in my heart, that I dared not but speak with my tongue.
For several meeting days I hesitated, not from willful disobedience,
but awful fear to move in so great a work, and felt consequent poverty,
though not severe condemnation; but one day, about the eleventh month, I think,
in the year 1773, sitting with Friends in their meeting-house in the Friars, Bristol,
(I had once in a little country meeting moved before,
but never here where the cross was great indeed,) my spirit
bowed in awful reverence before the God of my life,
and a few words so settled, that I could not any way shake them from me.
I sat and trembled exceedingly, and desired to be excused,
till a valuable friend from America, Robert Willis,
then on a religious visit to that city, stood up, and spoke so encouragingly to my state,
that when he closed I stood on my feet, and the words impressing my mind,
seemed to run through me as a passive vessel; he almost instantly kneeled down,
and supplicated for the preservation of the little ones, saying,
'`Thou hast brought to the birth and given strength to bring forth,`' etc.
I could not stand while he was thus engaged,
being as though my whole frame was shaken through the power of truth.
When meeting closed I got as quickly as I could out of it, and walked a back way home,
with such a covering of sweet peace, that I felt the evidence indisputably clear,
that if I were then called out of time, an everlasting inheritance was sure:
the whole creation wore the aspect of serenity,
and the Creator of all things was my friend.
Oh! on my return home and retiring to my chamber, how sweetly precious did the language,
addressed to the holy patriarch in an instance of obedience, feel to my spirit,
and it was indeed sealed by divine power,
'`Because thou hast been faithful in this thing, in blessing I will bless thee,`' etc., etc.
None of my family knew of this matter, and I strove to appear cheerful,
which indeed I could in the sweet feeling of life;
but so awful was the consideration of what was thus begun,
that solemnity was also my garment, and I wished to be hid from the sight of every one.
My body being very weak, the exercise and agitation greatly affected me,
and I was that night taken alarmingly ill, but in a few days recovered,
and got again to meetings.
Friends manifested great tenderness towards me, and though not frequently,
I sometimes said a few words in the same simplicity I first moved,
and once or twice ventured on my knees; after which exercises, I mean all of this nature,
I felt quiet and easy,
but never partook in the like degree as before recited of divine consolation.`"

Here it may not be unseasonable to remark,
that her dedication was made the means of reconciling her offended mother,
to the change which had so exceedingly tried her.
This dear parent being accidentally at a meeting where her daughter spoke,
was greatly affected by the circumstance,
and calling upon an intimate acquaintance afterwards,
expressed her regret at having ever opposed her, adding,
that she was then convinced it must be the work of God,
as from the knowledge she had of her daughter`'s disposition,
she was well aware it must have cost her close suffering to
undergo the exposure she had witnessed that evening.
The fruit of this conviction became immediately apparent,
so that although no direct allusion was ever made to the subject,
the return of maternal tenderness and love was a sufficient,
and very grateful evidence to one,
who had deeply lamented the necessity of giving pain to a parent,
by acknowledging the superior duty she owed to her heavenly Father.

In her own memoranda she then writes: "`My acquaintance now increased amongst Friends,
and I had frequent opportunities of hearing the
observations of some very wise and experienced persons,
respecting ministry.
Though great was the encouragement given me by many, as well residents in the same place,
as strangers, a disposition always prevalent in me, especially on religious subjects,
now took the lead, and I fell into great reasoning respecting my call to,
and preparation for, so great a work.
I imagined if I had longer abode in the furnace of refinement it had been better,
and sometimes thought I was wholly mistaken; that perhaps the first,
or all the little offerings, were acceptable as proofs of the surrender of my will; but,
the ministry I was not designed for, the woe had not been sufficiently felt, etc., etc.
Oh I it would be difficult for me to mention, nor might it be safe,
what my spirit was by these reasonings plunged into,
insomuch that at last life itself was bitter,
and a coincidence of outward circumstances added to my inward pressures,
so that I fainted in my sighing, and found little or no rest.
Meeting after meeting I refused to move at the word of holy command,
which hereby became less intelligible,
and my understanding gradually darkened through rebellion, so that I said with Jonah,
'`It is better for me to die than to live.`' Frequently, before going to meeting,
has my spirit felt the interceding language, '`Leave me not altogether, but,
if this thing be required of me, again reveal thy power, and I will yield obedience;
and such has been the condescension of the Lord that I have been repeatedly so favoured;
but presuming to say, this is not a motion strong or clear enough,
I cannot move in doubt or uncertainty, my covenant was not kept,
and I again incurred divine displeasure, and in a manner only comprehended by experience,
knew the poverty of withholding more than was meet.
I at last became almost insensible to any clear call or manifestation of duty;
yet when deprived of my health, and not expected by others to recover,
I was favoured with inward quiet, and perhaps might have obtained mercy,
had I then been taken; but He, whose goodness and ways are unfathomable,
saw meet to raise from the bed of languishing and soon after, in the year 1777,
I entered into the married state, and removed to settle in Ireland.

"`It was now about four years since I had first opened my mouth in the ministry,
and perhaps three years since the reasoning of
my mind had kept me from a state of obedience,
in which time I had removed from Bristol to Frenchay, where I was married,
at which place of residence I never recollect appearing in any meeting,
and seldom in any private sitting; often concluding, that,
if any gift had ever been entrusted, it was now quite removed,
and I must endeavour in some other form to be a vessel, if that could be, of use.
I well remember, as I had nearly centred in this state, and in more than distress,
even wretchedness at times, a language saluted the ear of my soul,
which`' I then knew not was in Scripture, but on searching found it.
'`The gifts and callings of God are without repentance:`' then
my strong hold of settling in that state was broken up,
and I was humbled in grateful acknowledgment that I might still be restored.
Being in the situation above described,
I was recommended to the meeting which I had now removed to, only as a member of Society,
which was done in a very affectionate manner;
though in the certificate from Bristol to Frenchay,
my appearances in the ministry had been mentioned.
Soon after settling in Clonmel, I was, however,
introduced into the Meeting of Ministers and Elders, and also made an overseer,
in which station I sometimes made remarks in
private sittings and meetings for discipline;
hoping thereby to obtain relief;
but alas! every effort in this line failed to procure me ease of spirit,
and instead of becoming more weaned from visible things,
these attractions revived feelings which I had before known to be in subjection,
and every act of disobedience strengthened the enemy of my
soul`'s happiness in his efforts to keep me in bondage.
When sitting in religious meetings, I was often sensible of the revival of exercise;
and undoubtedly felt a sufficient degree of strength to have gone forth,
had I been willing to use it; but the old plea, more clearness, more power,
prevented my accepting the often-offered deliverance;
and at last the intimation became so low, the command so doubtful,
that it seemed as though I might either move, or be still, as I liked,
and I even have rejoiced after meeting, in an ungodly sort,
that I had been kept from the temptation of speaking in the Lord`'s name.

"`The concern of sensible minds on my account now became frequent,
and several were led into near and tender sympathy with me,
and travailed for my deliverance; but I now had no hope of ever again experiencing this;
and often was I brought apparently to the borders of the grave,
by trying attacks of illness;
so that I may describe my situation as being often miserable,
though the sackcloth was worn more within than without;
and I appeared to men not to fast, when my soul lacked even a crumb of sustaining bread.
Thus I went on, as nearly as my recollection serves, for about seven years,
after my first yielding to the reasonings before described;
and indeed just before being brought out of this
'`horrible pit,`' I think the extremity never was so great,
insomuch that I fainted in my spirit, and all hope was cut off, my language being,
'`I shall die in the pit.`'
"`In this state I attended a Province or Quarterly Meeting, in Cork,
and after sitting two meetings for worship on First-day, in, I fear,
willful rebellion to the gentle intimations of duty, I went to Samuel Neale`'s,
in a trying situation of mind and body,
and his conduct towards me was like a tender father, saying,
'`The gift in thee must be stirred up.`' I got little rest that night,
and next morning went in extreme distress to meeting,
where I had not sat long before a serenity long withheld covered my mind,
and I thought I intelligibly heard a language uttered, which exactly suited my own state;
but it so hung about me, as at my first appearance,
though not any thing like the same clear command to express it,
that being lifted above all reasonings, before I was aware I stood on my feet with it,
and oh! the rest I again felt,
the precious holy quiet! unequal in degree to what was first my portion;
but as though I was altogether a changed creature,
so that to me there was no condemnation.
Here was indeed a recompense even for years of suffering, but with this alloy,
that I had long deprived myself of the precious privilege,
by yielding to those reasonings which held me in a state of painful captivity.
One might naturally suppose, that after obtaining so great mercy,
and feeling the precious effects of deliverance, great care would be taken,
lest the fetters should again be felt; but though in some sort this was the case,
my dedication seemed only partial,
and frequent relapses into want of faith again involved in distress and uncertainty,
so that the relief at seasons obtained, was broken in upon.
And sometimes as delivering only a part of the commission obstructed the return of peace,
it might have been easy for me to conclude all wrong;
so at other times great serenity was my covering,
and the honest discharge of duty was rewarded with the incomes of life.

"`Having a disposition naturally prone to affectionate attachment, I now began,
in the addition of children, to feel my heart in danger of so centering in these gifts,
as to fall short of occupying in the manner designed, with the gift received;
and though at seasons I was brought in the secret of my heart to make
an entire surrender to the work I saw that I was called to,
yet when any little opening presented, how did I shrink from the demanded sacrifice,
and crave to be excused in this thing;
so that an enlargement was not witnessed for some years,
though I several times took journeys, and experienced holy help to be extended.`"
