== Chapter III.

Visit to Friends at Limerick; and Journey into Leinster Province.
1786 to end of 1787.

The first religious engagement, of which she has left any account,
was a visit to the families of Friends in Limerick,
accompanied by her dear friend Margaret Grubb, of which service she writes as follows:

"`We arrived, through the protecting care of a kind Providence, in safety,
on Seventh-day, the 2nd of the Ninth month, 1786,
and met with a kind reception at T. M.`'s. My spirits
were sensibly sunk at not meeting my dear friend E. H.,
whom I had expected to join in the visit,
but in a degree of hope that the great Master would aid
with a little help and supply every want,
we concluded to begin after meeting.
In this season truth seemed at a low ebb, and the language of my poor spirit was,
what came I here for?
Yet with a remaining view or prospect of what had been before me; though almost afraid,
from the painful feeling of things, how we might get through:
but although we commenced the service, poor and stripped,
we were favoured with a little supply of strength.

"`Third-day, the 5th, sat a laborious, heavy meeting, truth exceedingly low,
and the life sensibly oppressed: many men absent,
and very few of those who were gathered, seemed digging for the rising of the spring.

"`Sixth-day, the 8th--went again to meeting, where after a hard,
laborious travail of spirit, the command seemed clear to sound the call formerly uttered:
'`Wash ye, make ye clean,`' etc.
Help was graciously administered, yet life felt low,
and I thought there was very little room in the minds of the people.
We had two family sittings afterwards; and thus ended the arduous labour,
whereunto I humbly trust the great and good Master led,
and though it has been a very exercising time, the Lord has been near,
enabling his poor little ones to discharge what appeared his requiring,
in which a degree of peace is mercifully afforded,
and it is to His name I would ascribe all the praise.`"

In the spring of the next year,
she felt her mind attracted to Friends of Leinster Province.
The following is extracted from her own account of this journey,
and its attendant exercises.

"`14th of Third month, 1787, left my own habitation,
in company with my dear friend Sarah Shackleton,
and proceeded by easy stages to Mount-Mellick,
where we were favoured to arrive in safety the following day.

"`16th. Sat a low exercising meeting, which was silent,
except a few sentences delivered by dear Mary Ridgway,
recommending a self-examination to know why the
spring did not rise in our solemn assemblies.
The women`'s meeting was also a low season,
but attended with more liberty to labour a little in heart,
and some openness in expressing something of the sense impressed on the mind;
there seems few in this place under qualification to help in the discipline,
and I thought,
(though it seemed conducted very regularly as to the letter,)
there wanted more of the spirit or life attending.
I felt myself after meeting, low and poorly in mind and body;
no light as to moving from hence, I therefore concluded to stay over First-day.

"`17th. Went to breakfast at J. G.`'s, and had, afterwards, a little sitting,
in much sweetness, with them and a few Friends not of the family;
great nearness of sympathy with A. G.,
and much liberty in communicating what impressed the mind.
Dear Richard Shackleton, who kindly met me here,
was well engaged in recommending fervour of spirit,
that there might be dedication to serve the Lord.

"`First-day.
Sat a most laborious, hard meeting, no words uttered,
nor any springing up of that well whose waters refresh the thirsty soul.
The second meeting was low and silent, my mind under very close exercise, from the view,
which now seemed confirmed, of sitting in the families here;
the struggle on this subject was great,
yet I got courage to throw it before my kind sympathising friend Richard Shackleton,
who uniting with the concern, we began on the 19th.

"`Fifth-day, 22nd. Sat with the children in the Provincial school,
which was a season of great favour and liberty;
much opened in pure love to this hopeful plantation,
which seems evidently to me to be under the cultivating hand of Divine power.
We dismissed the children, and had afterwards a sitting with the masters and mistresses,
which was also owned by continued solemnity,
and great liberty in mentioning what was felt;
and we parted in the renewings of best love.

"`First-day, 25th. Sat a very exercising meeting held in silence.
Life exceedingly low.
In the afternoon another trying meeting; dear Mary Ridgeway,
was beautifully engaged in speaking to various states,
and had to address some in the very language which had been used in several families;
this tended greatly to comfort and strengthen my poor mind;
which amidst this arduous work, has been deeply plunged and discouraged.

"`Fourth-day, 28th. Sat another low, exercising, and silent meeting,
though I believe it had been better for me to have spoken.
Went that afternoon to Mountrath, and attended meeting there next day,
which was a time of uncommon travail to my spirit; all seemed death and darkness;
but through long waiting in silent baptism,
I at length ventured on my feet with the language, '`Arise and be baptized,
and wash away thy sins,`' etc.; great liberty followed,
but very little entrance seemed in the minds of the people.

"`I felt at the conclusion of this meeting quite easy to proceed,
so we set forward for Roscrea, and got safely and timely there,
meeting a cordial reception from cousin Eleazer Dudley and his hospitable wife.
Before leaving Mount-Mellick,
I had expected that I might feel something about the families here,
and soon after arriving was confirmed in the view of it, and got very low,
desiring in the night season I might be rightly directed:
but as it had arisen in the light, and there seemed enough to move in,
we have concluded to begin this engagement today.

"`First-day, 1st of Fourth month.
Sat two deeply exercising meetings; the sense weightily impressed my mind,
that there would be no revival in this place, till individuals come under the washing,
sanctifying power of Truth; to which, I think, in the renewed love of the gospel,
they were intreated to attend.

"`After tea we had a solemn sitting in the family, long in silence,
which was a profitable season;
liberty was felt to invite the youth to abide much in stillness, to learn there,
and also attend to the language, '`The Master is come and calleth for thee;`' and,
indeed.
He does seem calling for that family to support His slighted testimonies.
I have much hope of the dear children,
if the chilling air that surrounds them does not blast their tender shootings.

"`I was thankful for feeling clear of Roscrea, a place of extreme suffering to my mind;
yet, though things were so low, and very close doctrine was given to declare,
I have seldom been more sensible of help,
than in my little exercise in these family visits.
The sympathy and accordant feeling of my valuable companion Richard Shackleton,
tended to strengthen me in the hope, that the light which deceiveth not,
had manifested the right line to move in.

"`We got to Mount-Mellick third-day evening,
and next day sat an exercising silent meeting there;
afterwards a select one for this Monthly Meeting, which was silent also,
except a few remarks by Richard Shackleton, much to the purpose.

"`Sixth-day, Fourth month 6th. The Quarterly-Meeting of Ministers and Elders,
was to me a low season, though dear Edward Hatton and Mary Ridgeway,
seemed favoured in delivering close testimonies.

In an evening sitting, Edward Hatton spoke in an encouraging line to the young people;
and feeling a little matter moving on my mind
respecting going down to the potter`'s house,
etc., I ventured to follow him;
holy help was near to open and enlarge beyond my first view--
recommending to go down deep into Jordan for living stones,
fit for memorials of the Lord`'s goodness and leadings.

"`These seasons are precious, they strengthen Christian fellowship.
I thought this little renewal of mutual exercise,
cemented and bound closer in the one bundle--there seems,
notwithstanding the low state of things, a stirring of good; may it be attended to,
and carefully cherished, by all who feel it.

"`Seventh-day began the Quarterly Meeting, which was long, and life low.
In the morning meeting on first-day my mind was much exercised,
but desiring greater clearness,! refrained from moving.
J+++.+++ Williams was well engaged, and I rejoiced, as far as I was able,
that the Great Master was preparing and causing new trumpets to sound in His name;
this dear friend seems coming forth in gospel authority.
Edward Hatton, followed, and Mary Ridgeway, afterwards addressed different states;
first the tried, apparently unfruitful branches under the purging hand, and then,
the careless, worldly-minded professors; she closed in solemn supplication.

"`I left the meeting in heaviness, fearing all was wrong with me,
and sorely tried for disobedience.
After this I parted with my beloved husband, who came to attend the Quarterly-Meeting,
and comforted me by bringing good accounts of our dear little flock.
I was almost ready to conclude I should accompany him, but dared not do so.

"`Though very low and poorly, I went again to meeting at four o`'clock, where He,
whose mercy faileth not, was pleased a little to cheer my drooping spirit:
the command once more went forth, '`Blow the trumpet in Zion,`' etc.; it seemed to me,
as though this command had been obeyed, and the trumpet had given a certain sound;
but few were prepared for the battle,
the spiritual weapons having fallen as on the mountains of
Gilboa--the shield of the mighty being vilely cast away;
yet a little sympathy was felt with the wrestling seed,
to whom this language was addressed; '`Fear not, I am with thee, be not dismayed,
I am thy God.`'--Peace succeeded, and the meeting closed comfortably.

"`Second-day the 9th, a solemn cementing season at J. G.`'s,
after which we parted with some dear friends, under a renewed hope that each,
in their different portions of labour, would be shielded by divine power:
we had afterwards two family sittings, and dining at +++_______+++'`s, a solemnity ensued;
'`The Master hath need of him,`' struck my mind,
with the remembrance that '`the colt was tied;`' caution was freely administered,
that neither the world, nor any hindering thing, might tie and confine from service,
or coming forward, into usefulness.
I felt great love to this young couple,
and wish they may not be hurt by any thing in this life.
My mind was rather peculiarly attracted towards a young
woman who had come to the Quarterly Meeting,
and getting her alone, a season followed worthy of being held in thankful remembrance,
as one wherein the flowing of the Father`'s love was evident.--I felt deep travail
that she might obey the call to come thoroughly out of every wrong thing,
by submitting to the power of Truth: her mind was much tendered,
the words seeming to have entrance, as into softened ground:
may no presumptuous hand close the eye and ear which I
do believe have been opened in this dear child,
though in her appearance gay and trifling: I fear for her,
lest some fowls of the air hovering about her may pick up some of the precious seed.

"`Thus ended our exercising labour in this place, which is indeed a favoured one,
though too many seem like the ground which has been often watered,
and bringeth forth briars and thorns; few comparatively, concerned for themselves,
but depending on the labour of the poor oppressed servants;
and I often thought while here, the day was advancing,
when the people must be scattered every one to his own: a wrestling seed, however,
seems preserved; a little Goshen as in Egypt.

"`Third-day, 10th, parted with our kind friends, I. and M. H.,
and set forward for Tullamore, where we arrived to dinner.
Two Friends`' families only residing in the town, it felt easier to me to sit with them,
separately, than to appoint a meeting; after which service I felt quite released,
and we left them; getting to Birr that night.
Attended meeting there next day, in silence, and under a feeling of distress:
several genteel people were present, to whom I was sensible of gospel love;
but the members of our own little community seemed the objects of my travail,
so far as I was able to travail.
I thought if I could get them alone I should be more at liberty,
we therefore concluded to sit with them in their families; which we did,
and so ended the visit in this place, where darkness seemed indeed prevalent,
and scarcely name or memorial for the Lord of Hoats to be found among them.
I was glad to leave it, and after dinner we set off for Roscrea.

"`Seventh-day, the 14th,
felt a stop in my mind to proceeding this day to Knockballymaher,
where I purposed being on first-day:
some uneasiness respecting home had been hovering about me for several days; I tried,
however, to have my mind as much disengaged from all anxiety as I could,
and desired to be singly turned to whatever point light most shone on.
We went in the afternoon to Dungar, and took tea with dear M. P.,
and her aunt A. P. On returning to our lodgings found W. N., just come from Clonmel;
he informed me that the young woman who had the
chief care of my children had taken the measles,
and was removed out of the house.
I sensibly felt this intelligence, and the struggle was not small to endeavour after,
and attain, a degree of quietude, sufficient to discover the right path.

"`I went distressed to bed, I think honestly resigned,
either to go forward or return home, as truth opened.
I got but little sleep in the night, and Knockballymaher seemed uppermost in the morning,
so I rose early, and roused my companions--we set out,
and after a rough ride for nearly two hours,
got to meeting soon after Friends were assembled.

"`Through the continuance of that mercy which never faileth,
all thoughts of home seemed dispersed,
and I was helped to get a little to my own exercise--my lot through most of
this journey--that of being dipped into sympathy with the imprisoned seed.
There seemed to be much business going forward in this meeting,
but it was not the Lord`'s business--one seemed at his farm, another with his oxen,
and almost all pleading excuse for not obeying the gracious
invitation to the marriage--the ground of the hearts of many seemed
never to have had the clods broken up by the holy plough,
so the seed could not take root or spring up.
With these feelings I was helped upon my feet, and enabled to deal honestly,
as truth enlarged, in matter and manner--a few excited my sympathy,
who knowing where to look for food,
were concerned to wait for it--the faith of these was, I hope,
a little strengthened to continue asking for daily bread.

"`This is a poor spot--the members of the meeting far
scattered one from another as to places of residence,
and I think such situations unfavourable to the right growth;
though if all were careful to dwell near the life in themselves,
no doubt the animating virtue would diffuse in their assemblies--instead of which,
in many places it seems so oppressed that there
is scarcely liberty to labour for its arising;
it feels as though the hardness in many minds would stone those who are sent unto them.

"`Several Friends kindly asked me home with them after meeting,
but I felt an inclination to go to a family who did not urge it, that of a widow Friend,
so went on with them to dinner.
After tea we got into stillness,
which proved a season of profit to my mind--much instruction was afforded therein,
and I thought not only for my own advantage,
but that something flowed to the younger part of the company,
of which number there were I think nine or ten;
some of these felt to me evidently under the cultivating hand,
and such as would become fruitful boughs, and their branches run over the wall, if they,
like Joseph, abode by the well, whose waters nourish and make green.
Some caution was administered not to get out of the valley, where the dew lies long,
but to abide in humility and holy fear,
that so sound and acceptable fruit might be brought forth.
This family manifests that much religious care has been exercised in their education,
they are plain, exemplary, and solid--a fine sight in this degenerate day.

"`After this visit I saw no way further, and,
though the feeling of love was strong to other quarters,
I was most satisfied to return home, believing the suspension for a while,
might work increasing liberty at some other period if the weight continued;
so on Second-day the 16th I set off for Clonmel,
and was favoured to find my dear husband and children in health; for which blessing,
with that of merciful preservation through this journey,
I desire humble gratitude may fill my heart to Him,
who is indeed the Alpha and Omega of all that is good.`"
