== Chapter VII.

[.chapter-synopsis]
* 1792+++.+++ Continuation of the same journey, comprising a visit to the North of England and Scotland

"`We remained in the city over first-day, attending Peel meeting in the morning,
and Gracechurch-street in the afternoon,
at each of which there was an affecting instance of mortality presented to our view:
in the forenoon the remains of a young woman named Boyle were taken into meeting,
and at Gracechurch street those of Mary, the wife of Thomas Wagstaffe;
both seasons were low and mostly silent.
In the evening we attended the Meeting for Ministers and Elders,
for the Peel Monthly Meeting, which was held at the School and Workhouse,
and proved a time of renewed strength; for though the communing was sad,
I was thankful for the belief that our gracious Master
approved it by joining Himself to the little company,
and affording a portion of food which could be travelled in the strength of,
for a little while, if not many days.

"`We left London about one o`'clock on second-day, the 17th of the ninth month,
John and Abigail Pim accompanying us as far as Wellingborough,
where we attended meeting on fifth-day, as we had that of Olney, on fourth;
we lodged at dear Benjamin and Tabitha Middleton`'s,
and the former kindly taking charge of us,
we proceeded after dinner to Market Harborough, lodged there,
and travelled next day forty miles to Nottingham, where we arrived late,
and were kindly received by John Storer and his wife.

"`We were weary and exhausted upon reaching Sheffield seventh-day,
but attended both meetings on first.
That in the morning was a season of very close exercise,
but I think owned with a good degree of the overshadowing of divine power,
under which humbling influence there was a moving in the line of apprehended duty,
so that relief of mind was obtained,
and I hope a little profitable instruction sealed on some present.
The number was very large, at both sittings, the latter heavy and laborious:
we drank tea at William Fairbank`'s, where a season of solemn retirement ensued,
and after supper at our lodgings,
were again sweetly invited to inward attention by the spreading of the holy wing;
and ability to perform spiritual worship was, I believe,
renewedly experienced by several then assembled,
to whom encouragement was administered still to maintain the warfare in faith:
this was the crowning of a laborious day.

"`24th. Our kind friend John Barlow took Elizabeth Pim and me in a chaise to Ackworth,
where, with several other Friends, we arrived to tea.
When the children were summoned to supper, we went to look first at the girls,
and here I know not that I can do justice either to my feelings,
or the sight my eyes were saluted with: the silence that prevailed,
the solidity of the mistresses and children,
and the sense of good melting into an humble admiration,
only to be expressed in such language as, the one half was not told me.
The view of the boys afterwards was attended with similar feelings,
and as our time was limited,
it seemed best to desire the whole family might be collected.
Several Friends from Sheffield and other places were present, and I believe all,
in some measure, young an old, bowed under an awful sense of the divine presence,
which indeed administered life,
and excited thankful returns of praise to Him who is forever worthy.
This one season was worth a long journey,
and the feeling of sweet peace while under the roof,
accepted as a precious pledge to our minds of the Lord`'s
gracious regard towards this extraordinary institution,
which is surely stamped with holy approbation, and will, I doubt not,
be a blessing to future generations.
I felt regret at being obliged to leave Ackworth so soon,
but our prospects precluded a longer tarriance.

"`We proceeded to York, in company with a large number of Friends,
meeting with a cordial reception from William Tuke and his excellent wife.
The Quarterly Select Meeting was held that evening,
and largely attended from different parts of this county, as well as by strangers;
dear Esther Tuke was beautifully concerned in the line of close doctrine in this sitting,
and I ventured to drop the little fragment out of my small basket.

"`Fourth-day, the meeting for worship was very large,
and several living testimonies were borne:
the meetings for discipline were held by adjournment till fifth-day noon;
and the last sitting especially was one of solemnity,
wherein precious fellowship was renewed,
and the concluding meeting in the afternoon might, I hope, be accounted one of worship.
Several young ministers appeared sweetly in their Master`'s cause,
and that mother in Israel, Esther Tuke, was also well engaged.
After these offerings Mary Proud rose,
and beautifully began what I expected would be an enlarged testimony,
but after standing only about ten minutes in gospel authority,
she closed in the very spot that one of the poorest sisters was dipped into,
so the sentence remained, as it were, to be finished;
and whether rightly concluded by me or not, is not my place to determine;
but I trust the wing of heavenly love overshadowed some minds,
and that this separating season was a fresh confirmation,
that gracious regard is continued to a church so
abundantly favoured as ours has been and still is.

"`After parting with many Friends who had been made renewedly dear to us,
we remained in this hospitable mansion, (William Tuke`'s,) not feeling ready to depart;
and indeed my spirit has been afresh led to feel after the right way to move hence,
and I hope a little light shone upon our proceeding on second-day to Leeds,
where a meeting is appointed to be held that afternoon, and one next day at Bradford;
after which we expect to go on to Kendal.

"`When this conclusion was come to, the weight of another matter,
respecting which I had been feeling,
so increased that it seemed best to mention the
prospect of having a public meeting in this place,
(York;) William and Esther Tuke feelingly entered into the concern,
saying they had expected it, which felt encouraging to my mind.
The meeting with Friends on first-day morning was a season of liberty honestly to labour,
and at five o`'clock a very large number of those not
professing with us gave us their company,
the house being nearly filled.
A covering of solemnity early prevailed,
under which there was an engagement to approach the throne of grace,
and supplicate for ability acceptably to worship,
after which dear Esther Tuke explained the doctrines of
Truth with great clearness and authority;
and I trust there was an endeavour, upon the part of each of us,
to move in the order of our respective courses,
whereby the harmony of gospel labour was maintained;
and through merciful assistance the meeting terminated well,
leaving upon our minds a humbling sense of gracious and unmerited regard.

"`We had a sweet season of retirement in the evening
with the little flock at our comfortable quarters;
they are a lovely set of girls, and favoured with great advantages,
in being under the superintendence of such friends as William and Esther Tuke.

"`We paid a very interesting visit to our valuable friends Lindley and Hannah Murray;
he is in a debilitated state of health,
having been for a long time unable to walk or stand upright, except at a few intervals;
at present his speech is so affected that he only whispers; yet he looks well,
and has a countenance that would cheer one, indicating where he dwells,
and what consolation is the source of his support.
He cannot now attend meetings, but rejoices to see his friends,
as they well may to see him, for indeed it felt to me that the Son of Peace was there,
and had sanctified those dispensations which would otherwise be hard to bear.
In a season of retirement after tea,
we were favoured to experience true Christian fellowship,
and our intercourse was attended with feelings which are precious even in the retrospect.

"`Second-day, Tenth month, 1st. We left York,
Henry and Mabel Tuke going on with us to Leeds, where we arrived in the afternoon.
The appointed public meeting was held at six o`'clock
in one of the most commodious houses I have seen;
it is a new one, calculated to contain twelve hundred persons,
and at this time was thought to be nearly full, and a precious season it proved.

"`Dear Sarah Lees met us here,
and was first and well concerned to draw the attention of the people to that
quietness which is so requisite as a preparation for acceptable worship.
Henry Tuke spoke afterwards, on the subject of feeding the multitude,
and I believe the subsequent labour was thus made easier:
indeed it was scarcely labour in this meeting, compared with what is often the case,
for the minds of the people seemed so like prepared ground,
that if a little seed was handed by the good Husbandman it felt pleasant work to drop it,
and I trust all that fell that night will not be lost.
I have since heard that there are many serious persons in this town;
and within about a year past,
I think seven united to our Society from among the Methodists.
It was remarkable that the line of expression ran
mostly towards such as were under divine visitation,
but had not attained to a settlement in religion.

"`After the dispersion of the public meeting, Friends were requested to remain,
and here labour was experienced; but in the gospel, because love was the covering,
which induced '`plainness of speech,`' and led to pour forth humble supplication.

"`Third-day, 2nd. Parting with dear Henry and Mabel Tuke,
we set forward to an appointed meeting at Bradford, which proved a low exercising time;
in the afternoon dear Sarah Hustler took us in a carriage to Keighley,
where we lodged at an inn:
next morning we took leave of this precious young woman Sarah Hustler,
and went on to Settle.
Having felt about this place before seeing it,
we had a meeting appointed and notice circulated,
so that with Friends and others a considerable number were assembled by six o`'clock,
and we were favoured with a solemn opportunity.

"`Our kind friends John and Mary Birkbeck accompanied us next day to Kendal,
which we reached in time for the Select Meeting, and were kindly received by John Wilson.

"`On Sixth-day the Quarterly Meeting was held,
and mercifully owned by the spreading of the holy wing;
though the last meeting for worship, at six in the evening, was an exercising season,
I thought owing to the lukewarmness of many, and revolting of others.
In both these general meetings life felt in a state of oppression,
but much honest labour was bestowed.
Alice Rigge, a mother in Israel, was engaged in a lively manner, and Anthony Mason,
who is bright and fruitful at the advanced age of eighty-seven,
cried aloud to the careless ones.

"`Seventh-day was mostly occupied in calling on Friends--one sick in body,
several so in mind; and among individuals here, as in many other places,
the precious life is buried in visible things.

"`First-day, 7th. We went nine miles to Windermere,
where a meeting is held twice in the year on a fixed day,
chiefly on account of the people who live about there and incline to attend.
Sarah Wilson and several other Friends from Kendal, accompanied us;
I believe it was felt by every sensible mind to be a solemn, favoured season;
the extension of gospel love being evident to those assembled,
concerning some of whom there is no doubt with me,
the declaration of our Lord will in His own time be accomplished,
'`them also I must bring.`'

"`We returned to Kendal to dinner,
and having mentioned to Friends there our view of having a public meeting in the evening,
we found notice had been given.
It was largely attended, and though the people did not seem so like the prepared,
or thirsty ground, as in some other places,
there was a solemn covering felt increasingly to prevail over the assembled company;
and as there was an endeavour simply to move and minister in the ability received,
spiritual harmony was maintained, and the season graciously owned;
so that for this renewed unmerited favour,
we had cause to make the return of praise to Him who is forever worthy.

"`After this the springs of nature were so run down,
that it seemed needful to rest a day for winding up again;
we therefore indulged part of second-day,
and went to dine with George and Deborah Benson and their large family,
and called to see Robert Dodgson, a valuable man in a very declining state of health,
but with a mind, I believe, resigned, and in good measure prepared to be unclothed,
if such be the divine will: it was consoling thus to feel in our sitting with him,
which I hope was mutually refreshing.
After tea, at George Braithwaite`'s, where many kind friends met us,
a peculiarly solemn stillness occurred, not from any plan,
but like the wind blowing where, and how it listeth; and hearing the sound there of,
we were sweetly gathered into pure silence,
under which covering Sarah Wilson supplicated for continued preservation,
and I thought the feeling of solemnity was thereby increased:
she has appeared only a few months in ministry.
Several others were engaged in testifying to the truth, as it is in Jesus,
and I was ready to hope it might be the termination of labour in this field;
but hearing of the usual meeting day being on the morrow,
began to fear that we might not be liberated, and so it proved.

"`Third-day was truly one of close exercise, but by an endeavour to owe no man any thing,
I hope there was a clearing honestly out of this place, and was truly glad we remained.
In this, as well as other instances, I found the use of a companion,
for I should have tried to escape this meeting, if she had not been earnest for staying.

"`We went fifteen miles that afternoon, and on Fourth-day morning proceeded to Penrith,
where a meeting had been appointed for eleven o`'clock;
most of the members were supposed to be present, and it was, upon the whole,
satisfactory.
There, as in other parts, the life of pure religion is low,
but it is consoling that a few are preserved living,
and exercised on account of the spiritually dead;
and I doubt not but the baptisms of these are in degree availing;
that their prayers and alms-deeds come up as a sweet memorial before the throne,
and find gracious acceptance.
We spent the afternoon, which proved a very wet one, with Friends named Ritson,
who entertained us in true kindness.

"`Fifth-day, the 11th. Rode eighteen miles of hilly rough road, to Carlisle, where,
next morning, we had an appointed meeting for Friends,
but apprehend all the members were not there; it was a low, exercising time.
We did not feel satisfied to proceed before First-day,
and spent part of Seventh in social intercourse with our friends.
We lodged with dear Mary Richardson, who is lively in spirit, and peaceful,
though she has had to partake of a bitter cup in the form of domestic affliction;
she bears up wonderfully,
and says her mind was prepared for something trying before her return from Ireland.

"`First-day, 14th. Attended the usual meeting at Carlisle, which was large,
most of those in profession with Friends and many not so being present.
It was a truly laborious time, and long before the spring of liberty opened;
but when it did, relief of mind was mercifully obtained,
through an endeavour to discharge manifested duty.
Here, as well as in other places, much rubbish is in the way,
and there are but few builders;
while it is to be feared the strength of some burden-bearers is decayed.
There feels a little life, but a deal of death,
so that the baptism of the living is deep, and no doubt the query often arises,
'`What advantageth it us if the dead rise not?`"

"`The uncertainty of our continuance in mutability was
at this season very awful to my mind,
and the necessity of preparation to mix with redeemed
spirits in the kingdom of purity renewedly impressed.
To draw from these solemn considerations,
to present other objects to the active mind of man,
and centre in that which gives temporary ease,
remains the business of the great adversary of our soul`'s happiness; and,
alas! how has he prevailed to the irretrievable loss of many preciously visited minds.
I thought I was favoured to dip a little into a painful sense of these things;
and were all not only to dip into them,
but dwell under the impressions which are at times mercifully made upon their hearts,
more hope might be encouraged of the restoration
of our Zion than there now seems ground for.
The meeting concluded under a humbling and thankful sense of unmerited regard;
and we proceeded to Sykeside, near Kirk-Levington,
where there is a little settlement of Friends,
and with some difficulty in bad road and after dark, arrived at our lodging-place.

"`Next day, 15th,
had notice given of a meeting to be held at two o`'clock in the afternoon,
to which the greater number who belong to it came, though very busy about their harvest;
several not in profession with us also attended.
It was a solemn season, and I hope some were graciously recompensed for their dedication,
by the gentle descendings of heavenly love,
which hath sweetly gathered several of this little,
and comparatively poor flock into the fold,
where He who is their holy leader and feeder keeps in a
state of humble dependence upon Himself.
There was far more liberty for the gospel to be preached here than in many other places,
for although the cares of this life have, if the snare be not guarded against,
a tendency to choke the good seed,
I am ready to think the glories of the present world
have settled many in so high and exalted a situation,
that with such, as on the mountains of Gilboa,
there is less of an opening into the fields of offering,
than amongst those who not finding a great deal of enjoyment in visible things,
feel in want of rest for their souls;
and being weary and heavy laden are of the number to
whom the gracious invitation of the Saviour extends.
The countenances of some of these simple ones cheered my heart,
which is indeed often sad,
and I was glad we had the opportunity of beholding and feeling with them.
A fine old man, a minister, belonging to that meeting,
accompanied us on third-day morning, and we reached Hawick, in Scotland,
the following evening.

"`Our road led through a beautiful country, and a diversity of pleasing scenes;
sometimes between lofty hills or mountains,
with the river Tiviot winding through the fruitful valleys;
at other times in view of finely cultivated plantations,
and substantial seats of the affluent inhabitants,
with the comfortable though more humble dwellings of the laborious farmers,
whose various toil might instruct an attentive mind, that there is no time for idleness,
if the ground of the heart require as much cultivation
and care as are apparently needful in the outward.

"`After we had rode a few miles from Hawick, on fifth-day morning,
we met dear Margaret Anderson going towards Carlisle;
but like one who felt something of that truth '`as iron sharpeneth iron,
so a man sharpeneth the countenance of his friend,`' she had the chaise turned,
and went back with us the seventeen miles she had travelled, and after dining at Ancram,
we were favoured to arrive at her hospitable dwelling at Kelso, in the evening.
The next afternoon, a meeting was held for the inhabitants,
but not very largely attended;
our guide and valuable friend James Graham had good service in it;
and I expect his mind was relieved by the opportunity,
as the chief weight seemed to have fallen upon him.

"`After taking tea at Jane Waldie`'s,
a season of religious retirement in her family proved one of peculiar solemnity: her son,
about twenty-two years of age, is likely to be taken from her by a consumption;
he does not appear much like a Friend, but seems brought to a state of still,
patient resignation, wherein I do hope he has, under this dispensation,
been mercifully instructed, and that heavenly regard is sweetly manifested towards him,
preparing for the awful change.
We were sensible in this visit of the renewings of that fellowship,
wherein there is not only a rejoicing in one another`'s joy,
but a bearing each other`'s burdens.

"`The usual meeting, on first-day morning, was attended by many others besides Friends,
though no notice had been circulated, and proved a season of divine favour.
I believe there were several feeling and awakened minds present, who,
if they are but willing to centre deeply enough into quietness,
will experience a state of true settlement.
But, alas! many,
who are at times enlightened to behold that path which '`the vulture`'s eye hath
not seen,`' are unwilling to part with those things which are for a prey,
and therefore know not an establishment in the
peace and rest that attend the submissive soul.

"`Not feeling relieved by this meeting, we had another appointed for the afternoon,
which was largely attended by persons of various denominations,
and proved a season of much gospel liberty; one wherein we were renewedly taught,
that those who trust in the extension of holy help need not be dismayed;
for let their endeavours be ever so feeble to promote His blessed cause,
the Lord is able to supply all deficiencies,
as well as graciously willingly to forgive all transgressions.
At the close, Friends were desired to keep their seats,
which gave us an opportunity of imparting what we apprehended was their due.
There are but few in membership,
and perhaps not all of these really initiated into the fold, by spiritual baptism.

"`A hopeful man who attends meetings, resides about three miles from Kelso,
at a place called Roxborough,
whither I found my mind attracted before I knew it was a village,
or that he lived in that direction.
We went there on second-day morning,
and having hinted our feelings to J. C. the preceding evening,
he had prepared a school room near his own house, where, in a short time,
a considerable number collected; and we were favoured with a solemn relieving meeting,
and after a little visit to J. C.`'s family returned peaceably to Kelso.

"`In the evening we had a time of religious retirement
with dear Margaret Anderson and her children,
wherein we were afresh owned by the overshadowing of divine goodness,
and she solemnly returned the sacrifice of praise.
This kind Friend concluded to proceed on her journey the next morning, as we did on ours,
and we parted under feelings of near sympathy and love.
She had, at the time we met her,
left home with a certificate to visit a few meetings in Cumberland;
and had we known this, I believe we should have hardly been willing for her to return,
though being a little together proved mutually pleasant.

"`When we arrived at Edinburgh, on fourth-day,
we found our dear friends I. and J. J. and A. T. which was truly gratifying;
they had been at G. Miller`'s a week, but inclined to wait for us.

"`Fifth-day, 25th. We all sat their usual meeting,
and afterwards an adjournment of the Monthly Meeting;
there were appointments to visit two, who had applied for membership,
in both of which we united, and in the subsequent conference.
Here, as in other places, the language may truly arise,
'`the fathers where are they?`' So few, almost everywhere,
being qualified to administer help or consolation to inquiring visited minds,
for want of seeking themselves to be renewedly supplied with heavenly virtue.

"`Since being in this city I trust we have endeavoured
honestly to move in the line of apprehended duty,
though our lot has been in a peculiar manner exercising.
The meetings on first-day were low, but little verbal communication:
several not in profession with Friends were there; and at our lodgings, in the evening,
we had the company of most of our Society residing here,
besides several students from the college.

"`On third-day we held a public meeting,
which was very largely attended by persons of various descriptions;
and through gracious unmerited regard it was, I trust, a satisfactory season,
owned by the influence of divine love,
and terminating under a precious sense of inward peace.
We took tea with a family not in profession with us, who were desirous of our company,
and were afterwards favoured with a solemn season, wherein I hope,
we partook together of a little '`of that bread which cometh down from heaven,`'
and when this is obtained how do the barriers of names and distinctions fall under
the prevalence of that feeling which breathes '`Good will towards all men.`'

"`We went next day to Dalkeith, and held a meeting which was largely attended.
There are no Friends there, but many Methodists, several of whom were present.
Some of the audience seemed scarcely in a state to have the gospel preached to them,
however, even on this occasion,
we had cause to speak well of his name who furnishes strength according to the day.

"`The usual meeting at Edinburgh on fifth-day,
proved one of more relief to my mind than any former sitting of the same sort;
and in the evening a public meeting was held in the new town;
it was largely attended by the genteel inhabitants, and I hope proved satisfactory.

"`First-day, my dear companion and I were unable to attend either meeting,
having both suffered considerable indisposition for many days;
yet we had religious sittings in several families, times of conference, etc.,
and on second-day, the 5th of eleventh month, left Edinburgh,
which had been a place of peculiarly laborious exercise,
and one wherein the necessity of obeying the sacred injunction
to '`watch,`' was renewed and deeply impressed,
under the feeling that, although good seed may be sown in the field of the heart, yet,
while men sleep, the enemy industriously improves the unguarded season,
and sows his tares,
endeavouring to defeat the Lord`'s gracious design and prevent intended produce.

"`We arrived at Perth on third-day evening,
and after trying at six inns to gain admittance,
we obtained accommodations at a small one,
where the people were very civil and gave us a dry bed;
the town being thronged on account of some local circumstance,
occasioned the difficulty in procuring lodging.
A few persons who are thought to be in some measure convinced of our principles,
residing in this place,
we appointed ten o`'clock next morning to meet with them at our inn; seven came,
and I hope this opportunity was not void of instruction to them or us,
nor what was communicated such as would do harm.
There seems a work begun in their minds, though still in a state of infancy,
but considering how they are situated,
it is wonderfiil that even so much fruit of a divine
visitation is to be traced as is really the case;
and knowing that He who hath visited is able to complete the work,
I trust something may in due season spring up to His praise.

"`We felt nothing further to bind us at Perth, than the visit to this little plantation;
and having for sometime past been sensible of somewhat like a cloud
intercepting the remaining meetings of Friends in this nation from my view,
and now a ray of light shining on the way towards Portpatrick,
I believed it safest to follow this,
and after a solemn season at parting with dear I. and J. J.
and A. T. they pursued their course towards Aberdeen,
and we sat out for Glasgow, travelling over some of the roughest road I ever encountered,
through Dunblane, Stirling, etc.
Being detained the whole of seventh-day for want of a carriage,
(extremely heavy rain rendered it unfit to use our chaise,) we did
not reach our place of destination till first-day afternoon.

"`We had heard of two persons who met together,
before the meetinghouse belonging to Friends at Glasgow was sold,
and on inquiring for these, discovered two more,
with all of whom we had a season of religious retirement,
which proved one of memorable instruction to my tried mind,
and I hope of some profit to those present.
Although in degree relieved,
a weight remained on me which prevented my feeling at liberty to move forward;
but on second-day morning, those we had sat with all came to take leave of us,
and I then understood the occasion of this pressure;
and after communicating what I considered to be my duty towards them,
felt clear to proceed.
We got on twenty-one miles to Kilmarnock that evening, next day to Girvan,
and on fourth-day the 14th, to a place called Stranraer, six miles from Portpatrick.

"`Being informed that the packet was to sail at three o`'clock on fifth-day,
we went forward about noon, but on arriving found no one was inclined to venture out,
as the wind blew almost tempestuously, and the sea looked terrific.
We got pretty well accommodated at this village, and the wind lowering,
we were told in the morning that a vessel was about to sail that afternoon,
we therefore got ready, feeling easy to embark,
though with the prospect of a tossing passage:
but going home rendered this less formidable, and hitherto,
every step towards Ireland has felt peaceful,
which is indeed cause of humble admiration at the dealings of divine goodness.
When this prospect opened some weeks ago,
it was attended with such feelings as I still believe
had not their origin in natural affection;
which, without something deeper, might prove fallacious;
but were of that mercy which beholding it enough,
graciously released from this embassy and permitted a return to different,
though perhaps not less, exercise in the land of my residence.

"`Though greatly tossed and very sick, we had what may be termed a favourable passage,
of three hours and twenty minutes, for which I trust we were humbly thankful;
we could not obtain lodging at the inn, the whole house being engaged; therefore,
though very unfit to take such a ride, and much in want of rest,
we proceeded ten miles to Milecross, where we arrived about seven o`'clock,
and met a cordial reception from Thomas Bradshaw and his family.

"`We attended their usual meeting on first-day,
and having felt what I judged it would be wrong wholly
to suppress towards the inhabitants of Newtown,
one mile distant, I mentioned it to our Friends here,
and on third-day Thomas Bradshaw with a Friend from Lisburn, went to Newtown,
and obtained the use of the Assembly-room;
but deemed it best not to circulate notice till the next morning,
and it was well they formed this conclusion,
as on fourth-day there was such a violent storm of wind and rain,
as rendered it very improbable that many would come out;
and though I very reluctantly yielded to the detention,
I had reason to be more than reconciled to the disappointment,
by the usual weekday meeting at Milecross being
a season of solemnity and favour to myself;
and, I hope, a time of profit to some others.
So that there is cause still to trust in the Lord,
and endeavour to do what little we can,
the promise being from time to time graciously accomplished,
'`verily thou shalt be fed,`' with such a portion of
peace as a wise Master sees meet to support the mind,
and excite a willingness to endure further conflict.

"`On fifth-day, at eleven o`'clock, the meeting was held at Newtown,
and attended by a large number who behaved in a remarkably solid manner;
indeed such a solemnity prevailed as is seldom known in meetings of this sort,
so that it proved what may be thankfully denominated a favoured season;
tending to the relief of our minds, and I hope the instruction of others,
and was a compensation for much previous suffering and exercise.
This seems like another woe being past, for such prospects try my poor frame and mind,
beyond what I could easily set forth; and the fear lest the holy, precious cause,
should suffer rather than be promoted,
is awfully felt by one who has indeed occasion to
marvel why so weak a creature should be thus led.

"`We had a solid time of religious retirement that evening in Thomas Bradshaw`'s family,
and next morning he accompanied us to Lambeg, where we lodged.
Seventh-day proceeded to John Conran`'s;
Sarah Harrison and Sarah Benton also arriving there soon after.
We all went to Ballinderry meeting next day,
after which I became so much indisposed as to think it
proper to give up to take some little care of myself,
which I was favourably situated for doing; dear Louisa Conran acting like a kind sister,
and ministering to my wants every way in her power.

"`Fifth-day, 29th. We attended meeting at Lisburn,
which proved a truly exercising season, I believe, to every feeling mind;
no voice was heard but that of dear Sarah Harrison,
who expressed a few sentences in a close line near the conclusion.

"`Seventh-day we went to Lurgan,
where we found our dear friend James Christy confined to his bed,
and suffering from acute pain, the nature of which is not clearly ascertained;
but his mind is sweetly composed and resigned, indeed wonderfully supported,
for which he expressed himself grateful, though sensible of being unworthy.

"`The Quarterly Select Meeting was held that afternoon;
the usual one on first-day morning was one of close exercise, and wholly silent:
in the evening some liberty was experienced, and more of a consoling hope,
that although so much death prevails, life is not entirely lost in our Israel,
nor the prospect of its increase altogether withdrawn.

"`In this meeting I was satisfied at our detention, but know not whether others were;
however, if a little peace be obtained, it is enough,
and I do desire to take this feeling home with me after an embassy, which has,
on various accounts, been peculiarly exercising.

"`The meetings for discipline occupied the whole of second-day, and on third,
one for worship was solemn and satisfactory.
In the evening we were favoured at our lodgings with being
refreshed together in the fellowship of the gospel,
and on the following morning set forward, accompanied by four Friends of Ulster province,
besides five from Dublin, who had come to attend the Quarterly Meeting.
As we advanced towards Dundalk, which was the place of our resting for the night,
I felt a weight on my mind,
under the apprehended discovery that there was something here to be visited,
and on entering the town believed it would be my lot to appoint a meeting.

"`I did not reveal this fresh and unexpected exercise to any one, until the morning;
when after endeavouring in solitude to acquiesce in this unfolding,
and desiring resignation to do the day`'s work in the day time,
I mentioned the subject to my ten friends, and they encouraging me to faithfulness,
a place was sought for; and the Sessions-house being procured,
a considerable number assembled at eleven o`'clock,
and we were so favoured with the overshadowing of the holy wing,
that I trust the minds of many were gathered into a
state fitted to receive the counsel given to impart;
and for this renewed manifestation of unmerited love and mercy,
my spirit was bowed in reverent gratitude to our Almighty and unfailing Helper.`"

This being the last meeting of which there is any
account in connection with the present journey,
it is presumed that she went on without further detention,
reaching Dublin on seventh-day, the 8th of twelfth month, where she met her husband,
and returning with him to their own habitation,
obtained the rest and care which her exhausted frame was greatly in need of.
My dear mother travelled in this engagement about two thousand miles by land,
and crossed the sea six times.
