== Chapter VIII.

Visit to North and South Wales, Bristol and some parts of Lancashire.
1793.

Soon after getting home,
my dear mother was cheered by having the society of her
highly esteemed friend Samuel Emlen under her own roof,
who, in the course of a religious visit to Ireland,
was at Clonmel about the end of the year 1792.
In the second or third month following she also met with this beloved friend in Cork,
whither she felt her mind attracted,
and they were mutually comforted by the opportunity of
uniting together in the attendance of meetings,
and visiting some of the families of Friends, in that city.
But it was not long before a more extensive prospect opened to the
view of this diligent and devoted handmaid j and she laid before her
Monthly and Quarterly Meetings a concern to visit Friends,
and appoint public meetings in North and South Wales,
and some parts of England contiguous to the principality.

In returning from Youghal, where the Quarterly Meeting was held,
and her certificate endorsed,
she met with a dangerous accident by the oversetting of
the chaise in which she and her husband travelled;
and though no fracture occurred,
the injury was such as to produce considerable suffering,
and render several weeks confinement to her chamber necessary;
and indeed she was in a very delicate state of
health upon leaving home in the eighth month.

Sarah Shackleton was again her affectionate companion in this journey,
and her friend and relative John Grubb, kindly offering his services as an attendant,
she deemed herself favourably provided for.
They sailed from Waterford to Milford, landing after a good passage,
on the evening of the 10th of eighth month, 1793.
The following account of this mission is extracted from my dear mother`'s letters.

"`On First-day, the 11th, we sat down with most of the little colony here,
(Milford,) which consists of seven families,
and hope the season proved measurably a meeting of worship,
and that under solemn preparation some of their minds were a little encouraged,
and gospel fellowship experienced.

"`On Second-day we went to Robinson-hall, where several families of Friends reside;
and after seeing the whole of these new settlers,
I should have gladly felt liberty to proceed; but from the time of landing at Huberston,
I had felt about the people there,
and every other movement looked clouded till this was out of the way.
I informed my friends of the prospect,
and a large school-room at the Packethouse being readily granted for the purpose,
a meeting was appointed there for six o`'clock on third-day evening,
and very largely attended;
so that many could not be accommodated with
seats and were obliged to stand about the door.
The greater number appeared solid and attentive, and a covering of solemnity,
which through mercy was early spread over us, so increased,
as to incite humble thankfulness to Him who continues to be a helper in the needful time.

"`From the attendant feelings,
I rather hoped that there were those present to whom the gospel might be preached,
and whose hearts assented to the purity of its doctrines;
though perhaps the terms whereon its glorious
privileges are to be obtained might appear hard.
For such as these a secret travail was felt,
and oh! that it may be availingly raised in themselves,
until that which opposeth the sway of pure truth is removed,
and by a submission to the discoveries of heavenly light,
the superiority and excellency thereof may not only be discovered,
but a willingness wrought to sell all in order to purchase a possession herein.
The landlady of the inn behaved with great kindness to us,
provided a nice supper and good beds for us, and several others who remained,
and in the morning refused to take any payment for the accommodation,
expressing her satisfaction with the meeting and our company.

"`Fifth-day.
We sat the usual meeting with Friends, which I hope was, to some,
a season of instruction, though little was communicated in words.
Next morning we had a meeting appointed at Robinson-hall, and notice having been given,
several not in profession attended, besides most of the Friends from Milford.
This season was memorably owned by gracious regard,
nothing being felt to oppose that liberty which the gospel spirit produced;
and I think this sitting was the crown to the present little visit,
and left us in possession of that peace wherein we could comfortably proceed on our way.

"`Several Friends from Milford accompanied us to Haverfordwest that afternoon,
where we were kindly received by Jane Lewis;
and at six o`'clock sat down with the few Friends in the town,
some others also joining us; it was a low silent meeting:
but a season long to be remembered ensued after supper, at the sorrowful widow`'s,
who seems to come under the description the Apostle Paul gives of that state,
I hope in the whole of it, '`she that is a widow indeed and desolate,
trusteth in God,`' etc.
Near sympathy was felt with this dear Friend,
and I trust her tried mind was a little comforted and encouraged.

"`On Seventh-day morning heavy rain opposed our departure,
and perhaps this reconciled to standing still in a deeper sense,
resigned to further discoveries of duty: towards evening it cleared,
but it was only outwardly, the cloud remaining on the tabernacle,
so that journeying forward would not have been safe.

"`The meeting on First-day morning was attended by persons of different denominations,
and proved a truly solemn one, being sensible of rather unusual liberty,
such as confirmed the belief that in most places there are inquiring minds,
to whom the gospel may be preached,
though a willingness to come under its pure government is not effected in them.
We had the afternoon meeting deferred to six o`'clock,
and notice circulated among the inhabitants, a large number of whom were present,
and an appearance of general solidity prevailed,
though the season was for a long time laborious,
which was felt to be occasioned by ignorance of spiritual worship;
but I hope the veil was a little rent from some minds before we separated,
and the way no longer deemed heresy wherein we worship.

"`I often think it is a great favour when life is felt to increase in these assemblies;
for while I apprehend this very arduous line is that of my duty,
earnest is my desire to be kept from doing harm,
or through mistaken zeal for its prosperity, injuring the precious cause.
There seems a double guard requisite on such occasions, lest,
from the thirst prevalent in the minds of the people,
any thing not divinely consecrated should be administered;
as on the other hand there is danger that the smallness of the provision,
in its first appearance, should prevent resignation to go forth with it,
and so the designed portion be withheld: but if we are mercifully kept watchful,
how does the pointing of the Master`'s hand clearly direct the track,
so that in humble admiration, and a sense of His gracious help,
it may be reverently acknowledged,
that although He leads the blind by a way that they knew not.
He continueth to make darkness light before them, and crooked things straight.
The Moravian bishop, Henry Sulger, was at this meeting,
and he and his wife called on us in the evening
and manifested affectionate kindness towards us:
his brother had been our very kind friend and interpreter in Switzerland,
of which I told him.

"`Second-day morning, after some preparation for departure,
we were favoured with a solemn season at our friend Jane Lewis`'s,
and under a renewed sense of divine mercy,
parted with several who had been made dear in the covenant of love and life,
and arrived at a place called St. Clear`'s to lodge.
Here I passed a thoughtful night, feeling my mind drawn to Llangharn,
a little town three miles distant, where there is a meeting-house belonging to Friends,
but none resident.
However, on going there the people seemed pleased with the prospect,
and cheerfully circulated notice of a meeting to be held at four o`'clock.

"`The house, which is capable of accommodating about two hundred, gradually filled,
and many collected about the door:
the solidity which prevailed during nearly an hour`'s silence was extraordinary;
and when liberty to speak was experienced,
the feeling was very different from what is witnessed when the thirst is for words only;
for the minds of many felt like ground drinking in rain,
so that entrance was sensibly administered to the truths of the gospel,
according to the ability communicated to preach it.
When meeting concluded the people seemed unwilling to withdraw,
and were so kindly affectionate in their manner as to seem like old acquaintance.

"`We proceeded on Fourth-day morning to Carmarthen,
where we held a meeting with an unsettled sort of people,
to whom true godliness was indeed a mystery,
and likely so to remain until the veil of prejudice be taken away.
On reaching Llandilo fifth-day to dinner,
we heard of an old Friend residing about half a mile distant,
and went in rain to see her; she was named Bowen, upwards of an hundred years of age,
and with her son, an elderly man that had married from among Friends,
lived in a little farm-house.
The poor old Friend seemed pleased to see us,
but was so deaf that it appeared useless to attempt expression; we therefore left a note,
conveying what had been our feelings while in her chamber.

"`We arrived at Swansea on Sixth-day evening, where a friendly,
solid looking young woman soon came to us, and requested us to go with her to tea:
we found her mother and sister very kindly disposed,
though neither of them profess as we do.
This young person went to meetings here from a secret attraction in her own mind,
and though sometimes quite alone, has continued to do so about three years:
she appears rightly convinced, and is, I believe,
desirous to abide under the converting power of Truth.

"`Feeling inclined to sit with the few Friends in this place,
we had a meeting on seventh-day morning, which proved satisfactory,
though the doctrine opened in a close line to the mere professors of pure truth,
of which class it seemed to us, most present were.
The young woman before-mentioned felt near to us,
and I hope she was a little encouraged by this visit.

"`We went forward to Pyle, aiming at Cardiff for first-day;
but not getting on as fast as we had expected, we did not reach it until the afternoon.
My companions going in search of the few in profession with us,
found a valuable old Friend, Elizabeth Edwards, who, though very infirm, came to the inn,
rejoiced to see Friends,
and with her and our own little band we had a sweetly refreshing season in the evening.

"`Though not clearly in prospect upon leaving Clonmel,
I could now see no way but going to Bristol, the place of my nativity,
where some of my bitterest draughts were administered,
and I hope not altogether unprofitably taken; this felt much in the cross, and I came,
not knowing what shall befal me, save that bonds and afflictions assuredly await.

"`We crossed the New-passage on third-day, the 27th of eighth month,
and on landing found G. H. and G. W.,
the latter employed by Thomas Rutter to conduct us to his house,
where we met a cordial reception.

"`Fifth-day evening we attended the meeting which was formerly held on sixth-day morning;
it was silent, and proved to me the beginning of sorrows here,
giving some little perception of the oppressed state of the seed in this great city.
First-day was deeply trying throughout; in the morning I obtained but little relief:
the meeting in the afternoon was heavy and silent, that in the evening large, exercising,
and laborious; the people seemed full, and are, I believe, often filled; however,
it felt to me that medicine rather than cordials was necessary,
and I found it no easy matter to administer what was given in commission;
but deem it an abundant mercy to feel the sacrifice graciously accepted.
Oh! may we never turn back in the day of battle, though giants may be in the land,
but trust in Him who proves the bow and battle-axe to His poor little ones;
and while all the qualification, and strength to use spiritual weapons come from Him,
graciously encourages to future combat by incomes of heart-settling peace.

"`I should have rejoiced could we have left things thus, and proceeded on second-day,
but light did not spring up.
We attended meeting again on third-day, and next morning went to Frenchay,
where notice had been previously sent: the meeting there proved solemn and instructive,
and though the line of duty was close,
I hope some were renewedly encouraged to trust and not be afraid.

"`The usual meeting in Bristol on fifth-day evening was memorably relieving,
though laborious exercise was my portion;
it felt a thorough clearing out so far as respected Friends,
but a pressure which I had at times been under since getting here, so increased,
that I ventured to have a public meeting appointed for the next afternoon.
This was largely attended; many serious persons,
and among them a great number of Methodists, were present,
and the season was early owned with a covering
of solemnity gathering into solid attention,
under which the labour felt easier than on some similar occasions;
and the hope was excited, that,
whether much or any good effect was produced by this sacrifice of the will or not,
the precious cause of Truth was not injured:
a cause which is indeed worthy the surrender of the natural life,
if this were called for.
After meeting many of my old acquaintance kindly waited to speak to me.

By the appearance of some, it is evident that the world has not lost its attraction;
this is sorrowfully the case with those, under every denomination,
in whom the seed of the kingdom does not take root for want of depth of earth;
but there are some among the different names to religion, who, I hope,
will become fruitful, if after having inquired what is truth?
they are prevailed upon to wait for such an answer as
will settle their minds in the right path.
My spirit nearly saluted some of this description, and secretly travailed for their help;
but alas! the cross remains a stumbling block to many visited minds,
and the simplicity of truth foolishness.

"`Being now sensible of release,
and favoured with that peace which is the gift of divine compassion,
leaving this place felt pleasant, and Olveston meeting presenting for first-day,
we left the city on seventh-day afternoon the 7th of ninth month;
and lodged at the house of Daniel and Joan Holbrow,
the latter being an old and long beloved friend of mine,
it was mutually pleasant to meet, and once more enjoy a little of each other`'s company.^
footnote:[This was the Friend to whom the letters in
the early part of this volume were addressed.
She joined our religious Society on the ground of
convincement a few years after my dear mother,
and was a steady and valuable character to advanced life.]
Several Friends from Bristol joined us at Olveston,
and many not in profession with us also attended the meeting, which proved a solemn one.
Two who appear rightly convinced of our principles were present,
and I trust "`a little instruction was profitably sealed upon their minds.

"`Second-day was the Monthly Meeting, held at Thornbury, to which we felt bound,
and it was throughout an exercising season;
but help being mercifully afforded we had cause for thankfulness,
and as we met many Friends from the different particular meetings,
it was a relieving opportunity.
We returned to Tockington to lodge, and on third-day morning set out,
accompanied by nine or ten Friends for the New-passage;
John Lury and another Friend crossed the water with us; and when we got over,
one of our band went forward about five miles, to Shire Newton,
to appoint a meeting for three o`'clock.
There are only three Friends belong to it, but the meeting was attended by many others,
of the poorer class as to this world,
but to whom it felt that the gospel could be preached.

"`There being no suitable lodging here,
we judged it better to return to the Passage-house, where we were well accommodated,
and hoped to proceed on fourth-day to the next meeting, Pontypool;
but as I had felt about Cardiff, when there in our way to Bristol,
though without any clear opening to appoint a meeting,
and the pressure reviving in such a manner that all other movements became clouded,
we concluded to go thither,
though at the cost of about twenty-four miles of extra riding.

"`We arrived at Cardiff on fourth-day evening,
and finding a large room suitable for the purpose,
had notice circulated of a meeting for ten o`'clock on fifth-day morning;
when a solid company collected with us, among which was the minister of the parish,
and many Methodists.
Through gracious condescension, the season was memorably owned,
to the thankful admiration of our hearts;
the people seemed to hear the truth in the love of it; but oh! what can be hoped for,
when that which will let remains untaken away: however,
if even one poor mind is a little instructed,
may He who is forever worthy have all the praise.
We had afterwards a solemn season with three of our fellow professors,
and felt much sympathy with one who is, I believe, convinced in her judgment,
loves Friends,
and confesses this so far as to sit with the few in their little meetings here,
but she stumbles at the cross.

"`We proceeded on sixth-day to Pontypool,
and at six o`'clock that evening sat with the few Friends resident there.
It was a trying time on account of the lowness of the pure life;
but a solemn season after supper at our lodging seemed
as a refreshing brook to our weary spirits.
Feeling easy with respect to this place,
and the small meeting of Llanelthy about ten miles, distant,
by a road nearly impassible for a carriage,
we left Pontypool on seventh-day got to Monmouth to lodge,
and concluded to have a meeting at our inn next morning.

"`Hearing of a young woman, a Methodist, whom Job Scott had seen and conversed with,
we inclined to have some of her company,
and on telling her our intention she appeared well pleased,
and we retired to a quiet chamber,
where I think we were favoured with that sacred unction which unites all the living,
and throws down the barriers of outward distinction.
This young woman appears solid, and acquainted with the influence of good,
but not sufficiently emptied of self, to receive the kingdom as a little child;
but an openness being felt towards her,
I hope no harm was done in communicating what arose,
and we parted in that love which it is refreshing to feel.

"`We spent the remainder of the day at my brother`'s, and on Second-day morning the 16th,
parted from our dear attentive friend John Lury,
he being bound to Bristol Quarterly Meeting which began next day,
and we to pursue our journey; so without any guide or companion,
we proceeded to Hereford, arrived there to dinner,
and were a little puzzled which way to steer afterwards,
but we were favoured to reach Leominster in safety; and not knowing any Friend there,
went to the inn which was recommended to us.
Cousin J. G. walking out after tea, found some kindly disposed to entertain strangers,
and we were affectionately received and hospitably cared for,
by three children of dear Thomas Waring,
who entered his everlasting rest about four months since.
A meeting was appointed for third-day, to which, I believe, most Friends came,
and after a time of deep exercise, it was graciously owned by the renewings of holy help,
to the humbling and relief of our minds.
As our journey was not likely to be much advanced by proceeding this evening,
and the weather became wet, we abode with these dear Friends the remainder of the day,
feeling the sympathy of their spirits like a pleasant stream in a land of drought.

"`We have been in our travels through some parts, much like poor pilgrims.
Friends being so thinly scattered in Wales,
that except when our kind friend J. Lury was with us,
we have had to provide for ourselves in every sense.
We set forward fourth-day morning for the Pales meeting,
and travelled over a very indifferent road,
where we were in great danger of being overset, but mercifully escaped any injury.
We arrived late in the evening,
and found Rees and Joan Bowen kindly disposed to do what they could to accommodate us,
and though much in the simplicity, it was truly pleasant to rest after hard labour.
My frame sensibly feels such constant exertion,
but I am through divine assistance sustained,
my general health is better than on leaving home,
and I have not yet laid by one day from travelling or meeting.

"`In consequence of a fair at Kineton,
it was not practicable to hold a meeting fifth-day; the next being their usual time,
we had notice sent to Friends residing in different directions,
and also among the inhabitants generally; and though a time of close exercise,
this meeting proved solemn and relieving to our minds.
The number of Friends in these parts is small,
and that of deeply exercised members is only as one of a family and two of a tribe;
but these are worth visiting;
and among those of other denominations there are also such as deserve notice,
several of whom were at this meeting, and I believe felt a little strengthened.
We resumed our journey about four o`'clock,
and reached a comfortable little inn in Radnorshire twelve miles distant, to lodge.

"`Seventh-day we encountered what is called thirteen miles,
of some of the worst road I ever travelled,
being five hours in arriving at our place of destination;
but still we have to acknowledge the extension of protecting care, so that ourselves,
chaise and horses, were all sound on getting to Llanidloes in Montgomeryshire.

We lodged at an inn, very few Friends residing in the town.
The meeting here on first-day morning was, through gracious condescension,
a remarkably invigorating season,
feeling like the participation of such meat as the prophet went in the strength of,
many days.

"`The meeting here is held in a school-room,
(no house for the purpose being built,) which was closely
filled by those of different religious professions,
several of whom were very solid;
and the few Friends belonging to it are mostly of a description to whom,
as the Lord`'s poor, the gospel freely flowed.
The afternoon meeting was silent, but one of instruction.
There are two men Friends in this small congregation in the ministry.
We spent the whole day at the school, which is kept for the benefit of the principality,
and I apprehend supported by subscription,
though such as can afford it pay for their children.
A Friend and his wife from Lancashire, Robert and Mary Whitaker, are settled there;
they are a steady valuable couple,
but feel discouragingly the difference between their present and former situation;
we felt love and sympathy towards them.

"`Second-day morning, 23rd. We left Llanidloes with peaceful minds,
accompanied by two choice Friends; Richard Brown, a minister, and his sister Mary Hunt,
an elder, both going to the Quarterly Meeting at Shrewsbury, to which we felt attracted,
and where we were favoured to arrive in safety a little
before the time for Select meeting on third-day evening.
We were kindly received by dear John Young, and his daughters Jane and Hannah,
and comforted by the sight of several old and beloved Friends;
among these was Ann Summerland, who at that sitting,
and in the Quarterly Meeting next day, stood forth in the exercise of her beautiful gift,
a striking example of verdure in the winter of eighty-five.
The little business of this Quarterly Meeting being over, about two o`'clock,
I ventured to disclose a prospect which nearly
from entering Shrewsbury had impressed my mind,
that of inviting the inhabitants to a meeting in the evening;
and I think it may be thankfully acknowledged that this season also was mercifully owned,
by divine power rising into dominion; and a hope attended,
that this feeble effort to promote the precious cause of truth and righteousness,
would not prove wholly unavailing.

"`We sat the usual meeting with Friends on fifth-day to our comfort,
and afterwards proceeded to Coalbrook Dale, whither my mind felt strongly attracted.
We reached the hospitable mansion of Abiah Darby to tea,
and found many dear Friends who stayed the evening;
she is very infirm and mostly confined to one room, but joined us at supper,
and in a season of retirement after, was engaged in solemn supplication and praise.

"`We had previously requested a meeting might be appointed at New Dale,
for sixth-day morning, and many from the Old Dale accompanying us,
it seemed like visiting both meetings; and through the extension of merciful regard,
proved a memorable time:
the continued willingness of the great Master being
evident even to bring back those who have halted,
and such as have been driven out by the enemy of all good.
Some of this description being present,
earnest travail on their account was afresh excited,
and a few friendly calls afterwards tended to additional relief.

"`We proceeded that afternoon to Newport in Shropshire,
and on seventh-day rode twenty-five miles to Namptwich,
where we attended meeting on first-day morning; a laborious, heavy season,
but towards the last a little liberty was experienced.
Feeling in haste to get to Liverpool, we were easy to proceed on our way,
and arrived there the following evening.
It had for several days appeared to me as if we were
going to the funeral of dear Elizabeth Rathbone,
and finding at Warrington a letter from my beloved friend S. Benson,
informing me that her precious sister`'s release from suffering seemed near,
it was no surprise to me to hear, on stopping at Robert Benson`'s door,
that she had been some hours sweetly dismissed from this conflicting state.
We went to the house undetermined as to staying,
having received a kind invitation from William Rathbone to lodge;
but the affectionate solicitude of Robert and S. Benson
induced us to take up our residence in this house of mourning,
after being assured by dear S. Benson that she would not anxiously think about us,
but let us consider ourselves at home.

"`Our dear departed friend was many months ill,
but preserved in sweet resignation and quietness of mind,
saying a short time before her departure, '`My work is done and I am ready.`'

"`Third-day was the Monthly Meeting, which was largely attended, and a solemn,
favoured time; as was also the Quarterly Meeting for this county,
held on the succeeding day, wherein gospel liberty was experienced,
and the current of life so flowed that I trust the ever
blessed name of our Redeemer was exalted.
After supper at Robert Benson`'s there was a season of religious retirement,
in which I believe,
some minds felt renewedly strengthened under the sense of all-sufficient help;
our dear friend Robert Benson spoke instructively.

"`Fifth-day was the interment, which was largely attended; the pause at the grave side,
and a meeting held subsequently, were times of solemnity and favour;
so that this beloved exemplary young woman was owned in death,
as well as approved in life.
John Thorpe was well engaged on this occasion; his ministry is uncommonly lively,
sensible, and as dear Samuel Emlen says, with '`holy pertinence`' to the subject in view.
A large company returned to the house,
and after partaking of the bounties of heaven in a temporal sense,
a season of divine refreshment succeeded,
wherein some young persons present were reminded of the
precious counsel which the deceased had often given them.^
footnote:[For an account of E. Rathbone, see [.book-title]#Piety Promoted,# Part 10th.]

"`Having had a view before I came here, and being since confirmed in the belief,
that something was due from me to the families of this meeting, I ventured to mention,
after being altogether closed from public labours on first-day,
that I believed it best to move in this matter:
and finding there were some other minds under preparation for this service,
the performance of it was considerably lightened by the
sympathy and united exercise of several dear friends.
Robert Benson kept closely with us,
and his valuable wife and S. Hadwin occasionally joined.
We broke off in order to attend the Monthly Meeting
held at Manchester the 15th of tenth month,
which proved a time of deep and painful feeling;
but through the renewed extension of Holy aid, one of some relief,
which I consider an abundant favour;
though in thus endeavouring to fill up the allotted measure of suffering,
no mighty works may be done.
The efforts of some are indeed very feeble, but if these are only so preserved as at,
last to obtain that testimony, '`she hath done what she could,`' it will be enough; yea,
under such a prospect, the often tossed and weary spirit may even repose:
while in deep self-abasement the acknowledgment of
being an unprofitable servant is renewedly made.
But oh! that unto Him who is able to make up all deficiencies,
praise may be ascribed both here and everlastingly!`"

After the family visit, my dear mother held a public meeting at Liverpool,
which is stated to have been large and favoured; another at Prescot,
for which the use of the Sessions House was obtained;
and on the 25th of tenth month was at Warrington, where, after holding a public meeting,
she had a solemn and relieving opportunity with her fellow professors.

She returned to Ireland in time to attend the Half Year`'s Meeting in the eleventh month;
after which she was favoured to reach her own
habitation in better health than she had left it,
having accomplished an exercising journey of above three months.
