== Chapter IX

[.chapter-synopsis]
* 1794+++.+++ Visit to Leinster Province, particularly the County of Wexford
* Public Meetings in the County of Cork
* Letter to the French Prisoners at Kinsale

During the ensuing winter,
my beloved mother was mostly occupied in religious
service within the bounds of her own quarterly Meeting,
and early in the spring she obtained a certificate for visiting Leinster Province,
expressing that in this concern her view was much towards
holding meetings with those of other religious denominations.
Soon after avowing this prospect she was taken very ill,
and confined for many weeks to her chamber,
so that she did not enter upon the engagement until after the National Meeting in Dublin.
While attending that solemnity,
she felt her mind impressed to have a public meeting in the city, respecting which,
and subsequent religious service, she writes as follows:

"`I have frequently since coming here, feared what is now come upon me,
but waited for the conclusion of the meeting to have the matter matured.
First-day was a time of arduous labour indeed,
one wherein I was once more helped to feel a little for the state of the church,
and relievingly to cast off some of the burden under which I had been oppressed.
Third-day sat the usual meeting at Meath-street,
and my view being to the inhabitants of that neighbourhood,
notice was circulated for a meeting at six o`'clock in the evening;
the house was entirely full, and such remarkable solidity prevailed,
that I am willing to trust the blessed cause of Truth was not
dishonoured by this feeble attempt to advocate it,
though my mind was affected with many fears,
and earnest were my desires that the Lord`'s power might so
arise as to keep down all of an opposing nature,
which was in good measure the case.
Mary Ridgway was at the meeting, and though silent,
the sympathy of her spirit felt strengthening.

"`I proceeded on Fourth-day morning to Ballitore, attended meeting there on fifth-day,
and next morning accompanied Friends from thence to the Monthly Meeting held at Athy,
where, notwithstanding I got wet in going, I am glad to have been,
feeling my mind so relieved that I hope that place may
be off the list in my impending journey.
Returning to Ballitore, I remained there over meeting on first-day morning,
and had cause to be humbly thankful in doing so;
for while very much indisposed from the effects of a cold,
I was so helped to discharge my duty as to be left in possession of quiet poverty.
I rode to Carlow in the afternoon,
and feeling inclined to visit the widow and children of our friend John Watson,
went on second-day to Ballydarton.
Mary Watson and several other Friends dined there with me,
after which a season of solemn stillness ensued,
which was attended with feelings that proved a
sufficient recompense for this little turn.

"`I believed it best to appoint a meeting at Kilconnor for the following day,
and also requested that the invitation should
extend to those not in profession with Friends,
A considerable number assembled at ten o`'clock on third-day morning,
over whom a solid covering soon spread to the comfortable settling in outward quiet,
under which an unusual liberty for gospel labour was experienced; and it proved,
like many other seasons, one wherein that language might be gratefully adopted,
'`Hitherto the Lord hath helped,`' At the conclusion, Friends were requested to remain,
and on them, I hope, honest labour was, in received ability, bestowed: after which,
feeling liberated for the present, I deemed it best to turn homewards,
first attending the usual meeting at Carlow, on fourth-day, the 14th of fifth month.`"

Her continuance at home was but short, for early in the sixth month she set out,
accompanied by her beloved friend Margaret Grubb, for the county of Wexford;
they spent several days in Waterford, attending meetings there on first and third days,
and making calls on Friends who were confined by illness.
They went from thence to Ross,
and on the 17th of sixth month my dear mother thus writes from Enniscorthy:

"`Though my bodily strength as thou knowest, is not great,
I have cause to be thankful that the tabernacle
is so supported as that the work of the day is,
I humbly trust, advancing, wherein I have peace so far in the present embassy.
The lines fall not in pleasant places, our heritage is not goodly,
and if we visit the seed it must be in the prison house, where it too generally lies.
We attended Forest meeting on first-day, which was large and remarkably exercising to us,
but through merciful assistance our minds obtained relief:
we had a season of religious retirement in the evening in Jacob Goff`'s family,
at whose hospitable mansion we lodged and were affectionately entertained.

"`Feeling about the inhabitants of Taghmon, a little town through which we passed,
but where no room sufficiently large was to be found,
they were invited to our meetinghouse, about half a mile distant;
and on second-day forenoon we assembled with a considerable number of the military,
and others of different descriptions, who conducted themselves with solid attention,
and through divine mercy it proved a memorable time.
There was sensible liberty in declaring, and willingness to receive,
the testimony of truth.
At the conclusion some books were distributed,
with which the people seemed so pleased that we saw several
reclining on the grass as we passed by the fields,
employed in reading them.
Oh! that my heart may thankfully remember this favour, added to many others,
and be engaged resignedly to pay those vows made in the day of trouble;
for long indeed have I seen that sacrifices of this nature would be required at my hands.

"`We proceeded to Lambstown, made a few calls on Friends,
and had an appointed meeting at Cooladine, which proved a low trying time.
Sat with Friends here at their usual meeting on fifth-day,
wherein my dear Margaret Grubb was engaged to minister, but I was silent;
and believing it best for us to go into the few families resident in this place,
we began with the work, by having two visits that afternoon,
and at six o`'clock in the evening had a meeting for the inhabitants,
which was largely attended and mercifully owned.
Many books were distributed, and more were afterwards applied for,
which encouraged the hope that favourable impressions had been made on some minds.`"

Before leaving Enniscorthy,
my dear mother addressed the following letter to a man who had
attracted her notice after a public meeting at Ross,
which, with a few extracts from one he wrote to her in reply,
it is thought may prove both acceptable and instructive to some readers.

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

Strange as it may appear for one who has no acquaintance with thee,
to address thee in this manner,
I feel persuaded that it will not be altogether unacceptible to thee,
when I tell thee it proceeds from an apprehension that it may conduce to my peace;
and seems pointed out as the best means to throw off some of the feelings
which have attended my mind when thou hast been presented to my view.
It was, I conceive,
the drawing cords of gospel love that influenced
my heart to pay the present visit to these parts;
and not satisfied with coming to see how my brethren fared, I have been sensible,
since entering into the field of labour herein,
of the extension of the heavenly Father`'s love to His family universally;
and have been engaged, with my beloved companion,
to appoint meetings of a more general kind than such as
are usually held when our Society is the only object.
It was one of this nature at which thou, with many others,
wast present on this day week at Ross.
I knew not, by information or otherwise, who,
or of what description any then assembled were;
but I did at that season believe that there were present, one, or more,
in whom the deeply important query had been raised,
'`What is truth?`' and for such a travail was excited in my heart,
that they might patiently wait for,
and be indisputably favoured with such an answer from Him who can administer it,
as might fully settle and establish them in the way of righteousness and peace.

In the class already described I heard after meeting thy name;
and passing by thee on second-day morning on the quay,
I was so sensible of the extendings of gospel love towards thee,
that I thought I should have liked just to tell thee so much,
and admonish to faithfulness to the monitions of pure truth inwardly revealed.

I have this evening been so sensible of the renewing of this,
I trust rightly inspired solicitude, that while nature covets rest after a day of toil,
I am seeking refreshment to my spirit in thus saluting thee.
And believing it to be of the utmost consequence that we should singly attend to,
and obediently follow, the light which maketh manifest,
it is in my heart to say unto thee, dear friend, stand open to its unerring discoveries,
and believe in its infallible teachings; for as this disposition prevails in us,
we shall be instructed in all things appertaining to life and salvation.
Yea, if no inferior medium conveyed any thing fully satisfactory,
or sufficient to obviate the difficulties presenting to our view,
I am persuaded from a degree of certain experience,
that in this school of inward attention,
greater proficiency may be made in true and saving knowledge,
than will be the case in a far longer space whilst our views are outward;
as by ever so great exertion of the mental powers,
things viewed in the light and eye of reason only,
may be decided in a very erroneous manner.
Man, however enabled to write or speak on the most important points,
can only help to convince the judgment and inform the understanding,
but the divine principle wherewith we are mercifully favoured,
operates in a far more powerful manner;
it not only speaks in us the intelligible language of conviction, but,
whilst it discovers the reality, puts us in possession of it,
and conveys such soul satisfying virtue that it
allays the thirst for every inferior stream.
Here that water being partaken of which Christ the indwelling fountain administers,
we go not thither to draw--namely, to that spot whence we derived something,
but not fully adequate to the desire or thirst excited; because we feel,
that whosoever drinketh of this unmixed spring, it is in him a well of water,
springing up into everlasting life.

Now, dear friend, what my mind feels deeply solicitous for is,
that this may be thy favoured experience;
that the substantial part of true religion may be richly inherited by thee;
that being a witness of the inward and spiritual baptism,
as the door of initiation into the church, the mystical body of Christ,
thou mayest become thereby a partaker, at the spiritual table,
of the soul sustaining '`bread of life,`' and be
nourished with the wine of the heavenly kingdom,
comprehending the communion of saints, and being through the power of Truth,
sanctified throughout, body, soul and spirit,
participate everlastingly of the treasures of the Lord`'s
house;--so desireth the heart of thy truly well-wishing friend,

[.signed-section-signature]
Mary Dudley

--

[.offset]
The reply:

[.embedded-content-document.letter]
--

[.salutation]
Respected Friend,

For so I must call you,
your very unexpected and highly welcome letter was delivered to me last Saturday evening.

Just before I received it my mind was engaged on divine subjects,
and on some particulars relative to which your letter seemed as a message from heaven:
as such indeed I received it, and have been greatly affected by it;
and from the altar of my heart I return praise
and thanksgiving to that adorable Being who has,
in numerous instances, shown his kind, providential care of my poor soul.
And you, my much esteemed friend in the gospel, as an ambassadress of Christ,
and a messenger of the Lord to me for good,
I salute with my heartfelt and grateful acknowledgments.

Through your ministry I received of the baptizing power of Christ; it quickened my soul,
it reached, melted, and tendered my heart, and refreshed me as with the dew of heaven.
Those feelings we cannot bring upon ourselves; it is the Lord only,
either by himself immediately, or His agent or agents sent with power from on high,
that can effect such things.
The earnest solicitude raised in you to write to me,
the refreshment and comfort I received from your letter,
my state pointed out in your sermon, the effect it had on my dear children and myself,
all declare unto me the finger of the Lord in this matter,
and that you have come unto us '`in the fulness of the blessing of the gospel of
Christ.`' May we keep close to that light which maketh all things manifest,
until it shine more and more unto the brightness and clearness of the perfect day,
and so living in the light, we shall have fellowship one with another,
and the blood of Jesus Christ will cleanse us from all sin:
all the blessed merits of His death, and all the life-giving influences of His Spirit,
are to be had by being joined to this light, and walking in it; in Him was life,
and the life was the light of men.

Whatever others may do, as for me, my dear wife and children,
may we serve the Lord with our whole hearts, and be engrafted into the true vine.
To hear of our progress in true religion, will, I am very certain,
be highly pleasing to you.
And now, my respected friend,
I commend you to God and to the word of His
grace! go on in the baptizing power of the Lord.
May we, every one of us, hold out unto the end and be saved,
that so in the day when the Lord shall make up his jewels we may unitedly
partake of the boundless ocean of everlasting glory and bliss.
These are the fervent desires of your much obliged and sincere well wisher.`"

--

From Ennlscorthy she went to Ballinclay, whence she writes as follows:

"`We arrived here on seventh-day afternoon,
and met a truly cordial reception at John and
Abigail Wright`'s. The meeting on first-day was,
I believe, attended by all the members of it,
and in the evening we had a season of religious retirement in the family.
After this, Wicklow so forcibly attracted my mind,
that I saw no light on any other direction,
and my true yokefellow Margaret Grubb having adopted the resolution,
'`whither thou goest I will go,`' we sent forward to
have a meeting appointed therefor third-day;
this, through gracious condescension,
proved one concerning which it may be said that Truth rose into dominion.
There was not so large a number as on some similar occasions,
but the company was of the higher class,
and their solid attentive demeanour such as left no room to doubt that, at that season,
their minds were measurably awakened to serious consideration,
whether any further fruit be brought forth or not.
After dining with some Friends in the town, we returned to Ballikane,
and had a meeting appointed for Friends there on fourth-day morning,
which proved relieving to our minds, although a deeply exercising time.

"`Having felt respecting the inhabitants of Gorey, we turned thither sixteen miles,
and on arriving there found that John Wright had procured the use of the assembly room,
which being properly fitted up,
a large number were accommodated at a meeting held on fifth-day morning.
The company was not very promising to look at, but a solid covering soon spread,
and mercifully so prevailed as to keep in subjection the light chaffy nature;
so that not only solemn prayer could be offered,
but the testimony of Truth go forth with gospel liberty;
and there was a consoling hope in our hearts that this
day`'s labour would not be altogether in vain.
Several appeared very desirous of having books explanatory of our principles,
and expressed their satisfaction with the meeting.
I find there had not been any meeting held there
in the remembrance of some elderly Friends,
except one many years ago, and another by John Pemberton.`"

After this they went again to Enniscorthy,
where the Quarterly Meeting for Leinster Province was
held the last three days of the sixth month,
respecting which, and their subsequent engagements, she thus writes:

"`This season was on several accounts one of great conflict and exercise;
there was not an abundance of preaching,
indeed I thought what there was might be termed labouring,
and that in ground unbroken by the plough of divine power; however,
as ability was mercifully afforded to maintain the exercise and obtain relief,
this ought to be thankfully acknowledged.
We remained over the usual meeting on fourth-day,
which was a time of honestly clearing out, and consequently relieving.
We got that evening to Joseph Smithson`'s, at Ballintore,
and at five o`'clock on fifth-day afternoon held a public meeting at Ferns,
which proved a time memorable for the extension of gracious help,
and liberty for the precious testimony of Truth, which I trust was, by its own power,
exalted over all opposition.
The company was as large as the house could well contain;
among the number were two clergymen, one of whom was very cordial afterwards,
coming into Benjamin Smithson`'s, and introducing his children to us.

"`Feeling an impression to visit the families of Cooladine Meeting,
we entered upon that service, and were closely occupied during four days,
having many miles to ride in going from house to house,
and great part of it over very bad roads.
In the meeting at Cooladine, on first-day, although no capacity to minister was afforded,
it felt a favour that the oppressed seed could be prayed for:
it was their Preparative Meeting, and we also sat with a family who came to be visited,
before dinner, and immediately after with another, who, to save us eight miles riding,
had kindly remained.
In the evening another sitting ensued, and so ended this exercising day.

"`Third-day was their Monthly Meeting, held at Ballintore, and largely attended;
the first sitting by several not in profession with us,
among these one of the clergymen who was at the public meeting at Ferns;
my dear Margaret Grubb sweetly ministered, and we paid a visit to the men when separated.
A large company dined with us at B. Smithson`'s,
and in a season of retirement afterwards, a consoling persuasion was raised,
that some present, with many more in these parts, would be not only gathered under,
but everlastingly sheltered by the heavenly wing;
this precious influence felt as a seal to our release,
and we parted from many under the cementing virtue of divine love.
We lodged as before at J. Smithson`'s,
and after a solemn season there on fourth-day morning, left this field of labour,
and reached Ballykealy to dinner on our way towards Roscrea.`"

After visiting Friends at Birr and Roscrea,
my dear mother and her companion got to their own Quarterly Meeting,
which was held in Limerick about the middle of the seventh month,
and afterwards sat in most, if not all the families constituting that particular meeting.
Near the close of this service, she was confined with a severe attack of indisposition,
which tended greatly to reduce her already exhausted frame;
so that she returned home in a very weakly condition,
and was for some time unequal to much exertion.
Early in the ninth month, however,
she believed it required of her to enter again upon religious service,
and was engaged in holding public meetings in several
places within the compass of her own Monthly Meeting,
as well as attending some meetings for worship and discipline in Cork;
and near the close of the year she set out with a
prospect of more extensive labour in that county,
having S. L. for a companion, as also her nephew J. G.,
he being again kindly disposed to act the part of a care-taker to his dedicated relative.

During about four weeks which this journey occupied,
she was closely engaged in an arduous line of service, both among Friends and others,
visiting families in Youghal, and holding nine or ten public meetings;
most of these in places where none of our Society resided,
and where the principles we profess were but little known.
Of this description was Kinsale, and a number of French prisoners being confined there,
she felt her mind brought under concern on their account,
and in consequence wrote the following letter,
which being translated into their language, was soon after her return home,
conveyed to them.
Near the conclusion of this engagement she writes:

"`The present journey has indeed been memorable on several accounts,--in prospect,
the line of labour, and for the extension of holy help;
so that there is cause for continued trust in the arm of divine sufficiency.`"

[.embedded-content-document.address]
--

=== An Address to the French Prisoners at Kinsale

The love of the gospel having lately engaged me to pay a religious visit to Kinsale,
where by the sorrowful effects of that spirit which causeth wars in the earth,
yon have been cast into prison, I found my mind drawn towards you, my dear brethren.

Your situation claims the sympathy and attention of those who,
as they feel the influence of divine love,
are enabled to administer spiritual encouragement to others.
Your present circumstances are extremely affecting; you are detained from your friends,
and your native land; amongst strangers, and exposed to many difficulties.

Yet when we consider the kindness of that good Providence,
without whose sacred permission not a hair of our head falleth to the ground;
when we recollect that He is omnipresent,
watching continually over his creature man in every situation in life,
there is surely encouragement for each of us to trust in Him,
as a very present help in every time of need,
as well as a refuge and strength in the day of trouble.

My dear brethren, you may find Him in the prison as readily as if you were at liberty.
He is with the poor as well as the rich; for His abode is with the children of men.
His temple is the human heart,
and it is therein that the only altar is placed
on which acceptable sacrifice is offered to Him.

"`No outward obstruction need hinder us from finding him an unfailing helper;
and as we turn the attention of our minds immediately to Him,
He proves Himself all-sufficient for us.
Oh! how do I wish that every one of you may happily experience this to be the case.
A few years since, I paid a religious visit to some parts of France,
and I have comfort in believing there are many in that country
who are in search of that which alone is permanently good:
and being convinced that all the teachings and
doctrines of men fall short of procuring it for them,
they have inquired, as some formerly did of the Messiah,
'`Where dwellest thou?`' May all such wait for and accept the gracious answer,
'`Come and see.`'

Be assured, dear prisoners, that as this invitation is followed,
it will lead into liberty and enlargement from that state of thraldom
wherein the human mind is bound with oppressive chains.
By submitting to the Lord`'s call, we are converted from darkness to light,
and from the power of Satan unto God.
He causes us to feel that it is sin and corruption which separate us from Him;
and if we faithfully attend to the guidance of His Holy Spirit,
we come to experience the bonds thereof to be broken in us,
and know an introduction into the glorious liberty of His children.

Here is a privilege attainable even in your outward prison,
where you may sing to the Lord a new song,
because He doth marvellous things in and for you.
The great enemy uses every means to hinder this work,
and to chain the mind in the dungeon of transgression,
and plunge it deeper into sin and sorrow.
He tempts the unwary, especially in situations like yours,
to seek a temporary relief in things which divert from inward reflection:
the tossed mind flies to one false refuge after another,
which does not afford the rest it seeks; but leads gradually into a captivity that is,
at length, lamentably confirmed,
and the enemy gets full possession of the fortress of the heart.
Whereas, had there been attention given to the captain of the soul`'s salvation,
and obedience yielded to His commands,
the subtle adversary would have been repelled in all his attacks,
and prevented from obtaining the dominion.
Ah! my dear friends, I want you to be enlisted under the glorious banner of Christ Jesus.
I want you to be well disciplined in the use of those weapons which are not carnal,
but mighty through God to the pulling down of strong holds; casting down imaginations,
and every high thing that exalteth itself against the knowledge of God,
and bringing into captivity every thought to the obedience of Christ.

Under the impressions of divine love, a current of which I feel to flow towards you,
I invite you to Him who reveals Himself in the
secret of the heart--to His light--by which,
alone, you can discover the need you have of Him,
as the Saviour and Redeemer of your souls.
What a mercy it is, that in this glorious gospel day, none need say,
'`who shall ascend into heaven to bring Christ down from above,
or who shall descend into the deep to bring up Christ again from the dead;
for the word is nigh thee;`' the eternal Word of life and power,
inwardly manifested as a reprover for sin and a teacher in the way of righteousness.
He knows what instruction our several states require, and dispenses it accordingly;
affording sufficient strength to obey Him, and to follow His sure direction.
Now, how superior is this to all that man can do!
How ineffectual are those remedies which human wisdom proposes,
for the relief of the truly awakened mind!
How inadequate to the radical cure of that disease,
which a departure from the divine law has occasioned: thereby sin entered into the world,
and death by sin.
The divine life in Adam was lost by transgression,
and his posterity brought under the dominion of an evil seed, or enemy,
from which we all have need of redemption as well as he had, '`for as in Adam all die,
so in Christ shall all be made alive;`' all, who through faith in His holy power,
experience the blessed effects of His coming,
by suffering Him to accomplish in their minds the great work of transformation.
His name was called Jesus, because He should save His people from their sins,
not in them; so that, notwithstanding all that Christ Jesus has done and suffered for us,
and that His love is offered to us universally, we really know him not,
as a Saviour and Redeemer,
but in proportion as we are saved by Him from
that evil seed which leads into transgression.
As we submit to the operation of that power which effects the
one spiritual baptism of the Holy Ghost and fire,
the floor of the heart is thoroughly cleansed,
our lives and conversation become such as bring glory
to Him who created man for this very purpose.
May the convincing voice of Truth speak intelligibly to,
and engrave these most important subjects upon your hearts:
for surely the Lord is at work by His judgments, as well as mercies;
and it is high time for the people to learn His righteous law,
that so His glorious promises may be accomplished,
and the '`earth be filled with the knowledge of the Lord, as the waters cover the sea.`'

May the peaceable spirit of Christ Jesus and His pure government increase and spread,
and the day hasten when, all being gathered to His holy standard,
'`nation shall not lift up sword against nation,
neither shall they learn war any more.`' Oh! let
none of us obstruct this gracious design,
by hardening our hearts against Him; but let us submit to His holy government,
that we may experience an end put to sin,
and righteousness established in the place thereof.
Thus we shall, individually, know that Christ Jesus is indeed come,
not only as a Saviour universally, but as a Saviour and Redeemer in our hearts,
and that He is executing His powerful office there,
in order that He may proclaim everlasting victory over death, hell and the grave.

I am, in the love and sympathy of the gospel, your friend,

[.signed-section-signature]
Mary Dudley

--
