== Chapter X

[.chapter-synopsis]
* Visit to the Provinces of Ulster and Connaught
* Illness and consequent Journey to the Hotwells
* Family Visit at Waterford, from Second Month 1795, to Twelfth Month 1796

She was not long at home,
before the call of duty again summoned her to prepare for giving
fresh evidence of love and allegiance to her divine Master;
and although very delicate in health,
from the effects of a cold taken when last travelling,
she set out about the middle of the second month 1795,
on a religious visit to Ulster and Connaught; S. L. being united in the engagement.
They arrived in Dublin in time to attend a Monthly meeting there,
on third-day the 24th of second month,
after which my dear mother gives the following account of this exercising journey.

"`Life was low, and although several testimonies were borne,
if any '`mighty works`' were done I was insensible thereof.
I remember it is said,
that in some cities this could not be the case '`because of
unbelief.`' We left Dublin on fourth-day,
and got to Stramore sixth-day evening.

"`Seventh-day, the Quarterly Meeting held at Moyallen for this province commenced,
by that for Ministers and Elders being held.
The meetings on first-day were largely attended, as were those for discipline on second,
and the concluding meeting on third-day; but through all,
sadness was the covering of my spirit,
and I do not remember any season when more exercising labour fell to my lot;
but being mercifully relieved, though not refreshed,
I was thankful in renewedly experiencing the arm of holy help fully equal to support.
Even close doctrine is, with the people, preferable to silence;
the communion with their own hearts is closer work, therefore preaching,
preaching is still desired; but this is vain, and will ever be so,
if Christ be not raised.

"`Having felt my mind attracted in gospel love towards the inhabitants of Loughbrickland,
a little town about five miles from Lisburn, we went there on fourth-day morning;
and finding no place suitable for a meeting but the public worship house,
which the clergyman in a kind manner offered, we felt no objection to accept it.
A considerable number of Friends,
and a very large company of other religious denominations assembled,
about eleven o`'clock; a precious covering of solemnity was soon mercifully spread,
and we had occasion deeply to bow in prostrate
gratitude for the extension of divine assistance,
which was, indeed, memorably granted; and a hope was excited,
that all the bread that day distributed will not be lost.

"`Fifth-day we attended the usual meeting at Moyallen, to our relief;
and on sixth-day had a public meeting at Lisburn,
which was large and graciously owned by Him who
I trust prepared and called for the sacrifice.
An archdeacon and several others of the clergy attended,
besides many persons high in the estimation of this world.
I felt my bodily strength much exhausted, but was favoured with a quiet, easy mind;
and in the afternoon paid a visit to the Provincial School, to my refreshment.

"`First-day morning, the 8th of third month, we went to Lurgan meeting,
which proved a closely exercising season,
and left such feelings as made the prospect of another
meeting appointed for four o`'clock in the afternoon,
discouraging; the poor body seeming to have had enough.
However, we set forward to Portadown, a place where no Friends reside,
and found a great number of people waiting about the door of a large room at an inn,
which had been previously seated, and was soon much crowded, many also standing without:
yet there was a remarkable quietness,
and more liberty in proclaiming the gospel than is usually
felt in this day among the members of our own Society.
I was so weak and indisposed as to be unable to move forward, as designed, next morning;
but being better for a little rest, we set out on third-day,
and on fourth-day attended the meeting at Grange,
wherein deep anguish of spirit was my portion;
for although my heart and lips were engaged in prayer:
though I believed it the Master`'s will that the
children of the heavenly family should be visited,
yet such were my feelings, and so little way for relief appeared,
that I scarcely ever remember being so awfully and painfully instructed.
I was led to meditate on the great image, composed of various metals,
the efficacy of the little stone cut out of the mountain without hands, etc.
Some of these visions were opened, some sealed;
but after all my mind was so clothed with sadness,
that after meeting I hardly knew which way to turn.

"`However, as I had been previously exercised about Dungannon,
and the weather promised favourably, several Friends rode on,
and procured the Presbyterian meeting house,
where dear Job Scott held a meeting a few months before his death,
and at six o`'clock we assembled, and many hundreds with us.
In general the people were solid and attentive while the doctrines of the gospel were,
in received ability, a little opened, and I trust some instruction was sealed.
There seemed to me the piercing sense of a predestinarian spirit,
that which limits the pure principle, +++[+++the Spirit of Truth]
therefore the life; and so proportionate darkness covered the earth,
to penetrate which required proportionate help;
and it may be thankfully acknowledged this was mercifully afforded.

"`Several Friends kindly accompanied us on fifth-day afternoon from Berna,
whence we travelled over some very hilly road and through snow, seventy miles to Sligo,
which we reached on seventh-day evening.
First-day abode there at a good quiet inn,
and as a practice I have felt best satisfied with when not near a meetinghouse,
our little band had a season of retirement, which through favour proved refreshing.
Finding a removal hence clouded,
and the attraction to a meeting with the inhabitants increase,
our men Friends went to make inquiry respecting a place:
from different causes none could be procured that evening;
nine o`'clock next morning was therefore concluded on,
and the Presbyterian minister readily gave the use of his meeting house.
A large number of solid people attended,
who seemed disposed to receive the doctrines of Truth;
indeed I trust some bowed under its precious influence.

"`The labour in this meeting was of a truly arduous kind,
having to encounter that spirit which would limit divine grace,
and destroy the free agency of man.
The Lord was, however, mercifully near,
bringing to remembrance much that is written in opposition to this dangerous doctrine,
and confirming to the universal agency of the Spirit of Truth:
though in unfolding some of the blessed effects of this pure principle,
a belief attended that there were those present who marvelled, even like Nicodemus,
while taking upon them to be teachers,
without knowing the regenerating virtue of divine grace.
This principle offereth salvation to all,
and really bringeth it to every mind which is obedient to the heavenly vision,
as Paul was, who by his own declaration, did not confer with flesh and blood,
clearly implying that he could have done so.

"`Near the close of the meeting, the gospel seemed to flow freely to some seeking souls,
in the inviting language of our blessed Saviour, '`If any man thirst,
let him come unto me and drink;`' and in receiving the
books which were afterwards distributed,
many evinced their desire to know more of what this overflowing fountain is,
and where to be found.
Several clergymen and dissenting ministers were present,
and a very sensible presbyterian or seceder came to our inn, and invited us to his house;
he dined with us, and we had some free conversation,
wherein I trust no injury was done to the precious cause we are endeavouring to promote:
he told us that he took no money for preaching.
Several others called to see us, manifesting cordial regard,
and inviting us to their houses, indeed I have scarcely seen the like in these nations;
it reminded me of the disposition evinced in some foreign parts,
where the ground was measurably prepared for the seed,
and but few rightly qualified to sow it.
Oh! that for such the great Husbandman may arise in His own power and do the work.

"`We had intended proceeding that afternoon,
but found no suitable lodging place could be reached
timely and felt fully satisfied with our detention,
as if we had gone forward, the company of several who called on us would have been lost,
and perhaps part of the design of this visit defeated.
I think it was nine o`'clock when the last application for books was made.
My very soul cleaved to some of the inhabitants of Sligo,
and the remembrance of having been there is precious;
whether any fruit may ever appear or not.
We left it on third-day morning, purposing to proceed in a direct course to Roscommon,
but hearing on the way that the assizes were then holding,
and consequently accommodations at an inn not likely to be obtained,
we were obliged to change our plan, and went to Carrick on Shannon, where,
with much difficulty, we procured lodging.

"`I passed a night of very deep exercise, and little sleep,
so great a weight of darkness and distress covered my mind as I could not account for;
and very earnestly did my spirit crave that preservation might be vouchsafed.
In the morning I saw not which way to turn,
the track which had presented being of necessity diverged from, and when,
on examining the different directions of the roads,
one was pointed out as the nearest way to Moate, all seemed dark thereon,
though I knew not why; but when another, the least eligible as to appearance,
was mentioned, I felt satisfied to proceed on that.

"`As we went on I became less oppressed, until drawing near a town,
when the previous baptism to a bitter cup so affected my spirit, that,
by the time we arrived at the inn,
I was not left in ignorance respecting the line of duty which awaited me here;
and finding a very large room, and the landlord kindly disposed to accommodate us,
our men Friends soon went to work,
and had a laborious task in circulating the invitation,
nor did much encouragement appear respecting the attendance.
A very large company, however, assembled,
which it was difficult to get even into outward stillness,
so that although the burden of the word, rested,
it could not be cast off without frequent interruption,
owing to the unsettlement of the people;
which I suppose arose from the novelty of the circumstance,
as we cannot trace that a meeting was ever held there before by Friends.
Yet notwithstanding the difficulty of stepping on such untrodden ground,
and the awfulness of the labour, Truth was mercifully raised over all,
so as to chain down the rebellious nature,
and afford strength to discharge apprehended duty.
I trust there were some who assented to the importance of that work which
all their own creaturely willings and runnings could never effect;
so that if no more good was done than a little
ploughing up the fallow ground of Strokestown,
even that may prepare the way for some`' other labourers more
readily and availingly to enter into the field.
Though nearly all the inhabitants are Roman Catholics,
yet many applied for books after some had been distributed.

"`We passed through several other places with only secret travail of spirit,
and reached Moate fifth-day night, where we remained over first-day,
which was one of laborious exercise.
In the forenoon we sat with Friends, and had a large public meeting in the evening,
but through the renewings of holy help relief of mind was obtained.

"`Second-day we proceeded to Athlone, and procured the use of a Methodist meeting house,
wherein a large number of the inhabitants assembled at six o`'clock,
and though from the number, and various descriptions of persons, there was,
as might be expected, a difference in conduct,
I think it may be thankfully acknowledged that Truth was in dominion;
and we felt a hope that all the labour would not be lost, but to some,
instruction be profitably sealed.

"`We went the following day to Roscommon,
where the use of the Sessions-house being obtained,
we had notice circulated and a large attendance that evening.
The minds of many seemed like ground never broken up,
and for a while the unsettlement and confusion were trying;
but considering the ignorance and bigotry of the major part of the audience,
there was as much quiet as we could look for,
and great cause for thankfulness that a cup bitter in prospect and possession,
was mercifully sweetened by the feeling of relief.

"`In our way from Roscommon we stopped at Lanesborough,
where being sensible of inward exercise, and no clearness in proceeding,
we made inquiry for a place to hold a meeting,
but we were informed that no large room could be had, which,
with finding the inhabitants were mostly Roman Catholics, tended to discourage us.
However, as the pressure continued, we had a parlour at the inn prepared,
and notice spread, and in a short time had the room, passage, etc. crowded;
and I think there was in this poor place,
among a people who are kept in darkness by those who profess to be their guides,
as much liberty to declare the way of life and salvation,
as in many places where light seems to have more apparently made its way.
Many were solid, and I doubt not sensible of good impressions;
for which favour our spirits bowed in humble commemoration of divine goodness.

"`We reached Ballymahon that night,
where the clergyman of the parish readily gave
the use of the worship house for a meeting.
This town is mostly inhabited by Roman Catholics,
so that it was not expected many would attend;
but a large company of that description came, as well as most of the Protestants,
and among them the minister who gave us the house.
An arduous fine of labour fell to my lot;
it was truly like going forth with the gospel sword, if I was ever intrusted with it,
against those structures not reared by divine power.
Although the extreme ignorance of the people caused the work to feel heavy,
it may indeed be gratefully acknowledged,
with that praise which belongs to the glorious Author of all good,
that help was mercifully proportioned; and even while the enmity was evidently raised,
the Lord continued near to support and strengthen for the discharge of apprehended duty.

"`I hoped after this meeting that I might be excused
from any further service in poor Connaught,
and felt satisfied to turn towards the Quarterly Meeting at Mount Mellick.
I was much indisposed and in want of rest,
but struggled to keep up during first and second-days,
which caused me to have more suffering afterwards,
and I was unable to attend the concluding meeting on third-day, the 31st of third month,
being wholly confined to bed.
A few days nursing and kind care tended to recruit me,
so that by the end of the week I was able to go out among my friends,
and on first-day attended both meetings.
In these close exercise and labour fell to my lot, under the oppressive sense,
that the lamenting language of the great Master
is painfully applicable in the present day,
'`Oh!
Jerusalem, Jerusalem, how often would I have gathered thy children,
even as a hen gathereth her chickens under her wings,
and ye would not.`' Deeply did my spirit feel with our honourable friend Mary Ridgway,
who having long laboured in this part of the vineyard,
yet reaps little in an outward sense but sorrow; her everlasting reward, however,
is sure, and she seems so low and sunk in strength,
that I should not be surprised if this soon awaited her.

"`We left Mount Mellick on second-day morning,
and had a meeting in the Assemblyroom at Tullamore that evening,
and one in the Sessions-house at Maryborough on fourth,
proceeding to Durrow on fifth-day evening.
I felt attracted to Ballinakill, about three miles distant,
whither we went on sixth-day morning, and an invitation being circulated,
the few Friends residing there, and a quiet company of other denominations,
assembled with us about twelve o`'clock.
These meetings were all satisfactory,
and attended with a consoling hope that some would
retain the impressions they were favoured to receive;
many manifested great cordiality towards us,
and the applications for books were numerous.
The number belonging to our Society is small, but among these some feeling was evident,
and good near, to stir up the pure mind, even in such as had too much rested in the name,
without striving to experience the nature of vital Christianity.
From Durrow I should have gladly proceeded home some other way than through Kilkenny,
a place I have long felt about, and the prospect of which is now renewedly exercising,
but I believe it would be unsafe under present
pressure not to attempt having a meeting there.`"

The meeting in prospect was held on first-day, and proved a solemn relieving opportunity;
after which my dear mother felt easy to retreat from this engagement,
wherein she had been diligently occupied for about eight weeks,
and with her husband and several friends who met her at Kilkenny,
returned to Clonmel on second-day, the 13th of fourth month, peaceful in mind,
but with diminished strength of body.
The following was written under a review of this journey.

"`As to any little effort of mine to promote the glorious cause of Truth,
and the advancement of the spiritual kingdom of life and peace,
it is not worth entering upon.
Yet as the object is considered abstractedly, as the power, not the instrument,
is kept in view, I hope that in all humility the thankful acknowledgment may be made,
that although the line of service recently allotted has been very trying, humiliating,
and awful.
He who putteth forth has fulfilled His own promise,
and mercifully proportioned strength to the conflicts of the day;
superadding to the support immediately extended,
the encouraging belief that His gathering arm is reached,
and reaching forth to the workmanship of His holy hand;
and if the labour of the poor instruments go no further than the mission of John,
and prepare the way for greater breakings forth of light, let us be therewith content,
and faithfully do our part, leaving the issue to divine wisdom.
I have never been in any part of these nations where the ground seemed so unbroken,
as in some of the places lately visited, especially in Connaught,
nor have I been more sensibly convinced than during this engagement,
that light will break forth,
and the darkness which now covers the earth disperse by its glorious arising.`"

Notwithstanding her having a hard cough, and evident symptoms of pulmonary affection,
she went from home again in about two weeks to attend the Yearly Meeting in Dublin,
and as usual, took an active part in the concerns of that interesting season;
she also attended a few meetings in her return,
though struggling with an increase of indisposition from repeated colds,
and on arriving at her own house was so unwell as to render close confinement necessary.
This, however, and skillful medical attention, failed to produce the desired effect,
and in a few weeks she was advised to try the Mallow waters,
as a substitute for those of the Hotwells,
being unwilling to undertake so long a journey unless deemed absolutely needful.
After spending a month at the former place,
her complaints assumed so alarming an appearance,
and the reduction of strength was so rapid,
that her affectionate husband was not satisfied longer to delay resorting to those
means which in earlier life had proved beneficial to his beloved companion.
To herself, and many of her friends,
it appeared scarcely warrantable for her to undertake such a journey,
nor did she anticipate the result so fondly desired by her near connections;
rather looking to the disease which then affected her,
as one designed to bring down the poor earthly tabernacle,
and centre her immortal spirit in everlasting rest;
and the entire quietness of mind with which she was favoured,
tended to encourage this prospect.

Still she did not oppose the wishes of her husband,
and early in the eighth month she set out with him and her two eldest daughters.
They sailed from Waterford to Milford, and afterwards travelled slowly to Bristol;
the dear invalid bearing the voyage and journey
even beyond what they had dared to expect;
and after spending six weeks at the Hot-wells,
the improvement in her health was such as to afford strong hopes of ultimate recovery.
Her native air and the waters were so salutary to her lungs,
that the cough gradually abated, and her strength was renewed.
When the time for remaining at the wells was expired,
she passed some weeks at the house of her beloved friends John and Margaret Waring,
attending meetings in the city and neighbourhood of Bristol,
and enjoying the society of some old and intimate friends;
and although not from home on the ground of religious concern,
there is reason to believe that her company and ministerial
labours were productive of spiritual benefit to many,
both in and out of our Society, amongst whom her lot was cast at that time.

Near the end of the year she returned to Ireland,
so far restored in health as to give expectation of her being
strengthened for continued usefulness in the church.
Nor was it long before her dedication to the best of causes was again evinced,
for in the second month 1796,
she applied to her Monthly Meeting for a certificate to
visit the families of Friends in Waterford and Ross,
expressing her belief that some more public service
would also be required of her in those places.
After being awhile closely occupied at Waterford, she wrote as follows:

"`The work is truly a laborious one,
I think more so than any of the same nature heretofore has proved.
Life is, in the general, low, and yet such a renewed visitation is sensibly extended,
even to '`strengthen the things which remain,`' lest they utterly die,
and the exercise so expands in families, that we have sometimes to divide,
and take the different parts separately.
After some visits,
my poor frame is so sunk that I thought I should be
scarcely able to continue throughout the engagement,
though bound in spirit to the service.
I am indulged with a truly dear and very suitable companion in Margaret Hoyland,
who is evidently fitted for the work, and employed in it,
in what I believe the fulness of time.

"`The line does not seem circumscribed to those in membership,
and I continue to feel my mind attracted to several who
attend our meetings with honest inquiries,
'`what shall we do?`' etc.
Among these are a family, respecting whom I had no knowledge or information;
but while in meeting the day after I came here,
my heart was drawn into such a feeling of secret sympathy with two genteel looking women,
who sat solidly opposite the gallery, that I was ready to marvel,
not knowing by their appearance whether they had any connection with Friends or not.
At length I became so exercised, that the work in them might be carried forward,
and the new creation perfected, that vocal supplication was offered,
and inquiring after meeting respecting them,
I found they were a widow Ussher and her daughter,
and that they had constantly attended meetings for several months past.
I spoke to them on going out of the meeting house, and they cordially to me;
since then we have seen more of each other; they are indeed a wonderful family,
and the more I know of them, the more my heart is attached to them.`"^
footnote:[This Friend, Elizabeth Ussher,
was afterwards well known as an acceptable minister in our Society,
she and three daughters having joined it by convincement,--See
"`Ussher`'s Letters,`" printed in Dublin,
1812.]
After she and her companion had visited the few families in Ross,
she thus relates a circumstance which occurred there.

"`I sat the meeting under unutterable exercise;
dear Margaret Hoyland was engaged to minister to a state,
for which I then believed I was going through
such a baptism as I have seldom experienced,
and feeling, (as I apprehend,) a clear direction how to act, when the meeting terminated,
I requested that two men who had sat solidly, but were total strangers to me,
might be invited to our lodging; they willingly came,
and a time long to be remembered ensued.
One was the same person for whom I felt in my last visit to this place,
but whose countenance I did not know:
they are both evidently under the care of the great Shepherd,
but much tried on different accounts.
We sat and parted under such feelings as I have no language to describe,
and for this season alone I could bear to be separated from my nearest connections;
but we have reason thankfully to believe, that so far, our steppings have been right;
may future preservation be mercifully vouchsafed.`"

An account of a public meeting held at Waterford was thus given by a
Friend who had been her companion in part of this engagement,
and kindly wrote to her husband when she was prevented doing so by indisposition.

[.embedded-content-document.letter]
--

"`The house was nearly full, and those assembled behaved with becoming solidity;
the covering of good was soon felt, and after dear Mary had appeared in supplication,
she was largely engaged in the exercise of her precious gift;--on the
propriety of women`'s preaching,--against an hireling ministry,--and
in describing the universality of the grace of God.
It was a solemn, open season, and though as thou mayest suppose, she was much exhausted,
yet the sweet incomes of that peace she goes through so much to obtain,
were not withheld, but sweetly partaken of,
the Lord rewarding liberally for such acts of dedication,
and afresh inciting to confidence and trust in Him.
In the family retirement at our lodging in the evening,
she was again drawn forth to address some individuals in a very particular manner;
it was a time of sweet refreshment in which most present were tendered,
and I hope the sense of heavenly regard which then
prevailed will not soon be forgotten by some of us.`"

--

Near the close of this service my dear mother wrote as follows:

"`I feel unable to do as much in this line as I once could,
nor am I even qualified to keep any little sketch of what I go through from day to day,
as if all that is once`" passed was gone from my remembrance,
by fresh exercise continually occurring;
so that the poor vessel is kept in a state of quiet emptiness,
except when any thing is put into it for others,
which for a season refreshes and sweetens.
As to the earthen vessel, it is sensibly weakened,
yet I expect it will hold a while together, till not only this,
but what may still remain is done;
and truly my mind is humbled under a sense of unmerited regard,
and my own utter inability to move in the line of gracious acceptance,
without deep preparatory baptisms and renewed help,
and this having been almost marvellously extended,
I again feel stripped and unclothed of any strength.
If these are some of the mysteries,
attendant on the awful office which some apprehend they are appointed to,
then may the hope be safely cherished that, however hidden their life,
it is with Him who in his own time will again and everlastingly arise,
and they also partake of his glory.`"

She returned home in time to attend the Quarterly Meeting held at Clonmel,
in the fourth month, and early in the sixth month, she again left her own habitation,
to fulfil some prospects which had not been accomplished in her late journey;
among these were public meetings at Dunmore, Enniscorthy, and Ross,
respecting which she observes,
"`that though deeply exercising from the ignorance of
spiritual worship and want of true settlement,
which were generally obvious, yet faith being mercifully granted,
and holy assistance renewed,
ability was afforded to preach the glad tidings of salvation through Jesus Christ,
as the way, the truth and the life.`"

She also attended the Quarterly Meeting for Leinster Province,
and several meetings for worship and discipline in the county of Wexford.
In some of these services she had the acceptable company of her dear friend Mary Watson,
and after being laid up some days at Waterford with a
distressing complaint in her head and face,
returned home with a relieved and peaceful mind,
a short time before her own Quarterly Meeting held at Limerick;
where after attending that solemnity, she felt bound to sit in the families of Friends,
and in a letter written to her husband while thus engaged, makes the succeeding remarks:

"`I can afresh say it is well to follow the pointings of duty and stand in resignation,
for although the poor body is considerably exhausted,
my mind is mercifully relieved beyond what is usually the case with me;
so that I have reason to commemorate the unmerited regard of Him who leads about,
graciously instructs and encourages to confide in His holy sustaining arm.`"

After returning from this visit,
she was mostly at home during the remainder of this year;
the latter part of which was signalized by some very afflictive circumstances,
under which her body and mind were at times brought very low;
yet being supported by Him who had long proved her refuge and strength,
she was enabled instructively to manifest that
those who trust in the Lord are not confounded,
but in the permitted, as well as appointed, trials of their day,
find His grace sufficient for them,
and the spirit of humble resignation equal to counteract the effects of human weakness.
