== Chapter XI

[.chapter-synopsis]
* 1797+++.+++ Attendance of Yearly Meeting in London
* Dangerous illness of her Husband
* Visit to the County of Cork, etc.

In the spring of 1797,
my beloved mother believed it best for her to attend the Yearly Meeting in London,
which she did to the relief and comfort of her mind,
spending a little time in Bristol on her return.
While absent on this journey she writes as follows:

"`Though not professedly out in the service of Truth,
I think it may be truly said I am not spending idle time;
every day seems to bring its work with it, and some meetings,
and more private seasons of retirement have been peculiarly marked by the
covering of solemnity and the cementing influence of divine regard;
so that while I feel myself a poor creature, I have renewed cause,
thankfully to acknowledge gracious help,
and depend upon the leadings of an ever worthy Master,
who does not forsake in the needful time.`"

Soon after she returned home,
her affectionate feelings were called into painful exercise by
her husband`'s having a dangerous fall from his horse,
which occasioned an illness that for some time threatened his life;
and the anxiety and fatigue which she underwent at that season
produced an indisposition of the bilious and gouty kind,
the effects whereof greatly tried her constitution for several months.
She had, however, the comfort of seeing her beloved partner gradually restored to health,
and they were both benefited by spending some time at the sea-side,
first at Tramore and then in Youghal.
At both these places David Sands of America was a good deal with them,
and towards the end of the year my dear mother united with this
Friend in some religious service in the city and county of Cork,
being also accompanied by her niece, Hannah Grubb,
who during this journey first appeared as a minister.
The following extracts from her letters contain an account of the engagement.

"`Fifth-day was the Monthly Meeting here; until the previous one for worship,
David Sands had been a silent travailer in every meeting,
but in that he was exercised in a close line,
comparing the people to sheep who had been richly fed, and walked in good pasture,
but had not become strong, nay, were sick, and some even in danger of dying;
but yet he felt a few were alive, to whom he ministered encouragement.
I felt inclined to take my little certificate to the men`'s meeting,
and had it read while there, which opened my way among my brethren to my own relief.

"`First-day evening we appointed a public meeting which was largely attended.
I had to revive the gracious invitation of the Saviour of the world,
'`If any man thirst let him come unto me and drink,`' and doubt not
the love of Israel`'s Shepherd was then afresh extended,
for the gathering of the people from the shadows to the substance of religion.
David Sands was engaged in the unity of feeling,
and though we have no report of mighty works being done,
I trust that profit was sealed upon some minds.

"`I had a view of going to Kinsale while in these borders,
but being very much indisposed it seemed unlikely I should be able to
unite with David Sands who was going on fourth-day night;
yet feeling inclined, Hannah Grubb and I went next morning in a close carriage,
and reached Kinsale time enough for the meeting, which was appointed for eleven o`'clock,
but the people coming in irregularly the house was not filled for nearly an hour.
Several appeared very light, conversing, etc., but after deep, laborious exercise,
there was more settlement and some relief obtained.
David Sands was enlarged in testimony and supplication,
and in endeavouring to do my part of the business, I found to my humbling admiration,
the truth of that assurance,
'`as thy day so shall thy strength be,`' even as to the body,
which was made equal to required exertion.
Another meeting was appointed for the evening,
which I had almost given up the prospect of attending, but,
being recruited by a little rest, went again; the house filled,
and some solid people were among the multitude, to whom David was largely opened,
in a manner _teaching_ to their states.
A portion of labour also fell to my lot,
and I trust the precious cause was rather magnified than hurt, by these opportunities,
and some minds measurably gathered to a state of true waiting.
But oh! the labour that is requisite to have
even so much of the way of the Lord prepared;
and how few comparatively are in a state of fitness to
receive even the messengers in the previous mission,
or baptism, for the Master`'s appearance, the revelation of his power and spirit.
Darkness seems to cover the earth, and gross darkness the minds of the people,
so that every step is like working with the plough to
gain an entrance for the seed of spiritual doctrine;
but, if the labourers perform their assigned part,
all afterwards ought to be resolved into the hand and
further operation of the great and powerful Husbandman,
in faith and patience.

"`I hope I have done with anxiety on this head; I neither look for much, if any,
fruit from my little exercises,
nor conclude I am right or wrong from the voice of the people.
Oh! how unavailing are all voices but that of gracious acceptance,
and when this is through unmerited mercy afforded,
what a stay is it found amidst the fluctuating spirit or language of the world, yea,
of those who are in degree, but not altogether, gathered out of a worldly spirit.

"`This last meeting held above three hours,
so thou mayest conclude our bodies wanted rest, which we obtained at a good inn.
In the morning I found David Sands inclined for Milltown, which I felt easy to turn from,
but before leaving Kinsale had a memorable season with
the landlady and three single daughters.
Their minds were remarkably tendered,
and so opened in love to us that they constrained us to accept some refreshment,
after which we left them and the place in peaceful poverty.

"`After dinner at a Friend`'s, where was a pretty large company,
and several young people,
a precious and remarkably solemn covering was mercifully spread as a canopy over us,
and rather singular enlargement experienced in the line
of close communication to different individuals.
The settling power of Truth prevailed in no small degree,
leaving a savour that remained during the evening, which I spent in their company.
Yesterday I joined in a visit paid by appointment to
two young women received into membership,
which was a solemn, relieving time to my mind:
as I have thankfully to acknowledge several have proved,
so as to leave no room to question that my being here has been,
and I hope continues to be, in providential direction,
though my body feels greatly reduced with exercise.

"`After we had sat awhile in meeting on first-day, William Savery unexpectedly came in,
and near the close said,
that he felt as he often did when in meetings with his brethren and sisters,
not having much to say, except that he wished them well,
and that if they were not admitted to the communion table, the supper of the Lamb,
it was not because they were not the bidden guests,
but because they were in the same state as those formerly bidden, not ready,
being full of, or employed too much about, things lawful in themselves,
but pursued to the hindering their acceptance.
On concluding, he desired a meeting with the inhabitants in the evening,
which proved a very large assemblage of most ranks, who behaved with quiet attention.
William Savery was largely opened on the past and
present state of the visibly gathered churches,
describing where the departure from genuine religion had crept in,
and through what means it must be restored to its primitive state, etc.
David Sands also stood some time.
The following day we went together to the Foundling Hospital, where,
there were about two hundred children collected, to whom, with their masters,
we all three felt and expressed a salutation of love,
and the season was one of divine favour,
as was another more select sitting in a Friend`'s family after tea.

"`Yesterday the week-day meeting was unusually large, and proved, to my tried mind,
the most relieving of any since my coming here;
though the labour was of a truly close and exercising nature,
which if I apprehend rightly, was what the states of the people called for.
Dear William Savery followed in harmonious supplication,
and the meeting terminated under a solemn covering.
In the evening another public meeting was held, which was large and pretty quiet,
though some of the company appeared thoughtless and unconcerned,
and perhaps from a longer silence than before, in degree impatient;
but while William Savery was engaged in speaking they were attentive,
and he was enabled excellently to comment on the superior nature of divine wisdom.
His openings were not only clear, but attended with religious authority;
so that I do hope it was a season of instruction to some,
though after the closing of this weighty communication
an unsettlement succeeded and many withdrew.

"`I am to day sadly indisposed from fresh cold, and can hardly stoop to write,
though mercifully supported in the path of duty;
but as William Savery intends being at Clonmel by first-day,
and seems particularly to wish me to meet him,
I at present purpose endeavouring to do so,
and hope to reach home some time on seventh-day.`"

This prospect she was enabled to fulfill,
arriving at her own house a few hours before
this valuable fellow-labourer William Savery,
whom she was glad to receive and entertain,
as he was to be in the company of one whom he esteemed a mother in the truth.
She accompanied him in his public service within those borders,
and after being together at a meeting in Carrick, they separated;
he proceeding to Waterford, and she returning home,
whence she pretty soon went again to Cork,
and after attending the Quarterly Meeting held there in the first month,
had public meetings in several places which she had felt about when there before,
viz. Blarney, Passage, Glanmire, and Milltown,
also one appointed for the inhabitants of a particular district in the city.
All these meetings appear to have been satisfactory and relieving,
as may be inferred from the following observations written at the close of this journey.

"`Through the mercy of Him who hath never failed
in the needful time to supply every want,
ability was administered to proclaim the doctrines of the gospel,
for the reception of which I believe some were prepared;
and it is a renewed encouragement to trust in the arm of holy help,
that at intervals the power of Truth preciously prevailed,
so as to still the minds of the people, for which my spirit bows in thankfulness.
I begin very sensibly to feel the effects of such exercise,
and am at present quite hoarse; but I expect shall be relieved,
if there be occasion for so poor a creature to be employed,
in vocally advocating a cause, the promotion of which is, if I know my own heart,
dearer to me than my natural life,`"
