== Chapter XIV.

Religious Visit to some parts of Leinster and Munster--Illness in the family,
and death of her Husband and Son.
From Second month, 1805, to Twelfth month, 1807.

In the second month, 1805,
she obtained liberty from the Monthly Meeting for the performance of
some religious service within the limits of her own Quarterly Meeting,
and at Ross, in the county of Wexford;
respecting which the following particulars are extracted from her letters and memoranda.

"`Youghal, Second month 9th, 1805.--The meeting here on fourth-day was a solemn,
relieving season, rather unusually so.
Several not in profession with us were there,
and I ventured to appoint a public meeting for next day, which was a very favoured time.
Those present behaved solidly,
and were of a description towards whom much liberty was felt in preaching the gospel,
and for whom I trust prayer was acceptably made.
I was more than satisfied, as I have had cause to be, through gracious unmerited regard,
at different seasons, since coming here.
A solid young man who has attended meetings for a year past, was with us last evening,
to my comfort, and I hope his also.

"`Yesterday, the 18th, was fully occupied with two laborious meetings in Cork,
the first unusually so.
Many of different religious denominations were present at the second meeting,
but I felt excused from appointing one of a more public kind, which I esteem a favour;
the time was altered an hour, as the morning meeting held long.
This day the meeting at Castle Martyr was held at twelve o`'clock,
in a room over the market-house.
I was relieved by this opportunity with the people,
though the veil which seems indeed thick over the minds of many,
causes the labour to be hard, and at times attended with but little hope.
Yet if the line of duty so open, it ought to be simply followed,
and the help mercifully vouchsafed is enough to stimulate to steady obedience.

"`The meetings at Glanmire and Middleton were satisfactory,
and as the inhabitants of Riverstown were invited when that at Glanmire was held,
relief of mind respecting that place also was obtained;
and visits to some public institutions in the
neighbourhood were also productive of peace.

"`Third month 7th, left home for Waterfbrd,
and on the 8th attended the usual meeting there,
a very low season to the travailing seed.
10th. A suffering meeting, but through an acceptable testimony life was a little raised,
and supplication poured forth.
Several solid persons came to the afternoon meeting, which was a time of some relief,
but the views being too much outward, tended to check the rising of the pure spring.

"`On the 11th, went to Ross, sat in the families of Friends there,
and on fifth day had notice circulated of a public meeting at eleven o`'clock,
to which an apparently seriously company of the genteeler class came.
It was a memorable season indeed; a precious solemn influence being prevalent,
and much liberty felt in proclaiming the way of life and salvation.
At the conclusion of the meeting, Friends were desired to remain,
and a time of relief ensued with them collectively.

"`This long impending visit to Ross was comfortably accomplished,
and I left the place peacefully,
under the consoling belief that the Lord is
raising the standard of His power in many minds,
by bowing to which some who were not a people are become His,
and bringing forth fruits acceptable in His holy sight.

"`Returned to Waterford on the 16th,
and next day sat a low suffering meeting again with Friends there.
Oh! the want of that spiritual exercise which would bring down the blessing,
not only upon the head of Aaron, but every class of the people.
In the afternoon meeting, the remembrance of Elijah`'s sufferings was awful,
yet encouraging to the partakers of his spirit;
and liberty was felt in saluting this description of the people,
under a view of what the ministry, the state of eldership, yea,
of all called to active service in the church, should, and might be.
Close doctrine also flowed to the worldly-minded, the supine and unwatchful in spirit;
but with how little hope does the poor servant sometimes labour,
having as it were to plough up as he goes over the ground-,
instead of finding it in a softened, prepared state.
Faith was, however, renewed, and the reaching forth of a love precious to feel,
led to the appointment of a public meeting for the following evening.
This was largely attended by persons of various professions,
and ability mercifully extended to proclaim the doctrine of
free and universal redemption through Christ Jesus.
Somewhat of a different spirit was to be felt,
even a degree of that which leads to a judging and reasoning
down the simplicity of the pure unchangeable gospel.
But while the mysteries of the everlasting kingdom are hidden from the wise and prudent,
they are still revealed unto babes, the humble and the contrite;
a precious remnant of whom could be saluted in the prevalence of love and life,
and at the conclusion praise waited in Zion and
thanksgiving was poured forth in the congregation.

May the vessel,
(altogether unworthy of such refreshing influence,) be preserved by Him who
can only keep it in sanctification and fitness to receive renewed fillings,
or bear resignedly the emptyings which infinite wisdom may appoint,
that the Lord may be all and all for evermore.
Amen and amen!

"`Third month, 21st. Left Waterford for Pilltown,
where a meeting was held at twelve o`'clock.
It was attended by a considerable number of serious Protestants,
and a few Roman Catholics, and proved a time of remarkable solemnity.
The people appeared to be measurably acquainted with the nature of spiritual worship,
so that way readily opened for the gospel message,
which through the renewings of holy help was
proclaimed to some happily alive to its power.

"`The succeeding day there was a meeting in the village of Portlaw,
with a large company of very quiet orderly people;
many having left their ploughs and other
employments to come at the invitation of Friends.
This season was also memorably owned by the spreading of the holy wing, and my spirit,
with that of others present, bowed in thankfulness to the author of all good.
A clergyman who was at the meeting came afterwards to see us,
and expressed satisfaction at having been there;
making observations which affected me greatly,
as evidencing an increase of that glorious light
which is opening the spirituality of religion,
where education and long habit had strengthened prejudice against It.

"`I returned home next day, the 23rd of third month, and was favoured to find all well,
which I had been helped to leave under the great Shepherd`'s care,
to whom be the praise of His own works, and conducting, preserving goodness,
now and for ever!`"

Soon after her return home,
my dear mother became indisposed with an affection of the lungs,
and was wholly confined for several months,
during which time she was brought very low both in body and mind;
several afflicting circumstances in her family, and the circle of her friends,
combining to mark the remainder of this year, and nearly the whole of the following,
as a period of peculiar trial.
For many months her own habitation presented a scene of sickness and sorrow,
she and her daughter Hannah being ill at the same time,
and confined in separate chambers, unable to see each other,
and for a while with but little prospect of either being restored.

In the sixth month 1806,
a bitter cup was administered in the decease of my dear brother Robert,
who had resided for some time at a distance from his near connexions;
and being removed after only a few hours illness, the stroke was indeed heavy,
and as such keenly felt.

He was the last of five sons whom she had taken the charge of on her marriage,
and being the first who addressed her by the endearing appellation of mother,
and very affectionate in his behaviour, he had always been peculiarly near to her;
though her love and tender care were uniformly manifested towards each of them; while,
on their part,
an attentive and respectful demeanour has frequently induced her to observe,
with grateful emotion,
that she never desired more affectionate or dutiful conduct from her own children,
than what she received from some of her adopted sons.

When she had herself become a parent,
she was so circumspect in preventing any discernible difference,
that it was not until after the death of several of the former family,
the younger part had any idea that such a distinction existed.
She found one of her husband`'s sons far gone in a consumption,
who died the year after her marriage at about the age of thirteen years;
and another sweet youth was taken off before he attained that of twenty.
The eldest, a valuable religious character, married agreeably,
and seemed likely to possess length of days, but being attacked with rheumatic fever,
his constitution rapidly sunk,
and exactly fourteen weeks from the day of his
marriage his remains were consigned to the grave.
These three she had the satisfaction of attending to the last,
as they all died under the parental roof,
and bore ample testimony to the tenderness and unremitting care of their anxious mother.

Nor was this less the case with one who lived many years longer,
and experienced her kind and efficient help under a suffering and tedious illness,
which at length terminated in his death in the year 1801, at Clifton.
When informed that his little children were taken charge of,
in order to set his wife at liberty to visit and stay with him,
he spoke of this last act of his dear mother`'s as crowning her invariable kindness,
and calling forth from him lively feelings of gratitude.

In the third month 1807, she spent a week or two in Cork,
feeling bound to sit a few meetings with Friends there,
and also to encourage some who were appointed to perform a
family visit by joining in a few of the first sittings.
She afterwards obtained from her own Monthly Meeting a
certificate for some religious service among Friends,
as well as those of other professions in Leinsler and Munster,
and after attending the National Yearly Meeting in Dublin,
had a public meeting in that city, and thence proceeded to Mount Mellick.
Her friend Jane Jacob was united with her in this engagement,
of which the following account is transcribed from my dear mother`'s letters:

"`In the meeting at Mount Mellick on first-day morning,
a lively offering was the means of raising life,
and opening the way for my relief in a considerable degree.
The afternoon meeting was not so large as it might have
been if Friends had a little more faith;
but fearing the people could not be accommodated they
were too confined in the notice they circulated,
so that although a solid time, it was not so fully relieving as I wished.

"`The meeting at Portarlington on second-day was
one worthy of being remembered with gratitude;
and one at Maryborough, held in the Sessions-house, on fourth-day evening,
was uncommonly large, quiet, and mercifully owned by the precious influence of good,
A large portion of vocal exercise fell to my lot,
and the attention evinced while the doctrines of the gospel were unfolded,
encouraged the belief that in many hearts the ground is
preparing for the reception of the heavenly seed.
The season terminated with humble acknowledgment of the Lord`'s continued favour;
many looked at and spoke to us so kindly, that it was manifest they received us in love.

"`The usual meeting at Mountrath was deferred to twelve o`'clock on fifth-day,
and an invitation circulated among the inhabitants; many solid persons attended,
and He who prepareth the heart, and from whom is the answer of the tongue,
strengthened for the work which He required.
At the conclusion, such as were in profession with us were requested to remain,
and a time of labour succeeded which proved relieving to my mind.

"`Sixth-day we went to Rosenallis, where a barn had been nicely fitted up,
and a meeting appointed lor the evening.
It was nearly filled, principally with those of the labouring classes,
while some few of a different description were present;
and though it is not remembered by any Friends here
that a meeting has been held in this place before,
yet the manner of the people sitting,
was like those who were well acquainted with silent waiting.
Their minds felt in such a prepared state,
that it was no wonder a gracious provider should see
meet to afford something for their refreshment,
which I trust was the case;
and the labour was attended with a hope that it would not be all in vain.
The manner of their withdrawing from the meeting was solemn, and I heard no word spoken,
nor saw any one even whispering: a good lesson for us after solid meetings,
to keep in quiet and digest what hath been given.

"`The morning meeting at Mount Mellick on first-day, the 17th of fifth month,
was exercising as to what appeared my duty in it.
I had hoped that the meeting, though thinly attended the week before,
would have relieved me without a second attempt;
but at the close of the morning meeting I found otherwise,
and therefore had notice given of one for six in the evening,
which with one held in a Methodist meeting-house at Monastereven, was large,
and both proved solemn and relieving seasons.
Feeling my heart attracted to a small place called Castletown,
where many genteel people reside, a few Friends went to try for a place;
but no suitable one presenting,
I felt desirous of information being circulated in the town
that a meeting would be held in our meeting-house at Mountrath.
This answered the purpose, and we were favoured with a very precious opportunity indeed,
many coming from Castletown a mile and a half distant,
and some from a mile or two beyond it;
and I believe the gospel message was thankfully received, under which feeling,
and after solemn thanksgiving, we parted.`"

On her way home she had a meeting at Kilkenny, which tended to her further relief;
and in the sixth month she again set out with the same companion for Limerick,
joining her beloved friends Deborah Darby and Rebecca Byrd, in a public meeting at Caber,
and another at Tippernry, on the way.
In Limerick she felt bound to visit the families of Friends,
respecting which service and other religious engagements, she thus writes:

"`The path of public meetings is trying, but family visiting is the hardest by far.
Ah! it is lamentable to feel how the precious seed is oppressed almost every where,
while many who have not our privileges would
thankfully partake of even the least of them.

"`The meeting on first-day evening was largely
attended by the upper class of inhabitants,
several clergymen, the mayor, recorder, etc. being present.
It was mercifully owned by the sweet influence of divine regard,
under which ability was graciously vouchsafed for the appointed work;
and a sustaining hope attended,
that the precious cause of Truth and righteousness was
not injured by the humble advocate,
and that the efforts to promote it would not be altogether lost.

"`In the meeting on first-day morning we passed through much close exercise.
There is a variety of ground on which labour is to be bestowed;
and truly there is a very hard soil in the minds of many professors of the pure truth;
but it felt like getting through the work, the sense whereof was thankfully accepted.

"`Having felt much respecting Adair, a village eight miles from Limerick,
I was not satisfied to defer the visit there longer than first-day afternoon;
we therefore went soon after meeting,
and I. M. H. having written to a serious clergyman on the subject,
we found a large room preparing and the meeting appointed for five o`'clock.
He came to see us a little before the time, and some interesting conversation occurred;
but the season was too limited for all he appeared anxious to know or say,
and we went to meeting, where a large number of solid people assembled.
The stillness was remarkable,
and the doctrines of the gospel seemed to have ready entrance into prepared minds,
as Truth qualified for declaring them.
My soul was bowed in thankful acknowledgment of divine mercy,
and we separated from this simple, religiously disposed company,
under the impression of much love.
They are called Palatines, being mostly descendants of Germans;
they are generally farmers, who live in a neat and comfortable manner.

"`Fourth-day at twelve o`'clock, a meeting was held at Castleconnell; it was,
to my feelings, an awful season.
The room was crowded with different descriptions, some giddy and thoughtless,
many disposed to be solid, two clergymen,
and several of a superior class of the inhabitants;
but a large number of such as know little beyond getting within sound of the voice,
unsettled and at times disturbing to others; but gracious help was near,
and we had reason to be thankful, whether the labour prove availing or not.`"

Before leaving Limerick, she addressed the following letter to the clergyman at Adair.

Limerick, Sixth month 22nd, 1807.

Dear Friend,

I regretted that we were so limited for time, yesterday,
as to prevent our further acquaintance with each other`'
s sentiments in the line of free communication,
to which thou appeared inclined; and wherein as far as I might be enabled and at liberty,
I should have willingly met thee,
believing it is consistent with the duty we owe one to another,
to '`be ready to give an answer to every man that
asketh us a reason of the hope that is in us,
with meekness and fear.`' I believe when this is done in the spirit of love,
which is that of the gospel, it will not have a tendency to raise a wall of separation;
but even when we do not think exactly alike on some points,
draw us nearer to that source of light and life,
wherein the one blessed state of Christian unity is attained,
and the acknowledgment produced that to such as believe, to the saving of the soul,
there is but '`one Lord, one faith, one baptism.`'

I doubt not thou earnestly desires that this
precious experience may be that of thousands,
and tens of thousands, yea,
that '`the earth may be filled with the knowledge of the Lord,
as the waters cover the sea.`' I can fully unite herein,
and believe assuredly that the God of universal love and mercy,
is bringing many to the knowledge of that salvation so freely and fully offered;
and also preparing many instruments who, in His holy hand,
will be used in forwarding the great work which
is evidently on the wheel of divine power.
When led to contemplate this,
I frequently consider that in order to be made as polished shafts in His quiver,
such must abide in patient submission to His preparing, qualifying power,
and wisely learn the times and seasons, which being in the heavenly Father`'s hand,
are in His wisdom, measured out, and prove, by His blessing,
times of refreshing from His holy presence.

These remarks I had not a view of making when I took up my pen,
just to say I sincerely wished thee well, and the Lord`'s cause well,
in that and every part of His habitable earth;
but having moved in the liberty which I trust the truth warrants,
I hope it may not be unacceptable to thee, from whom in the same,
I should be well pleased to hear at any time, shouldst thou feel inclined to write to me.
I herewith send, and request thy kind acceptance of two little tracts,
which I consider instructively explanatory of the
religious principles professed by us as a Society:
and with sentiments of esteem and gospel love, I am thy sincerely well wishing friend.

Mary Dudley.

A visit to the families in Youghal succeeded her engagements at Limerick,
and she also held several public meetings there, and in the city of Cork;
respecting these services she observes:

"`I have struggled on under a weight of bodily oppression, but faith is, at times,
mercifully victorious over the weakness of the flesh and spirit.
So doth our gracious helper fulfil His own promise,
and evince His power in the needed time.

"`My conflicts have not been small for right direction,
and I wish for the clothing of resignation,
though my own will may be more and more crucified.
Some seasons were in a very particular manner owned by the diffusion of solemn influence;
and while I have a humble hope that the precious cause of Truth has not suffered,
I do gratefully accept the feeling of release from this part of the vineyard.`"

My beloved mother returned home from this journey early in the eighth month,
with a relieved and peaceful mind;
but under such a sense of impending affliction as made her frequently sad,
and induced the expression of a settled belief that
something peculiarly trying to her nature was at hand.
It was not long before her habitation became the scene of awful calamity;
her beloved husband, the only son who was at home, and her eldest daughter,
being attacked at almost the same instant with symptoms of fever.
The latter, and another who subsequently caught the disease, were pretty soon restored,
but to the two former,
it pleased Divine Providence to make this illness the
means of translation to another state of being.

She was wonderfully supported during the long season of
anxiety and fatigue which fell to her lot;
her bodily and mental powers seeming to be renewed day by day,
as she watched the declining strength,
and ministered to the wants of her affectionate and tenderly beloved husband,
who survived his son three weeks,
and was favoured to make a happy and peaceful close on the 14th of the twelfth month,
in the seventy-fifth year of his age.
Although his bodily sufferings were at times great,
yet he was preserved in remarkable patience,
and enabled to contemplate his departure from the world with resignation and composure;
whilst he frequently testified,
that his faith and hope were founded on the mercy and merits of his Redeemer.

He derived much comfort from the holy Scriptures,
and the 12th chapter of the Epistle to the
Hebrews afforded him such peculiar encouragement,
that during the last few days of his life, he repeatedly desired it might be read to him,
dwelling in an especial manner upon the following verses:
'`But ye are come unto Mount Sion, and unto the city of the living God,
the heavenly Jerusalem, and to an innumerable company of angels,
to the general assembly and church of the first born, which are written in heaven,
and to God the judge of all, and to the spirits of just men made perfect,
and to Jesus the Mediator of the new covenant, and to the blood of sprinkling,
that speaketh better things than that of Abel.`' This gracious
declaration he was favoured to feel so applied to his own soul,
that death was disarmed of its sting; and he several times said,
that through the rich mercy of God in Christ Jesus,
the king of terrors was not such to him.

The fruits of Christian faith and resignation were
instructively manifested under this afflictive bereavement;
for while the loss was deeply wounding to her affectionate feelings,
and after a union of thirty years, my beloved mother found herself, '`a widow indeed,
and desolate,`' she was mercifully enabled to trust in God;
and so to supplicate for His saving help,
that instead of sinking into gloomy sorrow she was qualified to comfort her children,
and set them an animating example of humble acquiescence with the divine will,
and diligent attention to the performance of social and religious duties.
