== Chapter XVI.

Visit to Kent,
Surrey and Sussex--Religious service within the Quarterly
Meeting of London and Middlesex--Journey into Essex,
and Family visit in the meetings of Peel and Westminster--
Visit to some parts of Yorkshire--Family visit in Southwark, etc.
From Fourth month, 1815, to Twelfth month, 1822.

In the spring of 1815,
my beloved mother obtained the necessary concurrence of her own Monthly meeting,
for religious service among Friends and those of other denominations,
within the bounds of the Quarterly meeting of London and Middlesex,
and in the counties of Kent, Surrey and Sussex.

Although considerably indisposed at the time of entering upon this engagement,
she was enabled to perform it without much interruption,
and greatly to the relief of her own mind.

In the course of it she travelled upwards of six
hundred miles--held about thirty public meetings,
many of them in places where none of our Society reside;
besides visiting all the meetings of Friends,
and most of the families which constitute them, in Kent, Surrey and Sussex.

In some of the public meetings in the vicinity of London,
she was joined by her dear friend W. F.,
whose company and gospel labours were acceptable to her; and it may be safely said,
that in her ministerial engagements she always
evinced a tender care for the feelings of others,
rejoiced in the dedication of her brethren and sisters,
and endeavoured to make way for their obtaining relief of mind,
in meetings which were appointed at her request.

In the summer of 1816, she paid a religious visit to Friends in Berks and Oxfordshire,
holding public meetings in many parts of those counties,
and some places in Buckinghamshire.
During the following year,
she had a large number of public meetings in the city and neighbourhood of London,
among these one at the west end of the town, which was held in the Argyle Rooms,
and attended by many of the nobility and higher class of society.
For this description of persons my dear mother`'s mind had been long exercised;
but although several meetings had been appointed,
with a view to having their company at our own meeting house,
no attempt had succeeded so as to relieve her of the burden.
Friends of Westminster entered very feelingly into the concern,
and many Friends attending from other meetings also,
their joint sympathy proved strengthening under the prospect and
performance of what she considered an awfully important service;
while her spirit bowed in thankful acknowledgment of Almighty help,
and the peace which resulted from this sacrifice.

In returning the certificate of her Monthly meeting she wrote as follows:

To Friends of the Monthly meeting of Southwark.

"`Dear Friends,--Feeling unequal to the personal attendance of our Monthly meeting,
I adopt this method of returning the minute which was kindly issued a long time since,
leaving me at liberty to move, in fulfilment of the avowed prospect, as Truth,
might direct, and health permit.
While the latter was favourably afforded,
I hope there was attention given to the apprehended discoveries of duty,
by appointing many meetings in the city and its vicinity;
finding in the general not only a willingness to
lend suitable places for such to he held in,
but much openness to receive these visits of gospel love,
to my humbling relief I may thankfully acknowledge,
that with respect to this engagement a peaceful retrospect is vouchsafed;
and as it seems unlikely I should be enabled to avail myself of the liberty given,
by attempting further service of this sort at present, I resign the minute;
and conclude beloved friends, your very affectionate interested friend,

Mary Dudley.

14th of Twelfth month 1817.

Towards the conclusion of the year she was much confined to the house by illness,
and while thus circumstanced wrote some observations relative to the state of her mind,
from which the following have been extracted.

"`When I contemplate the years of deeply trying
probation through which I have been sustained,
the bereavements dispensed, the anguish experienced,
whilst links most tenderly binding to the natural part,
and in some instances sweetly cementing to the best feelings, have been severed;
what waves have rolled, and billows followed in succession;
I may well query where had a stay and support been found but in Him,
who under the early visitation of His love was
graciously pleased to seal the sacred promise,
'`I will never leave thee,
nor forsake thee.`' To the Lord`'s adorable mercy be it ascribed that He has not left,
or I had uttered the reprehensible language,
'`what doest thou?`' under His dealings with me
a poor feeble and naturally erring creature;
disposed to '`cleave unto the dust,`' and centre in the gifts of divine love.

"`The hand of inexplicable wisdom has been laid, in the line of judgment,
upon the very closest ties, so that nearly through my pilgrimage thus far,
that which clung the nearest has been called for, or crucified,
by death passing upon even apparently allowable possessions.
The life has been so shaken in desirable things,
that '`I am consumed by the blow of thy hand,`' has been a
language well understood in the line of my experience.

"`Oh the depth of that repugnance to the heart-cleansing work
of religion which is hid in the human mind:
in mine how has it impeded a growing fitness to join in
the consecrated anthem of redeemed spirits,
'`Thy will be done.`' I reverently acknowledge my unshaken
belief in the loss which mankind has sustained by the fall,
and the need of a Mediator to reconcile a degenerate world to a pure and holy Being.

"`I dare not hope for acceptance on any inferior ground than that opened by Him,
who is '`the way, the truth and the life.`' My foundation for that hope,
which through abundant mercy is at seasons felt to enter within the veil,
rests on the great propitiatory sacrifice for sin,
and the operation of His divine spirit as a deliverer from sin.

"`Here, with all my short comings, my errings, strayings, commissions and omissions,
a God in Christ can be humbly confided in,
for continued support through the remaining steps of the wilderness journey,
and sustaining goodness at the end.
This end may be yet more distant than my weak sight has a view of,
the pins having been allowed to hold the feeble
structure far longer than could have been expected;
and the Lord only knows the need there yet is for trials and afflictions,
in order that the work of preparation may be happily effected.

"`Oh the immeasurable distance which is at times contemplated,
between uncreated good and the mixed state of a finite being,
surrounded with the encumbering load of frail mortality!

"`If others more subdued, more zealous, and more active in the line of duty,
are carried above these discouraging sensations,
or not called upon to take the abasing views,
which some of the Lord`'s feeble ministers feel to be their lot,
I wish not to judge or shake their faith and obedience.
While in traversing the solemn path of preparation,
and for many years feeling the humble desire to be so
strengthened as to fill up the allotted ministry,
there feels to me nothing but divine mercy to look to.
Therefore, from my very heart I must renounce all hope,
even for the acceptance of any feeble effort towards
promoting the glorious cause of truth and righteousness,
but what is founded on the one blessed advocate, my God and Saviour!
He only has filled, He has a right to empty;
and never does my soul more enrichingly rejoice, than when every view of righteous,
and unrighteous self, is absorbed in the calm, silent,
and utter reliance on unmerited and everlasting love; my hope in time,
my only anticipated joy in eternity.`"

In the Second month 1818,
my beloved parent began a visit to the families
belonging to Gracechurch-street Monthly meeting,
her certificate leaving her also at liberty for other religious service;
and during the engagement she appointed many public meetings in the city,
and some country places adjacent.
Among these was one at Woolwich,
which was remarkable for the numbers by which it was attended,
the general solidity that prevailed,
and the freedom felt in declaring the way of salvation.

In the Ninth month she obtained a certificate for religious service in Essex,
and was diligently occupied in that county for above nine weeks.
She visited most of the families which composed Witham Monthly meeting,
and held numerous public meetings to the relief and peace of her exercised mind,
which was often enlarged in the feeling of that Christian love
which embraces the highest interests of mankind universally.

She travelled in this journey above four hundred miles;
returned home in a very broken state of health, and was for a considerable time,
confined by illness,
her body and mind suffering under a combination of afflictive circumstances.
She was, however, mercifully sustained; and in the summer of 1819,
again felt herself called upon to manifest the continuance of
gospel concern on behalf of her fellow professors,
by applying for the requisite liberty to visit families within
the compass of Peel and Westminster Monthly meetings.
In the latter service Abigail Pim united,
and it proved the last religious engagement of this dear friend, who,
in the following year,
was attacked with the illness which ultimately removed her from the militant church.

In the year 1820, my dear mother felt inclined to attend the General meeting at Ackworth,
and informed the Friends of her own Monthly meeting,
that she believed it her duty to stand resigned to such religious
service as she might feel required of her while in Yorkshire,
as well as in going and returning from thence.

This engagement occupied about four months,
during which time my beloved mother was diligently employed in
such service as from day to day opened to her view,
being, notwithstanding the sensible increase of bodily infirmities,
enabled to perform the labour assigned her both among Friends and others; for,
besides attending two Quarterly, six Monthly and above sixty Particular meetings,
she also held twenty-six appointed for those of other religious professions.

In going from a meeting of this description, held at Tadcaster,
to another appointed at Ferrybridge,
she sustained a very serious injury by the carriage in which she rode being overturned,
which prevented her reaching the place until the
people had been a considerable time assembled.

Through the display of that power to which all things are possible,
she was wonderfully strengthened for the service that devolved upon her,
and the refreshment of spirit which was felt in declaring the doctrines of the gospel,
to persons who seemed prepared for receiving them,
for awhile overcame the sense of bodily labour;
but after the meeting this was acutely felt,
and she was so ill as to excite much apprehension for the consequences.

She proceeded at once to Doncaster,
and was there confined above two week at the house of her dear friends W. and M. Smith,
who, when she was able to move forward,
continued their kind care by accompanying her as far as Hitchin,
where she spent a few days with her long loved friend E. J. Wheeler.
Upon a review of this journey, wherein she had travelled upwards of nine hundred miles,
my dear mother wrote as follows, in the twelfth month, 1820.^
footnote:[The Editor thinks it may be best for her to state,
that in this and several preceding journeys,
as well as in all her subsequent religious service, she was her dear mother`'s companion,
having certificates from the monthly meeting for uniting in such engagements.]

"`Hitherto hath the Lord helped, may well be deeply inscribed on my heart,
and acknowledged with my pen, in retrospect of innumerable unmerited mercies,
preservations, and deliverances, through a long journey, and on many accounts,
one of the most exercising of my life.
I have to commemorate the goodness which veiled the prospect as to its nature and extent,
and left us to depend on the fresh arisings of light to guide from day to day,
and from place to place.

"`After attending the General meeting, at Ackworth,
where there was reason to believe we were in our right place,
the field of labour enlarged before us, amongst those of our own profession,
and many of various names and sects in that extensive county;
while to the praise of Infinite Wisdom and love,
a precious evidence was often felt that the Shepherd of
Israel is sweetly gathering by His all-powerful arm,
many who are not, and never may by outward designation be, of the same name with us.
The preparation frequently witnessed among such to receive the gospel message,
the solemnity of the stillness spread over some uncommonly large assemblies,
exceeded what we had before experienced,
and encouraged to the full belief that the present is a deeply interesting period;
one wherein the call is loudly proclaimed to us
as a distinct and highly professing people,
to '`stand continually upon the watch tower in the day time,
and sit in our ward whole nights;`' to place a double guard upon our words and actions,
lest even one of the inquiring little ones be offended,
or turned out of the way of steady advancement.

"`Oh! how did my soul lament within our camp, the want of that holy discipline which,
if submitted to, would prepare to be accoutred for service in the Lord`'s hand,
and amongst the people.
The lack of righteous zeal, of spiritual discernment,
of heavenly skill in savouring the things that be of God,
while those that be of man merely, can be nicely discriminated and understood.

"`The faculties and reasoning powers of many are strong,
their perceptions clear respecting that path wherein self can rejoice and is nourished;
but oh the cross! to some I fear that even the
preaching of it is as to the Jews and Greeks.
There is an unwillingness to lose the life,
in order that that which deserves the name may be found,
while any substitute is readily adopted, rather than submission to the humbling,
reducing state where, as little children, the kingdom is alone received.

"`An endeavour to reconcile the world, and religion, seems the hindrance of a multitude;
the strong assertion of our blessed Redeemer being too much overlooked,
'`ye cannot serve God and mammon.`' Thus the eye becomes dim, and the ear often deafened,
so that imparting what is seen to be the whole counsel
to such is like breaking down a fenced wall;
the healing power of a physician to those who are whole, needless tidings,
an unwelcome message.
How hardly shall they that have riches enter into the kingdom?
Various are the possessions wherein there is a resting;
many have their good things in this life.
Oh! that the abundance might be passed through, and temporal blessings not centered in,
so as to cloud the view of the things that are eternal.

"`I often think inherited or obtained treasures have blinded the spiritual eye of many,
who are descended from those sons of the morning, as it respects our little community,
to whom great things would have been burdensome;
and earnest are my desires that worldly prosperity may
not be allowed to settle in a state of dangerous ease,
lest the language formerly uttered in the Lord`'s name should be applicable,
'`They that depart from me shall be written in the earth.`'`"

Early in the year 1821,
my dear mother again felt her mind drawn to the performance of some
religious service within the limits of her own Quarterly meeting;
in the prospect of which she wrote as follows:

"`Amidst the sense of feebleness and trial,
I find no rest but in what I believe to be the divine will.
I therefore informed my brethren and sisters, in a joint conference today,
that I believed resignation on my part was called for,
to pay a visit of gospel love to the Monthly
meetings constituting this Quarterly meeting;
accompanied with a view of appointing some meetings
among Friends and others of a more public kind,
besides visiting the families belonging to Southwark Monthly meeting,
awful as it is to contemplate such a large number.

"`I feel relieved by having thus acknowledged the exercise, but as to procedure,
it is likely in my enfeebled state to be slow, and if never accomplished by me,
I wish to leave all to unerring wisdom and love,
with an humble hope that in the sacrifice of the
will acceptance may be mercifully granted.

"`In seasons of abstractedness from visible things,
and precious preparation for communion with Him who is invisible,
the capacity is strengthened to comprehend that redeeming influence,
whereby knowing that we are not our own,
fervent desires are raised to '`glorify God in
our bodies and in our spirits which are His.`'

"`The lapse of time offers matter for solemn consideration;
the end of it when viewed in connection with an
entrance upon that state which admits of no change,
feels truly awful; and a sense of the purity which must clothe disembodied,
glorified spirits, contrasted with our own poor vestment of mortal infirmity,
is felt almost appalling, even to the eye of feeble faith.
Yet under the sustaining hope that '`the white linen`' will be prepared,
and when unclothed a being '`clothed upon`' mercifully experienced,
while in prostration of soul the term unworthy can be indeed adopted,
there is ground whereon the end of time can be contemplated with a
serenity which nothing inferior to such feelings can possibly produce.

"`The mind, when raised in such holy contemplation,
is ready to utter the language of good old Simeon,
'`Lord now lettest thou thy servant depart in peace,
for mine eyes have seen thy salvation;`' but He who is
infinite in wisdom only knows what is best for us,
what is most calculated to effect in and through us, the appointed work,
the measure of suffering, the degree of patience in it, needful to be proved,
and the portion of active service He designs to prepare for.

"`Under these views, the longer I sojourn on earth,
the more I see the value and safety of endeavouring daily to learn this one lesson;
leave all, attend to present duty, and in humility cast every care for the future on Him,
who careth for, and will provide for,
those who love and serve Him in time and through eternity.`"

T+++.+++ L. joined in part of the visit to the families of Southwark,
which was accomplished with as little interruption as could be expected,
considering my beloved parent`'s age and infirmities;
and she frequently mentioned feeling it as a farewell visit to the members of a meeting,
where she had been long bound in peculiar interest and concern.

After this she was again engaged in public service,
holding meetings in the different meeting houses belonging to Friends in London,
and in many of the surrounding villages, much to the relief of her own mind,
and there is reason to believe the satisfaction and help of others.
Some of these seasons were attended with remarkable solemnity,
and the clearness and liberty which were evident in her declaration of gospel truths,
frequently excited the apprehension that her labours were drawing to a close;
while she spoke of the sensible help afforded her,
and the feelings of peace and comfort which succeeded these engagements,
as greater than she had been accustomed to, adding,
"`I believe if I were to continue long in the body I should not have such feelings,
nor be so filled with divine love as is sometimes the case.`"

One of the meetings just alluded to was at Hampstead,
a place respecting which she had long felt her mind exercised,
but where a meeting of Friends had not been held for many years.
In a record of this season my dear mother says:

"`Though heavy in prospect it has been relievingly held,
and I humbly trust gracious help may be acknowledged to have been near:
many who attended the meeting had never been present on such an occasion;
yet the attention manifested during the communication of gospel truths was remarkable,
and the solemnity which was early evident, and continued to increase,
tended to renew the trust in Almighty aid and goodness.`"

Once upon retiring to bed in a very exhausted state after an evening meeting in the city,
my dear mother said with much tenderness of spirit,
"`I long to be joined to the general assembly and church of the first-born,
yet such is the love and concern I feel for the souls of the people,
that my life seems of little consequence,
and I could be satisfied to drop while declaring the
mercy of God in Christ Jesus to a fallen race.`"

On another occasion of the same kind she observed, "`What a favour to have a good bed,
but what a still greater mercy to have '`a good hope through grace,`' that
after a few more fleeting days there will be a settlement in unmingled,
everlasting rest.
I am so weaned from anxiety that I seem to have nothing in the world to think of;
there is, however, one thing which weighs heavily on my mind,
and that is the prosperity of the blessed cause of truth and righteousness.
To promote this in any way I could be willing to live a little longer;
and the separation from all of you who are so dear to
me will be keenly felt when it comes to the point.`"

After a meeting had been appointed at Dulwich, she wrote as follows:

"`I feel this an awful occasion,
for such prospects are becoming almost too heavy through infirmities abounding,
and bodily ability sensibly decaying,
yet I trust I may humbly adopt the resigned language,

'`My life, while Thou preserv`'st ray life,

Thy sacrifice shall be.`'

Oh, that I may be enabled, through the continuance of sustaining faith,
to add the subsequent expressions,

'`And death, when death shall be my doom,

Shall join my soul to thee.`'

For when the eternal union is formed, conflict will have finally ceased.`"

On returning from this meeting she remarked, that under the consolation vouchsafed her,
she seemed insensible to pain or weakness, and felt as if healed in body and mind;
strongly expressing her thankfulness for the covering of good whereby
that evening sacrifice had been owned by her gracious Master.
