[#hannah-dudley, short="Illness and Death of Hannah Dudley"]
== Some Account Of The Last Illness And Death Of Hannah Dudley

[.chapter-subtitle--blurb]
Who Was Released From The Troubles And Dangers
Of Time on the 19th day of the third month 1810,
in the twenty-sixth year of her age.

The following account was drawn up by E. Dudley at the time,
and has been circulated in manuscript among the
cotemporaries and friends of the deceased.
Her dear mother having left a written request,
that if any memorial of her life were ever prepared for publication,
this should be added to the work,
it now seems proper to premise a few particulars respecting the character of
one who was but little known beyond the circle of her immediate connections.

Hannah Dudley was the third daughter of Robert and Mary Dudley, and born at Clonmel,
in Ireland.
Her disposition was amiable and tender, combined with a degree of reserve, so that,
although naturally cheerful, she shrunk from observation,
and was peculiarly diffident in her manner.
She was seriously thoughtful from a child; fond of reading the Holy Scriptures,
and remarkable for the solidity of her demeanour in religious meetings,
which she delighted to attend.
As she advanced to youth, the favourable impressions thus early made upon her mind,
were in some measure counteracted by indulgence in self-gratification,
and she took greater latitude with respect to dress and
reading than was consistent with her education,
though not to an extent which would be generally deemed reprehensible,
nor by any means equal to what many young persons of our Society give way to.
In the twentieth year of her age she had a long and very suffering illness,
during which it pleased the Lord so to renew the visitation of his love,
as greatly to humble and contrite her spirit.
In this state she saw the vanity and unsatisfying nature of worldly enjoyments,
mourned over the time which she had spent unprofitably,
and was brought under conviction for deviating, even in little things,
from that simplicity which she then felt it would be right for her to practise,
however in the cross to her natural inclination.

She was strengthened to enter into covenant with her heavenly
Father by the sacrifice of her will and affections;
and when raised from the bed of sickness,
the fruits of humble dedication were obvious to others.
She continued subject to trying attacks of indisposition,
but her patient endurance of pain, increasing watchfulness and stability of conduct,
with an evident weaning from worldly objects,
proved that the great work of transformation was powerfully, though secretly,
carried forward in her heart.

Some papers being found after her decease,
which describe the earnestness of her desire for complete sanctification,
it is thought that the following extracts may be a suitable
introduction to the particulars of her last illness and death.

[.alt.centered]
=== EXTRACTS

Eighth month 25th, 1805.
"`This day I completed my 21st year;
may the succeeding one witness a more perfect dedication of
heart to the Creator and preserver of my life,
and may He graciously sanctify,
(if his will,) the late severe dispensation with which he thought fit to visit.`"

Third month 31st, 1806.
"`Although disease may be permitted to make its advances by almost
imperceptible degrees towards a final termination of life,
and with it all terrene incumbrances, be pleased to grant.
Oh! thou dispenser of every blessing, an entire acquiescence and unreserved submission;
but, if consistent with Thy holy will, merciful Father bestow more patience,
more perfect resignation of heart, to every dispensation of thy Providence.
Thou alone canst afford ability in the moment of trial,
to rely on thine unfailing arm for consolation and divine support.
Teach me, then, I beseech thee, teach this unsubdued will, to bend unreservedly to thine.
And, O Lord! if so mean a suppliant may be suffered to cast a petition at thy footstool,
in abundant condescension be pleased, Creator and preserver of my life,
to continue near when pain and weakness prove
almost too much for the small grain of faith;
for thou alone, dearest Father, canst afford strength in such a moment.`"

First month 1st, 1809, one o`'clock First-day morning:

[verse]
____
Another year forever gone
Proclaims the end of time.
____

[.no-indent]
"`May the succeeding one be passed more circumspectly,
and an increase of knowledge be acquired on
subjects worthy the pursuit of an immortal soul!
But resolutions formed without mature and necessary reflection and perseverance, steady,
unvarying perseverance therein, can avail but little--alas, how little!`"

Eighth month 25th, 1809, Sixth-day.
"`The first of which I have ever attempted to set down the occurrences,
and the last I have to spend of my twenty-fifth year;
a year in which there has been little or no progress
made in what ought to be the grand pursuit of my life,
and is designed to be the end of my being.
O Thou! whose ways are not as our ways, nor thy thoughts as our thoughts,
grant that I may experience,
(if permitted to measure another year in this state of probation,) an increase of desire,
and stability in that desire, to follow more implicitly, more resignedly,
thy holy commandments;
to watch more guardedly over a disposition naturally prone to be too
easily excited by the occurrence of trivial circumstances,
to what is improper and reprehensible, both in my feelings and language.
Oh! be pleased to teach me the way most suited to curb, if not overcome,
the propensity I have so frequently to combat with,
indulgence in imaginary prospects which never can be realized,
and which tends more than any other weakness,
to alienate my mind from devotedness to Thee, thou great Source of light and life.
And ere I close this weak attempt to petition for
further strength and support at thy footstool,
thou God and Father of my life,
be pleased to grant the humble request of one of thy most unworthy creatures,
that this effort to acquire some improvement in the most essential point,
may be blessed.`"

Twenty-sixth, 1809, 7 o`'clock, Seventh-day morning.
"`This day I enter a new year.
Oh may the numberless blessings conferred on so
unworthy an object during the preceding one,
as well as every other of my life, be thankfully had in remembrance,
and with sincere humility of heart considered of,
every rising and setting sun I may be permitted to behold.
But, more often than the rising or setting sun,
may I be strengthened to return thanks to his name who has been the preserver of my life,
who would be the enlightener of my eyes,
did I permit them to be opened to revealed conviction.
Through His adorable condescension am I still preserved;
but were I more devotedly to resign every selfish, sordid, low propensity,
and substitute for them the meekness, humility,
and self-denial of the true follower of a crucified Redeemer,
of how much more the instrument of good to others should I be permitted to become;
and how much larger a portion of that peace which the world cannot give,
neither take from its happy possessor, should I be frequently blessed with.`"

On the 15th of the First month, 1810,
my precious sister was attacked with violent pain in her face,
to which she had been liable since a long illness five years before,
so that we did not feel alarmed by it.
Lying in bed that day, and using proper care, seemed to have the desired effect,
and she was so much better the two following days as to bear sitting up for a short time.
On the 18th the pain returned with much severity, and was attended by symptoms of fever,
and inability to sleep, which she remarked was very trying.
Towards noon her spirits became much affected, but after being relieved by weeping,
she lay in a composed state, though still without sleeping, and said,
"`My poor dear Thomas seems continually before my eyes.`"^
footnote:[A brother who had died in his 21st year, about two years before,
and to whom she was very tenderly attached.]
At night she grew more easy, and fell into a sweet sleep, which lasted nearly five hours;
on awaking, however, she felt no way refreshed, though tolerably free of pain;
and expressed such great anxiety at my not going to bed,
that to satisfy her I lay down for an hour or two.

The next evening she was sweetly collected, and we had some very interesting conversation.
She observed, "`How just is that line of Young`'s,
'`All men think all men mortal but themselves,`' and added,
"`how apt we are to forget that we are not to continue here.
I have been thinking of the 91st Psalm, as applicable to our dear mother;
does it not end with '`I will bless him with long life,
and show to him my salvation?`'`" She then asked me to read the whole of it, which I did,
apparently to her comfort: when I came to the last verse, she cheerfully said,
"`that is not one of the blessings I desire,`" meaning long life; her mother answering,
"`but, my love, thou hast no objection if such be the divine will?`"
"`Oh no,`" she replied, "`if it be the Lord`'s blessed will.`"
That night, while in great pain, she said she was afraid of being impatient,
to which I replied that she had always been much
favoured with patience when tried by illness;
which indeed was the case in a very striking manner: she sweetly answered,
"`The Lord has never laid more on me than he enabled me to bear;
we should be poor creatures without his help.`"
She then calmly said, "`I think I shall not recover this illness.`"
Being told that she had been worse in former attacks, she replied, "`Yes, I have,
a great deal worse and been restored, and I may be now; but somehow I think I shall not;
and if it be the will of the Almighty I should rejoice; at least I hope I should.
Is it in the Romans that passage is?
'`We are troubled on every side, yet not distressed; persecuted, but not forsaken;
cast down, but not destroyed;
always bearing about in the body the dying of the Lord Jesus,
that the life also of Jesus might be made manifest in
our body.`' '`For our light affliction,
which is but for a moment,
worketh for us a far more exceeding and eternal weight of glory.`'`"

Soon after this, mentioning a relation who had lately died; "`Poor +++_______+++,`" said she,
"`had a bustling life; I trust she is at rest.
Oh! if people did but consider rightly I often think how insignificant those
things would appear which now make us anxious and uneasy.

[verse]
____
'`Ah! what is life, that thoughtless wish of all,
A drop of honey in a draft of gall.`'
____

[.no-indent]
I remarked that the next line was also striking:

[verse]
____
'`A half existence, or a waking dream.`'
____

[.no-indent]
"`Yes, indeed,`" she replied,
"`we do not exist here; it is in eternity we shall have our existence.`"

After awhile she again spoke on the improbability of her recovery,
and mentioned her absent brothers with much tenderness, desiring that when any one wrote,
her love might be given them; adding, "`I think I shall never see them again,
but I don`'t know, of course none of us can tell; but if not, we must be satisfied;
His holy, blessed will be done!`"

On my saying that I hoped such a sorrow as losing her did not await us,
after all we had gone through, she cheerfully repeated, "`Sorrow!`"
I replied, "`that it will not be sorrow to thee, my love, I can readily believe,
but it will be a sore privation to us.`"
She sweetly answered, alluding to the term sorrow, "`I hope not;
I trust in the mercy of a gracious Saviour, and rely on his merits only.`"
I think it was on first-day evening, that being in great agony, she clasped her hands,
as in the attitude of prayer, and exclaimed,
"`Oh! merciful Father! thou hast never laid more on me than thou enabled me to bear.`"
Presently after she queried where is that expression,
"`The Lord hear thee in the day of trouble;`" her mother repeated the verse to her,
which is the first of the 20th Psalm.
"`Yes,`" said she, "`but there is something more.`"
The whole passage was then repeated.
"`Send thee help from the sanctuary, and strengthen thee out of Zion;
grant thee according to thine own heart, and fulfill all thy counsel.`"
"`Yes, yes,`" said she, "`that`'s it; Oh, merciful goodness!`"

On getting a little ease she quickly told us she was better,
being always anxious to say any thing calculated to relieve our minds, and sweetly added,
"`what a favour this is.`"
Upon asking whether her mother was gone to bed, "`my poor, careworn mother,`" said she,
"`does she take nourishment?
You should make her take as much as possible, now she has so much to bear,`" Her amiable,
affectionate solicitude for those she loved, never seemed more acute,
and she often expressed her fears of our being overdone by watching with her,
frequently saying, "`I am not worth half the trouble you have with me.`"
Hearing some noise in the street,
which we told her was owing to a ball being in the neighbourhood, she remarked,
"`how giddy the world is,
and how serious everything appears to one who is not
likely to recover;`" then lying still awhile,
she looked at me with inexpressible sweetness, and said, "`Come,
let us join with angels round the throne!`"

When she had been about a week ill,
the doctor proposed our calling in further medical advice;
but feeling very delicate of alarming her,
though convinced that she was fully aware of her own situation,
we avoided speaking of it until the second physician was in the house.
Her kind attendant then told her that he had brought his friend Doctor to see her,
not because he thought her worse,
but that it would be a satisfaction to him to have his own judgment confirmed.
She calmly answered, "`I have no objection, he may come in,
though I have full confidence in thee, but I cannot answer many questions.
Thou art trying to make me think I am not in a dangerous disorder, but I know I am,
and you can do nothing for me.
I do not depend on physicians; thou need not be afraid to tell me.`"
When both the doctors had withdrawn, she inquired of me,
"`what do they say my complaint is?`"
I told her they called it inflammatory rheumatism.

"`Ah,`" said she,
"`it is more than that;`" and signified that she felt the disease very deeply seated.
Her mother saying that she hoped the means used for her help would prove effectual,
she sweetly answered, "`but, my dear mother, if the means are not effectual,
I want thee not to be depressed; thou art too good, too good to us all.
I cannot say that I have an evidence that it will be so,
but the impression that I shall not recover remains.`"
Her mother answering that she had heretofore been wonderfully
sustained and brought through severe sufferings,
she replied, "`The Lord is all goodness, all mercy, all mercy.`"
She seemed religiously to comply with everything proposed for her benefit,
though some very painful means were thought necessary.
She usually suffered much from the application of blisters,
and had an uncommon dread of them;
so that when it was proposed to put a large one to her neck,
where the pain was very severe, she objected, and seemed to think she could not bear it;
yet after a few hours she called me to her and said,
"`thou had better put on that blister;
if I grow worse I shall blame myself for refusing it.`"

Complaining that she felt very heavily loaded with illness,
yet could hardly tell where her pain was, she said, in a solemn and impressive manner,
"`It is in seasons like this,
we find the necessity of exerting all the little religion we may be favoured with;
every other support fails me now.`"
The scriptures appeared to be mostly the subject of her meditations,
and the remembrance of them to contribute largely to her comfort.
"`What a treat it will be to me,`" she would say,
"`when I am able to hear thee read a chapter.`"
At a time when her bodily affliction seemed enough to absorb every other feeling,
she astonished me by querying,
"`Dost thou know who is the author of that observation respecting the sacred records,
'`They have God for their author, Salvation for their end, and Truth,
without any mixture of error, for their matter?`' How just,`" added she,
"`is the description!`"
At another time she asked, "`Is it the Apostle James who says, '`we walk by faith,
not by sight.`'`" She would frequently observe,
"`what trouble and care these bodies cost us;`" "`Oh! the encumbering flesh,`" etc.;
and repeatedly, when undergoing violent pain,
which it was often hard for those who loved her calmly to witness, she would say,
in an animated and heavenly tone of voice,
"`What are these sufferings when compared to what the Saviour bore for us.
The sufferings of this present time are not worthy to
be compared with the glory which shall be revealed.`"

Whenever a little respite from pain was afforded, she would mention it as a mercy,
and say,
"`what a favour it was that she had not such or such suffering to struggle with;`" or,
"`thank gracious Providence, that pain is lessened.`"
Want of sleep was one
distressing feature of the complaint throughout,
but she lay so still that we often thought her dozing,
until she would break forth in some sweet observation,
tending to manifest how her mind had been occupied.
On one of these occasions she asked me if I remembered these four lines:

[verse]
____
"`We`'ve no abiding city here,
We seek a city out of sight;
Zion its name--we`'ll soon be there,
It shines with everlasting light.`"
____

The 5th of the second month was a day of extreme suffering to my beloved sister,
although when the physicians came they pronounced her not worse,
which she listened to without making any remark;
but after passing a most distressing night, she said to me very composedly,
"`Surely Dr. +++________+++ is too honest a man to tell you I am recovering.
I am not, nor do I believe I ever shall.
I have never lost the belief that I should not recover this illness.
I dreamed last night that I saw my precious father, and remembering that he was gone,
I asked him if he was happy?
he answered me in the sweetest manner by repeating that passage of
scripture which he used to speak of on his deathbed,
relative to the general assembly and church of the first-born; adding,
'`thou shalt be with me in a short time; only make thy peace with God,
and he will admit thee into his holy presence.
She wept much while relating this dream,
and on my remarking that I trusted her peace was not then to make, she said,
"`if I only had an evidence, but I trust I shall at last.`"
I reminded her of the manner in which she had
been favoured at the beginning of her illness,
when she had said she could rejoice in the prospect of being taken away;
"`Yes,`" she replied, "`and I hope I can rejoice.
I trust in my Saviour, I have many sins, and I pray they may go beforehand to judgment.`"
She then mentioned that her nights were so trying as to make her dread their approach;
"`yet,`" said she, "`I enjoy sweet peace in the night.
How do the doctors account for my passing such uneasy nights, and being unable to sleep;
but, (as if unconcerned about an answer,) it is an unspeakable favour,
that even when I am racked with pain,
I feel such sweet peace as more than compensates for all I suffer.
Oh! what condescension of a gracious Saviour to a poor
sinner! this bed is not like a bed of sickness:
I feel holy joy.`"

In the afternoon being asked how she felt, she cheerfully answered, "`rather better,
thank Providence;
it is a great mercy that my head is not always so bad as it is sometimes.`"
When the doctor came in he queried whether the pain was more bearable,
to which she sweetly answered, "`It ought always to be bearable,
but I think it is somewhat lessened.`"

Speaking to her mother of her illness, and its probable increase and termination,
she said,
"`If I grow worse my dear mother do not get any other physicians,`"
Her mother replying that she knew her confidence was not in man,
but in the Lord, "`Ah!`" said she, "`what poor creatures we should be but for his help!`"
Her mother observing,
thou canst say with Job that "`painful nights and wearisome
days are appointed thee;`" "`yes,`" she returned,
"`I suffer much, but what are mine when compared with the sufferings of many others;
and though my nights are trying, there are times when my Saviour is near me,
I feel him near me!`"
Her mother again repeating the first two verses of the twentieth Psalm, added,
my soul craves that this may be thy experience; to which she solemnly answered,
"`my dear mother, the effectual fervent prayer of the righteous availeth much,
and if I have thy prayers they will be such.`"

After the doctor had paid his visit at night, she said,
"`I pity that poor man when standing by the bed;
he is very affectionate and wishes to help me I believe, but it is out of his power,
and I do not depend upon them;
the opinion of any physician is not of the weight of a pin with me.
I know the Lord is able to do all things, he can raise me up if he pleases,
and he can grant me patience, though I fear if it lasts much longer,
(meaning her illness,) mine will be worn out.`"
Her mother saying thou art favoured with patience, it is renewed to thee;
"`It is renewed;`" she emphatically replied.
On my begging her to try for rest, "`ah! my dear!`" said she in her own placid manner,
"`I believe there is not much rest for me on earth.`"

As the night advanced, her pain and restlessness increased,
and on my querying where her uneasiness was, she replied, "`my head is_ very bad,
but it is a mercy my senses are preserved, I think I have had a sight of heaven.`"
She then spoke of her death, and said,
"`tell my dear brothers not to grieve like those who have no hope.
I trust we shall meet in another and a better world; take care of our precious mother.`"
Finding that this conversation affected my feelings,
although natural emotion was generally suppressed in her chamber, she sweetly said,
"`Is it not our Saviour`'s language?
Daughters of Jerusalem weep not for me; but weep for yourselves and for your children:
thou art doing too much; Heaven bless thee for all thy kindness to me;
but what should I do if thou wast sick.`"
Then correcting what might seem like selfish consideration, she added,
"`but it is more for thy own sake than mine I speak; do go to bed,
perhaps I may get a little sleep.`"
This she often said with a view of allaying our solicitude;
for notwithstanding any little temporary amendment,
from which those about her were at times willing to cherish hope,
her opinion that she was in her death illness remained unshaken.
And the whole tenor of her conduct evinced,
that she was patiently waiting her Lord`'s time for an
admittance into that mansion of rest which she confidently,
though humbly, believed was prepared for her; and it was indeed an unspeakable favour,
considering the pain of body she endured, that she was spared those mental conflicts,
which many experienced Christians have been tried with.
Her prospect of a glorious fruition appeared to be unclouded.

Whenever she mentioned any thing that she wished done, or spoke of any little alteration,
it was with this provision, "`please Providence my life is spared,
I hope to be moved into the other bed tomorrow, etc.`"
One night she inquired whether she was to take medicine, or have any thing done for her;
I replied no, that she had nothing to do but to try for sleep.
"`Only,`" she returned with great sweetness, "`to pray for patience.`"

At one time she suffered much from the use of a painful prescription,
which seemed almost too much for her exhausted state, and she frequently exclaimed,
"`mercy! mercy!`"
When somewhat relieved she called me to her, and said with much tenderness,
"`I was very unguarded awhile ago, I was impatient.`"
I replied that we had not observed it, but thought she was much favoured with patience.
"`I felt it,`" said she, with emphasis, "`I was unwatchful.`"

Thus was the "`swift witness`" attended to by this happily instructed spirit,
and no allowance made for emotions which perhaps few would
deem culpable under such distress as was allotted her.
Her nurse once mentioning how hard it was to bear such agony,
and that it would have been better never to have been born,
"`Oh do not speak so,`" said she with earnestness, "`it is good for us to suffer.`"

Second month 17th. For some days past the increased illness of
my precious sister rendered her unable to speak much,
but the little she did utter,
clearly evinced that the Lord still sustained her in holy confidence,
amidst the storms and tempests of a peculiarly trying season.
Many times, when a sentence could hardly be connected,
the language of supplication was heard,
and her patient acquiescence with the divine will manifested in words like these,
"`Oh Lord look down upon thy poor child:
heavenly Father! not my will but thine be done,`" etc. etc.

18th. Her weakness and debility this morning seemed greater than at any time before,
so that she was scarcely able to articulate;
yet on being asked whether she had got any sleep, she answered, "`very disturbed sleep,
but it was a sweet peaceful night.`"
Her bodily sufferings throughout the day were extreme,
and she appeared to think herself hastening to the close;
once on calling me to her she said, "`Pray, pray, pray;`" and soon after,
"`this is an awful day; preparation for a final change.`"
Her mother saying that she did believe her soul was anchored on the Rock of Ages,
and that the Lord was her Father and Helper, she said in an animated manner,
"`Come then holy Father!
Lord preserve me!
Oh the encumbering flesh.`"

19th. About five o`'clock this morning her sufferings
of body were such as nearly to overcome her,
and desiring I might be called to her,
she described her sensations as peculiarly distressing.
On finding that I was greatly afflicted at being unable to relieve her,
the different means prescribed proving ineffectual, she affectionately held my hand,
and said with sweet composure, "`be content, whatever way I am taken, be content,
the Lord is near me.
He is near me; my God and Saviour!`"
Soon after, while under great conflict, she raised her eyes, and awfully exclaimed,
"`My blessed Redeemer!`"
Her brother coming into the room she spoke very tenderly to him,
saying that it was a mercy they were permitted to hear each other`'s voices again,
(for the room was necessarily kept so dark that he could not
see her,) and in strong terms expressed her love for him.
After he left the chamber she called me to her and said,
"`It is surprising how my affections are loosened from every earthly object.
I seem weaning from all of you, and oh that God may be all in all to all of us.
Every tie seems fast loosening, if I am taken this will be a mitigation of my sufferings,
but perhaps when the time comes it may feel harder.`"
I remarked that everything had been made easy to her during her illness.
"`Oh yes,`" she emphatically answered, "`from the very first.
I sometimes forget that I am on a sick bed; the serenity I feel is so great,
that at times I fear it is carnal security,
and think it is presumptuous in so poor a worm to trust as I do, but no!
He cannot deceive me, none ever trusted in the Lord and was confounded.`"
She often said she was not half thankful enough for the blessings she enjoyed,
so superior to what many poor creatures under bodily suffering are favoured with.
In the night while her pains were very acute she repeated the following lines.

[verse]
____
Hide me, oh my Saviour, hide!
Till the storm of life be past,
Safe into the haven guide.
Oh receive my soul at last!
____

"`Ah, that is it,`" said she, "`If I be but safely landed.`"
In the intervals of pain she prayed in these words,
"`Oh my God! help thy creature who depends on thee.`"
Turning to her mother, she said, "`when thou hast access pray for me.
I have often thought my dear mother, that I could not bear to see thee go,
that I could not bear to stay behind thee,
and now it looks as though I should be spared that trial.`"
At another time, when speaking to her mother respecting the nature of her disorder,
she signified how unimportant it was what name it might be called, adding,
"`we must all have something to bring us to our end;`" and then turning to
the subject which appeared to her the only one worthy of attention,
she spoke of her strong confidence in the mercy of a Redeemer,
and said that her hopes of salvation were grounded on that alone, observing,
"`Oh my dear mother, what could works do for me now?`"
Her mother replied, "`nothing my precious child,
all we have to trust to is the mercy of God in Christ Jesus.`"

On the night of the 21st she was affected with something of a spasm,
which we were apprehensive might prove the last struggle,
and she seemed herself to have a similar idea,
for clasping her hands and raising her eyes, she solemnly said,
"`Now Lord for an evidence!`" and presently after, "`yes, yes; peace, peace, peace.`"
When a little recovered she observed, alluding to the Pilgrim`'s Progress,
(which she had read through a short time before her illness,) "`poor Christian said,
though I walk through the valley and shadow of death I will fear no evil,
for thy rod and thy staff they comfort me;`" then with a more cheerful voice,
"`poor Feeble-minded too got over the river, so may I.`"

She lay during the whole of the 22nd in a state of great suffering,
being generally unable to say more than yes or no,
and even that effort frequently produced distressing symptoms.

--About eleven o`'clock at night we were surprised by
her reviving so as to call us all by name.
Finding that only her mother and sisters were in the room, she asked for her brother,
who quickly came in, and we all sat round the bed;
when to our admiration she was strengthened to approach the throne of
her heavenly Father in the language of solemn supplication,
praying for us individually,
and commending in a strain of Christian confidence yet deep humility,
all and each of her near connections to his protecting care:
and then for herself "`Oh gracious Lord and Saviour,
if I do not weary thy throne with petitions, look down upon thy poor dying sinner:
favour her with an evidence that she shall be received up into glory;
but thou hast already, my God and Saviour, nearly done so.
Oh! accept my humble thanks for thy preserving care throughout my life,
and for the last five weeks that thou hast been near me and supported me.
Thou hast answered my petitions.
Oh my Saviour! posture is nothing, thou hearest prayer!`"

She then sent messages to her absent brothers,
and sweetly addressed her sisters in the language of serious advice, concluding with,
"`comfort our dear tried mother, console and support her.`"
Observing that some of us were affected,
and indeed it would have been hard to restrain the tide of feeling on such an occasion;
"`Suppress nature,`" said she very forcibly, "`I endeavour to do so.`"
After we had all remained some time silent, she inquired, "`who are here?`"
Her mother answered,
"`none but thy poor mother, thy sisters and brother, and the Shepherd of Israel;`"
"`He is here,`" she replied, "`He is near me.`"
After a while she addressed her nurse in an affectionate and grateful manner, and added,
"`I am dying, and it is a very awful thing to die.
Oh be circumspect, we must all die; but the presence of the Lord supports me,
his presence is near me.`"

Then dismissing the servant, she said, "`Give my love to Dr.+++_______+++ ,
tell him I am much obliged to him for his kind attention,
but that the knowledge of this world gendereth to bondage.
I am afraid he is too fond of vain philosophy to think enough of religion.`"
She next gave me a message to a relation at a distance,
comprising much important counsel in a few words;
and mentioning the attendance of places of amusement,
she said in a plaintive and lamenting tone, "`Oh it is a pity, a great pity, a sin,
and waste of time.`"
After lying still a few minutes she broke forth thus; "`What is life! a bubble;
five and twenty years and a little more, and all is over; but I am taken in great mercy,
oh! in great mercy I do believe, from the evil to come.
The grass withereth, the flower fadeth, but the word of our God shall stand forever.`"
Remaining awhile quiet she said,
"`I hope I have not said more than was given me:`" her
mother telling her that she need not fear,
as it was evident her lips had been touched with a live coal from the holy altar;
"`It is the Lord`'s doings,`" she replied, "`it is His doings, oh what mercy!
He hears and answers prayer!`"

It is worthy of remark,
and proved an undoubted evidence of her having been strengthened for the occasion,
that although my beloved sister had spoken so
much more during this solemnly interesting scene,
(which lasted for about two hours,) than at any time of her illness,
yet she did not seem at all exhausted by it,
nor to suffer afterwards from such great exertion of voice:
for notwithstanding her weakness was such that we generally
had to lean over her in order to gather what she said,
she spoke while thus engaged in so clear and distinct a
manner that she could be heard in any part of the room.

For about two weeks after this memorable period,
her debility was such that she could seldom bear to be touched,
or have any one very near the bed, and usually made signs for what she wished done,
the distressing sickness at her stomach rendering it hard to her to speak a word.
Yet ejaculations were sometimes heard which manifested
that her mind was still kept in confidence,
and her faith in the sufficiency of her Almighty Helper preserved unshaken.

One evening during this sore conflict, after her mother had supplicated at her bed side,
and was engaged to petition that the Lord might preserve her
amidst all the suffering he saw meet to dispense,
in steady reliance upon himself, and grant that patience might have its perfect work,
etc. etc. "`Amen!
Amen!`" said she with uncommon energy and sweetness, and then made this appeal;
"`Thou hast told me that mine eyes shall see thy salvation.
Thou hast told me so in the secret of my heart; only Lord keep in the patience,
until it is thy good pleasure to set the spirit free.
I am afraid the spirit is too anxious to get free.`"
Durmg exquisite distress of body the following aspirations were distinctly heard,
though uttered in a weak and broken voice.
"`Gracious Father, remember I am but dust!
Oh, my Saviour, look down with compassion upon thy poor sufferer,
take her this night if it be thy good pleasure; yet not my will but thine be done!`"

Speaking one time of the dying expressions of dear Sarah Grubb,
she seemed comforted by her mother`'s repeating that part
relative to the grain of faith being mercifully vouchsafed,
amidst deep conflict of flesh and spirit, etc.,
and afterwards mentioned the account of a young woman who had made a very happy end,
saying, "`How apt we are when in health to scan over records of this kind,
without considering their value and importance,
though they are calculated to do much good.`"
She several times mentioned dear Deborah Darby, (of whose death we did not inform her,
though it occurred during her illness,) saying, she had dreamt of her,
and often remembered her and her companion`'s
sweet visits to our family when last in Ireland;
remarking what a favour it was to be noticed by
the messengers and servants of the Most High;
but that His visits to the soul were beyond all.
She sent a message to a beloved and intimate young friend on the subject of reading,
which at that awful period she saw required great caution,
and lamented that much precious time was often wasted in perusing works of imagination.
"`Tell her,`" said she,
"`to read the Holy Scriptures,`" intimating that the more she did so,
the less she would feel disposed for perusing books of an unprofitable tendency.

About a week before her death, she said, one evening while in great pain,
"`I pray that the Lord may terminate my sufferings before my patience is exhausted,
and I believe and trust he will.`"
On my querying where her pain was,
and expressing surprise at her having such constant uneasiness, "`Oh death,
death!`" she calmly replied, "`in how many forms does death approach,
it is hard work to die.`"
She once or twice asked her mother,
"`dost thou think it can be long,`" meaning her continuance in suffering.
At a time when we thought she scarcely noticed any sound,
she remarked the death-bell tolling, and said, in an animated manner,
"`some one escaped from life, a spirit released.`"

Third month 14th. Her sufferings and consequent debility were very distressing,
so that we were often apprehensive she had really ceased to breathe;
yet on a little revival,
it was evident that her faith and patience continued in lively exercise.
She said with great sweetness and composure, "`How pleasant it will be to get home,
after all these conflicts, into the arms of Jesus! how trifling they will then appear,
though so hard to poor mortality; but the Lord is near; oh what an eminent favour,
what an unspeakable mercy that he is so near:
from the very first he has seemed to overshadow me,
all my impatience he passes by and forgives; he remembers that I am but dust; he smiles,
he comforts, he cherishes me.`"
I remarked that her bodily sufferings had been very great almost throughout.
"`Yes,`" she answered, "`in the beginning I had great conflict,
and felt my pain very trying; but at length I got to resignation,
and by prayer could say.
Thy will be done;
and now I have desired that when I am taken it may be in a calm and tranquil moment,
that the pangs may not be such as to preclude the
possibility of my nearest connections being around me;
but the Lord`'s blessed will be done.
He is all goodness to me, and will relieve me in his own good time.`"

For the last two days of her life, she spoke but seldom, and that with difficulty,
apparently owing to the oppression and hurry of breathing: which were such,
that except when someone fanned her, she dared not venture to doze,
feeling as she herself expressed it,
that without that artificial air she could not breathe at all.

On first-day evening she had a little of that
rambling which results from extreme weakness,
and did not seem fully to know those about her; but this quite subsided,
and she was next morning perfectly clear, yet did not say much,
being mostly in great pain and suffering,
more so under the approaches of dissolution than we thought could be the case,
considering her exhausted state.
But about four hours previously to her release,
as if permitted to show us that the bias of her
mind remained firm even at that awful moment,
she said, with strength and clearness, "`thank merciful Goodness, that pain is better.`"
She appeared once or twice after this to be engaged in prayer,
but the words could not be understood: and so peaceful was her close,
that those around her knew not the precise moment when she entered her everlasting rest;
though her nearest connections were witnesses of the solemn,
and to them deeply afflictive scene,
about half past eight o`'clock on second-day evening, 19th of third month,
being exactly nine weeks from her first seizure.
The desire of her soul was thus remarkably granted,
and the last enemy disarmed of his sting.
May she,
"`being dead,`" yet speak with availing emphasis the awfully instructive language,
"`Be ye also ready.`"
